/*
 This file was generated by genstub.py, do not edit manually!
*/

int sprx_dlsym(unsigned int handle, const char *nid, void *addr);
int sprx_dlopen(const char* libname, unsigned short *handle);
int sprx_dlclose(unsigned int handle);

static __attribute__ ((used)) void* __ptr_png_calloc;
asm(".intel_syntax noprefix\n"
    ".global png_calloc\n"
    ".type png_calloc @function\n"
    "png_calloc:\n"
    "jmp qword ptr [rip + __ptr_png_calloc]\n");

static __attribute__ ((used)) void* __ptr_png_create_info_struct;
asm(".intel_syntax noprefix\n"
    ".global png_create_info_struct\n"
    ".type png_create_info_struct @function\n"
    "png_create_info_struct:\n"
    "jmp qword ptr [rip + __ptr_png_create_info_struct]\n");

static __attribute__ ((used)) void* __ptr_png_create_read_struct;
asm(".intel_syntax noprefix\n"
    ".global png_create_read_struct\n"
    ".type png_create_read_struct @function\n"
    "png_create_read_struct:\n"
    "jmp qword ptr [rip + __ptr_png_create_read_struct]\n");

static __attribute__ ((used)) void* __ptr_png_create_read_struct_2;
asm(".intel_syntax noprefix\n"
    ".global png_create_read_struct_2\n"
    ".type png_create_read_struct_2 @function\n"
    "png_create_read_struct_2:\n"
    "jmp qword ptr [rip + __ptr_png_create_read_struct_2]\n");

static __attribute__ ((used)) void* __ptr_png_create_write_struct;
asm(".intel_syntax noprefix\n"
    ".global png_create_write_struct\n"
    ".type png_create_write_struct @function\n"
    "png_create_write_struct:\n"
    "jmp qword ptr [rip + __ptr_png_create_write_struct]\n");

static __attribute__ ((used)) void* __ptr_png_create_write_struct_2;
asm(".intel_syntax noprefix\n"
    ".global png_create_write_struct_2\n"
    ".type png_create_write_struct_2 @function\n"
    "png_create_write_struct_2:\n"
    "jmp qword ptr [rip + __ptr_png_create_write_struct_2]\n");

static __attribute__ ((used)) void* __ptr_png_destroy_read_struct;
asm(".intel_syntax noprefix\n"
    ".global png_destroy_read_struct\n"
    ".type png_destroy_read_struct @function\n"
    "png_destroy_read_struct:\n"
    "jmp qword ptr [rip + __ptr_png_destroy_read_struct]\n");

static __attribute__ ((used)) void* __ptr_png_destroy_write_struct;
asm(".intel_syntax noprefix\n"
    ".global png_destroy_write_struct\n"
    ".type png_destroy_write_struct @function\n"
    "png_destroy_write_struct:\n"
    "jmp qword ptr [rip + __ptr_png_destroy_write_struct]\n");

static __attribute__ ((used)) void* __ptr_png_error;
asm(".intel_syntax noprefix\n"
    ".global png_error\n"
    ".type png_error @function\n"
    "png_error:\n"
    "jmp qword ptr [rip + __ptr_png_error]\n");

static __attribute__ ((used)) void* __ptr_png_free;
asm(".intel_syntax noprefix\n"
    ".global png_free\n"
    ".type png_free @function\n"
    "png_free:\n"
    "jmp qword ptr [rip + __ptr_png_free]\n");

static __attribute__ ((used)) void* __ptr_png_free_data;
asm(".intel_syntax noprefix\n"
    ".global png_free_data\n"
    ".type png_free_data @function\n"
    "png_free_data:\n"
    "jmp qword ptr [rip + __ptr_png_free_data]\n");

static __attribute__ ((used)) void* __ptr_png_free_default;
asm(".intel_syntax noprefix\n"
    ".global png_free_default\n"
    ".type png_free_default @function\n"
    "png_free_default:\n"
    "jmp qword ptr [rip + __ptr_png_free_default]\n");

static __attribute__ ((used)) void* __ptr_png_get_IHDR;
asm(".intel_syntax noprefix\n"
    ".global png_get_IHDR\n"
    ".type png_get_IHDR @function\n"
    "png_get_IHDR:\n"
    "jmp qword ptr [rip + __ptr_png_get_IHDR]\n");

static __attribute__ ((used)) void* __ptr_png_get_PLTE;
asm(".intel_syntax noprefix\n"
    ".global png_get_PLTE\n"
    ".type png_get_PLTE @function\n"
    "png_get_PLTE:\n"
    "jmp qword ptr [rip + __ptr_png_get_PLTE]\n");

static __attribute__ ((used)) void* __ptr_png_get_bit_depth;
asm(".intel_syntax noprefix\n"
    ".global png_get_bit_depth\n"
    ".type png_get_bit_depth @function\n"
    "png_get_bit_depth:\n"
    "jmp qword ptr [rip + __ptr_png_get_bit_depth]\n");

static __attribute__ ((used)) void* __ptr_png_get_channels;
asm(".intel_syntax noprefix\n"
    ".global png_get_channels\n"
    ".type png_get_channels @function\n"
    "png_get_channels:\n"
    "jmp qword ptr [rip + __ptr_png_get_channels]\n");

static __attribute__ ((used)) void* __ptr_png_get_color_type;
asm(".intel_syntax noprefix\n"
    ".global png_get_color_type\n"
    ".type png_get_color_type @function\n"
    "png_get_color_type:\n"
    "jmp qword ptr [rip + __ptr_png_get_color_type]\n");

static __attribute__ ((used)) void* __ptr_png_get_error_ptr;
asm(".intel_syntax noprefix\n"
    ".global png_get_error_ptr\n"
    ".type png_get_error_ptr @function\n"
    "png_get_error_ptr:\n"
    "jmp qword ptr [rip + __ptr_png_get_error_ptr]\n");

static __attribute__ ((used)) void* __ptr_png_get_filter_type;
asm(".intel_syntax noprefix\n"
    ".global png_get_filter_type\n"
    ".type png_get_filter_type @function\n"
    "png_get_filter_type:\n"
    "jmp qword ptr [rip + __ptr_png_get_filter_type]\n");

static __attribute__ ((used)) void* __ptr_png_get_gAMA;
asm(".intel_syntax noprefix\n"
    ".global png_get_gAMA\n"
    ".type png_get_gAMA @function\n"
    "png_get_gAMA:\n"
    "jmp qword ptr [rip + __ptr_png_get_gAMA]\n");

static __attribute__ ((used)) void* __ptr_png_get_iCCP;
asm(".intel_syntax noprefix\n"
    ".global png_get_iCCP\n"
    ".type png_get_iCCP @function\n"
    "png_get_iCCP:\n"
    "jmp qword ptr [rip + __ptr_png_get_iCCP]\n");

static __attribute__ ((used)) void* __ptr_png_get_image_height;
asm(".intel_syntax noprefix\n"
    ".global png_get_image_height\n"
    ".type png_get_image_height @function\n"
    "png_get_image_height:\n"
    "jmp qword ptr [rip + __ptr_png_get_image_height]\n");

static __attribute__ ((used)) void* __ptr_png_get_image_width;
asm(".intel_syntax noprefix\n"
    ".global png_get_image_width\n"
    ".type png_get_image_width @function\n"
    "png_get_image_width:\n"
    "jmp qword ptr [rip + __ptr_png_get_image_width]\n");

static __attribute__ ((used)) void* __ptr_png_get_interlace_type;
asm(".intel_syntax noprefix\n"
    ".global png_get_interlace_type\n"
    ".type png_get_interlace_type @function\n"
    "png_get_interlace_type:\n"
    "jmp qword ptr [rip + __ptr_png_get_interlace_type]\n");

static __attribute__ ((used)) void* __ptr_png_get_io_ptr;
asm(".intel_syntax noprefix\n"
    ".global png_get_io_ptr\n"
    ".type png_get_io_ptr @function\n"
    "png_get_io_ptr:\n"
    "jmp qword ptr [rip + __ptr_png_get_io_ptr]\n");

static __attribute__ ((used)) void* __ptr_png_get_progressive_ptr;
asm(".intel_syntax noprefix\n"
    ".global png_get_progressive_ptr\n"
    ".type png_get_progressive_ptr @function\n"
    "png_get_progressive_ptr:\n"
    "jmp qword ptr [rip + __ptr_png_get_progressive_ptr]\n");

static __attribute__ ((used)) void* __ptr_png_get_rows;
asm(".intel_syntax noprefix\n"
    ".global png_get_rows\n"
    ".type png_get_rows @function\n"
    "png_get_rows:\n"
    "jmp qword ptr [rip + __ptr_png_get_rows]\n");

static __attribute__ ((used)) void* __ptr_png_get_sBIT;
asm(".intel_syntax noprefix\n"
    ".global png_get_sBIT\n"
    ".type png_get_sBIT @function\n"
    "png_get_sBIT:\n"
    "jmp qword ptr [rip + __ptr_png_get_sBIT]\n");

static __attribute__ ((used)) void* __ptr_png_get_sPLT;
asm(".intel_syntax noprefix\n"
    ".global png_get_sPLT\n"
    ".type png_get_sPLT @function\n"
    "png_get_sPLT:\n"
    "jmp qword ptr [rip + __ptr_png_get_sPLT]\n");

static __attribute__ ((used)) void* __ptr_png_get_sRGB;
asm(".intel_syntax noprefix\n"
    ".global png_get_sRGB\n"
    ".type png_get_sRGB @function\n"
    "png_get_sRGB:\n"
    "jmp qword ptr [rip + __ptr_png_get_sRGB]\n");

static __attribute__ ((used)) void* __ptr_png_get_tIME;
asm(".intel_syntax noprefix\n"
    ".global png_get_tIME\n"
    ".type png_get_tIME @function\n"
    "png_get_tIME:\n"
    "jmp qword ptr [rip + __ptr_png_get_tIME]\n");

static __attribute__ ((used)) void* __ptr_png_get_tRNS;
asm(".intel_syntax noprefix\n"
    ".global png_get_tRNS\n"
    ".type png_get_tRNS @function\n"
    "png_get_tRNS:\n"
    "jmp qword ptr [rip + __ptr_png_get_tRNS]\n");

static __attribute__ ((used)) void* __ptr_png_get_text;
asm(".intel_syntax noprefix\n"
    ".global png_get_text\n"
    ".type png_get_text @function\n"
    "png_get_text:\n"
    "jmp qword ptr [rip + __ptr_png_get_text]\n");

static __attribute__ ((used)) void* __ptr_png_get_uint_16;
asm(".intel_syntax noprefix\n"
    ".global png_get_uint_16\n"
    ".type png_get_uint_16 @function\n"
    "png_get_uint_16:\n"
    "jmp qword ptr [rip + __ptr_png_get_uint_16]\n");

static __attribute__ ((used)) void* __ptr_png_get_uint_32;
asm(".intel_syntax noprefix\n"
    ".global png_get_uint_32\n"
    ".type png_get_uint_32 @function\n"
    "png_get_uint_32:\n"
    "jmp qword ptr [rip + __ptr_png_get_uint_32]\n");

static __attribute__ ((used)) void* __ptr_png_get_user_chunk_ptr;
asm(".intel_syntax noprefix\n"
    ".global png_get_user_chunk_ptr\n"
    ".type png_get_user_chunk_ptr @function\n"
    "png_get_user_chunk_ptr:\n"
    "jmp qword ptr [rip + __ptr_png_get_user_chunk_ptr]\n");

static __attribute__ ((used)) void* __ptr_png_get_valid;
asm(".intel_syntax noprefix\n"
    ".global png_get_valid\n"
    ".type png_get_valid @function\n"
    "png_get_valid:\n"
    "jmp qword ptr [rip + __ptr_png_get_valid]\n");

static __attribute__ ((used)) void* __ptr_png_init_io;
asm(".intel_syntax noprefix\n"
    ".global png_init_io\n"
    ".type png_init_io @function\n"
    "png_init_io:\n"
    "jmp qword ptr [rip + __ptr_png_init_io]\n");

static __attribute__ ((used)) void* __ptr_png_longjmp;
asm(".intel_syntax noprefix\n"
    ".global png_longjmp\n"
    ".type png_longjmp @function\n"
    "png_longjmp:\n"
    "jmp qword ptr [rip + __ptr_png_longjmp]\n");

static __attribute__ ((used)) void* __ptr_png_malloc;
asm(".intel_syntax noprefix\n"
    ".global png_malloc\n"
    ".type png_malloc @function\n"
    "png_malloc:\n"
    "jmp qword ptr [rip + __ptr_png_malloc]\n");

static __attribute__ ((used)) void* __ptr_png_malloc_default;
asm(".intel_syntax noprefix\n"
    ".global png_malloc_default\n"
    ".type png_malloc_default @function\n"
    "png_malloc_default:\n"
    "jmp qword ptr [rip + __ptr_png_malloc_default]\n");

static __attribute__ ((used)) void* __ptr_png_process_data;
asm(".intel_syntax noprefix\n"
    ".global png_process_data\n"
    ".type png_process_data @function\n"
    "png_process_data:\n"
    "jmp qword ptr [rip + __ptr_png_process_data]\n");

static __attribute__ ((used)) void* __ptr_png_process_data_pause;
asm(".intel_syntax noprefix\n"
    ".global png_process_data_pause\n"
    ".type png_process_data_pause @function\n"
    "png_process_data_pause:\n"
    "jmp qword ptr [rip + __ptr_png_process_data_pause]\n");

static __attribute__ ((used)) void* __ptr_png_progressive_combine_row;
asm(".intel_syntax noprefix\n"
    ".global png_progressive_combine_row\n"
    ".type png_progressive_combine_row @function\n"
    "png_progressive_combine_row:\n"
    "jmp qword ptr [rip + __ptr_png_progressive_combine_row]\n");

static __attribute__ ((used)) void* __ptr_png_read_end;
asm(".intel_syntax noprefix\n"
    ".global png_read_end\n"
    ".type png_read_end @function\n"
    "png_read_end:\n"
    "jmp qword ptr [rip + __ptr_png_read_end]\n");

static __attribute__ ((used)) void* __ptr_png_read_image;
asm(".intel_syntax noprefix\n"
    ".global png_read_image\n"
    ".type png_read_image @function\n"
    "png_read_image:\n"
    "jmp qword ptr [rip + __ptr_png_read_image]\n");

static __attribute__ ((used)) void* __ptr_png_read_info;
asm(".intel_syntax noprefix\n"
    ".global png_read_info\n"
    ".type png_read_info @function\n"
    "png_read_info:\n"
    "jmp qword ptr [rip + __ptr_png_read_info]\n");

static __attribute__ ((used)) void* __ptr_png_read_row;
asm(".intel_syntax noprefix\n"
    ".global png_read_row\n"
    ".type png_read_row @function\n"
    "png_read_row:\n"
    "jmp qword ptr [rip + __ptr_png_read_row]\n");

static __attribute__ ((used)) void* __ptr_png_read_rows;
asm(".intel_syntax noprefix\n"
    ".global png_read_rows\n"
    ".type png_read_rows @function\n"
    "png_read_rows:\n"
    "jmp qword ptr [rip + __ptr_png_read_rows]\n");

static __attribute__ ((used)) void* __ptr_png_read_update_info;
asm(".intel_syntax noprefix\n"
    ".global png_read_update_info\n"
    ".type png_read_update_info @function\n"
    "png_read_update_info:\n"
    "jmp qword ptr [rip + __ptr_png_read_update_info]\n");

static __attribute__ ((used)) void* __ptr_png_save_uint_16;
asm(".intel_syntax noprefix\n"
    ".global png_save_uint_16\n"
    ".type png_save_uint_16 @function\n"
    "png_save_uint_16:\n"
    "jmp qword ptr [rip + __ptr_png_save_uint_16]\n");

static __attribute__ ((used)) void* __ptr_png_save_uint_32;
asm(".intel_syntax noprefix\n"
    ".global png_save_uint_32\n"
    ".type png_save_uint_32 @function\n"
    "png_save_uint_32:\n"
    "jmp qword ptr [rip + __ptr_png_save_uint_32]\n");

static __attribute__ ((used)) void* __ptr_png_set_IHDR;
asm(".intel_syntax noprefix\n"
    ".global png_set_IHDR\n"
    ".type png_set_IHDR @function\n"
    "png_set_IHDR:\n"
    "jmp qword ptr [rip + __ptr_png_set_IHDR]\n");

static __attribute__ ((used)) void* __ptr_png_set_bKGD;
asm(".intel_syntax noprefix\n"
    ".global png_set_bKGD\n"
    ".type png_set_bKGD @function\n"
    "png_set_bKGD:\n"
    "jmp qword ptr [rip + __ptr_png_set_bKGD]\n");

static __attribute__ ((used)) void* __ptr_png_set_background;
asm(".intel_syntax noprefix\n"
    ".global png_set_background\n"
    ".type png_set_background @function\n"
    "png_set_background:\n"
    "jmp qword ptr [rip + __ptr_png_set_background]\n");

static __attribute__ ((used)) void* __ptr_png_set_bgr;
asm(".intel_syntax noprefix\n"
    ".global png_set_bgr\n"
    ".type png_set_bgr @function\n"
    "png_set_bgr:\n"
    "jmp qword ptr [rip + __ptr_png_set_bgr]\n");

static __attribute__ ((used)) void* __ptr_png_set_chunk_cache_max;
asm(".intel_syntax noprefix\n"
    ".global png_set_chunk_cache_max\n"
    ".type png_set_chunk_cache_max @function\n"
    "png_set_chunk_cache_max:\n"
    "jmp qword ptr [rip + __ptr_png_set_chunk_cache_max]\n");

static __attribute__ ((used)) void* __ptr_png_set_chunk_malloc_max;
asm(".intel_syntax noprefix\n"
    ".global png_set_chunk_malloc_max\n"
    ".type png_set_chunk_malloc_max @function\n"
    "png_set_chunk_malloc_max:\n"
    "jmp qword ptr [rip + __ptr_png_set_chunk_malloc_max]\n");

static __attribute__ ((used)) void* __ptr_png_set_crc_action;
asm(".intel_syntax noprefix\n"
    ".global png_set_crc_action\n"
    ".type png_set_crc_action @function\n"
    "png_set_crc_action:\n"
    "jmp qword ptr [rip + __ptr_png_set_crc_action]\n");

static __attribute__ ((used)) void* __ptr_png_set_expand;
asm(".intel_syntax noprefix\n"
    ".global png_set_expand\n"
    ".type png_set_expand @function\n"
    "png_set_expand:\n"
    "jmp qword ptr [rip + __ptr_png_set_expand]\n");

static __attribute__ ((used)) void* __ptr_png_set_expand_16;
asm(".intel_syntax noprefix\n"
    ".global png_set_expand_16\n"
    ".type png_set_expand_16 @function\n"
    "png_set_expand_16:\n"
    "jmp qword ptr [rip + __ptr_png_set_expand_16]\n");

static __attribute__ ((used)) void* __ptr_png_set_expand_gray_1_2_4_to_8;
asm(".intel_syntax noprefix\n"
    ".global png_set_expand_gray_1_2_4_to_8\n"
    ".type png_set_expand_gray_1_2_4_to_8 @function\n"
    "png_set_expand_gray_1_2_4_to_8:\n"
    "jmp qword ptr [rip + __ptr_png_set_expand_gray_1_2_4_to_8]\n");

static __attribute__ ((used)) void* __ptr_png_set_filler;
asm(".intel_syntax noprefix\n"
    ".global png_set_filler\n"
    ".type png_set_filler @function\n"
    "png_set_filler:\n"
    "jmp qword ptr [rip + __ptr_png_set_filler]\n");

static __attribute__ ((used)) void* __ptr_png_set_filter;
asm(".intel_syntax noprefix\n"
    ".global png_set_filter\n"
    ".type png_set_filter @function\n"
    "png_set_filter:\n"
    "jmp qword ptr [rip + __ptr_png_set_filter]\n");

static __attribute__ ((used)) void* __ptr_png_set_gAMA;
asm(".intel_syntax noprefix\n"
    ".global png_set_gAMA\n"
    ".type png_set_gAMA @function\n"
    "png_set_gAMA:\n"
    "jmp qword ptr [rip + __ptr_png_set_gAMA]\n");

static __attribute__ ((used)) void* __ptr_png_set_gamma;
asm(".intel_syntax noprefix\n"
    ".global png_set_gamma\n"
    ".type png_set_gamma @function\n"
    "png_set_gamma:\n"
    "jmp qword ptr [rip + __ptr_png_set_gamma]\n");

static __attribute__ ((used)) void* __ptr_png_set_gray_to_rgb;
asm(".intel_syntax noprefix\n"
    ".global png_set_gray_to_rgb\n"
    ".type png_set_gray_to_rgb @function\n"
    "png_set_gray_to_rgb:\n"
    "jmp qword ptr [rip + __ptr_png_set_gray_to_rgb]\n");

static __attribute__ ((used)) void* __ptr_png_set_interlace_handling;
asm(".intel_syntax noprefix\n"
    ".global png_set_interlace_handling\n"
    ".type png_set_interlace_handling @function\n"
    "png_set_interlace_handling:\n"
    "jmp qword ptr [rip + __ptr_png_set_interlace_handling]\n");

static __attribute__ ((used)) void* __ptr_png_set_invalid;
asm(".intel_syntax noprefix\n"
    ".global png_set_invalid\n"
    ".type png_set_invalid @function\n"
    "png_set_invalid:\n"
    "jmp qword ptr [rip + __ptr_png_set_invalid]\n");

static __attribute__ ((used)) void* __ptr_png_set_keep_unknown_chunks;
asm(".intel_syntax noprefix\n"
    ".global png_set_keep_unknown_chunks\n"
    ".type png_set_keep_unknown_chunks @function\n"
    "png_set_keep_unknown_chunks:\n"
    "jmp qword ptr [rip + __ptr_png_set_keep_unknown_chunks]\n");

static __attribute__ ((used)) void* __ptr_png_set_longjmp_fn;
asm(".intel_syntax noprefix\n"
    ".global png_set_longjmp_fn\n"
    ".type png_set_longjmp_fn @function\n"
    "png_set_longjmp_fn:\n"
    "jmp qword ptr [rip + __ptr_png_set_longjmp_fn]\n");

static __attribute__ ((used)) void* __ptr_png_set_packing;
asm(".intel_syntax noprefix\n"
    ".global png_set_packing\n"
    ".type png_set_packing @function\n"
    "png_set_packing:\n"
    "jmp qword ptr [rip + __ptr_png_set_packing]\n");

static __attribute__ ((used)) void* __ptr_png_set_packswap;
asm(".intel_syntax noprefix\n"
    ".global png_set_packswap\n"
    ".type png_set_packswap @function\n"
    "png_set_packswap:\n"
    "jmp qword ptr [rip + __ptr_png_set_packswap]\n");

static __attribute__ ((used)) void* __ptr_png_set_palette_to_rgb;
asm(".intel_syntax noprefix\n"
    ".global png_set_palette_to_rgb\n"
    ".type png_set_palette_to_rgb @function\n"
    "png_set_palette_to_rgb:\n"
    "jmp qword ptr [rip + __ptr_png_set_palette_to_rgb]\n");

static __attribute__ ((used)) void* __ptr_png_set_progressive_read_fn;
asm(".intel_syntax noprefix\n"
    ".global png_set_progressive_read_fn\n"
    ".type png_set_progressive_read_fn @function\n"
    "png_set_progressive_read_fn:\n"
    "jmp qword ptr [rip + __ptr_png_set_progressive_read_fn]\n");

static __attribute__ ((used)) void* __ptr_png_set_read_fn;
asm(".intel_syntax noprefix\n"
    ".global png_set_read_fn\n"
    ".type png_set_read_fn @function\n"
    "png_set_read_fn:\n"
    "jmp qword ptr [rip + __ptr_png_set_read_fn]\n");

static __attribute__ ((used)) void* __ptr_png_set_read_user_chunk_fn;
asm(".intel_syntax noprefix\n"
    ".global png_set_read_user_chunk_fn\n"
    ".type png_set_read_user_chunk_fn @function\n"
    "png_set_read_user_chunk_fn:\n"
    "jmp qword ptr [rip + __ptr_png_set_read_user_chunk_fn]\n");

static __attribute__ ((used)) void* __ptr_png_set_read_user_transform_fn;
asm(".intel_syntax noprefix\n"
    ".global png_set_read_user_transform_fn\n"
    ".type png_set_read_user_transform_fn @function\n"
    "png_set_read_user_transform_fn:\n"
    "jmp qword ptr [rip + __ptr_png_set_read_user_transform_fn]\n");

static __attribute__ ((used)) void* __ptr_png_set_shift;
asm(".intel_syntax noprefix\n"
    ".global png_set_shift\n"
    ".type png_set_shift @function\n"
    "png_set_shift:\n"
    "jmp qword ptr [rip + __ptr_png_set_shift]\n");

static __attribute__ ((used)) void* __ptr_png_set_strip_16;
asm(".intel_syntax noprefix\n"
    ".global png_set_strip_16\n"
    ".type png_set_strip_16 @function\n"
    "png_set_strip_16:\n"
    "jmp qword ptr [rip + __ptr_png_set_strip_16]\n");

static __attribute__ ((used)) void* __ptr_png_set_swap;
asm(".intel_syntax noprefix\n"
    ".global png_set_swap\n"
    ".type png_set_swap @function\n"
    "png_set_swap:\n"
    "jmp qword ptr [rip + __ptr_png_set_swap]\n");

static __attribute__ ((used)) void* __ptr_png_set_tRNS_to_alpha;
asm(".intel_syntax noprefix\n"
    ".global png_set_tRNS_to_alpha\n"
    ".type png_set_tRNS_to_alpha @function\n"
    "png_set_tRNS_to_alpha:\n"
    "jmp qword ptr [rip + __ptr_png_set_tRNS_to_alpha]\n");

static __attribute__ ((used)) void* __ptr_png_set_text;
asm(".intel_syntax noprefix\n"
    ".global png_set_text\n"
    ".type png_set_text @function\n"
    "png_set_text:\n"
    "jmp qword ptr [rip + __ptr_png_set_text]\n");

static __attribute__ ((used)) void* __ptr_png_set_user_limits;
asm(".intel_syntax noprefix\n"
    ".global png_set_user_limits\n"
    ".type png_set_user_limits @function\n"
    "png_set_user_limits:\n"
    "jmp qword ptr [rip + __ptr_png_set_user_limits]\n");

static __attribute__ ((used)) void* __ptr_png_set_write_fn;
asm(".intel_syntax noprefix\n"
    ".global png_set_write_fn\n"
    ".type png_set_write_fn @function\n"
    "png_set_write_fn:\n"
    "jmp qword ptr [rip + __ptr_png_set_write_fn]\n");

static __attribute__ ((used)) void* __ptr_png_set_write_user_transform_fn;
asm(".intel_syntax noprefix\n"
    ".global png_set_write_user_transform_fn\n"
    ".type png_set_write_user_transform_fn @function\n"
    "png_set_write_user_transform_fn:\n"
    "jmp qword ptr [rip + __ptr_png_set_write_user_transform_fn]\n");

static __attribute__ ((used)) void* __ptr_png_start_read_image;
asm(".intel_syntax noprefix\n"
    ".global png_start_read_image\n"
    ".type png_start_read_image @function\n"
    "png_start_read_image:\n"
    "jmp qword ptr [rip + __ptr_png_start_read_image]\n");

static __attribute__ ((used)) void* __ptr_png_warning;
asm(".intel_syntax noprefix\n"
    ".global png_warning\n"
    ".type png_warning @function\n"
    "png_warning:\n"
    "jmp qword ptr [rip + __ptr_png_warning]\n");

static __attribute__ ((used)) void* __ptr_png_write_end;
asm(".intel_syntax noprefix\n"
    ".global png_write_end\n"
    ".type png_write_end @function\n"
    "png_write_end:\n"
    "jmp qword ptr [rip + __ptr_png_write_end]\n");

static __attribute__ ((used)) void* __ptr_png_write_image;
asm(".intel_syntax noprefix\n"
    ".global png_write_image\n"
    ".type png_write_image @function\n"
    "png_write_image:\n"
    "jmp qword ptr [rip + __ptr_png_write_image]\n");

static __attribute__ ((used)) void* __ptr_png_write_info;
asm(".intel_syntax noprefix\n"
    ".global png_write_info\n"
    ".type png_write_info @function\n"
    "png_write_info:\n"
    "jmp qword ptr [rip + __ptr_png_write_info]\n");

static __attribute__ ((used)) void* __ptr_png_write_row;
asm(".intel_syntax noprefix\n"
    ".global png_write_row\n"
    ".type png_write_row @function\n"
    "png_write_row:\n"
    "jmp qword ptr [rip + __ptr_png_write_row]\n");

static __attribute__ ((used)) void* __ptr_png_write_rows;
asm(".intel_syntax noprefix\n"
    ".global png_write_rows\n"
    ".type png_write_rows @function\n"
    "png_write_rows:\n"
    "jmp qword ptr [rip + __ptr_png_write_rows]\n");

static unsigned short __handle = 0;
static void __attribute__((constructor(104)))
__constructor(void) {
  if(sprx_dlopen("libpng16", &__handle)) return;
  if(sprx_dlsym(__handle, "e4j-rkRbvNw", &__ptr_png_calloc)) return;
  if(sprx_dlsym(__handle, "Ce9OAueql30", &__ptr_png_create_info_struct)) return;
  if(sprx_dlsym(__handle, "pgrAmiR9KXc", &__ptr_png_create_read_struct)) return;
  if(sprx_dlsym(__handle, "fnxQfHHlzpE", &__ptr_png_create_read_struct_2)) return;
  if(sprx_dlsym(__handle, "d0FY5xvaA28", &__ptr_png_create_write_struct)) return;
  if(sprx_dlsym(__handle, "NNcJnwqxmjY", &__ptr_png_create_write_struct_2)) return;
  if(sprx_dlsym(__handle, "WqDYv9bWc1E", &__ptr_png_destroy_read_struct)) return;
  if(sprx_dlsym(__handle, "bF8-X1KRT+s", &__ptr_png_destroy_write_struct)) return;
  if(sprx_dlsym(__handle, "3esC3xhwwac", &__ptr_png_error)) return;
  if(sprx_dlsym(__handle, "Ofz1AcKLESA", &__ptr_png_free)) return;
  if(sprx_dlsym(__handle, "pU2Smb1a7jE", &__ptr_png_free_data)) return;
  if(sprx_dlsym(__handle, "+TF60FmY-hk", &__ptr_png_free_default)) return;
  if(sprx_dlsym(__handle, "joDkiMqALkM", &__ptr_png_get_IHDR)) return;
  if(sprx_dlsym(__handle, "MIwCdFQOMJM", &__ptr_png_get_PLTE)) return;
  if(sprx_dlsym(__handle, "1FDLh7g440s", &__ptr_png_get_bit_depth)) return;
  if(sprx_dlsym(__handle, "8VoOXhaFbp8", &__ptr_png_get_channels)) return;
  if(sprx_dlsym(__handle, "THO0RsxD6hY", &__ptr_png_get_color_type)) return;
  if(sprx_dlsym(__handle, "ntw5MF+O8pg", &__ptr_png_get_error_ptr)) return;
  if(sprx_dlsym(__handle, "C-4AXvmxXK4", &__ptr_png_get_filter_type)) return;
  if(sprx_dlsym(__handle, "AWHt8gDYjEU", &__ptr_png_get_gAMA)) return;
  if(sprx_dlsym(__handle, "nWwBEkoMtCE", &__ptr_png_get_iCCP)) return;
  if(sprx_dlsym(__handle, "5BlrhmRn+ww", &__ptr_png_get_image_height)) return;
  if(sprx_dlsym(__handle, "zFwPB6djiUE", &__ptr_png_get_image_width)) return;
  if(sprx_dlsym(__handle, "0ztgt9yYb1s", &__ptr_png_get_interlace_type)) return;
  if(sprx_dlsym(__handle, "zo2La0t9A5E", &__ptr_png_get_io_ptr)) return;
  if(sprx_dlsym(__handle, "FTvuO6kEYc8", &__ptr_png_get_progressive_ptr)) return;
  if(sprx_dlsym(__handle, "-pVA-QEcWok", &__ptr_png_get_rows)) return;
  if(sprx_dlsym(__handle, "gEn4o7mSMnY", &__ptr_png_get_sBIT)) return;
  if(sprx_dlsym(__handle, "848+jm1RbPw", &__ptr_png_get_sPLT)) return;
  if(sprx_dlsym(__handle, "ckcuWdb1US4", &__ptr_png_get_sRGB)) return;
  if(sprx_dlsym(__handle, "CAx7X0QmDNg", &__ptr_png_get_tIME)) return;
  if(sprx_dlsym(__handle, "amUx1Imsa9E", &__ptr_png_get_tRNS)) return;
  if(sprx_dlsym(__handle, "2QGFkodBuuM", &__ptr_png_get_text)) return;
  if(sprx_dlsym(__handle, "hGThy3P3lt4", &__ptr_png_get_uint_16)) return;
  if(sprx_dlsym(__handle, "jbGv+QGGopI", &__ptr_png_get_uint_32)) return;
  if(sprx_dlsym(__handle, "bxAfmsH5wS4", &__ptr_png_get_user_chunk_ptr)) return;
  if(sprx_dlsym(__handle, "5ux94o4IbC0", &__ptr_png_get_valid)) return;
  if(sprx_dlsym(__handle, "tZdMwygCW2w", &__ptr_png_init_io)) return;
  if(sprx_dlsym(__handle, "si5cGkRLSH8", &__ptr_png_longjmp)) return;
  if(sprx_dlsym(__handle, "iJbG4E+cTL4", &__ptr_png_malloc)) return;
  if(sprx_dlsym(__handle, "gC2k54oPeFY", &__ptr_png_malloc_default)) return;
  if(sprx_dlsym(__handle, "eIphLYOgAWM", &__ptr_png_process_data)) return;
  if(sprx_dlsym(__handle, "dQJAe3CGHPo", &__ptr_png_process_data_pause)) return;
  if(sprx_dlsym(__handle, "yZ4EJ0rUh9c", &__ptr_png_progressive_combine_row)) return;
  if(sprx_dlsym(__handle, "n+JGk7gk9gs", &__ptr_png_read_end)) return;
  if(sprx_dlsym(__handle, "b3DGdzmYGzE", &__ptr_png_read_image)) return;
  if(sprx_dlsym(__handle, "UcyA+RDgXHg", &__ptr_png_read_info)) return;
  if(sprx_dlsym(__handle, "0wc3eo2S-RE", &__ptr_png_read_row)) return;
  if(sprx_dlsym(__handle, "o1WZhqSSUcI", &__ptr_png_read_rows)) return;
  if(sprx_dlsym(__handle, "S+plqe4pVgs", &__ptr_png_read_update_info)) return;
  if(sprx_dlsym(__handle, "V5ojK9mvCJI", &__ptr_png_save_uint_16)) return;
  if(sprx_dlsym(__handle, "N7gzoBpy+vc", &__ptr_png_save_uint_32)) return;
  if(sprx_dlsym(__handle, "6-KDz3WqEAc", &__ptr_png_set_IHDR)) return;
  if(sprx_dlsym(__handle, "4B9olYHnHnQ", &__ptr_png_set_bKGD)) return;
  if(sprx_dlsym(__handle, "RJz0iQpTa8M", &__ptr_png_set_background)) return;
  if(sprx_dlsym(__handle, "yLAMIlW84rc", &__ptr_png_set_bgr)) return;
  if(sprx_dlsym(__handle, "G8BTwv-UHhU", &__ptr_png_set_chunk_cache_max)) return;
  if(sprx_dlsym(__handle, "yI6EdumLZDY", &__ptr_png_set_chunk_malloc_max)) return;
  if(sprx_dlsym(__handle, "W0yjXro3i4E", &__ptr_png_set_crc_action)) return;
  if(sprx_dlsym(__handle, "-4KVgXHGMdw", &__ptr_png_set_expand)) return;
  if(sprx_dlsym(__handle, "fvpjTvRYrOs", &__ptr_png_set_expand_16)) return;
  if(sprx_dlsym(__handle, "3uKk4puCQoQ", &__ptr_png_set_expand_gray_1_2_4_to_8)) return;
  if(sprx_dlsym(__handle, "JmOLVFL6pEY", &__ptr_png_set_filler)) return;
  if(sprx_dlsym(__handle, "4BuSoL+GHSE", &__ptr_png_set_filter)) return;
  if(sprx_dlsym(__handle, "k6eJxKaYRro", &__ptr_png_set_gAMA)) return;
  if(sprx_dlsym(__handle, "7RUwcMgn2J4", &__ptr_png_set_gamma)) return;
  if(sprx_dlsym(__handle, "68d4tUskfS0", &__ptr_png_set_gray_to_rgb)) return;
  if(sprx_dlsym(__handle, "SSI2xRfgKJo", &__ptr_png_set_interlace_handling)) return;
  if(sprx_dlsym(__handle, "UWnY-csxdhk", &__ptr_png_set_invalid)) return;
  if(sprx_dlsym(__handle, "a+Ns-FwjHwM", &__ptr_png_set_keep_unknown_chunks)) return;
  if(sprx_dlsym(__handle, "0rfZ5SbLBN4", &__ptr_png_set_longjmp_fn)) return;
  if(sprx_dlsym(__handle, "-9BHlFnLjVg", &__ptr_png_set_packing)) return;
  if(sprx_dlsym(__handle, "SexflgihwlY", &__ptr_png_set_packswap)) return;
  if(sprx_dlsym(__handle, "PosyHI1Qm2A", &__ptr_png_set_palette_to_rgb)) return;
  if(sprx_dlsym(__handle, "r3SJxnlaTlg", &__ptr_png_set_progressive_read_fn)) return;
  if(sprx_dlsym(__handle, "CxxHgMg2FS0", &__ptr_png_set_read_fn)) return;
  if(sprx_dlsym(__handle, "j-zFZRfydsU", &__ptr_png_set_read_user_chunk_fn)) return;
  if(sprx_dlsym(__handle, "H8-HSuGeyy0", &__ptr_png_set_read_user_transform_fn)) return;
  if(sprx_dlsym(__handle, "KZ2QQCkqaiA", &__ptr_png_set_shift)) return;
  if(sprx_dlsym(__handle, "RnOtQ1-DQSs", &__ptr_png_set_strip_16)) return;
  if(sprx_dlsym(__handle, "0YEXGwJHdY4", &__ptr_png_set_swap)) return;
  if(sprx_dlsym(__handle, "NYQSe+APp8U", &__ptr_png_set_tRNS_to_alpha)) return;
  if(sprx_dlsym(__handle, "0qcQlD9MKWU", &__ptr_png_set_text)) return;
  if(sprx_dlsym(__handle, "oDVaBU-8ZOo", &__ptr_png_set_user_limits)) return;
  if(sprx_dlsym(__handle, "djm5QUVG74A", &__ptr_png_set_write_fn)) return;
  if(sprx_dlsym(__handle, "2MwwGOkHrvA", &__ptr_png_set_write_user_transform_fn)) return;
  if(sprx_dlsym(__handle, "uD3Iz6lyy0Q", &__ptr_png_start_read_image)) return;
  if(sprx_dlsym(__handle, "EZ94ewo1vHE", &__ptr_png_warning)) return;
  if(sprx_dlsym(__handle, "0teUd1yBOKg", &__ptr_png_write_end)) return;
  if(sprx_dlsym(__handle, "nleYBZY-BsY", &__ptr_png_write_image)) return;
  if(sprx_dlsym(__handle, "Bdn6SlO1+NQ", &__ptr_png_write_info)) return;
  if(sprx_dlsym(__handle, "N09SXXRD6VI", &__ptr_png_write_row)) return;
  if(sprx_dlsym(__handle, "9qACCyOUAx8", &__ptr_png_write_rows)) return;
}

static void __attribute__((destructor(104)))
__destructor(void) {
  sprx_dlclose(__handle);
}
