/*
 This file was generated by genstub.py, do not edit manually!
*/

int sprx_dlsym(unsigned int handle, const char *nid, void *addr);
int sprx_dlopen(const char* libname, unsigned short *handle);
int sprx_dlclose(unsigned int handle);

static __attribute__ ((used)) void* __ptr_sceNpTrophy2AbortHandle;
asm(".intel_syntax noprefix\n"
    ".global sceNpTrophy2AbortHandle\n"
    ".type sceNpTrophy2AbortHandle @function\n"
    "sceNpTrophy2AbortHandle:\n"
    "jmp qword ptr [rip + __ptr_sceNpTrophy2AbortHandle]\n");

static __attribute__ ((used)) void* __ptr_sceNpTrophy2CreateContext;
asm(".intel_syntax noprefix\n"
    ".global sceNpTrophy2CreateContext\n"
    ".type sceNpTrophy2CreateContext @function\n"
    "sceNpTrophy2CreateContext:\n"
    "jmp qword ptr [rip + __ptr_sceNpTrophy2CreateContext]\n");

static __attribute__ ((used)) void* __ptr_sceNpTrophy2CreateHandle;
asm(".intel_syntax noprefix\n"
    ".global sceNpTrophy2CreateHandle\n"
    ".type sceNpTrophy2CreateHandle @function\n"
    "sceNpTrophy2CreateHandle:\n"
    "jmp qword ptr [rip + __ptr_sceNpTrophy2CreateHandle]\n");

static __attribute__ ((used)) void* __ptr_sceNpTrophy2DestroyContext;
asm(".intel_syntax noprefix\n"
    ".global sceNpTrophy2DestroyContext\n"
    ".type sceNpTrophy2DestroyContext @function\n"
    "sceNpTrophy2DestroyContext:\n"
    "jmp qword ptr [rip + __ptr_sceNpTrophy2DestroyContext]\n");

static __attribute__ ((used)) void* __ptr_sceNpTrophy2DestroyHandle;
asm(".intel_syntax noprefix\n"
    ".global sceNpTrophy2DestroyHandle\n"
    ".type sceNpTrophy2DestroyHandle @function\n"
    "sceNpTrophy2DestroyHandle:\n"
    "jmp qword ptr [rip + __ptr_sceNpTrophy2DestroyHandle]\n");

static __attribute__ ((used)) void* __ptr_sceNpTrophy2GetGameIcon;
asm(".intel_syntax noprefix\n"
    ".global sceNpTrophy2GetGameIcon\n"
    ".type sceNpTrophy2GetGameIcon @function\n"
    "sceNpTrophy2GetGameIcon:\n"
    "jmp qword ptr [rip + __ptr_sceNpTrophy2GetGameIcon]\n");

static __attribute__ ((used)) void* __ptr_sceNpTrophy2GetGameInfo;
asm(".intel_syntax noprefix\n"
    ".global sceNpTrophy2GetGameInfo\n"
    ".type sceNpTrophy2GetGameInfo @function\n"
    "sceNpTrophy2GetGameInfo:\n"
    "jmp qword ptr [rip + __ptr_sceNpTrophy2GetGameInfo]\n");

static __attribute__ ((used)) void* __ptr_sceNpTrophy2GetGroupIcon;
asm(".intel_syntax noprefix\n"
    ".global sceNpTrophy2GetGroupIcon\n"
    ".type sceNpTrophy2GetGroupIcon @function\n"
    "sceNpTrophy2GetGroupIcon:\n"
    "jmp qword ptr [rip + __ptr_sceNpTrophy2GetGroupIcon]\n");

static __attribute__ ((used)) void* __ptr_sceNpTrophy2GetGroupInfo;
asm(".intel_syntax noprefix\n"
    ".global sceNpTrophy2GetGroupInfo\n"
    ".type sceNpTrophy2GetGroupInfo @function\n"
    "sceNpTrophy2GetGroupInfo:\n"
    "jmp qword ptr [rip + __ptr_sceNpTrophy2GetGroupInfo]\n");

static __attribute__ ((used)) void* __ptr_sceNpTrophy2GetGroupInfoArray;
asm(".intel_syntax noprefix\n"
    ".global sceNpTrophy2GetGroupInfoArray\n"
    ".type sceNpTrophy2GetGroupInfoArray @function\n"
    "sceNpTrophy2GetGroupInfoArray:\n"
    "jmp qword ptr [rip + __ptr_sceNpTrophy2GetGroupInfoArray]\n");

static __attribute__ ((used)) void* __ptr_sceNpTrophy2GetRewardIcon;
asm(".intel_syntax noprefix\n"
    ".global sceNpTrophy2GetRewardIcon\n"
    ".type sceNpTrophy2GetRewardIcon @function\n"
    "sceNpTrophy2GetRewardIcon:\n"
    "jmp qword ptr [rip + __ptr_sceNpTrophy2GetRewardIcon]\n");

static __attribute__ ((used)) void* __ptr_sceNpTrophy2GetTrophyIcon;
asm(".intel_syntax noprefix\n"
    ".global sceNpTrophy2GetTrophyIcon\n"
    ".type sceNpTrophy2GetTrophyIcon @function\n"
    "sceNpTrophy2GetTrophyIcon:\n"
    "jmp qword ptr [rip + __ptr_sceNpTrophy2GetTrophyIcon]\n");

static __attribute__ ((used)) void* __ptr_sceNpTrophy2GetTrophyInfo;
asm(".intel_syntax noprefix\n"
    ".global sceNpTrophy2GetTrophyInfo\n"
    ".type sceNpTrophy2GetTrophyInfo @function\n"
    "sceNpTrophy2GetTrophyInfo:\n"
    "jmp qword ptr [rip + __ptr_sceNpTrophy2GetTrophyInfo]\n");

static __attribute__ ((used)) void* __ptr_sceNpTrophy2GetTrophyInfoArray;
asm(".intel_syntax noprefix\n"
    ".global sceNpTrophy2GetTrophyInfoArray\n"
    ".type sceNpTrophy2GetTrophyInfoArray @function\n"
    "sceNpTrophy2GetTrophyInfoArray:\n"
    "jmp qword ptr [rip + __ptr_sceNpTrophy2GetTrophyInfoArray]\n");

static __attribute__ ((used)) void* __ptr_sceNpTrophy2RegisterContext;
asm(".intel_syntax noprefix\n"
    ".global sceNpTrophy2RegisterContext\n"
    ".type sceNpTrophy2RegisterContext @function\n"
    "sceNpTrophy2RegisterContext:\n"
    "jmp qword ptr [rip + __ptr_sceNpTrophy2RegisterContext]\n");

static __attribute__ ((used)) void* __ptr_sceNpTrophy2RegisterUnlockCallback;
asm(".intel_syntax noprefix\n"
    ".global sceNpTrophy2RegisterUnlockCallback\n"
    ".type sceNpTrophy2RegisterUnlockCallback @function\n"
    "sceNpTrophy2RegisterUnlockCallback:\n"
    "jmp qword ptr [rip + __ptr_sceNpTrophy2RegisterUnlockCallback]\n");

static __attribute__ ((used)) void* __ptr_sceNpTrophy2ShowTrophyList;
asm(".intel_syntax noprefix\n"
    ".global sceNpTrophy2ShowTrophyList\n"
    ".type sceNpTrophy2ShowTrophyList @function\n"
    "sceNpTrophy2ShowTrophyList:\n"
    "jmp qword ptr [rip + __ptr_sceNpTrophy2ShowTrophyList]\n");

static __attribute__ ((used)) void* __ptr_sceNpTrophy2SystemAbortHandle;
asm(".intel_syntax noprefix\n"
    ".global sceNpTrophy2SystemAbortHandle\n"
    ".type sceNpTrophy2SystemAbortHandle @function\n"
    "sceNpTrophy2SystemAbortHandle:\n"
    "jmp qword ptr [rip + __ptr_sceNpTrophy2SystemAbortHandle]\n");

static __attribute__ ((used)) void* __ptr_sceNpTrophy2SystemBuildGroupIconUri;
asm(".intel_syntax noprefix\n"
    ".global sceNpTrophy2SystemBuildGroupIconUri\n"
    ".type sceNpTrophy2SystemBuildGroupIconUri @function\n"
    "sceNpTrophy2SystemBuildGroupIconUri:\n"
    "jmp qword ptr [rip + __ptr_sceNpTrophy2SystemBuildGroupIconUri]\n");

static __attribute__ ((used)) void* __ptr_sceNpTrophy2SystemBuildRewardIconUri;
asm(".intel_syntax noprefix\n"
    ".global sceNpTrophy2SystemBuildRewardIconUri\n"
    ".type sceNpTrophy2SystemBuildRewardIconUri @function\n"
    "sceNpTrophy2SystemBuildRewardIconUri:\n"
    "jmp qword ptr [rip + __ptr_sceNpTrophy2SystemBuildRewardIconUri]\n");

static __attribute__ ((used)) void* __ptr_sceNpTrophy2SystemBuildTrophyIconUri;
asm(".intel_syntax noprefix\n"
    ".global sceNpTrophy2SystemBuildTrophyIconUri\n"
    ".type sceNpTrophy2SystemBuildTrophyIconUri @function\n"
    "sceNpTrophy2SystemBuildTrophyIconUri:\n"
    "jmp qword ptr [rip + __ptr_sceNpTrophy2SystemBuildTrophyIconUri]\n");

static __attribute__ ((used)) void* __ptr_sceNpTrophy2SystemCheckCallback;
asm(".intel_syntax noprefix\n"
    ".global sceNpTrophy2SystemCheckCallback\n"
    ".type sceNpTrophy2SystemCheckCallback @function\n"
    "sceNpTrophy2SystemCheckCallback:\n"
    "jmp qword ptr [rip + __ptr_sceNpTrophy2SystemCheckCallback]\n");

static __attribute__ ((used)) void* __ptr_sceNpTrophy2SystemCheckNetSyncTitles;
asm(".intel_syntax noprefix\n"
    ".global sceNpTrophy2SystemCheckNetSyncTitles\n"
    ".type sceNpTrophy2SystemCheckNetSyncTitles @function\n"
    "sceNpTrophy2SystemCheckNetSyncTitles:\n"
    "jmp qword ptr [rip + __ptr_sceNpTrophy2SystemCheckNetSyncTitles]\n");

static __attribute__ ((used)) void* __ptr_sceNpTrophy2SystemCreateContext;
asm(".intel_syntax noprefix\n"
    ".global sceNpTrophy2SystemCreateContext\n"
    ".type sceNpTrophy2SystemCreateContext @function\n"
    "sceNpTrophy2SystemCreateContext:\n"
    "jmp qword ptr [rip + __ptr_sceNpTrophy2SystemCreateContext]\n");

static __attribute__ ((used)) void* __ptr_sceNpTrophy2SystemCreateHandle;
asm(".intel_syntax noprefix\n"
    ".global sceNpTrophy2SystemCreateHandle\n"
    ".type sceNpTrophy2SystemCreateHandle @function\n"
    "sceNpTrophy2SystemCreateHandle:\n"
    "jmp qword ptr [rip + __ptr_sceNpTrophy2SystemCreateHandle]\n");

static __attribute__ ((used)) void* __ptr_sceNpTrophy2SystemDebugLockTrophy;
asm(".intel_syntax noprefix\n"
    ".global sceNpTrophy2SystemDebugLockTrophy\n"
    ".type sceNpTrophy2SystemDebugLockTrophy @function\n"
    "sceNpTrophy2SystemDebugLockTrophy:\n"
    "jmp qword ptr [rip + __ptr_sceNpTrophy2SystemDebugLockTrophy]\n");

static __attribute__ ((used)) void* __ptr_sceNpTrophy2SystemDebugUnlockTrophy;
asm(".intel_syntax noprefix\n"
    ".global sceNpTrophy2SystemDebugUnlockTrophy\n"
    ".type sceNpTrophy2SystemDebugUnlockTrophy @function\n"
    "sceNpTrophy2SystemDebugUnlockTrophy:\n"
    "jmp qword ptr [rip + __ptr_sceNpTrophy2SystemDebugUnlockTrophy]\n");

static __attribute__ ((used)) void* __ptr_sceNpTrophy2SystemDestroyContext;
asm(".intel_syntax noprefix\n"
    ".global sceNpTrophy2SystemDestroyContext\n"
    ".type sceNpTrophy2SystemDestroyContext @function\n"
    "sceNpTrophy2SystemDestroyContext:\n"
    "jmp qword ptr [rip + __ptr_sceNpTrophy2SystemDestroyContext]\n");

static __attribute__ ((used)) void* __ptr_sceNpTrophy2SystemGetTrophyDetails;
asm(".intel_syntax noprefix\n"
    ".global sceNpTrophy2SystemGetTrophyDetails\n"
    ".type sceNpTrophy2SystemGetTrophyDetails @function\n"
    "sceNpTrophy2SystemGetTrophyDetails:\n"
    "jmp qword ptr [rip + __ptr_sceNpTrophy2SystemGetTrophyDetails]\n");

static __attribute__ ((used)) void* __ptr_sceNpTrophy2SystemGetTrophyGroupConf;
asm(".intel_syntax noprefix\n"
    ".global sceNpTrophy2SystemGetTrophyGroupConf\n"
    ".type sceNpTrophy2SystemGetTrophyGroupConf @function\n"
    "sceNpTrophy2SystemGetTrophyGroupConf:\n"
    "jmp qword ptr [rip + __ptr_sceNpTrophy2SystemGetTrophyGroupConf]\n");

static __attribute__ ((used)) void* __ptr_sceNpTrophy2SystemGetTrophySetArray;
asm(".intel_syntax noprefix\n"
    ".global sceNpTrophy2SystemGetTrophySetArray\n"
    ".type sceNpTrophy2SystemGetTrophySetArray @function\n"
    "sceNpTrophy2SystemGetTrophySetArray:\n"
    "jmp qword ptr [rip + __ptr_sceNpTrophy2SystemGetTrophySetArray]\n");

static __attribute__ ((used)) void* __ptr_sceNpTrophy2SystemGetTrophyTitleConf;
asm(".intel_syntax noprefix\n"
    ".global sceNpTrophy2SystemGetTrophyTitleConf\n"
    ".type sceNpTrophy2SystemGetTrophyTitleConf @function\n"
    "sceNpTrophy2SystemGetTrophyTitleConf:\n"
    "jmp qword ptr [rip + __ptr_sceNpTrophy2SystemGetTrophyTitleConf]\n");

static __attribute__ ((used)) void* __ptr_sceNpTrophy2SystemGetTrophyTitleDetails;
asm(".intel_syntax noprefix\n"
    ".global sceNpTrophy2SystemGetTrophyTitleDetails\n"
    ".type sceNpTrophy2SystemGetTrophyTitleDetails @function\n"
    "sceNpTrophy2SystemGetTrophyTitleDetails:\n"
    "jmp qword ptr [rip + __ptr_sceNpTrophy2SystemGetTrophyTitleDetails]\n");

static __attribute__ ((used)) void* __ptr_sceNpTrophy2SystemGetTrpIconByUri;
asm(".intel_syntax noprefix\n"
    ".global sceNpTrophy2SystemGetTrpIconByUri\n"
    ".type sceNpTrophy2SystemGetTrpIconByUri @function\n"
    "sceNpTrophy2SystemGetTrpIconByUri:\n"
    "jmp qword ptr [rip + __ptr_sceNpTrophy2SystemGetTrpIconByUri]\n");

static __attribute__ ((used)) void* __ptr_sceNpTrophy2SystemIsServerAvailable;
asm(".intel_syntax noprefix\n"
    ".global sceNpTrophy2SystemIsServerAvailable\n"
    ".type sceNpTrophy2SystemIsServerAvailable @function\n"
    "sceNpTrophy2SystemIsServerAvailable:\n"
    "jmp qword ptr [rip + __ptr_sceNpTrophy2SystemIsServerAvailable]\n");

static __attribute__ ((used)) void* __ptr_sceNpTrophy2SystemRegisterTitleSyncedCallback;
asm(".intel_syntax noprefix\n"
    ".global sceNpTrophy2SystemRegisterTitleSyncedCallback\n"
    ".type sceNpTrophy2SystemRegisterTitleSyncedCallback @function\n"
    "sceNpTrophy2SystemRegisterTitleSyncedCallback:\n"
    "jmp qword ptr [rip + __ptr_sceNpTrophy2SystemRegisterTitleSyncedCallback]\n");

static __attribute__ ((used)) void* __ptr_sceNpTrophy2SystemRegisterTitleUpdateCallback;
asm(".intel_syntax noprefix\n"
    ".global sceNpTrophy2SystemRegisterTitleUpdateCallback\n"
    ".type sceNpTrophy2SystemRegisterTitleUpdateCallback @function\n"
    "sceNpTrophy2SystemRegisterTitleUpdateCallback:\n"
    "jmp qword ptr [rip + __ptr_sceNpTrophy2SystemRegisterTitleUpdateCallback]\n");

static __attribute__ ((used)) void* __ptr_sceNpTrophy2SystemRemoveAll;
asm(".intel_syntax noprefix\n"
    ".global sceNpTrophy2SystemRemoveAll\n"
    ".type sceNpTrophy2SystemRemoveAll @function\n"
    "sceNpTrophy2SystemRemoveAll:\n"
    "jmp qword ptr [rip + __ptr_sceNpTrophy2SystemRemoveAll]\n");

static __attribute__ ((used)) void* __ptr_sceNpTrophy2SystemRemoveTitleData;
asm(".intel_syntax noprefix\n"
    ".global sceNpTrophy2SystemRemoveTitleData\n"
    ".type sceNpTrophy2SystemRemoveTitleData @function\n"
    "sceNpTrophy2SystemRemoveTitleData:\n"
    "jmp qword ptr [rip + __ptr_sceNpTrophy2SystemRemoveTitleData]\n");

static __attribute__ ((used)) void* __ptr_sceNpTrophy2SystemRemoveUserData;
asm(".intel_syntax noprefix\n"
    ".global sceNpTrophy2SystemRemoveUserData\n"
    ".type sceNpTrophy2SystemRemoveUserData @function\n"
    "sceNpTrophy2SystemRemoveUserData:\n"
    "jmp qword ptr [rip + __ptr_sceNpTrophy2SystemRemoveUserData]\n");

static __attribute__ ((used)) void* __ptr_sceNpTrophy2UnregisterUnlockCallback;
asm(".intel_syntax noprefix\n"
    ".global sceNpTrophy2UnregisterUnlockCallback\n"
    ".type sceNpTrophy2UnregisterUnlockCallback @function\n"
    "sceNpTrophy2UnregisterUnlockCallback:\n"
    "jmp qword ptr [rip + __ptr_sceNpTrophy2UnregisterUnlockCallback]\n");

static unsigned short __handle = 0;
static void __attribute__((constructor(104)))
__constructor(void) {
  if(sprx_dlopen("libSceNpTrophy2", &__handle)) return;
  if(sprx_dlsym(__handle, "fYapWA9xVmA", &__ptr_sceNpTrophy2AbortHandle)) return;
  if(sprx_dlsym(__handle, "Bagshr7OQ6Q", &__ptr_sceNpTrophy2CreateContext)) return;
  if(sprx_dlsym(__handle, "Gz1rmUZpROM", &__ptr_sceNpTrophy2CreateHandle)) return;
  if(sprx_dlsym(__handle, "sysY2FHYff4", &__ptr_sceNpTrophy2DestroyContext)) return;
  if(sprx_dlsym(__handle, "d8P11CI40KE", &__ptr_sceNpTrophy2DestroyHandle)) return;
  if(sprx_dlsym(__handle, "2QgUy+xJqS0", &__ptr_sceNpTrophy2GetGameIcon)) return;
  if(sprx_dlsym(__handle, "4IzqhhUQ3nk", &__ptr_sceNpTrophy2GetGameInfo)) return;
  if(sprx_dlsym(__handle, "6IjXJUy6ZnA", &__ptr_sceNpTrophy2GetGroupIcon)) return;
  if(sprx_dlsym(__handle, "DoZWauG8mu0", &__ptr_sceNpTrophy2GetGroupInfo)) return;
  if(sprx_dlsym(__handle, "+PDSI6WgPRc", &__ptr_sceNpTrophy2GetGroupInfoArray)) return;
  if(sprx_dlsym(__handle, "BsE-m8JxIOg", &__ptr_sceNpTrophy2GetRewardIcon)) return;
  if(sprx_dlsym(__handle, "-9LLVU0uvs8", &__ptr_sceNpTrophy2GetTrophyIcon)) return;
  if(sprx_dlsym(__handle, "EwNylPdWUTM", &__ptr_sceNpTrophy2GetTrophyInfo)) return;
  if(sprx_dlsym(__handle, "y3zHpdZO6ME", &__ptr_sceNpTrophy2GetTrophyInfoArray)) return;
  if(sprx_dlsym(__handle, "bIDov3wBu5Q", &__ptr_sceNpTrophy2RegisterContext)) return;
  if(sprx_dlsym(__handle, "sUXGfNMalIo", &__ptr_sceNpTrophy2RegisterUnlockCallback)) return;
  if(sprx_dlsym(__handle, "EHQEDVXZ0TI", &__ptr_sceNpTrophy2ShowTrophyList)) return;
  if(sprx_dlsym(__handle, "PCFtlcOHfW4", &__ptr_sceNpTrophy2SystemAbortHandle)) return;
  if(sprx_dlsym(__handle, "i2kbAbi3ozo", &__ptr_sceNpTrophy2SystemBuildGroupIconUri)) return;
  if(sprx_dlsym(__handle, "3ZWtClII0ME", &__ptr_sceNpTrophy2SystemBuildRewardIconUri)) return;
  if(sprx_dlsym(__handle, "v7IHQF5Lnqc", &__ptr_sceNpTrophy2SystemBuildTrophyIconUri)) return;
  if(sprx_dlsym(__handle, "1HrxhQoPEBs", &__ptr_sceNpTrophy2SystemCheckCallback)) return;
  if(sprx_dlsym(__handle, "pGFdISTgS6k", &__ptr_sceNpTrophy2SystemCheckNetSyncTitles)) return;
  if(sprx_dlsym(__handle, "fYaW4Ynxyzs", &__ptr_sceNpTrophy2SystemCreateContext)) return;
  if(sprx_dlsym(__handle, "H2TzUB5dpJw", &__ptr_sceNpTrophy2SystemCreateHandle)) return;
  if(sprx_dlsym(__handle, "Im235TKzFr4", &__ptr_sceNpTrophy2SystemDebugLockTrophy)) return;
  if(sprx_dlsym(__handle, "5VBAeTtoF0s", &__ptr_sceNpTrophy2SystemDebugUnlockTrophy)) return;
  if(sprx_dlsym(__handle, "7fMQZVzPqdc", &__ptr_sceNpTrophy2SystemDestroyContext)) return;
  if(sprx_dlsym(__handle, "AaFh1H8YTPY", &__ptr_sceNpTrophy2SystemGetTrophyDetails)) return;
  if(sprx_dlsym(__handle, "zsUmqFv3Lwk", &__ptr_sceNpTrophy2SystemGetTrophyGroupConf)) return;
  if(sprx_dlsym(__handle, "j3FpjemL6Zg", &__ptr_sceNpTrophy2SystemGetTrophySetArray)) return;
  if(sprx_dlsym(__handle, "7mrTdxGkB3U", &__ptr_sceNpTrophy2SystemGetTrophyTitleConf)) return;
  if(sprx_dlsym(__handle, "p4dYJFInGjQ", &__ptr_sceNpTrophy2SystemGetTrophyTitleDetails)) return;
  if(sprx_dlsym(__handle, "z7p4mxbkli0", &__ptr_sceNpTrophy2SystemGetTrpIconByUri)) return;
  if(sprx_dlsym(__handle, "7xSkVM0yhV0", &__ptr_sceNpTrophy2SystemIsServerAvailable)) return;
  if(sprx_dlsym(__handle, "fgtXCeaburA", &__ptr_sceNpTrophy2SystemRegisterTitleSyncedCallback)) return;
  if(sprx_dlsym(__handle, "L76Gd3hKuoU", &__ptr_sceNpTrophy2SystemRegisterTitleUpdateCallback)) return;
  if(sprx_dlsym(__handle, "Kbkk1pQWhN4", &__ptr_sceNpTrophy2SystemRemoveAll)) return;
  if(sprx_dlsym(__handle, "BnHnDvv6yAA", &__ptr_sceNpTrophy2SystemRemoveTitleData)) return;
  if(sprx_dlsym(__handle, "1muH18WXIQQ", &__ptr_sceNpTrophy2SystemRemoveUserData)) return;
  if(sprx_dlsym(__handle, "wVqxM58sIKs", &__ptr_sceNpTrophy2UnregisterUnlockCallback)) return;
}

static void __attribute__((destructor(104)))
__destructor(void) {
  sprx_dlclose(__handle);
}
