/*
 This file was generated by genstub.py, do not edit manually!
*/

int sprx_dlsym(unsigned int handle, const char *nid, void *addr);
int sprx_dlopen(const char* libname, unsigned short *handle);
int sprx_dlclose(unsigned int handle);

static __attribute__ ((used)) void* __ptr_ScePsmMonoArrayAddrWithSize;
asm(".intel_syntax noprefix\n"
    ".global ScePsmMonoArrayAddrWithSize\n"
    ".type ScePsmMonoArrayAddrWithSize @function\n"
    "ScePsmMonoArrayAddrWithSize:\n"
    "jmp qword ptr [rip + __ptr_ScePsmMonoArrayAddrWithSize]\n");

static __attribute__ ((used)) void* __ptr_ScePsmMonoArrayLength;
asm(".intel_syntax noprefix\n"
    ".global ScePsmMonoArrayLength\n"
    ".type ScePsmMonoArrayLength @function\n"
    "ScePsmMonoArrayLength:\n"
    "jmp qword ptr [rip + __ptr_ScePsmMonoArrayLength]\n");

static __attribute__ ((used)) void* __ptr_ScePsmMonoDomainGet;
asm(".intel_syntax noprefix\n"
    ".global ScePsmMonoDomainGet\n"
    ".type ScePsmMonoDomainGet @function\n"
    "ScePsmMonoDomainGet:\n"
    "jmp qword ptr [rip + __ptr_ScePsmMonoDomainGet]\n");

static __attribute__ ((used)) void* __ptr_ScePsmMonoFree;
asm(".intel_syntax noprefix\n"
    ".global ScePsmMonoFree\n"
    ".type ScePsmMonoFree @function\n"
    "ScePsmMonoFree:\n"
    "jmp qword ptr [rip + __ptr_ScePsmMonoFree]\n");

static __attribute__ ((used)) void* __ptr_ScePsmMonoGcWbarrierGenericStore;
asm(".intel_syntax noprefix\n"
    ".global ScePsmMonoGcWbarrierGenericStore\n"
    ".type ScePsmMonoGcWbarrierGenericStore @function\n"
    "ScePsmMonoGcWbarrierGenericStore:\n"
    "jmp qword ptr [rip + __ptr_ScePsmMonoGcWbarrierGenericStore]\n");

static __attribute__ ((used)) void* __ptr_ScePsmMonoStringChars;
asm(".intel_syntax noprefix\n"
    ".global ScePsmMonoStringChars\n"
    ".type ScePsmMonoStringChars @function\n"
    "ScePsmMonoStringChars:\n"
    "jmp qword ptr [rip + __ptr_ScePsmMonoStringChars]\n");

static __attribute__ ((used)) void* __ptr_ScePsmMonoStringFromUtf16;
asm(".intel_syntax noprefix\n"
    ".global ScePsmMonoStringFromUtf16\n"
    ".type ScePsmMonoStringFromUtf16 @function\n"
    "ScePsmMonoStringFromUtf16:\n"
    "jmp qword ptr [rip + __ptr_ScePsmMonoStringFromUtf16]\n");

static __attribute__ ((used)) void* __ptr_ScePsmMonoStringLength;
asm(".intel_syntax noprefix\n"
    ".global ScePsmMonoStringLength\n"
    ".type ScePsmMonoStringLength @function\n"
    "ScePsmMonoStringLength:\n"
    "jmp qword ptr [rip + __ptr_ScePsmMonoStringLength]\n");

static __attribute__ ((used)) void* __ptr_ScePsmMonoStringNew;
asm(".intel_syntax noprefix\n"
    ".global ScePsmMonoStringNew\n"
    ".type ScePsmMonoStringNew @function\n"
    "ScePsmMonoStringNew:\n"
    "jmp qword ptr [rip + __ptr_ScePsmMonoStringNew]\n");

static __attribute__ ((used)) void* __ptr_ScePsmMonoStringNewWrapper;
asm(".intel_syntax noprefix\n"
    ".global ScePsmMonoStringNewWrapper\n"
    ".type ScePsmMonoStringNewWrapper @function\n"
    "ScePsmMonoStringNewWrapper:\n"
    "jmp qword ptr [rip + __ptr_ScePsmMonoStringNewWrapper]\n");

static __attribute__ ((used)) void* __ptr_ScePsmMonoStringToUtf8;
asm(".intel_syntax noprefix\n"
    ".global ScePsmMonoStringToUtf8\n"
    ".type ScePsmMonoStringToUtf8 @function\n"
    "ScePsmMonoStringToUtf8:\n"
    "jmp qword ptr [rip + __ptr_ScePsmMonoStringToUtf8]\n");

static __attribute__ ((used)) void* __ptr__ZN3sce3pss4core14IntHandleTable13NextIntHandleEv;
asm(".intel_syntax noprefix\n"
    ".global _ZN3sce3pss4core14IntHandleTable13NextIntHandleEv\n"
    ".type _ZN3sce3pss4core14IntHandleTable13NextIntHandleEv @function\n"
    "_ZN3sce3pss4core14IntHandleTable13NextIntHandleEv:\n"
    "jmp qword ptr [rip + __ptr__ZN3sce3pss4core14IntHandleTable13NextIntHandleEv]\n");

static __attribute__ ((used)) void* __ptr__ZN3sce3pss4core8graphics14NativeGraphics18ReleaseVideoMemoryEPv;
asm(".intel_syntax noprefix\n"
    ".global _ZN3sce3pss4core8graphics14NativeGraphics18ReleaseVideoMemoryEPv\n"
    ".type _ZN3sce3pss4core8graphics14NativeGraphics18ReleaseVideoMemoryEPv @function\n"
    "_ZN3sce3pss4core8graphics14NativeGraphics18ReleaseVideoMemoryEPv:\n"
    "jmp qword ptr [rip + __ptr__ZN3sce3pss4core8graphics14NativeGraphics18ReleaseVideoMemoryEPv]\n");

static __attribute__ ((used)) void* __ptr__ZN3sce3pss4core8graphics14NativeGraphics19AllocateVideoMemoryEjj;
asm(".intel_syntax noprefix\n"
    ".global _ZN3sce3pss4core8graphics14NativeGraphics19AllocateVideoMemoryEjj\n"
    ".type _ZN3sce3pss4core8graphics14NativeGraphics19AllocateVideoMemoryEjj @function\n"
    "_ZN3sce3pss4core8graphics14NativeGraphics19AllocateVideoMemoryEjj:\n"
    "jmp qword ptr [rip + __ptr__ZN3sce3pss4core8graphics14NativeGraphics19AllocateVideoMemoryEjj]\n");

static __attribute__ ((used)) void* __ptr__ZN3sce3pss4core8graphics14NativeGraphics19AllocateVideoMemoryEjjPv;
asm(".intel_syntax noprefix\n"
    ".global _ZN3sce3pss4core8graphics14NativeGraphics19AllocateVideoMemoryEjjPv\n"
    ".type _ZN3sce3pss4core8graphics14NativeGraphics19AllocateVideoMemoryEjjPv @function\n"
    "_ZN3sce3pss4core8graphics14NativeGraphics19AllocateVideoMemoryEjjPv:\n"
    "jmp qword ptr [rip + __ptr__ZN3sce3pss4core8graphics14NativeGraphics19AllocateVideoMemoryEjjPv]\n");

static __attribute__ ((used)) void* __ptr__ZN3sce3pss4core8graphics14NativeGraphics19ReleaseSystemMemoryEPv;
asm(".intel_syntax noprefix\n"
    ".global _ZN3sce3pss4core8graphics14NativeGraphics19ReleaseSystemMemoryEPv\n"
    ".type _ZN3sce3pss4core8graphics14NativeGraphics19ReleaseSystemMemoryEPv @function\n"
    "_ZN3sce3pss4core8graphics14NativeGraphics19ReleaseSystemMemoryEPv:\n"
    "jmp qword ptr [rip + __ptr__ZN3sce3pss4core8graphics14NativeGraphics19ReleaseSystemMemoryEPv]\n");

static __attribute__ ((used)) void* __ptr__ZN3sce3pss4core8graphics14NativeGraphics20AllocateSystemMemoryEjj;
asm(".intel_syntax noprefix\n"
    ".global _ZN3sce3pss4core8graphics14NativeGraphics20AllocateSystemMemoryEjj\n"
    ".type _ZN3sce3pss4core8graphics14NativeGraphics20AllocateSystemMemoryEjj @function\n"
    "_ZN3sce3pss4core8graphics14NativeGraphics20AllocateSystemMemoryEjj:\n"
    "jmp qword ptr [rip + __ptr__ZN3sce3pss4core8graphics14NativeGraphics20AllocateSystemMemoryEjj]\n");

static __attribute__ ((used)) void* __ptr__ZN3sce3pss4core8graphics14NativeGraphics20AllocateSystemMemoryEjjPv;
asm(".intel_syntax noprefix\n"
    ".global _ZN3sce3pss4core8graphics14NativeGraphics20AllocateSystemMemoryEjjPv\n"
    ".type _ZN3sce3pss4core8graphics14NativeGraphics20AllocateSystemMemoryEjjPv @function\n"
    "_ZN3sce3pss4core8graphics14NativeGraphics20AllocateSystemMemoryEjjPv:\n"
    "jmp qword ptr [rip + __ptr__ZN3sce3pss4core8graphics14NativeGraphics20AllocateSystemMemoryEjjPv]\n");

static __attribute__ ((used)) void* __ptr__ZN3sce3pss4core9PsmObjectC1Ev;
asm(".intel_syntax noprefix\n"
    ".global _ZN3sce3pss4core9PsmObjectC1Ev\n"
    ".type _ZN3sce3pss4core9PsmObjectC1Ev @function\n"
    "_ZN3sce3pss4core9PsmObjectC1Ev:\n"
    "jmp qword ptr [rip + __ptr__ZN3sce3pss4core9PsmObjectC1Ev]\n");

static __attribute__ ((used)) void* __ptr__ZN3sce3pss4core9PsmObjectC2Ev;
asm(".intel_syntax noprefix\n"
    ".global _ZN3sce3pss4core9PsmObjectC2Ev\n"
    ".type _ZN3sce3pss4core9PsmObjectC2Ev @function\n"
    "_ZN3sce3pss4core9PsmObjectC2Ev:\n"
    "jmp qword ptr [rip + __ptr__ZN3sce3pss4core9PsmObjectC2Ev]\n");

static __attribute__ ((used)) void* __ptr__ZN3sce3pss4core9PsmObjectD0Ev;
asm(".intel_syntax noprefix\n"
    ".global _ZN3sce3pss4core9PsmObjectD0Ev\n"
    ".type _ZN3sce3pss4core9PsmObjectD0Ev @function\n"
    "_ZN3sce3pss4core9PsmObjectD0Ev:\n"
    "jmp qword ptr [rip + __ptr__ZN3sce3pss4core9PsmObjectD0Ev]\n");

static __attribute__ ((used)) void* __ptr__ZN3sce3pss4core9PsmObjectD1Ev;
asm(".intel_syntax noprefix\n"
    ".global _ZN3sce3pss4core9PsmObjectD1Ev\n"
    ".type _ZN3sce3pss4core9PsmObjectD1Ev @function\n"
    "_ZN3sce3pss4core9PsmObjectD1Ev:\n"
    "jmp qword ptr [rip + __ptr__ZN3sce3pss4core9PsmObjectD1Ev]\n");

static __attribute__ ((used)) void* __ptr__ZN3sce3pss4core9PsmObjectD2Ev;
asm(".intel_syntax noprefix\n"
    ".global _ZN3sce3pss4core9PsmObjectD2Ev\n"
    ".type _ZN3sce3pss4core9PsmObjectD2Ev @function\n"
    "_ZN3sce3pss4core9PsmObjectD2Ev:\n"
    "jmp qword ptr [rip + __ptr__ZN3sce3pss4core9PsmObjectD2Ev]\n");

static __attribute__ ((used)) void* __ptr__ZN3sce3pss4core9threading4Cond4WaitEi;
asm(".intel_syntax noprefix\n"
    ".global _ZN3sce3pss4core9threading4Cond4WaitEi\n"
    ".type _ZN3sce3pss4core9threading4Cond4WaitEi @function\n"
    "_ZN3sce3pss4core9threading4Cond4WaitEi:\n"
    "jmp qword ptr [rip + __ptr__ZN3sce3pss4core9threading4Cond4WaitEi]\n");

static __attribute__ ((used)) void* __ptr__ZN3sce3pss4core9threading4Cond6NotifyEv;
asm(".intel_syntax noprefix\n"
    ".global _ZN3sce3pss4core9threading4Cond6NotifyEv\n"
    ".type _ZN3sce3pss4core9threading4Cond6NotifyEv @function\n"
    "_ZN3sce3pss4core9threading4Cond6NotifyEv:\n"
    "jmp qword ptr [rip + __ptr__ZN3sce3pss4core9threading4Cond6NotifyEv]\n");

static __attribute__ ((used)) void* __ptr__ZN3sce3pss4core9threading4CondC1ERNS2_5MutexEPKci;
asm(".intel_syntax noprefix\n"
    ".global _ZN3sce3pss4core9threading4CondC1ERNS2_5MutexEPKci\n"
    ".type _ZN3sce3pss4core9threading4CondC1ERNS2_5MutexEPKci @function\n"
    "_ZN3sce3pss4core9threading4CondC1ERNS2_5MutexEPKci:\n"
    "jmp qword ptr [rip + __ptr__ZN3sce3pss4core9threading4CondC1ERNS2_5MutexEPKci]\n");

static __attribute__ ((used)) void* __ptr__ZN3sce3pss4core9threading4CondC2ERNS2_5MutexEPKci;
asm(".intel_syntax noprefix\n"
    ".global _ZN3sce3pss4core9threading4CondC2ERNS2_5MutexEPKci\n"
    ".type _ZN3sce3pss4core9threading4CondC2ERNS2_5MutexEPKci @function\n"
    "_ZN3sce3pss4core9threading4CondC2ERNS2_5MutexEPKci:\n"
    "jmp qword ptr [rip + __ptr__ZN3sce3pss4core9threading4CondC2ERNS2_5MutexEPKci]\n");

static __attribute__ ((used)) void* __ptr__ZN3sce3pss4core9threading4CondD1Ev;
asm(".intel_syntax noprefix\n"
    ".global _ZN3sce3pss4core9threading4CondD1Ev\n"
    ".type _ZN3sce3pss4core9threading4CondD1Ev @function\n"
    "_ZN3sce3pss4core9threading4CondD1Ev:\n"
    "jmp qword ptr [rip + __ptr__ZN3sce3pss4core9threading4CondD1Ev]\n");

static __attribute__ ((used)) void* __ptr__ZN3sce3pss4core9threading4CondD2Ev;
asm(".intel_syntax noprefix\n"
    ".global _ZN3sce3pss4core9threading4CondD2Ev\n"
    ".type _ZN3sce3pss4core9threading4CondD2Ev @function\n"
    "_ZN3sce3pss4core9threading4CondD2Ev:\n"
    "jmp qword ptr [rip + __ptr__ZN3sce3pss4core9threading4CondD2Ev]\n");

static __attribute__ ((used)) void* __ptr__ZN3sce3pss5orbis9framework11PsmArrayObj6LengthEv;
asm(".intel_syntax noprefix\n"
    ".global _ZN3sce3pss5orbis9framework11PsmArrayObj6LengthEv\n"
    ".type _ZN3sce3pss5orbis9framework11PsmArrayObj6LengthEv @function\n"
    "_ZN3sce3pss5orbis9framework11PsmArrayObj6LengthEv:\n"
    "jmp qword ptr [rip + __ptr__ZN3sce3pss5orbis9framework11PsmArrayObj6LengthEv]\n");

static __attribute__ ((used)) void* __ptr__ZN3sce3pss5orbis9framework11PsmArrayObj9ToPointerEv;
asm(".intel_syntax noprefix\n"
    ".global _ZN3sce3pss5orbis9framework11PsmArrayObj9ToPointerEv\n"
    ".type _ZN3sce3pss5orbis9framework11PsmArrayObj9ToPointerEv @function\n"
    "_ZN3sce3pss5orbis9framework11PsmArrayObj9ToPointerEv:\n"
    "jmp qword ptr [rip + __ptr__ZN3sce3pss5orbis9framework11PsmArrayObj9ToPointerEv]\n");

static __attribute__ ((used)) void* __ptr__ZN3sce3pss5orbis9framework11PsmCallList10UnregisterEPFvPvES4_;
asm(".intel_syntax noprefix\n"
    ".global _ZN3sce3pss5orbis9framework11PsmCallList10UnregisterEPFvPvES4_\n"
    ".type _ZN3sce3pss5orbis9framework11PsmCallList10UnregisterEPFvPvES4_ @function\n"
    "_ZN3sce3pss5orbis9framework11PsmCallList10UnregisterEPFvPvES4_:\n"
    "jmp qword ptr [rip + __ptr__ZN3sce3pss5orbis9framework11PsmCallList10UnregisterEPFvPvES4_]\n");

static __attribute__ ((used)) void* __ptr__ZN3sce3pss5orbis9framework11PsmCallList6UpdateEv;
asm(".intel_syntax noprefix\n"
    ".global _ZN3sce3pss5orbis9framework11PsmCallList6UpdateEv\n"
    ".type _ZN3sce3pss5orbis9framework11PsmCallList6UpdateEv @function\n"
    "_ZN3sce3pss5orbis9framework11PsmCallList6UpdateEv:\n"
    "jmp qword ptr [rip + __ptr__ZN3sce3pss5orbis9framework11PsmCallList6UpdateEv]\n");

static __attribute__ ((used)) void* __ptr__ZN3sce3pss5orbis9framework11PsmCallList8RegisterEPFvPvES4_;
asm(".intel_syntax noprefix\n"
    ".global _ZN3sce3pss5orbis9framework11PsmCallList8RegisterEPFvPvES4_\n"
    ".type _ZN3sce3pss5orbis9framework11PsmCallList8RegisterEPFvPvES4_ @function\n"
    "_ZN3sce3pss5orbis9framework11PsmCallList8RegisterEPFvPvES4_:\n"
    "jmp qword ptr [rip + __ptr__ZN3sce3pss5orbis9framework11PsmCallList8RegisterEPFvPvES4_]\n");

static __attribute__ ((used)) void* __ptr__ZN3sce3pss5orbis9framework11PsmCallListC1Ev;
asm(".intel_syntax noprefix\n"
    ".global _ZN3sce3pss5orbis9framework11PsmCallListC1Ev\n"
    ".type _ZN3sce3pss5orbis9framework11PsmCallListC1Ev @function\n"
    "_ZN3sce3pss5orbis9framework11PsmCallListC1Ev:\n"
    "jmp qword ptr [rip + __ptr__ZN3sce3pss5orbis9framework11PsmCallListC1Ev]\n");

static __attribute__ ((used)) void* __ptr__ZN3sce3pss5orbis9framework11PsmCallListC2Ev;
asm(".intel_syntax noprefix\n"
    ".global _ZN3sce3pss5orbis9framework11PsmCallListC2Ev\n"
    ".type _ZN3sce3pss5orbis9framework11PsmCallListC2Ev @function\n"
    "_ZN3sce3pss5orbis9framework11PsmCallListC2Ev:\n"
    "jmp qword ptr [rip + __ptr__ZN3sce3pss5orbis9framework11PsmCallListC2Ev]\n");

static __attribute__ ((used)) void* __ptr__ZN3sce3pss5orbis9framework12PsmEventData8SetValueERKNS_4Json5ValueE;
asm(".intel_syntax noprefix\n"
    ".global _ZN3sce3pss5orbis9framework12PsmEventData8SetValueERKNS_4Json5ValueE\n"
    ".type _ZN3sce3pss5orbis9framework12PsmEventData8SetValueERKNS_4Json5ValueE @function\n"
    "_ZN3sce3pss5orbis9framework12PsmEventData8SetValueERKNS_4Json5ValueE:\n"
    "jmp qword ptr [rip + __ptr__ZN3sce3pss5orbis9framework12PsmEventData8SetValueERKNS_4Json5ValueE]\n");

static __attribute__ ((used)) void* __ptr__ZN3sce3pss5orbis9framework12PsmFramework10InitializeERKNS2_12PsmInitParamEiPPc;
asm(".intel_syntax noprefix\n"
    ".global _ZN3sce3pss5orbis9framework12PsmFramework10InitializeERKNS2_12PsmInitParamEiPPc\n"
    ".type _ZN3sce3pss5orbis9framework12PsmFramework10InitializeERKNS2_12PsmInitParamEiPPc @function\n"
    "_ZN3sce3pss5orbis9framework12PsmFramework10InitializeERKNS2_12PsmInitParamEiPPc:\n"
    "jmp qword ptr [rip + __ptr__ZN3sce3pss5orbis9framework12PsmFramework10InitializeERKNS2_12PsmInitParamEiPPc]\n");

static __attribute__ ((used)) void* __ptr__ZN3sce3pss5orbis9framework12PsmFramework20RegisterInternalCallEPKNS2_12PsmCallEntryE;
asm(".intel_syntax noprefix\n"
    ".global _ZN3sce3pss5orbis9framework12PsmFramework20RegisterInternalCallEPKNS2_12PsmCallEntryE\n"
    ".type _ZN3sce3pss5orbis9framework12PsmFramework20RegisterInternalCallEPKNS2_12PsmCallEntryE @function\n"
    "_ZN3sce3pss5orbis9framework12PsmFramework20RegisterInternalCallEPKNS2_12PsmCallEntryE:\n"
    "jmp qword ptr [rip + __ptr__ZN3sce3pss5orbis9framework12PsmFramework20RegisterInternalCallEPKNS2_12PsmCallEntryE]\n");

static __attribute__ ((used)) void* __ptr__ZN3sce3pss5orbis9framework12PsmFramework24RegisterPInvokeCallTableEPKNS2_15PsmLibraryEntryE;
asm(".intel_syntax noprefix\n"
    ".global _ZN3sce3pss5orbis9framework12PsmFramework24RegisterPInvokeCallTableEPKNS2_15PsmLibraryEntryE\n"
    ".type _ZN3sce3pss5orbis9framework12PsmFramework24RegisterPInvokeCallTableEPKNS2_15PsmLibraryEntryE @function\n"
    "_ZN3sce3pss5orbis9framework12PsmFramework24RegisterPInvokeCallTableEPKNS2_15PsmLibraryEntryE:\n"
    "jmp qword ptr [rip + __ptr__ZN3sce3pss5orbis9framework12PsmFramework24RegisterPInvokeCallTableEPKNS2_15PsmLibraryEntryE]\n");

static __attribute__ ((used)) void* __ptr__ZN3sce3pss5orbis9framework12PsmFramework3RunEv;
asm(".intel_syntax noprefix\n"
    ".global _ZN3sce3pss5orbis9framework12PsmFramework3RunEv\n"
    ".type _ZN3sce3pss5orbis9framework12PsmFramework3RunEv @function\n"
    "_ZN3sce3pss5orbis9framework12PsmFramework3RunEv:\n"
    "jmp qword ptr [rip + __ptr__ZN3sce3pss5orbis9framework12PsmFramework3RunEv]\n");

static __attribute__ ((used)) void* __ptr__ZN3sce3pss5orbis9framework12PsmFramework8FinalizeEv;
asm(".intel_syntax noprefix\n"
    ".global _ZN3sce3pss5orbis9framework12PsmFramework8FinalizeEv\n"
    ".type _ZN3sce3pss5orbis9framework12PsmFramework8FinalizeEv @function\n"
    "_ZN3sce3pss5orbis9framework12PsmFramework8FinalizeEv:\n"
    "jmp qword ptr [rip + __ptr__ZN3sce3pss5orbis9framework12PsmFramework8FinalizeEv]\n");

static __attribute__ ((used)) void* __ptr__ZN3sce3pss5orbis9framework12PsmInitParamC1Ev;
asm(".intel_syntax noprefix\n"
    ".global _ZN3sce3pss5orbis9framework12PsmInitParamC1Ev\n"
    ".type _ZN3sce3pss5orbis9framework12PsmInitParamC1Ev @function\n"
    "_ZN3sce3pss5orbis9framework12PsmInitParamC1Ev:\n"
    "jmp qword ptr [rip + __ptr__ZN3sce3pss5orbis9framework12PsmInitParamC1Ev]\n");

static __attribute__ ((used)) void* __ptr__ZN3sce3pss5orbis9framework12PsmInitParamC2Ev;
asm(".intel_syntax noprefix\n"
    ".global _ZN3sce3pss5orbis9framework12PsmInitParamC2Ev\n"
    ".type _ZN3sce3pss5orbis9framework12PsmInitParamC2Ev @function\n"
    "_ZN3sce3pss5orbis9framework12PsmInitParamC2Ev:\n"
    "jmp qword ptr [rip + __ptr__ZN3sce3pss5orbis9framework12PsmInitParamC2Ev]\n");

static __attribute__ ((used)) void* __ptr__ZN3sce3pss5orbis9framework12PsmStringObj17NewAndStoreStringEPvPc;
asm(".intel_syntax noprefix\n"
    ".global _ZN3sce3pss5orbis9framework12PsmStringObj17NewAndStoreStringEPvPc\n"
    ".type _ZN3sce3pss5orbis9framework12PsmStringObj17NewAndStoreStringEPvPc @function\n"
    "_ZN3sce3pss5orbis9framework12PsmStringObj17NewAndStoreStringEPvPc:\n"
    "jmp qword ptr [rip + __ptr__ZN3sce3pss5orbis9framework12PsmStringObj17NewAndStoreStringEPvPc]\n");

static __attribute__ ((used)) void* __ptr__ZN3sce3pss5orbis9framework12PsmStringObj6ToUtf8Ev;
asm(".intel_syntax noprefix\n"
    ".global _ZN3sce3pss5orbis9framework12PsmStringObj6ToUtf8Ev\n"
    ".type _ZN3sce3pss5orbis9framework12PsmStringObj6ToUtf8Ev @function\n"
    "_ZN3sce3pss5orbis9framework12PsmStringObj6ToUtf8Ev:\n"
    "jmp qword ptr [rip + __ptr__ZN3sce3pss5orbis9framework12PsmStringObj6ToUtf8Ev]\n");

static __attribute__ ((used)) void* __ptr__ZN3sce3pss5orbis9framework12PsmStringObj8FreeUtf8EPc;
asm(".intel_syntax noprefix\n"
    ".global _ZN3sce3pss5orbis9framework12PsmStringObj8FreeUtf8EPc\n"
    ".type _ZN3sce3pss5orbis9framework12PsmStringObj8FreeUtf8EPc @function\n"
    "_ZN3sce3pss5orbis9framework12PsmStringObj8FreeUtf8EPc:\n"
    "jmp qword ptr [rip + __ptr__ZN3sce3pss5orbis9framework12PsmStringObj8FreeUtf8EPc]\n");

static __attribute__ ((used)) void* __ptr__ZN3sce3pss5orbis9framework14PsmDelegateObj11FreePointerEv;
asm(".intel_syntax noprefix\n"
    ".global _ZN3sce3pss5orbis9framework14PsmDelegateObj11FreePointerEv\n"
    ".type _ZN3sce3pss5orbis9framework14PsmDelegateObj11FreePointerEv @function\n"
    "_ZN3sce3pss5orbis9framework14PsmDelegateObj11FreePointerEv:\n"
    "jmp qword ptr [rip + __ptr__ZN3sce3pss5orbis9framework14PsmDelegateObj11FreePointerEv]\n");

static __attribute__ ((used)) void* __ptr__ZN3sce3pss5orbis9framework14PsmDelegateObj15AllocatePointerEv;
asm(".intel_syntax noprefix\n"
    ".global _ZN3sce3pss5orbis9framework14PsmDelegateObj15AllocatePointerEv\n"
    ".type _ZN3sce3pss5orbis9framework14PsmDelegateObj15AllocatePointerEv @function\n"
    "_ZN3sce3pss5orbis9framework14PsmDelegateObj15AllocatePointerEv:\n"
    "jmp qword ptr [rip + __ptr__ZN3sce3pss5orbis9framework14PsmDelegateObj15AllocatePointerEv]\n");

static __attribute__ ((used)) void* __ptr__ZN3sce3pss5orbis9framework18PsmFrameworkCsharp21SetEnableNativeMethodEb;
asm(".intel_syntax noprefix\n"
    ".global _ZN3sce3pss5orbis9framework18PsmFrameworkCsharp21SetEnableNativeMethodEb\n"
    ".type _ZN3sce3pss5orbis9framework18PsmFrameworkCsharp21SetEnableNativeMethodEb @function\n"
    "_ZN3sce3pss5orbis9framework18PsmFrameworkCsharp21SetEnableNativeMethodEb:\n"
    "jmp qword ptr [rip + __ptr__ZN3sce3pss5orbis9framework18PsmFrameworkCsharp21SetEnableNativeMethodEb]\n");

static __attribute__ ((used)) void* __ptr__ZN3sce3pss5orbis9framework21PsmMainThreadCallList10UnregisterEPFvPvES4_;
asm(".intel_syntax noprefix\n"
    ".global _ZN3sce3pss5orbis9framework21PsmMainThreadCallList10UnregisterEPFvPvES4_\n"
    ".type _ZN3sce3pss5orbis9framework21PsmMainThreadCallList10UnregisterEPFvPvES4_ @function\n"
    "_ZN3sce3pss5orbis9framework21PsmMainThreadCallList10UnregisterEPFvPvES4_:\n"
    "jmp qword ptr [rip + __ptr__ZN3sce3pss5orbis9framework21PsmMainThreadCallList10UnregisterEPFvPvES4_]\n");

static __attribute__ ((used)) void* __ptr__ZN3sce3pss5orbis9framework21PsmMainThreadCallList6UpdateEv;
asm(".intel_syntax noprefix\n"
    ".global _ZN3sce3pss5orbis9framework21PsmMainThreadCallList6UpdateEv\n"
    ".type _ZN3sce3pss5orbis9framework21PsmMainThreadCallList6UpdateEv @function\n"
    "_ZN3sce3pss5orbis9framework21PsmMainThreadCallList6UpdateEv:\n"
    "jmp qword ptr [rip + __ptr__ZN3sce3pss5orbis9framework21PsmMainThreadCallList6UpdateEv]\n");

static __attribute__ ((used)) void* __ptr__ZN3sce3pss5orbis9framework21PsmMainThreadCallList8RegisterEPFvPvES4_;
asm(".intel_syntax noprefix\n"
    ".global _ZN3sce3pss5orbis9framework21PsmMainThreadCallList8RegisterEPFvPvES4_\n"
    ".type _ZN3sce3pss5orbis9framework21PsmMainThreadCallList8RegisterEPFvPvES4_ @function\n"
    "_ZN3sce3pss5orbis9framework21PsmMainThreadCallList8RegisterEPFvPvES4_:\n"
    "jmp qword ptr [rip + __ptr__ZN3sce3pss5orbis9framework21PsmMainThreadCallList8RegisterEPFvPvES4_]\n");

static __attribute__ ((used)) void* __ptr__ZN3sce3pss5orbis9framework23TerminatePsmEventCsharpEv;
asm(".intel_syntax noprefix\n"
    ".global _ZN3sce3pss5orbis9framework23TerminatePsmEventCsharpEv\n"
    ".type _ZN3sce3pss5orbis9framework23TerminatePsmEventCsharpEv @function\n"
    "_ZN3sce3pss5orbis9framework23TerminatePsmEventCsharpEv:\n"
    "jmp qword ptr [rip + __ptr__ZN3sce3pss5orbis9framework23TerminatePsmEventCsharpEv]\n");

static __attribute__ ((used)) void* __ptr__ZN3sce3pss5orbis9framework24InitializePsmEventCsharpEv;
asm(".intel_syntax noprefix\n"
    ".global _ZN3sce3pss5orbis9framework24InitializePsmEventCsharpEv\n"
    ".type _ZN3sce3pss5orbis9framework24InitializePsmEventCsharpEv @function\n"
    "_ZN3sce3pss5orbis9framework24InitializePsmEventCsharpEv:\n"
    "jmp qword ptr [rip + __ptr__ZN3sce3pss5orbis9framework24InitializePsmEventCsharpEv]\n");

static __attribute__ ((used)) void* __ptr__ZN3sce3pss5orbis9framework27TerminatePsmFrameworkCsharpEv;
asm(".intel_syntax noprefix\n"
    ".global _ZN3sce3pss5orbis9framework27TerminatePsmFrameworkCsharpEv\n"
    ".type _ZN3sce3pss5orbis9framework27TerminatePsmFrameworkCsharpEv @function\n"
    "_ZN3sce3pss5orbis9framework27TerminatePsmFrameworkCsharpEv:\n"
    "jmp qword ptr [rip + __ptr__ZN3sce3pss5orbis9framework27TerminatePsmFrameworkCsharpEv]\n");

static __attribute__ ((used)) void* __ptr__ZN3sce3pss5orbis9framework28InitializePsmFrameworkCsharpEv;
asm(".intel_syntax noprefix\n"
    ".global _ZN3sce3pss5orbis9framework28InitializePsmFrameworkCsharpEv\n"
    ".type _ZN3sce3pss5orbis9framework28InitializePsmFrameworkCsharpEv @function\n"
    "_ZN3sce3pss5orbis9framework28InitializePsmFrameworkCsharpEv:\n"
    "jmp qword ptr [rip + __ptr__ZN3sce3pss5orbis9framework28InitializePsmFrameworkCsharpEv]\n");

static __attribute__ ((used)) void* __ptr__ZN3sce3pss5orbis9framework8PsmEvent10UnregisterEiPFvRKNS2_12PsmEventDataEPvES7_;
asm(".intel_syntax noprefix\n"
    ".global _ZN3sce3pss5orbis9framework8PsmEvent10UnregisterEiPFvRKNS2_12PsmEventDataEPvES7_\n"
    ".type _ZN3sce3pss5orbis9framework8PsmEvent10UnregisterEiPFvRKNS2_12PsmEventDataEPvES7_ @function\n"
    "_ZN3sce3pss5orbis9framework8PsmEvent10UnregisterEiPFvRKNS2_12PsmEventDataEPvES7_:\n"
    "jmp qword ptr [rip + __ptr__ZN3sce3pss5orbis9framework8PsmEvent10UnregisterEiPFvRKNS2_12PsmEventDataEPvES7_]\n");

static __attribute__ ((used)) void* __ptr__ZN3sce3pss5orbis9framework8PsmEvent17RegisterDelegatorEPFvRKNS2_12PsmEventDataEPvES7_;
asm(".intel_syntax noprefix\n"
    ".global _ZN3sce3pss5orbis9framework8PsmEvent17RegisterDelegatorEPFvRKNS2_12PsmEventDataEPvES7_\n"
    ".type _ZN3sce3pss5orbis9framework8PsmEvent17RegisterDelegatorEPFvRKNS2_12PsmEventDataEPvES7_ @function\n"
    "_ZN3sce3pss5orbis9framework8PsmEvent17RegisterDelegatorEPFvRKNS2_12PsmEventDataEPvES7_:\n"
    "jmp qword ptr [rip + __ptr__ZN3sce3pss5orbis9framework8PsmEvent17RegisterDelegatorEPFvRKNS2_12PsmEventDataEPvES7_]\n");

static __attribute__ ((used)) void* __ptr__ZN3sce3pss5orbis9framework8PsmEvent19UnregisterDelegatorEPFvRKNS2_12PsmEventDataEPvES7_;
asm(".intel_syntax noprefix\n"
    ".global _ZN3sce3pss5orbis9framework8PsmEvent19UnregisterDelegatorEPFvRKNS2_12PsmEventDataEPvES7_\n"
    ".type _ZN3sce3pss5orbis9framework8PsmEvent19UnregisterDelegatorEPFvRKNS2_12PsmEventDataEPvES7_ @function\n"
    "_ZN3sce3pss5orbis9framework8PsmEvent19UnregisterDelegatorEPFvRKNS2_12PsmEventDataEPvES7_:\n"
    "jmp qword ptr [rip + __ptr__ZN3sce3pss5orbis9framework8PsmEvent19UnregisterDelegatorEPFvRKNS2_12PsmEventDataEPvES7_]\n");

static __attribute__ ((used)) void* __ptr__ZN3sce3pss5orbis9framework8PsmEvent4PostERKNS2_12PsmEventDataE;
asm(".intel_syntax noprefix\n"
    ".global _ZN3sce3pss5orbis9framework8PsmEvent4PostERKNS2_12PsmEventDataE\n"
    ".type _ZN3sce3pss5orbis9framework8PsmEvent4PostERKNS2_12PsmEventDataE @function\n"
    "_ZN3sce3pss5orbis9framework8PsmEvent4PostERKNS2_12PsmEventDataE:\n"
    "jmp qword ptr [rip + __ptr__ZN3sce3pss5orbis9framework8PsmEvent4PostERKNS2_12PsmEventDataE]\n");

static __attribute__ ((used)) void* __ptr__ZN3sce3pss5orbis9framework8PsmEvent4SendERKNS2_12PsmEventDataE;
asm(".intel_syntax noprefix\n"
    ".global _ZN3sce3pss5orbis9framework8PsmEvent4SendERKNS2_12PsmEventDataE\n"
    ".type _ZN3sce3pss5orbis9framework8PsmEvent4SendERKNS2_12PsmEventDataE @function\n"
    "_ZN3sce3pss5orbis9framework8PsmEvent4SendERKNS2_12PsmEventDataE:\n"
    "jmp qword ptr [rip + __ptr__ZN3sce3pss5orbis9framework8PsmEvent4SendERKNS2_12PsmEventDataE]\n");

static __attribute__ ((used)) void* __ptr__ZN3sce3pss5orbis9framework8PsmEvent8RegisterEiPFvRKNS2_12PsmEventDataEPvES7_;
asm(".intel_syntax noprefix\n"
    ".global _ZN3sce3pss5orbis9framework8PsmEvent8RegisterEiPFvRKNS2_12PsmEventDataEPvES7_\n"
    ".type _ZN3sce3pss5orbis9framework8PsmEvent8RegisterEiPFvRKNS2_12PsmEventDataEPvES7_ @function\n"
    "_ZN3sce3pss5orbis9framework8PsmEvent8RegisterEiPFvRKNS2_12PsmEventDataEPvES7_:\n"
    "jmp qword ptr [rip + __ptr__ZN3sce3pss5orbis9framework8PsmEvent8RegisterEiPFvRKNS2_12PsmEventDataEPvES7_]\n");

static __attribute__ ((used)) void* __ptr_scePsmRegisterInternalCall;
asm(".intel_syntax noprefix\n"
    ".global scePsmRegisterInternalCall\n"
    ".type scePsmRegisterInternalCall @function\n"
    "scePsmRegisterInternalCall:\n"
    "jmp qword ptr [rip + __ptr_scePsmRegisterInternalCall]\n");

static __attribute__ ((used)) void* __ptr_scePsmRegisterPInvokeCallTable;
asm(".intel_syntax noprefix\n"
    ".global scePsmRegisterPInvokeCallTable\n"
    ".type scePsmRegisterPInvokeCallTable @function\n"
    "scePsmRegisterPInvokeCallTable:\n"
    "jmp qword ptr [rip + __ptr_scePsmRegisterPInvokeCallTable]\n");

static unsigned short __handle = 0;
static void __attribute__((constructor(104)))
__constructor(void) {
  if(sprx_dlopen("libScePsm", &__handle)) return;
  if(sprx_dlsym(__handle, "DNb-Y-33FyE", &__ptr_ScePsmMonoArrayAddrWithSize)) return;
  if(sprx_dlsym(__handle, "WUKXnNDqQrM", &__ptr_ScePsmMonoArrayLength)) return;
  if(sprx_dlsym(__handle, "hQMZAaNGHAs", &__ptr_ScePsmMonoDomainGet)) return;
  if(sprx_dlsym(__handle, "ZyBRuMgQYvM", &__ptr_ScePsmMonoFree)) return;
  if(sprx_dlsym(__handle, "BVdp6O0nF3k", &__ptr_ScePsmMonoGcWbarrierGenericStore)) return;
  if(sprx_dlsym(__handle, "O4LAoN2b7y4", &__ptr_ScePsmMonoStringChars)) return;
  if(sprx_dlsym(__handle, "1WXYJN+b-e0", &__ptr_ScePsmMonoStringFromUtf16)) return;
  if(sprx_dlsym(__handle, "83i-0wbUtlM", &__ptr_ScePsmMonoStringLength)) return;
  if(sprx_dlsym(__handle, "GtOEkqZ1LDA", &__ptr_ScePsmMonoStringNew)) return;
  if(sprx_dlsym(__handle, "6zGifD5IqRo", &__ptr_ScePsmMonoStringNewWrapper)) return;
  if(sprx_dlsym(__handle, "VvAMtxBHcZc", &__ptr_ScePsmMonoStringToUtf8)) return;
  if(sprx_dlsym(__handle, "WJTGKfpoa1Q", &__ptr__ZN3sce3pss4core14IntHandleTable13NextIntHandleEv)) return;
  if(sprx_dlsym(__handle, "nXD2WHjuPVY", &__ptr__ZN3sce3pss4core8graphics14NativeGraphics18ReleaseVideoMemoryEPv)) return;
  if(sprx_dlsym(__handle, "BCfMrh6R4AY", &__ptr__ZN3sce3pss4core8graphics14NativeGraphics19AllocateVideoMemoryEjj)) return;
  if(sprx_dlsym(__handle, "lAFXMCX8wJc", &__ptr__ZN3sce3pss4core8graphics14NativeGraphics19AllocateVideoMemoryEjjPv)) return;
  if(sprx_dlsym(__handle, "khKtQ6XhB-M", &__ptr__ZN3sce3pss4core8graphics14NativeGraphics19ReleaseSystemMemoryEPv)) return;
  if(sprx_dlsym(__handle, "H8S62po9mYM", &__ptr__ZN3sce3pss4core8graphics14NativeGraphics20AllocateSystemMemoryEjj)) return;
  if(sprx_dlsym(__handle, "zkmLrEtTrOk", &__ptr__ZN3sce3pss4core8graphics14NativeGraphics20AllocateSystemMemoryEjjPv)) return;
  if(sprx_dlsym(__handle, "f68vfrl33DU", &__ptr__ZN3sce3pss4core9PsmObjectC1Ev)) return;
  if(sprx_dlsym(__handle, "h3Z6H5VoZQs", &__ptr__ZN3sce3pss4core9PsmObjectC2Ev)) return;
  if(sprx_dlsym(__handle, "ymlluwxOn8M", &__ptr__ZN3sce3pss4core9PsmObjectD0Ev)) return;
  if(sprx_dlsym(__handle, "i9A0GOpxryc", &__ptr__ZN3sce3pss4core9PsmObjectD1Ev)) return;
  if(sprx_dlsym(__handle, "gWR4Ab-qBsQ", &__ptr__ZN3sce3pss4core9PsmObjectD2Ev)) return;
  if(sprx_dlsym(__handle, "vzCxCYaLWdw", &__ptr__ZN3sce3pss4core9threading4Cond4WaitEi)) return;
  if(sprx_dlsym(__handle, "hMwnRRzjaIU", &__ptr__ZN3sce3pss4core9threading4Cond6NotifyEv)) return;
  if(sprx_dlsym(__handle, "A6tUo1vI7Tw", &__ptr__ZN3sce3pss4core9threading4CondC1ERNS2_5MutexEPKci)) return;
  if(sprx_dlsym(__handle, "KcPayBFYTDc", &__ptr__ZN3sce3pss4core9threading4CondC2ERNS2_5MutexEPKci)) return;
  if(sprx_dlsym(__handle, "G2y9Aln7HYg", &__ptr__ZN3sce3pss4core9threading4CondD1Ev)) return;
  if(sprx_dlsym(__handle, "VC9Kk+u2Xzc", &__ptr__ZN3sce3pss4core9threading4CondD2Ev)) return;
  if(sprx_dlsym(__handle, "v2y883L5C-E", &__ptr__ZN3sce3pss5orbis9framework11PsmArrayObj6LengthEv)) return;
  if(sprx_dlsym(__handle, "rvY1o0UBxaY", &__ptr__ZN3sce3pss5orbis9framework11PsmArrayObj9ToPointerEv)) return;
  if(sprx_dlsym(__handle, "u9jRWuEU9ZQ", &__ptr__ZN3sce3pss5orbis9framework11PsmCallList10UnregisterEPFvPvES4_)) return;
  if(sprx_dlsym(__handle, "JRQDxlSFesA", &__ptr__ZN3sce3pss5orbis9framework11PsmCallList6UpdateEv)) return;
  if(sprx_dlsym(__handle, "A6PU1u15CRI", &__ptr__ZN3sce3pss5orbis9framework11PsmCallList8RegisterEPFvPvES4_)) return;
  if(sprx_dlsym(__handle, "37HHcr6Cw8M", &__ptr__ZN3sce3pss5orbis9framework11PsmCallListC1Ev)) return;
  if(sprx_dlsym(__handle, "YbDoF9zexZU", &__ptr__ZN3sce3pss5orbis9framework11PsmCallListC2Ev)) return;
  if(sprx_dlsym(__handle, "JMA7QKrZvjc", &__ptr__ZN3sce3pss5orbis9framework12PsmEventData8SetValueERKNS_4Json5ValueE)) return;
  if(sprx_dlsym(__handle, "lWlBrUu77Kg", &__ptr__ZN3sce3pss5orbis9framework12PsmFramework10InitializeERKNS2_12PsmInitParamEiPPc)) return;
  if(sprx_dlsym(__handle, "vNcLSBfLtbk", &__ptr__ZN3sce3pss5orbis9framework12PsmFramework20RegisterInternalCallEPKNS2_12PsmCallEntryE)) return;
  if(sprx_dlsym(__handle, "MEuF5zm-r4o", &__ptr__ZN3sce3pss5orbis9framework12PsmFramework24RegisterPInvokeCallTableEPKNS2_15PsmLibraryEntryE)) return;
  if(sprx_dlsym(__handle, "co1TwYJ2ybU", &__ptr__ZN3sce3pss5orbis9framework12PsmFramework3RunEv)) return;
  if(sprx_dlsym(__handle, "6hSAbrbC3sE", &__ptr__ZN3sce3pss5orbis9framework12PsmFramework8FinalizeEv)) return;
  if(sprx_dlsym(__handle, "FqHN0elWA6E", &__ptr__ZN3sce3pss5orbis9framework12PsmInitParamC1Ev)) return;
  if(sprx_dlsym(__handle, "xfw84SLnzeI", &__ptr__ZN3sce3pss5orbis9framework12PsmInitParamC2Ev)) return;
  if(sprx_dlsym(__handle, "PRfVGYzxSCI", &__ptr__ZN3sce3pss5orbis9framework12PsmStringObj17NewAndStoreStringEPvPc)) return;
  if(sprx_dlsym(__handle, "LyT+ncBHMW8", &__ptr__ZN3sce3pss5orbis9framework12PsmStringObj6ToUtf8Ev)) return;
  if(sprx_dlsym(__handle, "CQpBDm9Ykzs", &__ptr__ZN3sce3pss5orbis9framework12PsmStringObj8FreeUtf8EPc)) return;
  if(sprx_dlsym(__handle, "w7PUHXO-d8I", &__ptr__ZN3sce3pss5orbis9framework14PsmDelegateObj11FreePointerEv)) return;
  if(sprx_dlsym(__handle, "LZlnmcG6iO8", &__ptr__ZN3sce3pss5orbis9framework14PsmDelegateObj15AllocatePointerEv)) return;
  if(sprx_dlsym(__handle, "2eLBy9mcYx4", &__ptr__ZN3sce3pss5orbis9framework18PsmFrameworkCsharp21SetEnableNativeMethodEb)) return;
  if(sprx_dlsym(__handle, "uLq7dPUZAyY", &__ptr__ZN3sce3pss5orbis9framework21PsmMainThreadCallList10UnregisterEPFvPvES4_)) return;
  if(sprx_dlsym(__handle, "6Pl+Tx8TW2g", &__ptr__ZN3sce3pss5orbis9framework21PsmMainThreadCallList6UpdateEv)) return;
  if(sprx_dlsym(__handle, "m2fYt-s+A7E", &__ptr__ZN3sce3pss5orbis9framework21PsmMainThreadCallList8RegisterEPFvPvES4_)) return;
  if(sprx_dlsym(__handle, "MUyZpNLfV3I", &__ptr__ZN3sce3pss5orbis9framework23TerminatePsmEventCsharpEv)) return;
  if(sprx_dlsym(__handle, "TGsos8ZCV8c", &__ptr__ZN3sce3pss5orbis9framework24InitializePsmEventCsharpEv)) return;
  if(sprx_dlsym(__handle, "zEJf7JZDmrM", &__ptr__ZN3sce3pss5orbis9framework27TerminatePsmFrameworkCsharpEv)) return;
  if(sprx_dlsym(__handle, "fFD0QoqKajY", &__ptr__ZN3sce3pss5orbis9framework28InitializePsmFrameworkCsharpEv)) return;
  if(sprx_dlsym(__handle, "cLwb9r8x0+8", &__ptr__ZN3sce3pss5orbis9framework8PsmEvent10UnregisterEiPFvRKNS2_12PsmEventDataEPvES7_)) return;
  if(sprx_dlsym(__handle, "I14Gu-NUIUY", &__ptr__ZN3sce3pss5orbis9framework8PsmEvent17RegisterDelegatorEPFvRKNS2_12PsmEventDataEPvES7_)) return;
  if(sprx_dlsym(__handle, "yvp6fh6kF6E", &__ptr__ZN3sce3pss5orbis9framework8PsmEvent19UnregisterDelegatorEPFvRKNS2_12PsmEventDataEPvES7_)) return;
  if(sprx_dlsym(__handle, "7W6jR0LyiSg", &__ptr__ZN3sce3pss5orbis9framework8PsmEvent4PostERKNS2_12PsmEventDataE)) return;
  if(sprx_dlsym(__handle, "xmqLf-a8vYY", &__ptr__ZN3sce3pss5orbis9framework8PsmEvent4SendERKNS2_12PsmEventDataE)) return;
  if(sprx_dlsym(__handle, "m3YkcPqYBzQ", &__ptr__ZN3sce3pss5orbis9framework8PsmEvent8RegisterEiPFvRKNS2_12PsmEventDataEPvES7_)) return;
  if(sprx_dlsym(__handle, "vl8QdnxNxq4", &__ptr_scePsmRegisterInternalCall)) return;
  if(sprx_dlsym(__handle, "34V2Umd+mwM", &__ptr_scePsmRegisterPInvokeCallTable)) return;
}

static void __attribute__((destructor(104)))
__destructor(void) {
  sprx_dlclose(__handle);
}
