/*
 This file was generated by genstub.py, do not edit manually!
*/

int sprx_dlsym(unsigned int handle, const char *nid, void *addr);
int sprx_dlopen(const char* libname, unsigned short *handle);
int sprx_dlclose(unsigned int handle);

static __attribute__ ((used)) void* __ptr_sceRazorCpuBeginLogicalFileAccess;
asm(".intel_syntax noprefix\n"
    ".global sceRazorCpuBeginLogicalFileAccess\n"
    ".type sceRazorCpuBeginLogicalFileAccess @function\n"
    "sceRazorCpuBeginLogicalFileAccess:\n"
    "jmp qword ptr [rip + __ptr_sceRazorCpuBeginLogicalFileAccess]\n");

static __attribute__ ((used)) void* __ptr_sceRazorCpuDisableFiberUserMarkers;
asm(".intel_syntax noprefix\n"
    ".global sceRazorCpuDisableFiberUserMarkers\n"
    ".type sceRazorCpuDisableFiberUserMarkers @function\n"
    "sceRazorCpuDisableFiberUserMarkers:\n"
    "jmp qword ptr [rip + __ptr_sceRazorCpuDisableFiberUserMarkers]\n");

static __attribute__ ((used)) void* __ptr_sceRazorCpuEndLogicalFileAccess;
asm(".intel_syntax noprefix\n"
    ".global sceRazorCpuEndLogicalFileAccess\n"
    ".type sceRazorCpuEndLogicalFileAccess @function\n"
    "sceRazorCpuEndLogicalFileAccess:\n"
    "jmp qword ptr [rip + __ptr_sceRazorCpuEndLogicalFileAccess]\n");

static __attribute__ ((used)) void* __ptr_sceRazorCpuFiberLogNameChange;
asm(".intel_syntax noprefix\n"
    ".global sceRazorCpuFiberLogNameChange\n"
    ".type sceRazorCpuFiberLogNameChange @function\n"
    "sceRazorCpuFiberLogNameChange:\n"
    "jmp qword ptr [rip + __ptr_sceRazorCpuFiberLogNameChange]\n");

static __attribute__ ((used)) void* __ptr_sceRazorCpuFiberSwitch;
asm(".intel_syntax noprefix\n"
    ".global sceRazorCpuFiberSwitch\n"
    ".type sceRazorCpuFiberSwitch @function\n"
    "sceRazorCpuFiberSwitch:\n"
    "jmp qword ptr [rip + __ptr_sceRazorCpuFiberSwitch]\n");

static __attribute__ ((used)) void* __ptr_sceRazorCpuFlushOccurred;
asm(".intel_syntax noprefix\n"
    ".global sceRazorCpuFlushOccurred\n"
    ".type sceRazorCpuFlushOccurred @function\n"
    "sceRazorCpuFlushOccurred:\n"
    "jmp qword ptr [rip + __ptr_sceRazorCpuFlushOccurred]\n");

static __attribute__ ((used)) void* __ptr_sceRazorCpuGetDataTagStorageSize;
asm(".intel_syntax noprefix\n"
    ".global sceRazorCpuGetDataTagStorageSize\n"
    ".type sceRazorCpuGetDataTagStorageSize @function\n"
    "sceRazorCpuGetDataTagStorageSize:\n"
    "jmp qword ptr [rip + __ptr_sceRazorCpuGetDataTagStorageSize]\n");

static __attribute__ ((used)) void* __ptr_sceRazorCpuGpuMarkerSync;
asm(".intel_syntax noprefix\n"
    ".global sceRazorCpuGpuMarkerSync\n"
    ".type sceRazorCpuGpuMarkerSync @function\n"
    "sceRazorCpuGpuMarkerSync:\n"
    "jmp qword ptr [rip + __ptr_sceRazorCpuGpuMarkerSync]\n");

static __attribute__ ((used)) void* __ptr_sceRazorCpuInitDataTags;
asm(".intel_syntax noprefix\n"
    ".global sceRazorCpuInitDataTags\n"
    ".type sceRazorCpuInitDataTags @function\n"
    "sceRazorCpuInitDataTags:\n"
    "jmp qword ptr [rip + __ptr_sceRazorCpuInitDataTags]\n");

static __attribute__ ((used)) void* __ptr_sceRazorCpuInitializeGpuMarkerContext;
asm(".intel_syntax noprefix\n"
    ".global sceRazorCpuInitializeGpuMarkerContext\n"
    ".type sceRazorCpuInitializeGpuMarkerContext @function\n"
    "sceRazorCpuInitializeGpuMarkerContext:\n"
    "jmp qword ptr [rip + __ptr_sceRazorCpuInitializeGpuMarkerContext]\n");

static __attribute__ ((used)) void* __ptr_sceRazorCpuInitializeInternal;
asm(".intel_syntax noprefix\n"
    ".global sceRazorCpuInitializeInternal\n"
    ".type sceRazorCpuInitializeInternal @function\n"
    "sceRazorCpuInitializeInternal:\n"
    "jmp qword ptr [rip + __ptr_sceRazorCpuInitializeInternal]\n");

static __attribute__ ((used)) void* __ptr_sceRazorCpuIsCapturing;
asm(".intel_syntax noprefix\n"
    ".global sceRazorCpuIsCapturing\n"
    ".type sceRazorCpuIsCapturing @function\n"
    "sceRazorCpuIsCapturing:\n"
    "jmp qword ptr [rip + __ptr_sceRazorCpuIsCapturing]\n");

static __attribute__ ((used)) void* __ptr_sceRazorCpuJobManagerDispatch;
asm(".intel_syntax noprefix\n"
    ".global sceRazorCpuJobManagerDispatch\n"
    ".type sceRazorCpuJobManagerDispatch @function\n"
    "sceRazorCpuJobManagerDispatch:\n"
    "jmp qword ptr [rip + __ptr_sceRazorCpuJobManagerDispatch]\n");

static __attribute__ ((used)) void* __ptr_sceRazorCpuJobManagerJob;
asm(".intel_syntax noprefix\n"
    ".global sceRazorCpuJobManagerJob\n"
    ".type sceRazorCpuJobManagerJob @function\n"
    "sceRazorCpuJobManagerJob:\n"
    "jmp qword ptr [rip + __ptr_sceRazorCpuJobManagerJob]\n");

static __attribute__ ((used)) void* __ptr_sceRazorCpuJobManagerSequence;
asm(".intel_syntax noprefix\n"
    ".global sceRazorCpuJobManagerSequence\n"
    ".type sceRazorCpuJobManagerSequence @function\n"
    "sceRazorCpuJobManagerSequence:\n"
    "jmp qword ptr [rip + __ptr_sceRazorCpuJobManagerSequence]\n");

static __attribute__ ((used)) void* __ptr_sceRazorCpuNamedSync;
asm(".intel_syntax noprefix\n"
    ".global sceRazorCpuNamedSync\n"
    ".type sceRazorCpuNamedSync @function\n"
    "sceRazorCpuNamedSync:\n"
    "jmp qword ptr [rip + __ptr_sceRazorCpuNamedSync]\n");

static __attribute__ ((used)) void* __ptr_sceRazorCpuPlotValue;
asm(".intel_syntax noprefix\n"
    ".global sceRazorCpuPlotValue\n"
    ".type sceRazorCpuPlotValue @function\n"
    "sceRazorCpuPlotValue:\n"
    "jmp qword ptr [rip + __ptr_sceRazorCpuPlotValue]\n");

static __attribute__ ((used)) void* __ptr_sceRazorCpuPopMarker;
asm(".intel_syntax noprefix\n"
    ".global sceRazorCpuPopMarker\n"
    ".type sceRazorCpuPopMarker @function\n"
    "sceRazorCpuPopMarker:\n"
    "jmp qword ptr [rip + __ptr_sceRazorCpuPopMarker]\n");

static __attribute__ ((used)) void* __ptr_sceRazorCpuPushMarker;
asm(".intel_syntax noprefix\n"
    ".global sceRazorCpuPushMarker\n"
    ".type sceRazorCpuPushMarker @function\n"
    "sceRazorCpuPushMarker:\n"
    "jmp qword ptr [rip + __ptr_sceRazorCpuPushMarker]\n");

static __attribute__ ((used)) void* __ptr_sceRazorCpuPushMarkerStatic;
asm(".intel_syntax noprefix\n"
    ".global sceRazorCpuPushMarkerStatic\n"
    ".type sceRazorCpuPushMarkerStatic @function\n"
    "sceRazorCpuPushMarkerStatic:\n"
    "jmp qword ptr [rip + __ptr_sceRazorCpuPushMarkerStatic]\n");

static __attribute__ ((used)) void* __ptr_sceRazorCpuResizeTaggedBuffer;
asm(".intel_syntax noprefix\n"
    ".global sceRazorCpuResizeTaggedBuffer\n"
    ".type sceRazorCpuResizeTaggedBuffer @function\n"
    "sceRazorCpuResizeTaggedBuffer:\n"
    "jmp qword ptr [rip + __ptr_sceRazorCpuResizeTaggedBuffer]\n");

static __attribute__ ((used)) void* __ptr_sceRazorCpuSetPopMarkerCallback;
asm(".intel_syntax noprefix\n"
    ".global sceRazorCpuSetPopMarkerCallback\n"
    ".type sceRazorCpuSetPopMarkerCallback @function\n"
    "sceRazorCpuSetPopMarkerCallback:\n"
    "jmp qword ptr [rip + __ptr_sceRazorCpuSetPopMarkerCallback]\n");

static __attribute__ ((used)) void* __ptr_sceRazorCpuSetPushMarkerCallback;
asm(".intel_syntax noprefix\n"
    ".global sceRazorCpuSetPushMarkerCallback\n"
    ".type sceRazorCpuSetPushMarkerCallback @function\n"
    "sceRazorCpuSetPushMarkerCallback:\n"
    "jmp qword ptr [rip + __ptr_sceRazorCpuSetPushMarkerCallback]\n");

static __attribute__ ((used)) void* __ptr_sceRazorCpuSetPushMarkerStaticCallback;
asm(".intel_syntax noprefix\n"
    ".global sceRazorCpuSetPushMarkerStaticCallback\n"
    ".type sceRazorCpuSetPushMarkerStaticCallback @function\n"
    "sceRazorCpuSetPushMarkerStaticCallback:\n"
    "jmp qword ptr [rip + __ptr_sceRazorCpuSetPushMarkerStaticCallback]\n");

static __attribute__ ((used)) void* __ptr_sceRazorCpuShutdownDataTags;
asm(".intel_syntax noprefix\n"
    ".global sceRazorCpuShutdownDataTags\n"
    ".type sceRazorCpuShutdownDataTags @function\n"
    "sceRazorCpuShutdownDataTags:\n"
    "jmp qword ptr [rip + __ptr_sceRazorCpuShutdownDataTags]\n");

static __attribute__ ((used)) void* __ptr_sceRazorCpuStartCaptureInternal;
asm(".intel_syntax noprefix\n"
    ".global sceRazorCpuStartCaptureInternal\n"
    ".type sceRazorCpuStartCaptureInternal @function\n"
    "sceRazorCpuStartCaptureInternal:\n"
    "jmp qword ptr [rip + __ptr_sceRazorCpuStartCaptureInternal]\n");

static __attribute__ ((used)) void* __ptr_sceRazorCpuStopCaptureInternal;
asm(".intel_syntax noprefix\n"
    ".global sceRazorCpuStopCaptureInternal\n"
    ".type sceRazorCpuStopCaptureInternal @function\n"
    "sceRazorCpuStopCaptureInternal:\n"
    "jmp qword ptr [rip + __ptr_sceRazorCpuStopCaptureInternal]\n");

static __attribute__ ((used)) void* __ptr_sceRazorCpuSync;
asm(".intel_syntax noprefix\n"
    ".global sceRazorCpuSync\n"
    ".type sceRazorCpuSync @function\n"
    "sceRazorCpuSync:\n"
    "jmp qword ptr [rip + __ptr_sceRazorCpuSync]\n");

static __attribute__ ((used)) void* __ptr_sceRazorCpuTagArray;
asm(".intel_syntax noprefix\n"
    ".global sceRazorCpuTagArray\n"
    ".type sceRazorCpuTagArray @function\n"
    "sceRazorCpuTagArray:\n"
    "jmp qword ptr [rip + __ptr_sceRazorCpuTagArray]\n");

static __attribute__ ((used)) void* __ptr_sceRazorCpuTagBuffer;
asm(".intel_syntax noprefix\n"
    ".global sceRazorCpuTagBuffer\n"
    ".type sceRazorCpuTagBuffer @function\n"
    "sceRazorCpuTagBuffer:\n"
    "jmp qword ptr [rip + __ptr_sceRazorCpuTagBuffer]\n");

static __attribute__ ((used)) void* __ptr_sceRazorCpuUnTagBuffer;
asm(".intel_syntax noprefix\n"
    ".global sceRazorCpuUnTagBuffer\n"
    ".type sceRazorCpuUnTagBuffer @function\n"
    "sceRazorCpuUnTagBuffer:\n"
    "jmp qword ptr [rip + __ptr_sceRazorCpuUnTagBuffer]\n");

static __attribute__ ((used)) void* __ptr_sceRazorCpuWorkloadRunBegin;
asm(".intel_syntax noprefix\n"
    ".global sceRazorCpuWorkloadRunBegin\n"
    ".type sceRazorCpuWorkloadRunBegin @function\n"
    "sceRazorCpuWorkloadRunBegin:\n"
    "jmp qword ptr [rip + __ptr_sceRazorCpuWorkloadRunBegin]\n");

static __attribute__ ((used)) void* __ptr_sceRazorCpuWorkloadRunEnd;
asm(".intel_syntax noprefix\n"
    ".global sceRazorCpuWorkloadRunEnd\n"
    ".type sceRazorCpuWorkloadRunEnd @function\n"
    "sceRazorCpuWorkloadRunEnd:\n"
    "jmp qword ptr [rip + __ptr_sceRazorCpuWorkloadRunEnd]\n");

static __attribute__ ((used)) void* __ptr_sceRazorCpuWorkloadSubmit;
asm(".intel_syntax noprefix\n"
    ".global sceRazorCpuWorkloadSubmit\n"
    ".type sceRazorCpuWorkloadSubmit @function\n"
    "sceRazorCpuWorkloadSubmit:\n"
    "jmp qword ptr [rip + __ptr_sceRazorCpuWorkloadSubmit]\n");

static __attribute__ ((used)) void* __ptr_sceRazorCpuWriteBookmark;
asm(".intel_syntax noprefix\n"
    ".global sceRazorCpuWriteBookmark\n"
    ".type sceRazorCpuWriteBookmark @function\n"
    "sceRazorCpuWriteBookmark:\n"
    "jmp qword ptr [rip + __ptr_sceRazorCpuWriteBookmark]\n");

static unsigned short __handle = 0;
static void __attribute__((constructor(104)))
__constructor(void) {
  if(sprx_dlopen("libSceRazorCpu", &__handle)) return;
  if(sprx_dlsym(__handle, "JFzLJBlYIJE", &__ptr_sceRazorCpuBeginLogicalFileAccess)) return;
  if(sprx_dlsym(__handle, "SfRTRZ1Sh+U", &__ptr_sceRazorCpuDisableFiberUserMarkers)) return;
  if(sprx_dlsym(__handle, "gVioM9cbiDs", &__ptr_sceRazorCpuEndLogicalFileAccess)) return;
  if(sprx_dlsym(__handle, "G90IIOtgFQ0", &__ptr_sceRazorCpuFiberLogNameChange)) return;
  if(sprx_dlsym(__handle, "PAytDtFGpqY", &__ptr_sceRazorCpuFiberSwitch)) return;
  if(sprx_dlsym(__handle, "sPhrQD31ClM", &__ptr_sceRazorCpuFlushOccurred)) return;
  if(sprx_dlsym(__handle, "B782NptkGUc", &__ptr_sceRazorCpuGetDataTagStorageSize)) return;
  if(sprx_dlsym(__handle, "EH9Au2RlSrE", &__ptr_sceRazorCpuGpuMarkerSync)) return;
  if(sprx_dlsym(__handle, "A7oRMdaOJP8", &__ptr_sceRazorCpuInitDataTags)) return;
  if(sprx_dlsym(__handle, "NFwh-J-BrI0", &__ptr_sceRazorCpuInitializeGpuMarkerContext)) return;
  if(sprx_dlsym(__handle, "ElNyedXaa4o", &__ptr_sceRazorCpuInitializeInternal)) return;
  if(sprx_dlsym(__handle, "EboejOQvLL4", &__ptr_sceRazorCpuIsCapturing)) return;
  if(sprx_dlsym(__handle, "dnEdyY4+klQ", &__ptr_sceRazorCpuJobManagerDispatch)) return;
  if(sprx_dlsym(__handle, "KP+TBWGHlgs", &__ptr_sceRazorCpuJobManagerJob)) return;
  if(sprx_dlsym(__handle, "9FowWFMEIM8", &__ptr_sceRazorCpuJobManagerSequence)) return;
  if(sprx_dlsym(__handle, "XCuZoBSVFG8", &__ptr_sceRazorCpuNamedSync)) return;
  if(sprx_dlsym(__handle, "njGikRrxkC0", &__ptr_sceRazorCpuPlotValue)) return;
  if(sprx_dlsym(__handle, "YpkGsMXP3ew", &__ptr_sceRazorCpuPopMarker)) return;
  if(sprx_dlsym(__handle, "zw+celG7zSI", &__ptr_sceRazorCpuPushMarker)) return;
  if(sprx_dlsym(__handle, "uZrOwuNJX-M", &__ptr_sceRazorCpuPushMarkerStatic)) return;
  if(sprx_dlsym(__handle, "D0yUjM33QqU", &__ptr_sceRazorCpuResizeTaggedBuffer)) return;
  if(sprx_dlsym(__handle, "jqYWaTfgZs0", &__ptr_sceRazorCpuSetPopMarkerCallback)) return;
  if(sprx_dlsym(__handle, "DJsHcEb94n0", &__ptr_sceRazorCpuSetPushMarkerCallback)) return;
  if(sprx_dlsym(__handle, "EZtqozPTS4M", &__ptr_sceRazorCpuSetPushMarkerStaticCallback)) return;
  if(sprx_dlsym(__handle, "emklx7RK-LY", &__ptr_sceRazorCpuShutdownDataTags)) return;
  if(sprx_dlsym(__handle, "TIytAjYeaik", &__ptr_sceRazorCpuStartCaptureInternal)) return;
  if(sprx_dlsym(__handle, "jWpkVWdMrsM", &__ptr_sceRazorCpuStopCaptureInternal)) return;
  if(sprx_dlsym(__handle, "Ax7NjOzctIM", &__ptr_sceRazorCpuSync)) return;
  if(sprx_dlsym(__handle, "we3oTKSPSTw", &__ptr_sceRazorCpuTagArray)) return;
  if(sprx_dlsym(__handle, "vyjdThnQfQQ", &__ptr_sceRazorCpuTagBuffer)) return;
  if(sprx_dlsym(__handle, "0yNHPIkVTmw", &__ptr_sceRazorCpuUnTagBuffer)) return;
  if(sprx_dlsym(__handle, "eRn6vlfK6ac", &__ptr_sceRazorCpuWorkloadRunBegin)) return;
  if(sprx_dlsym(__handle, "q1GxBfGHO0s", &__ptr_sceRazorCpuWorkloadRunEnd)) return;
  if(sprx_dlsym(__handle, "6rUvx-6QmYc", &__ptr_sceRazorCpuWorkloadSubmit)) return;
  if(sprx_dlsym(__handle, "G3brhegfyNg", &__ptr_sceRazorCpuWriteBookmark)) return;
}

static void __attribute__((destructor(104)))
__destructor(void) {
  sprx_dlclose(__handle);
}
