/*
 This file was generated by genstub.py, do not edit manually!
*/

int sprx_dlsym(unsigned int handle, const char *nid, void *addr);
int sprx_dlopen(const char* libname, unsigned short *handle);
int sprx_dlclose(unsigned int handle);

static __attribute__ ((used)) void* __ptr_sceNpAppLauncherInitialize;
asm(".intel_syntax noprefix\n"
    ".global sceNpAppLauncherInitialize\n"
    ".type sceNpAppLauncherInitialize @function\n"
    "sceNpAppLauncherInitialize:\n"
    "jmp qword ptr [rip + __ptr_sceNpAppLauncherInitialize]\n");

static __attribute__ ((used)) void* __ptr_sceNpAppLauncherLaunchApp;
asm(".intel_syntax noprefix\n"
    ".global sceNpAppLauncherLaunchApp\n"
    ".type sceNpAppLauncherLaunchApp @function\n"
    "sceNpAppLauncherLaunchApp:\n"
    "jmp qword ptr [rip + __ptr_sceNpAppLauncherLaunchApp]\n");

static __attribute__ ((used)) void* __ptr_sceNpAppLauncherTerminate;
asm(".intel_syntax noprefix\n"
    ".global sceNpAppLauncherTerminate\n"
    ".type sceNpAppLauncherTerminate @function\n"
    "sceNpAppLauncherTerminate:\n"
    "jmp qword ptr [rip + __ptr_sceNpAppLauncherTerminate]\n");

static __attribute__ ((used)) void* __ptr_sceNpGameIntentGetPropertyValueString;
asm(".intel_syntax noprefix\n"
    ".global sceNpGameIntentGetPropertyValueString\n"
    ".type sceNpGameIntentGetPropertyValueString @function\n"
    "sceNpGameIntentGetPropertyValueString:\n"
    "jmp qword ptr [rip + __ptr_sceNpGameIntentGetPropertyValueString]\n");

static __attribute__ ((used)) void* __ptr_sceNpGameIntentGetUdsNpComId;
asm(".intel_syntax noprefix\n"
    ".global sceNpGameIntentGetUdsNpComId\n"
    ".type sceNpGameIntentGetUdsNpComId @function\n"
    "sceNpGameIntentGetUdsNpComId:\n"
    "jmp qword ptr [rip + __ptr_sceNpGameIntentGetUdsNpComId]\n");

static __attribute__ ((used)) void* __ptr_sceNpGameIntentInitialize;
asm(".intel_syntax noprefix\n"
    ".global sceNpGameIntentInitialize\n"
    ".type sceNpGameIntentInitialize @function\n"
    "sceNpGameIntentInitialize:\n"
    "jmp qword ptr [rip + __ptr_sceNpGameIntentInitialize]\n");

static __attribute__ ((used)) void* __ptr_sceNpGameIntentLaunchApp;
asm(".intel_syntax noprefix\n"
    ".global sceNpGameIntentLaunchApp\n"
    ".type sceNpGameIntentLaunchApp @function\n"
    "sceNpGameIntentLaunchApp:\n"
    "jmp qword ptr [rip + __ptr_sceNpGameIntentLaunchApp]\n");

static __attribute__ ((used)) void* __ptr_sceNpGameIntentLaunchApp2;
asm(".intel_syntax noprefix\n"
    ".global sceNpGameIntentLaunchApp2\n"
    ".type sceNpGameIntentLaunchApp2 @function\n"
    "sceNpGameIntentLaunchApp2:\n"
    "jmp qword ptr [rip + __ptr_sceNpGameIntentLaunchApp2]\n");

static __attribute__ ((used)) void* __ptr_sceNpGameIntentNotifyAppLaunched;
asm(".intel_syntax noprefix\n"
    ".global sceNpGameIntentNotifyAppLaunched\n"
    ".type sceNpGameIntentNotifyAppLaunched @function\n"
    "sceNpGameIntentNotifyAppLaunched:\n"
    "jmp qword ptr [rip + __ptr_sceNpGameIntentNotifyAppLaunched]\n");

static __attribute__ ((used)) void* __ptr_sceNpGameIntentReceiveIntent;
asm(".intel_syntax noprefix\n"
    ".global sceNpGameIntentReceiveIntent\n"
    ".type sceNpGameIntentReceiveIntent @function\n"
    "sceNpGameIntentReceiveIntent:\n"
    "jmp qword ptr [rip + __ptr_sceNpGameIntentReceiveIntent]\n");

static __attribute__ ((used)) void* __ptr_sceNpGameIntentTerminate;
asm(".intel_syntax noprefix\n"
    ".global sceNpGameIntentTerminate\n"
    ".type sceNpGameIntentTerminate @function\n"
    "sceNpGameIntentTerminate:\n"
    "jmp qword ptr [rip + __ptr_sceNpGameIntentTerminate]\n");

static __attribute__ ((used)) void* __ptr_sceNpSessionServiceGetJoinedPartySession;
asm(".intel_syntax noprefix\n"
    ".global sceNpSessionServiceGetJoinedPartySession\n"
    ".type sceNpSessionServiceGetJoinedPartySession @function\n"
    "sceNpSessionServiceGetJoinedPartySession:\n"
    "jmp qword ptr [rip + __ptr_sceNpSessionServiceGetJoinedPartySession]\n");

static __attribute__ ((used)) void* __ptr_sceNpSessionServiceGetRunningGamePlayerSession;
asm(".intel_syntax noprefix\n"
    ".global sceNpSessionServiceGetRunningGamePlayerSession\n"
    ".type sceNpSessionServiceGetRunningGamePlayerSession @function\n"
    "sceNpSessionServiceGetRunningGamePlayerSession:\n"
    "jmp qword ptr [rip + __ptr_sceNpSessionServiceGetRunningGamePlayerSession]\n");

static __attribute__ ((used)) void* __ptr_sceNpSessionServiceSendPlayerSessionInvitations;
asm(".intel_syntax noprefix\n"
    ".global sceNpSessionServiceSendPlayerSessionInvitations\n"
    ".type sceNpSessionServiceSendPlayerSessionInvitations @function\n"
    "sceNpSessionServiceSendPlayerSessionInvitations:\n"
    "jmp qword ptr [rip + __ptr_sceNpSessionServiceSendPlayerSessionInvitations]\n");

static unsigned short __handle = 0;
static void __attribute__((constructor(104)))
__constructor(void) {
  if(sprx_dlopen("libSceNpGameIntent", &__handle)) return;
  if(sprx_dlsym(__handle, "od0pFsDoez0", &__ptr_sceNpAppLauncherInitialize)) return;
  if(sprx_dlsym(__handle, "GbayQ7DO8jA", &__ptr_sceNpAppLauncherLaunchApp)) return;
  if(sprx_dlsym(__handle, "sy3PioM8TPE", &__ptr_sceNpAppLauncherTerminate)) return;
  if(sprx_dlsym(__handle, "rPl0INNc-M8", &__ptr_sceNpGameIntentGetPropertyValueString)) return;
  if(sprx_dlsym(__handle, "KNggmcdqc2Q", &__ptr_sceNpGameIntentGetUdsNpComId)) return;
  if(sprx_dlsym(__handle, "m87BHxt-H60", &__ptr_sceNpGameIntentInitialize)) return;
  if(sprx_dlsym(__handle, "DAR+Nuv4E7M", &__ptr_sceNpGameIntentLaunchApp)) return;
  if(sprx_dlsym(__handle, "d-YDTQrxDJA", &__ptr_sceNpGameIntentLaunchApp2)) return;
  if(sprx_dlsym(__handle, "opFs796vTHg", &__ptr_sceNpGameIntentNotifyAppLaunched)) return;
  if(sprx_dlsym(__handle, "jEIXUAr9XE8", &__ptr_sceNpGameIntentReceiveIntent)) return;
  if(sprx_dlsym(__handle, "0HBYxYAjmf0", &__ptr_sceNpGameIntentTerminate)) return;
  if(sprx_dlsym(__handle, "EfgH5jBjqpM", &__ptr_sceNpSessionServiceGetJoinedPartySession)) return;
  if(sprx_dlsym(__handle, "tEGD9ugK0w8", &__ptr_sceNpSessionServiceGetRunningGamePlayerSession)) return;
  if(sprx_dlsym(__handle, "f2jyE0mDY5k", &__ptr_sceNpSessionServiceSendPlayerSessionInvitations)) return;
}

static void __attribute__((destructor(104)))
__destructor(void) {
  sprx_dlclose(__handle);
}
