/*
 This file was generated by genstub.py, do not edit manually!
*/

int sprx_dlsym(unsigned int handle, const char *nid, void *addr);
int sprx_dlopen(const char* libname, unsigned short *handle);
int sprx_dlclose(unsigned int handle);

static __attribute__ ((used)) void* __ptr_sceNpWebApi2AbortRequest;
asm(".intel_syntax noprefix\n"
    ".global sceNpWebApi2AbortRequest\n"
    ".type sceNpWebApi2AbortRequest @function\n"
    "sceNpWebApi2AbortRequest:\n"
    "jmp qword ptr [rip + __ptr_sceNpWebApi2AbortRequest]\n");

static __attribute__ ((used)) void* __ptr_sceNpWebApi2AddHttpRequestHeader;
asm(".intel_syntax noprefix\n"
    ".global sceNpWebApi2AddHttpRequestHeader\n"
    ".type sceNpWebApi2AddHttpRequestHeader @function\n"
    "sceNpWebApi2AddHttpRequestHeader:\n"
    "jmp qword ptr [rip + __ptr_sceNpWebApi2AddHttpRequestHeader]\n");

static __attribute__ ((used)) void* __ptr_sceNpWebApi2AddMultipartPart;
asm(".intel_syntax noprefix\n"
    ".global sceNpWebApi2AddMultipartPart\n"
    ".type sceNpWebApi2AddMultipartPart @function\n"
    "sceNpWebApi2AddMultipartPart:\n"
    "jmp qword ptr [rip + __ptr_sceNpWebApi2AddMultipartPart]\n");

static __attribute__ ((used)) void* __ptr_sceNpWebApi2AddWebTraceTag;
asm(".intel_syntax noprefix\n"
    ".global sceNpWebApi2AddWebTraceTag\n"
    ".type sceNpWebApi2AddWebTraceTag @function\n"
    "sceNpWebApi2AddWebTraceTag:\n"
    "jmp qword ptr [rip + __ptr_sceNpWebApi2AddWebTraceTag]\n");

static __attribute__ ((used)) void* __ptr_sceNpWebApi2CheckTimeout;
asm(".intel_syntax noprefix\n"
    ".global sceNpWebApi2CheckTimeout\n"
    ".type sceNpWebApi2CheckTimeout @function\n"
    "sceNpWebApi2CheckTimeout:\n"
    "jmp qword ptr [rip + __ptr_sceNpWebApi2CheckTimeout]\n");

static __attribute__ ((used)) void* __ptr_sceNpWebApi2CreateMultipartRequest;
asm(".intel_syntax noprefix\n"
    ".global sceNpWebApi2CreateMultipartRequest\n"
    ".type sceNpWebApi2CreateMultipartRequest @function\n"
    "sceNpWebApi2CreateMultipartRequest:\n"
    "jmp qword ptr [rip + __ptr_sceNpWebApi2CreateMultipartRequest]\n");

static __attribute__ ((used)) void* __ptr_sceNpWebApi2CreateRequest;
asm(".intel_syntax noprefix\n"
    ".global sceNpWebApi2CreateRequest\n"
    ".type sceNpWebApi2CreateRequest @function\n"
    "sceNpWebApi2CreateRequest:\n"
    "jmp qword ptr [rip + __ptr_sceNpWebApi2CreateRequest]\n");

static __attribute__ ((used)) void* __ptr_sceNpWebApi2CreateUserContext;
asm(".intel_syntax noprefix\n"
    ".global sceNpWebApi2CreateUserContext\n"
    ".type sceNpWebApi2CreateUserContext @function\n"
    "sceNpWebApi2CreateUserContext:\n"
    "jmp qword ptr [rip + __ptr_sceNpWebApi2CreateUserContext]\n");

static __attribute__ ((used)) void* __ptr_sceNpWebApi2DeleteRequest;
asm(".intel_syntax noprefix\n"
    ".global sceNpWebApi2DeleteRequest\n"
    ".type sceNpWebApi2DeleteRequest @function\n"
    "sceNpWebApi2DeleteRequest:\n"
    "jmp qword ptr [rip + __ptr_sceNpWebApi2DeleteRequest]\n");

static __attribute__ ((used)) void* __ptr_sceNpWebApi2DeleteUserContext;
asm(".intel_syntax noprefix\n"
    ".global sceNpWebApi2DeleteUserContext\n"
    ".type sceNpWebApi2DeleteUserContext @function\n"
    "sceNpWebApi2DeleteUserContext:\n"
    "jmp qword ptr [rip + __ptr_sceNpWebApi2DeleteUserContext]\n");

static __attribute__ ((used)) void* __ptr_sceNpWebApi2GetHttpResponseHeaderValue;
asm(".intel_syntax noprefix\n"
    ".global sceNpWebApi2GetHttpResponseHeaderValue\n"
    ".type sceNpWebApi2GetHttpResponseHeaderValue @function\n"
    "sceNpWebApi2GetHttpResponseHeaderValue:\n"
    "jmp qword ptr [rip + __ptr_sceNpWebApi2GetHttpResponseHeaderValue]\n");

static __attribute__ ((used)) void* __ptr_sceNpWebApi2GetHttpResponseHeaderValueLength;
asm(".intel_syntax noprefix\n"
    ".global sceNpWebApi2GetHttpResponseHeaderValueLength\n"
    ".type sceNpWebApi2GetHttpResponseHeaderValueLength @function\n"
    "sceNpWebApi2GetHttpResponseHeaderValueLength:\n"
    "jmp qword ptr [rip + __ptr_sceNpWebApi2GetHttpResponseHeaderValueLength]\n");

static __attribute__ ((used)) void* __ptr_sceNpWebApi2GetMemoryPoolStats;
asm(".intel_syntax noprefix\n"
    ".global sceNpWebApi2GetMemoryPoolStats\n"
    ".type sceNpWebApi2GetMemoryPoolStats @function\n"
    "sceNpWebApi2GetMemoryPoolStats:\n"
    "jmp qword ptr [rip + __ptr_sceNpWebApi2GetMemoryPoolStats]\n");

static __attribute__ ((used)) void* __ptr_sceNpWebApi2Initialize;
asm(".intel_syntax noprefix\n"
    ".global sceNpWebApi2Initialize\n"
    ".type sceNpWebApi2Initialize @function\n"
    "sceNpWebApi2Initialize:\n"
    "jmp qword ptr [rip + __ptr_sceNpWebApi2Initialize]\n");

static __attribute__ ((used)) void* __ptr_sceNpWebApi2InitializeForPresence;
asm(".intel_syntax noprefix\n"
    ".global sceNpWebApi2InitializeForPresence\n"
    ".type sceNpWebApi2InitializeForPresence @function\n"
    "sceNpWebApi2InitializeForPresence:\n"
    "jmp qword ptr [rip + __ptr_sceNpWebApi2InitializeForPresence]\n");

static __attribute__ ((used)) void* __ptr_sceNpWebApi2IntCreateRequest;
asm(".intel_syntax noprefix\n"
    ".global sceNpWebApi2IntCreateRequest\n"
    ".type sceNpWebApi2IntCreateRequest @function\n"
    "sceNpWebApi2IntCreateRequest:\n"
    "jmp qword ptr [rip + __ptr_sceNpWebApi2IntCreateRequest]\n");

static __attribute__ ((used)) void* __ptr_sceNpWebApi2IntInitialize;
asm(".intel_syntax noprefix\n"
    ".global sceNpWebApi2IntInitialize\n"
    ".type sceNpWebApi2IntInitialize @function\n"
    "sceNpWebApi2IntInitialize:\n"
    "jmp qword ptr [rip + __ptr_sceNpWebApi2IntInitialize]\n");

static __attribute__ ((used)) void* __ptr_sceNpWebApi2IntInitialize2;
asm(".intel_syntax noprefix\n"
    ".global sceNpWebApi2IntInitialize2\n"
    ".type sceNpWebApi2IntInitialize2 @function\n"
    "sceNpWebApi2IntInitialize2:\n"
    "jmp qword ptr [rip + __ptr_sceNpWebApi2IntInitialize2]\n");

static __attribute__ ((used)) void* __ptr_sceNpWebApi2IntPushEventCreateCtxIndFilter;
asm(".intel_syntax noprefix\n"
    ".global sceNpWebApi2IntPushEventCreateCtxIndFilter\n"
    ".type sceNpWebApi2IntPushEventCreateCtxIndFilter @function\n"
    "sceNpWebApi2IntPushEventCreateCtxIndFilter:\n"
    "jmp qword ptr [rip + __ptr_sceNpWebApi2IntPushEventCreateCtxIndFilter]\n");

static __attribute__ ((used)) void* __ptr_sceNpWebApi2IntPushEventCreateDestPs4CtxIndFilter;
asm(".intel_syntax noprefix\n"
    ".global sceNpWebApi2IntPushEventCreateDestPs4CtxIndFilter\n"
    ".type sceNpWebApi2IntPushEventCreateDestPs4CtxIndFilter @function\n"
    "sceNpWebApi2IntPushEventCreateDestPs4CtxIndFilter:\n"
    "jmp qword ptr [rip + __ptr_sceNpWebApi2IntPushEventCreateDestPs4CtxIndFilter]\n");

static __attribute__ ((used)) void* __ptr_sceNpWebApi2PushEventAbortHandle;
asm(".intel_syntax noprefix\n"
    ".global sceNpWebApi2PushEventAbortHandle\n"
    ".type sceNpWebApi2PushEventAbortHandle @function\n"
    "sceNpWebApi2PushEventAbortHandle:\n"
    "jmp qword ptr [rip + __ptr_sceNpWebApi2PushEventAbortHandle]\n");

static __attribute__ ((used)) void* __ptr_sceNpWebApi2PushEventCreateFilter;
asm(".intel_syntax noprefix\n"
    ".global sceNpWebApi2PushEventCreateFilter\n"
    ".type sceNpWebApi2PushEventCreateFilter @function\n"
    "sceNpWebApi2PushEventCreateFilter:\n"
    "jmp qword ptr [rip + __ptr_sceNpWebApi2PushEventCreateFilter]\n");

static __attribute__ ((used)) void* __ptr_sceNpWebApi2PushEventCreateHandle;
asm(".intel_syntax noprefix\n"
    ".global sceNpWebApi2PushEventCreateHandle\n"
    ".type sceNpWebApi2PushEventCreateHandle @function\n"
    "sceNpWebApi2PushEventCreateHandle:\n"
    "jmp qword ptr [rip + __ptr_sceNpWebApi2PushEventCreateHandle]\n");

static __attribute__ ((used)) void* __ptr_sceNpWebApi2PushEventCreatePushContext;
asm(".intel_syntax noprefix\n"
    ".global sceNpWebApi2PushEventCreatePushContext\n"
    ".type sceNpWebApi2PushEventCreatePushContext @function\n"
    "sceNpWebApi2PushEventCreatePushContext:\n"
    "jmp qword ptr [rip + __ptr_sceNpWebApi2PushEventCreatePushContext]\n");

static __attribute__ ((used)) void* __ptr_sceNpWebApi2PushEventDeleteFilter;
asm(".intel_syntax noprefix\n"
    ".global sceNpWebApi2PushEventDeleteFilter\n"
    ".type sceNpWebApi2PushEventDeleteFilter @function\n"
    "sceNpWebApi2PushEventDeleteFilter:\n"
    "jmp qword ptr [rip + __ptr_sceNpWebApi2PushEventDeleteFilter]\n");

static __attribute__ ((used)) void* __ptr_sceNpWebApi2PushEventDeleteHandle;
asm(".intel_syntax noprefix\n"
    ".global sceNpWebApi2PushEventDeleteHandle\n"
    ".type sceNpWebApi2PushEventDeleteHandle @function\n"
    "sceNpWebApi2PushEventDeleteHandle:\n"
    "jmp qword ptr [rip + __ptr_sceNpWebApi2PushEventDeleteHandle]\n");

static __attribute__ ((used)) void* __ptr_sceNpWebApi2PushEventDeletePushContext;
asm(".intel_syntax noprefix\n"
    ".global sceNpWebApi2PushEventDeletePushContext\n"
    ".type sceNpWebApi2PushEventDeletePushContext @function\n"
    "sceNpWebApi2PushEventDeletePushContext:\n"
    "jmp qword ptr [rip + __ptr_sceNpWebApi2PushEventDeletePushContext]\n");

static __attribute__ ((used)) void* __ptr_sceNpWebApi2PushEventRegisterCallback;
asm(".intel_syntax noprefix\n"
    ".global sceNpWebApi2PushEventRegisterCallback\n"
    ".type sceNpWebApi2PushEventRegisterCallback @function\n"
    "sceNpWebApi2PushEventRegisterCallback:\n"
    "jmp qword ptr [rip + __ptr_sceNpWebApi2PushEventRegisterCallback]\n");

static __attribute__ ((used)) void* __ptr_sceNpWebApi2PushEventRegisterPushContextCallback;
asm(".intel_syntax noprefix\n"
    ".global sceNpWebApi2PushEventRegisterPushContextCallback\n"
    ".type sceNpWebApi2PushEventRegisterPushContextCallback @function\n"
    "sceNpWebApi2PushEventRegisterPushContextCallback:\n"
    "jmp qword ptr [rip + __ptr_sceNpWebApi2PushEventRegisterPushContextCallback]\n");

static __attribute__ ((used)) void* __ptr_sceNpWebApi2PushEventSetHandleTimeout;
asm(".intel_syntax noprefix\n"
    ".global sceNpWebApi2PushEventSetHandleTimeout\n"
    ".type sceNpWebApi2PushEventSetHandleTimeout @function\n"
    "sceNpWebApi2PushEventSetHandleTimeout:\n"
    "jmp qword ptr [rip + __ptr_sceNpWebApi2PushEventSetHandleTimeout]\n");

static __attribute__ ((used)) void* __ptr_sceNpWebApi2PushEventStartPushContextCallback;
asm(".intel_syntax noprefix\n"
    ".global sceNpWebApi2PushEventStartPushContextCallback\n"
    ".type sceNpWebApi2PushEventStartPushContextCallback @function\n"
    "sceNpWebApi2PushEventStartPushContextCallback:\n"
    "jmp qword ptr [rip + __ptr_sceNpWebApi2PushEventStartPushContextCallback]\n");

static __attribute__ ((used)) void* __ptr_sceNpWebApi2PushEventUnregisterCallback;
asm(".intel_syntax noprefix\n"
    ".global sceNpWebApi2PushEventUnregisterCallback\n"
    ".type sceNpWebApi2PushEventUnregisterCallback @function\n"
    "sceNpWebApi2PushEventUnregisterCallback:\n"
    "jmp qword ptr [rip + __ptr_sceNpWebApi2PushEventUnregisterCallback]\n");

static __attribute__ ((used)) void* __ptr_sceNpWebApi2PushEventUnregisterPushContextCallback;
asm(".intel_syntax noprefix\n"
    ".global sceNpWebApi2PushEventUnregisterPushContextCallback\n"
    ".type sceNpWebApi2PushEventUnregisterPushContextCallback @function\n"
    "sceNpWebApi2PushEventUnregisterPushContextCallback:\n"
    "jmp qword ptr [rip + __ptr_sceNpWebApi2PushEventUnregisterPushContextCallback]\n");

static __attribute__ ((used)) void* __ptr_sceNpWebApi2ReadData;
asm(".intel_syntax noprefix\n"
    ".global sceNpWebApi2ReadData\n"
    ".type sceNpWebApi2ReadData @function\n"
    "sceNpWebApi2ReadData:\n"
    "jmp qword ptr [rip + __ptr_sceNpWebApi2ReadData]\n");

static __attribute__ ((used)) void* __ptr_sceNpWebApi2SendMultipartRequest;
asm(".intel_syntax noprefix\n"
    ".global sceNpWebApi2SendMultipartRequest\n"
    ".type sceNpWebApi2SendMultipartRequest @function\n"
    "sceNpWebApi2SendMultipartRequest:\n"
    "jmp qword ptr [rip + __ptr_sceNpWebApi2SendMultipartRequest]\n");

static __attribute__ ((used)) void* __ptr_sceNpWebApi2SendRequest;
asm(".intel_syntax noprefix\n"
    ".global sceNpWebApi2SendRequest\n"
    ".type sceNpWebApi2SendRequest @function\n"
    "sceNpWebApi2SendRequest:\n"
    "jmp qword ptr [rip + __ptr_sceNpWebApi2SendRequest]\n");

static __attribute__ ((used)) void* __ptr_sceNpWebApi2SetMultipartContentType;
asm(".intel_syntax noprefix\n"
    ".global sceNpWebApi2SetMultipartContentType\n"
    ".type sceNpWebApi2SetMultipartContentType @function\n"
    "sceNpWebApi2SetMultipartContentType:\n"
    "jmp qword ptr [rip + __ptr_sceNpWebApi2SetMultipartContentType]\n");

static __attribute__ ((used)) void* __ptr_sceNpWebApi2SetRequestTimeout;
asm(".intel_syntax noprefix\n"
    ".global sceNpWebApi2SetRequestTimeout\n"
    ".type sceNpWebApi2SetRequestTimeout @function\n"
    "sceNpWebApi2SetRequestTimeout:\n"
    "jmp qword ptr [rip + __ptr_sceNpWebApi2SetRequestTimeout]\n");

static __attribute__ ((used)) void* __ptr_sceNpWebApi2Terminate;
asm(".intel_syntax noprefix\n"
    ".global sceNpWebApi2Terminate\n"
    ".type sceNpWebApi2Terminate @function\n"
    "sceNpWebApi2Terminate:\n"
    "jmp qword ptr [rip + __ptr_sceNpWebApi2Terminate]\n");

static unsigned short __handle = 0;
static void __attribute__((constructor(104)))
__constructor(void) {
  if(sprx_dlopen("libSceNpWebApi2", &__handle)) return;
  if(sprx_dlsym(__handle, "zpiPsH7dbFQ", &__ptr_sceNpWebApi2AbortRequest)) return;
  if(sprx_dlsym(__handle, "egOOvrnF6mI", &__ptr_sceNpWebApi2AddHttpRequestHeader)) return;
  if(sprx_dlsym(__handle, "Io7kh1LHDoM", &__ptr_sceNpWebApi2AddMultipartPart)) return;
  if(sprx_dlsym(__handle, "MgsTa76wlEk", &__ptr_sceNpWebApi2AddWebTraceTag)) return;
  if(sprx_dlsym(__handle, "3Tt9zL3tkoc", &__ptr_sceNpWebApi2CheckTimeout)) return;
  if(sprx_dlsym(__handle, "+nz1Vq-NrDA", &__ptr_sceNpWebApi2CreateMultipartRequest)) return;
  if(sprx_dlsym(__handle, "3EI-OSJ65Xc", &__ptr_sceNpWebApi2CreateRequest)) return;
  if(sprx_dlsym(__handle, "sk54bi6FtYM", &__ptr_sceNpWebApi2CreateUserContext)) return;
  if(sprx_dlsym(__handle, "vvzWO-DvG1s", &__ptr_sceNpWebApi2DeleteRequest)) return;
  if(sprx_dlsym(__handle, "9X9+cneTGUU", &__ptr_sceNpWebApi2DeleteUserContext)) return;
  if(sprx_dlsym(__handle, "hksbskNToEA", &__ptr_sceNpWebApi2GetHttpResponseHeaderValue)) return;
  if(sprx_dlsym(__handle, "HwP3aM+c85c", &__ptr_sceNpWebApi2GetHttpResponseHeaderValueLength)) return;
  if(sprx_dlsym(__handle, "Xweb+naPZ8Y", &__ptr_sceNpWebApi2GetMemoryPoolStats)) return;
  if(sprx_dlsym(__handle, "+o9816YQhqQ", &__ptr_sceNpWebApi2Initialize)) return;
  if(sprx_dlsym(__handle, "dowMWFgowXY", &__ptr_sceNpWebApi2InitializeForPresence)) return;
  if(sprx_dlsym(__handle, "qmINYLuqzaA", &__ptr_sceNpWebApi2IntCreateRequest)) return;
  if(sprx_dlsym(__handle, "zXaFo7euxsQ", &__ptr_sceNpWebApi2IntInitialize)) return;
  if(sprx_dlsym(__handle, "9KSGFMRnp3k", &__ptr_sceNpWebApi2IntInitialize2)) return;
  if(sprx_dlsym(__handle, "2hlBNB96saE", &__ptr_sceNpWebApi2IntPushEventCreateCtxIndFilter)) return;
  if(sprx_dlsym(__handle, "81DkaQt6J30", &__ptr_sceNpWebApi2IntPushEventCreateDestPs4CtxIndFilter)) return;
  if(sprx_dlsym(__handle, "1OLgvahaSco", &__ptr_sceNpWebApi2PushEventAbortHandle)) return;
  if(sprx_dlsym(__handle, "MsaFhR+lPE4", &__ptr_sceNpWebApi2PushEventCreateFilter)) return;
  if(sprx_dlsym(__handle, "WV1GwM32NgY", &__ptr_sceNpWebApi2PushEventCreateHandle)) return;
  if(sprx_dlsym(__handle, "NNVf18SlbT8", &__ptr_sceNpWebApi2PushEventCreatePushContext)) return;
  if(sprx_dlsym(__handle, "KJdPcOGmK58", &__ptr_sceNpWebApi2PushEventDeleteFilter)) return;
  if(sprx_dlsym(__handle, "fIATVMo4Y1w", &__ptr_sceNpWebApi2PushEventDeleteHandle)) return;
  if(sprx_dlsym(__handle, "QafxeZM3WK4", &__ptr_sceNpWebApi2PushEventDeletePushContext)) return;
  if(sprx_dlsym(__handle, "fY3QqeNkF8k", &__ptr_sceNpWebApi2PushEventRegisterCallback)) return;
  if(sprx_dlsym(__handle, "lxtHJMwBsaU", &__ptr_sceNpWebApi2PushEventRegisterPushContextCallback)) return;
  if(sprx_dlsym(__handle, "KWkc6Q3tjXc", &__ptr_sceNpWebApi2PushEventSetHandleTimeout)) return;
  if(sprx_dlsym(__handle, "AAj9X+4aGYA", &__ptr_sceNpWebApi2PushEventStartPushContextCallback)) return;
  if(sprx_dlsym(__handle, "hOnIlcGrO6g", &__ptr_sceNpWebApi2PushEventUnregisterCallback)) return;
  if(sprx_dlsym(__handle, "PmyrbbJSFz0", &__ptr_sceNpWebApi2PushEventUnregisterPushContextCallback)) return;
  if(sprx_dlsym(__handle, "OOY9+ObfKec", &__ptr_sceNpWebApi2ReadData)) return;
  if(sprx_dlsym(__handle, "NKCwS8+5Fx8", &__ptr_sceNpWebApi2SendMultipartRequest)) return;
  if(sprx_dlsym(__handle, "lQOCF84lvzw", &__ptr_sceNpWebApi2SendRequest)) return;
  if(sprx_dlsym(__handle, "bltDCAskmfE", &__ptr_sceNpWebApi2SetMultipartContentType)) return;
  if(sprx_dlsym(__handle, "TjAutbrkr60", &__ptr_sceNpWebApi2SetRequestTimeout)) return;
  if(sprx_dlsym(__handle, "bEvXpcEk200", &__ptr_sceNpWebApi2Terminate)) return;
}

static void __attribute__((destructor(104)))
__destructor(void) {
  sprx_dlclose(__handle);
}
