/*
 This file was generated by genstub.py, do not edit manually!
*/

int sprx_dlsym(unsigned int handle, const char *nid, void *addr);
int sprx_dlopen(const char* libname, unsigned short *handle);
int sprx_dlclose(unsigned int handle);

static __attribute__ ((used)) void* __ptr_sceVdecCoreAnalyzeStream;
asm(".intel_syntax noprefix\n"
    ".global sceVdecCoreAnalyzeStream\n"
    ".type sceVdecCoreAnalyzeStream @function\n"
    "sceVdecCoreAnalyzeStream:\n"
    "jmp qword ptr [rip + __ptr_sceVdecCoreAnalyzeStream]\n");

static __attribute__ ((used)) void* __ptr_sceVdecCoreCreateDecoder;
asm(".intel_syntax noprefix\n"
    ".global sceVdecCoreCreateDecoder\n"
    ".type sceVdecCoreCreateDecoder @function\n"
    "sceVdecCoreCreateDecoder:\n"
    "jmp qword ptr [rip + __ptr_sceVdecCoreCreateDecoder]\n");

static __attribute__ ((used)) void* __ptr_sceVdecCoreCreateDecoderBid;
asm(".intel_syntax noprefix\n"
    ".global sceVdecCoreCreateDecoderBid\n"
    ".type sceVdecCoreCreateDecoderBid @function\n"
    "sceVdecCoreCreateDecoderBid:\n"
    "jmp qword ptr [rip + __ptr_sceVdecCoreCreateDecoderBid]\n");

static __attribute__ ((used)) void* __ptr_sceVdecCoreCreateDecoderSvp;
asm(".intel_syntax noprefix\n"
    ".global sceVdecCoreCreateDecoderSvp\n"
    ".type sceVdecCoreCreateDecoderSvp @function\n"
    "sceVdecCoreCreateDecoderSvp:\n"
    "jmp qword ptr [rip + __ptr_sceVdecCoreCreateDecoderSvp]\n");

static __attribute__ ((used)) void* __ptr_sceVdecCoreDeleteDecoder;
asm(".intel_syntax noprefix\n"
    ".global sceVdecCoreDeleteDecoder\n"
    ".type sceVdecCoreDeleteDecoder @function\n"
    "sceVdecCoreDeleteDecoder:\n"
    "jmp qword ptr [rip + __ptr_sceVdecCoreDeleteDecoder]\n");

static __attribute__ ((used)) void* __ptr_sceVdecCoreFinalizeComputeResource;
asm(".intel_syntax noprefix\n"
    ".global sceVdecCoreFinalizeComputeResource\n"
    ".type sceVdecCoreFinalizeComputeResource @function\n"
    "sceVdecCoreFinalizeComputeResource:\n"
    "jmp qword ptr [rip + __ptr_sceVdecCoreFinalizeComputeResource]\n");

static __attribute__ ((used)) void* __ptr_sceVdecCoreFlushDecodeOutput;
asm(".intel_syntax noprefix\n"
    ".global sceVdecCoreFlushDecodeOutput\n"
    ".type sceVdecCoreFlushDecodeOutput @function\n"
    "sceVdecCoreFlushDecodeOutput:\n"
    "jmp qword ptr [rip + __ptr_sceVdecCoreFlushDecodeOutput]\n");

static __attribute__ ((used)) void* __ptr_sceVdecCoreGetDecodeOutput;
asm(".intel_syntax noprefix\n"
    ".global sceVdecCoreGetDecodeOutput\n"
    ".type sceVdecCoreGetDecodeOutput @function\n"
    "sceVdecCoreGetDecodeOutput:\n"
    "jmp qword ptr [rip + __ptr_sceVdecCoreGetDecodeOutput]\n");

static __attribute__ ((used)) void* __ptr_sceVdecCoreInitializeComputeResource;
asm(".intel_syntax noprefix\n"
    ".global sceVdecCoreInitializeComputeResource\n"
    ".type sceVdecCoreInitializeComputeResource @function\n"
    "sceVdecCoreInitializeComputeResource:\n"
    "jmp qword ptr [rip + __ptr_sceVdecCoreInitializeComputeResource]\n");

static __attribute__ ((used)) void* __ptr_sceVdecCoreMapMemory;
asm(".intel_syntax noprefix\n"
    ".global sceVdecCoreMapMemory\n"
    ".type sceVdecCoreMapMemory @function\n"
    "sceVdecCoreMapMemory:\n"
    "jmp qword ptr [rip + __ptr_sceVdecCoreMapMemory]\n");

static __attribute__ ((used)) void* __ptr_sceVdecCoreMapMemoryBlock;
asm(".intel_syntax noprefix\n"
    ".global sceVdecCoreMapMemoryBlock\n"
    ".type sceVdecCoreMapMemoryBlock @function\n"
    "sceVdecCoreMapMemoryBlock:\n"
    "jmp qword ptr [rip + __ptr_sceVdecCoreMapMemoryBlock]\n");

static __attribute__ ((used)) void* __ptr_sceVdecCoreQueryComputeResourceInfo;
asm(".intel_syntax noprefix\n"
    ".global sceVdecCoreQueryComputeResourceInfo\n"
    ".type sceVdecCoreQueryComputeResourceInfo @function\n"
    "sceVdecCoreQueryComputeResourceInfo:\n"
    "jmp qword ptr [rip + __ptr_sceVdecCoreQueryComputeResourceInfo]\n");

static __attribute__ ((used)) void* __ptr_sceVdecCoreQueryFrameBufferInfo;
asm(".intel_syntax noprefix\n"
    ".global sceVdecCoreQueryFrameBufferInfo\n"
    ".type sceVdecCoreQueryFrameBufferInfo @function\n"
    "sceVdecCoreQueryFrameBufferInfo:\n"
    "jmp qword ptr [rip + __ptr_sceVdecCoreQueryFrameBufferInfo]\n");

static __attribute__ ((used)) void* __ptr_sceVdecCoreQueryInstanceSize;
asm(".intel_syntax noprefix\n"
    ".global sceVdecCoreQueryInstanceSize\n"
    ".type sceVdecCoreQueryInstanceSize @function\n"
    "sceVdecCoreQueryInstanceSize:\n"
    "jmp qword ptr [rip + __ptr_sceVdecCoreQueryInstanceSize]\n");

static __attribute__ ((used)) void* __ptr_sceVdecCoreResetDecoder;
asm(".intel_syntax noprefix\n"
    ".global sceVdecCoreResetDecoder\n"
    ".type sceVdecCoreResetDecoder @function\n"
    "sceVdecCoreResetDecoder:\n"
    "jmp qword ptr [rip + __ptr_sceVdecCoreResetDecoder]\n");

static __attribute__ ((used)) void* __ptr_sceVdecCoreSetDecodeInput;
asm(".intel_syntax noprefix\n"
    ".global sceVdecCoreSetDecodeInput\n"
    ".type sceVdecCoreSetDecodeInput @function\n"
    "sceVdecCoreSetDecodeInput:\n"
    "jmp qword ptr [rip + __ptr_sceVdecCoreSetDecodeInput]\n");

static __attribute__ ((used)) void* __ptr_sceVdecCoreSetDecodeInputSvp;
asm(".intel_syntax noprefix\n"
    ".global sceVdecCoreSetDecodeInputSvp\n"
    ".type sceVdecCoreSetDecodeInputSvp @function\n"
    "sceVdecCoreSetDecodeInputSvp:\n"
    "jmp qword ptr [rip + __ptr_sceVdecCoreSetDecodeInputSvp]\n");

static __attribute__ ((used)) void* __ptr_sceVdecCoreSetDecodeOutputSw;
asm(".intel_syntax noprefix\n"
    ".global sceVdecCoreSetDecodeOutputSw\n"
    ".type sceVdecCoreSetDecodeOutputSw @function\n"
    "sceVdecCoreSetDecodeOutputSw:\n"
    "jmp qword ptr [rip + __ptr_sceVdecCoreSetDecodeOutputSw]\n");

static __attribute__ ((used)) void* __ptr_sceVdecCoreSyncDecode;
asm(".intel_syntax noprefix\n"
    ".global sceVdecCoreSyncDecode\n"
    ".type sceVdecCoreSyncDecode @function\n"
    "sceVdecCoreSyncDecode:\n"
    "jmp qword ptr [rip + __ptr_sceVdecCoreSyncDecode]\n");

static __attribute__ ((used)) void* __ptr_sceVdecCoreSyncDecodeOutputSw;
asm(".intel_syntax noprefix\n"
    ".global sceVdecCoreSyncDecodeOutputSw\n"
    ".type sceVdecCoreSyncDecodeOutputSw @function\n"
    "sceVdecCoreSyncDecodeOutputSw:\n"
    "jmp qword ptr [rip + __ptr_sceVdecCoreSyncDecodeOutputSw]\n");

static __attribute__ ((used)) void* __ptr_sceVdecCoreSyncDecodeWptr;
asm(".intel_syntax noprefix\n"
    ".global sceVdecCoreSyncDecodeWptr\n"
    ".type sceVdecCoreSyncDecodeWptr @function\n"
    "sceVdecCoreSyncDecodeWptr:\n"
    "jmp qword ptr [rip + __ptr_sceVdecCoreSyncDecodeWptr]\n");

static __attribute__ ((used)) void* __ptr_sceVdecCoreTrySyncDecode;
asm(".intel_syntax noprefix\n"
    ".global sceVdecCoreTrySyncDecode\n"
    ".type sceVdecCoreTrySyncDecode @function\n"
    "sceVdecCoreTrySyncDecode:\n"
    "jmp qword ptr [rip + __ptr_sceVdecCoreTrySyncDecode]\n");

static __attribute__ ((used)) void* __ptr_sceVdecCoreTrySyncDecodeOutputSw;
asm(".intel_syntax noprefix\n"
    ".global sceVdecCoreTrySyncDecodeOutputSw\n"
    ".type sceVdecCoreTrySyncDecodeOutputSw @function\n"
    "sceVdecCoreTrySyncDecodeOutputSw:\n"
    "jmp qword ptr [rip + __ptr_sceVdecCoreTrySyncDecodeOutputSw]\n");

static __attribute__ ((used)) void* __ptr_sceVdecCoreTrySyncDecodeWptr;
asm(".intel_syntax noprefix\n"
    ".global sceVdecCoreTrySyncDecodeWptr\n"
    ".type sceVdecCoreTrySyncDecodeWptr @function\n"
    "sceVdecCoreTrySyncDecodeWptr:\n"
    "jmp qword ptr [rip + __ptr_sceVdecCoreTrySyncDecodeWptr]\n");

static unsigned short __handle = 0;
static void __attribute__((constructor(104)))
__constructor(void) {
  if(sprx_dlopen("libSceVdecCore.native", &__handle)) return;
  if(sprx_dlsym(__handle, "bWPuW6TnMjk", &__ptr_sceVdecCoreAnalyzeStream)) return;
  if(sprx_dlsym(__handle, "wnWMkCYv0m4", &__ptr_sceVdecCoreCreateDecoder)) return;
  if(sprx_dlsym(__handle, "ZZnvlKc8nfg", &__ptr_sceVdecCoreCreateDecoderBid)) return;
  if(sprx_dlsym(__handle, "xI8avtVkGWw", &__ptr_sceVdecCoreCreateDecoderSvp)) return;
  if(sprx_dlsym(__handle, "D0RWslNmK9s", &__ptr_sceVdecCoreDeleteDecoder)) return;
  if(sprx_dlsym(__handle, "DHQXNKiY-Dw", &__ptr_sceVdecCoreFinalizeComputeResource)) return;
  if(sprx_dlsym(__handle, "b0xbD0x+02M", &__ptr_sceVdecCoreFlushDecodeOutput)) return;
  if(sprx_dlsym(__handle, "K4sH-0WUfuc", &__ptr_sceVdecCoreGetDecodeOutput)) return;
  if(sprx_dlsym(__handle, "HPpz-oyX4vM", &__ptr_sceVdecCoreInitializeComputeResource)) return;
  if(sprx_dlsym(__handle, "hUza-a0hX2c", &__ptr_sceVdecCoreMapMemory)) return;
  if(sprx_dlsym(__handle, "7YW9rloMLYo", &__ptr_sceVdecCoreMapMemoryBlock)) return;
  if(sprx_dlsym(__handle, "zwcpjJ7WUgQ", &__ptr_sceVdecCoreQueryComputeResourceInfo)) return;
  if(sprx_dlsym(__handle, "UxV5adxfBFg", &__ptr_sceVdecCoreQueryFrameBufferInfo)) return;
  if(sprx_dlsym(__handle, "Zsh1K8YTD1E", &__ptr_sceVdecCoreQueryInstanceSize)) return;
  if(sprx_dlsym(__handle, "nFn-3CWQEyo", &__ptr_sceVdecCoreResetDecoder)) return;
  if(sprx_dlsym(__handle, "F4nrEfi-M84", &__ptr_sceVdecCoreSetDecodeInput)) return;
  if(sprx_dlsym(__handle, "cPn3fXO-J5M", &__ptr_sceVdecCoreSetDecodeInputSvp)) return;
  if(sprx_dlsym(__handle, "hF8Pz0rtPLU", &__ptr_sceVdecCoreSetDecodeOutputSw)) return;
  if(sprx_dlsym(__handle, "OyxRC7GT4Es", &__ptr_sceVdecCoreSyncDecode)) return;
  if(sprx_dlsym(__handle, "1hE5Sdn4U3U", &__ptr_sceVdecCoreSyncDecodeOutputSw)) return;
  if(sprx_dlsym(__handle, "JFcSDC6AD+k", &__ptr_sceVdecCoreSyncDecodeWptr)) return;
  if(sprx_dlsym(__handle, "iQRVLJQ+OYs", &__ptr_sceVdecCoreTrySyncDecode)) return;
  if(sprx_dlsym(__handle, "WMhw0IVNNC8", &__ptr_sceVdecCoreTrySyncDecodeOutputSw)) return;
  if(sprx_dlsym(__handle, "T9yCBYaGDew", &__ptr_sceVdecCoreTrySyncDecodeWptr)) return;
}

static void __attribute__((destructor(104)))
__destructor(void) {
  sprx_dlclose(__handle);
}
