/*
 This file was generated by genstub.py, do not edit manually!
*/

int sprx_dlsym(unsigned int handle, const char *nid, void *addr);
int sprx_dlopen(const char* libname, unsigned short *handle);
int sprx_dlclose(unsigned int handle);

static __attribute__ ((used)) void* __ptr_sceNpSignalingActivateConnection;
asm(".intel_syntax noprefix\n"
    ".global sceNpSignalingActivateConnection\n"
    ".type sceNpSignalingActivateConnection @function\n"
    "sceNpSignalingActivateConnection:\n"
    "jmp qword ptr [rip + __ptr_sceNpSignalingActivateConnection]\n");

static __attribute__ ((used)) void* __ptr_sceNpSignalingActivateConnectionA;
asm(".intel_syntax noprefix\n"
    ".global sceNpSignalingActivateConnectionA\n"
    ".type sceNpSignalingActivateConnectionA @function\n"
    "sceNpSignalingActivateConnectionA:\n"
    "jmp qword ptr [rip + __ptr_sceNpSignalingActivateConnectionA]\n");

static __attribute__ ((used)) void* __ptr_sceNpSignalingCancelPeerNetInfo;
asm(".intel_syntax noprefix\n"
    ".global sceNpSignalingCancelPeerNetInfo\n"
    ".type sceNpSignalingCancelPeerNetInfo @function\n"
    "sceNpSignalingCancelPeerNetInfo:\n"
    "jmp qword ptr [rip + __ptr_sceNpSignalingCancelPeerNetInfo]\n");

static __attribute__ ((used)) void* __ptr_sceNpSignalingCreateContext;
asm(".intel_syntax noprefix\n"
    ".global sceNpSignalingCreateContext\n"
    ".type sceNpSignalingCreateContext @function\n"
    "sceNpSignalingCreateContext:\n"
    "jmp qword ptr [rip + __ptr_sceNpSignalingCreateContext]\n");

static __attribute__ ((used)) void* __ptr_sceNpSignalingCreateContextA;
asm(".intel_syntax noprefix\n"
    ".global sceNpSignalingCreateContextA\n"
    ".type sceNpSignalingCreateContextA @function\n"
    "sceNpSignalingCreateContextA:\n"
    "jmp qword ptr [rip + __ptr_sceNpSignalingCreateContextA]\n");

static __attribute__ ((used)) void* __ptr_sceNpSignalingDeactivateConnection;
asm(".intel_syntax noprefix\n"
    ".global sceNpSignalingDeactivateConnection\n"
    ".type sceNpSignalingDeactivateConnection @function\n"
    "sceNpSignalingDeactivateConnection:\n"
    "jmp qword ptr [rip + __ptr_sceNpSignalingDeactivateConnection]\n");

static __attribute__ ((used)) void* __ptr_sceNpSignalingDeleteContext;
asm(".intel_syntax noprefix\n"
    ".global sceNpSignalingDeleteContext\n"
    ".type sceNpSignalingDeleteContext @function\n"
    "sceNpSignalingDeleteContext:\n"
    "jmp qword ptr [rip + __ptr_sceNpSignalingDeleteContext]\n");

static __attribute__ ((used)) void* __ptr_sceNpSignalingGetConnectionFromNpId;
asm(".intel_syntax noprefix\n"
    ".global sceNpSignalingGetConnectionFromNpId\n"
    ".type sceNpSignalingGetConnectionFromNpId @function\n"
    "sceNpSignalingGetConnectionFromNpId:\n"
    "jmp qword ptr [rip + __ptr_sceNpSignalingGetConnectionFromNpId]\n");

static __attribute__ ((used)) void* __ptr_sceNpSignalingGetConnectionFromPeerAddress;
asm(".intel_syntax noprefix\n"
    ".global sceNpSignalingGetConnectionFromPeerAddress\n"
    ".type sceNpSignalingGetConnectionFromPeerAddress @function\n"
    "sceNpSignalingGetConnectionFromPeerAddress:\n"
    "jmp qword ptr [rip + __ptr_sceNpSignalingGetConnectionFromPeerAddress]\n");

static __attribute__ ((used)) void* __ptr_sceNpSignalingGetConnectionFromPeerAddressA;
asm(".intel_syntax noprefix\n"
    ".global sceNpSignalingGetConnectionFromPeerAddressA\n"
    ".type sceNpSignalingGetConnectionFromPeerAddressA @function\n"
    "sceNpSignalingGetConnectionFromPeerAddressA:\n"
    "jmp qword ptr [rip + __ptr_sceNpSignalingGetConnectionFromPeerAddressA]\n");

static __attribute__ ((used)) void* __ptr_sceNpSignalingGetConnectionInfo;
asm(".intel_syntax noprefix\n"
    ".global sceNpSignalingGetConnectionInfo\n"
    ".type sceNpSignalingGetConnectionInfo @function\n"
    "sceNpSignalingGetConnectionInfo:\n"
    "jmp qword ptr [rip + __ptr_sceNpSignalingGetConnectionInfo]\n");

static __attribute__ ((used)) void* __ptr_sceNpSignalingGetConnectionInfoA;
asm(".intel_syntax noprefix\n"
    ".global sceNpSignalingGetConnectionInfoA\n"
    ".type sceNpSignalingGetConnectionInfoA @function\n"
    "sceNpSignalingGetConnectionInfoA:\n"
    "jmp qword ptr [rip + __ptr_sceNpSignalingGetConnectionInfoA]\n");

static __attribute__ ((used)) void* __ptr_sceNpSignalingGetConnectionStatistics;
asm(".intel_syntax noprefix\n"
    ".global sceNpSignalingGetConnectionStatistics\n"
    ".type sceNpSignalingGetConnectionStatistics @function\n"
    "sceNpSignalingGetConnectionStatistics:\n"
    "jmp qword ptr [rip + __ptr_sceNpSignalingGetConnectionStatistics]\n");

static __attribute__ ((used)) void* __ptr_sceNpSignalingGetConnectionStatus;
asm(".intel_syntax noprefix\n"
    ".global sceNpSignalingGetConnectionStatus\n"
    ".type sceNpSignalingGetConnectionStatus @function\n"
    "sceNpSignalingGetConnectionStatus:\n"
    "jmp qword ptr [rip + __ptr_sceNpSignalingGetConnectionStatus]\n");

static __attribute__ ((used)) void* __ptr_sceNpSignalingGetContextOption;
asm(".intel_syntax noprefix\n"
    ".global sceNpSignalingGetContextOption\n"
    ".type sceNpSignalingGetContextOption @function\n"
    "sceNpSignalingGetContextOption:\n"
    "jmp qword ptr [rip + __ptr_sceNpSignalingGetContextOption]\n");

static __attribute__ ((used)) void* __ptr_sceNpSignalingGetLocalNetInfo;
asm(".intel_syntax noprefix\n"
    ".global sceNpSignalingGetLocalNetInfo\n"
    ".type sceNpSignalingGetLocalNetInfo @function\n"
    "sceNpSignalingGetLocalNetInfo:\n"
    "jmp qword ptr [rip + __ptr_sceNpSignalingGetLocalNetInfo]\n");

static __attribute__ ((used)) void* __ptr_sceNpSignalingGetMemoryInfo;
asm(".intel_syntax noprefix\n"
    ".global sceNpSignalingGetMemoryInfo\n"
    ".type sceNpSignalingGetMemoryInfo @function\n"
    "sceNpSignalingGetMemoryInfo:\n"
    "jmp qword ptr [rip + __ptr_sceNpSignalingGetMemoryInfo]\n");

static __attribute__ ((used)) void* __ptr_sceNpSignalingGetPeerNetInfo;
asm(".intel_syntax noprefix\n"
    ".global sceNpSignalingGetPeerNetInfo\n"
    ".type sceNpSignalingGetPeerNetInfo @function\n"
    "sceNpSignalingGetPeerNetInfo:\n"
    "jmp qword ptr [rip + __ptr_sceNpSignalingGetPeerNetInfo]\n");

static __attribute__ ((used)) void* __ptr_sceNpSignalingGetPeerNetInfoA;
asm(".intel_syntax noprefix\n"
    ".global sceNpSignalingGetPeerNetInfoA\n"
    ".type sceNpSignalingGetPeerNetInfoA @function\n"
    "sceNpSignalingGetPeerNetInfoA:\n"
    "jmp qword ptr [rip + __ptr_sceNpSignalingGetPeerNetInfoA]\n");

static __attribute__ ((used)) void* __ptr_sceNpSignalingGetPeerNetInfoResult;
asm(".intel_syntax noprefix\n"
    ".global sceNpSignalingGetPeerNetInfoResult\n"
    ".type sceNpSignalingGetPeerNetInfoResult @function\n"
    "sceNpSignalingGetPeerNetInfoResult:\n"
    "jmp qword ptr [rip + __ptr_sceNpSignalingGetPeerNetInfoResult]\n");

static __attribute__ ((used)) void* __ptr_sceNpSignalingInitialize;
asm(".intel_syntax noprefix\n"
    ".global sceNpSignalingInitialize\n"
    ".type sceNpSignalingInitialize @function\n"
    "sceNpSignalingInitialize:\n"
    "jmp qword ptr [rip + __ptr_sceNpSignalingInitialize]\n");

static __attribute__ ((used)) void* __ptr_sceNpSignalingSetContextOption;
asm(".intel_syntax noprefix\n"
    ".global sceNpSignalingSetContextOption\n"
    ".type sceNpSignalingSetContextOption @function\n"
    "sceNpSignalingSetContextOption:\n"
    "jmp qword ptr [rip + __ptr_sceNpSignalingSetContextOption]\n");

static __attribute__ ((used)) void* __ptr_sceNpSignalingTerminate;
asm(".intel_syntax noprefix\n"
    ".global sceNpSignalingTerminate\n"
    ".type sceNpSignalingTerminate @function\n"
    "sceNpSignalingTerminate:\n"
    "jmp qword ptr [rip + __ptr_sceNpSignalingTerminate]\n");

static __attribute__ ((used)) void* __ptr_sceNpSignalingTerminateConnection;
asm(".intel_syntax noprefix\n"
    ".global sceNpSignalingTerminateConnection\n"
    ".type sceNpSignalingTerminateConnection @function\n"
    "sceNpSignalingTerminateConnection:\n"
    "jmp qword ptr [rip + __ptr_sceNpSignalingTerminateConnection]\n");

static unsigned short __handle = 0;
static void __attribute__((constructor(104)))
__constructor(void) {
  if(sprx_dlopen("libSceNpSignaling", &__handle)) return;
  if(sprx_dlsym(__handle, "0UvTFeomAUM", &__ptr_sceNpSignalingActivateConnection)) return;
  if(sprx_dlsym(__handle, "ZPLavCKqAB0", &__ptr_sceNpSignalingActivateConnectionA)) return;
  if(sprx_dlsym(__handle, "X1G4kkN2R-8", &__ptr_sceNpSignalingCancelPeerNetInfo)) return;
  if(sprx_dlsym(__handle, "5yYjEdd4t8Y", &__ptr_sceNpSignalingCreateContext)) return;
  if(sprx_dlsym(__handle, "dDLNFdY8dws", &__ptr_sceNpSignalingCreateContextA)) return;
  if(sprx_dlsym(__handle, "6UEembipgrM", &__ptr_sceNpSignalingDeactivateConnection)) return;
  if(sprx_dlsym(__handle, "hx+LIg-1koI", &__ptr_sceNpSignalingDeleteContext)) return;
  if(sprx_dlsym(__handle, "GQ0hqmzj0F4", &__ptr_sceNpSignalingGetConnectionFromNpId)) return;
  if(sprx_dlsym(__handle, "CkPxQjSm018", &__ptr_sceNpSignalingGetConnectionFromPeerAddress)) return;
  if(sprx_dlsym(__handle, "B7cT9aVby7A", &__ptr_sceNpSignalingGetConnectionFromPeerAddressA)) return;
  if(sprx_dlsym(__handle, "AN3h0EBSX7A", &__ptr_sceNpSignalingGetConnectionInfo)) return;
  if(sprx_dlsym(__handle, "rcylknsUDwg", &__ptr_sceNpSignalingGetConnectionInfoA)) return;
  if(sprx_dlsym(__handle, "C6ZNCDTj00Y", &__ptr_sceNpSignalingGetConnectionStatistics)) return;
  if(sprx_dlsym(__handle, "bD-JizUb3JM", &__ptr_sceNpSignalingGetConnectionStatus)) return;
  if(sprx_dlsym(__handle, "npU5V56id34", &__ptr_sceNpSignalingGetContextOption)) return;
  if(sprx_dlsym(__handle, "U8AQMlOFBc8", &__ptr_sceNpSignalingGetLocalNetInfo)) return;
  if(sprx_dlsym(__handle, "tOpqyDyMje4", &__ptr_sceNpSignalingGetMemoryInfo)) return;
  if(sprx_dlsym(__handle, "zFgFHId7vAE", &__ptr_sceNpSignalingGetPeerNetInfo)) return;
  if(sprx_dlsym(__handle, "Shr7bZq8QHY", &__ptr_sceNpSignalingGetPeerNetInfoA)) return;
  if(sprx_dlsym(__handle, "2HajCEGgG4s", &__ptr_sceNpSignalingGetPeerNetInfoResult)) return;
  if(sprx_dlsym(__handle, "3KOuC4RmZZU", &__ptr_sceNpSignalingInitialize)) return;
  if(sprx_dlsym(__handle, "IHRDvZodPYY", &__ptr_sceNpSignalingSetContextOption)) return;
  if(sprx_dlsym(__handle, "NPhw0UXaNrk", &__ptr_sceNpSignalingTerminate)) return;
  if(sprx_dlsym(__handle, "b4qaXPzMJxo", &__ptr_sceNpSignalingTerminateConnection)) return;
}

static void __attribute__((destructor(104)))
__destructor(void) {
  sprx_dlclose(__handle);
}
