/*
 This file was generated by genstub.py, do not edit manually!
*/

int sprx_dlsym(unsigned int handle, const char *nid, void *addr);
int sprx_dlopen(const char* libname, unsigned short *handle);
int sprx_dlclose(unsigned int handle);

static __attribute__ ((used)) void* __ptr_sceAcmBatchStartBuffer;
asm(".intel_syntax noprefix\n"
    ".global sceAcmBatchStartBuffer\n"
    ".type sceAcmBatchStartBuffer @function\n"
    "sceAcmBatchStartBuffer:\n"
    "jmp qword ptr [rip + __ptr_sceAcmBatchStartBuffer]\n");

static __attribute__ ((used)) void* __ptr_sceAcmBatchStartBuffers;
asm(".intel_syntax noprefix\n"
    ".global sceAcmBatchStartBuffers\n"
    ".type sceAcmBatchStartBuffers @function\n"
    "sceAcmBatchStartBuffers:\n"
    "jmp qword ptr [rip + __ptr_sceAcmBatchStartBuffers]\n");

static __attribute__ ((used)) void* __ptr_sceAcmBatchWait;
asm(".intel_syntax noprefix\n"
    ".global sceAcmBatchWait\n"
    ".type sceAcmBatchWait @function\n"
    "sceAcmBatchWait:\n"
    "jmp qword ptr [rip + __ptr_sceAcmBatchWait]\n");

static __attribute__ ((used)) void* __ptr_sceAcmContextCreate;
asm(".intel_syntax noprefix\n"
    ".global sceAcmContextCreate\n"
    ".type sceAcmContextCreate @function\n"
    "sceAcmContextCreate:\n"
    "jmp qword ptr [rip + __ptr_sceAcmContextCreate]\n");

static __attribute__ ((used)) void* __ptr_sceAcmContextDestroy;
asm(".intel_syntax noprefix\n"
    ".global sceAcmContextDestroy\n"
    ".type sceAcmContextDestroy @function\n"
    "sceAcmContextDestroy:\n"
    "jmp qword ptr [rip + __ptr_sceAcmContextDestroy]\n");

static __attribute__ ((used)) void* __ptr_sceAcm_ConvReverb_SharedInput;
asm(".intel_syntax noprefix\n"
    ".global sceAcm_ConvReverb_SharedInput\n"
    ".type sceAcm_ConvReverb_SharedInput @function\n"
    "sceAcm_ConvReverb_SharedInput:\n"
    "jmp qword ptr [rip + __ptr_sceAcm_ConvReverb_SharedInput]\n");

static __attribute__ ((used)) void* __ptr_sceAcm_ConvReverb_SharedIr;
asm(".intel_syntax noprefix\n"
    ".global sceAcm_ConvReverb_SharedIr\n"
    ".type sceAcm_ConvReverb_SharedIr @function\n"
    "sceAcm_ConvReverb_SharedIr:\n"
    "jmp qword ptr [rip + __ptr_sceAcm_ConvReverb_SharedIr]\n");

static __attribute__ ((used)) void* __ptr_sceAcm_FFT;
asm(".intel_syntax noprefix\n"
    ".global sceAcm_FFT\n"
    ".type sceAcm_FFT @function\n"
    "sceAcm_FFT:\n"
    "jmp qword ptr [rip + __ptr_sceAcm_FFT]\n");

static __attribute__ ((used)) void* __ptr_sceAcm_IFFT;
asm(".intel_syntax noprefix\n"
    ".global sceAcm_IFFT\n"
    ".type sceAcm_IFFT @function\n"
    "sceAcm_IFFT:\n"
    "jmp qword ptr [rip + __ptr_sceAcm_IFFT]\n");

static __attribute__ ((used)) void* __ptr_sceAcm_Panner;
asm(".intel_syntax noprefix\n"
    ".global sceAcm_Panner\n"
    ".type sceAcm_Panner @function\n"
    "sceAcm_Panner:\n"
    "jmp qword ptr [rip + __ptr_sceAcm_Panner]\n");

static unsigned short __handle = 0;
static void __attribute__((constructor(104)))
__constructor(void) {
  if(sprx_dlopen("libSceAcm", &__handle)) return;
  if(sprx_dlsym(__handle, "tW9W+CAG4FE", &__ptr_sceAcmBatchStartBuffer)) return;
  if(sprx_dlsym(__handle, "8fe55ktlNVo", &__ptr_sceAcmBatchStartBuffers)) return;
  if(sprx_dlsym(__handle, "RLN3gRlXJLE", &__ptr_sceAcmBatchWait)) return;
  if(sprx_dlsym(__handle, "ZIXln2K3XMk", &__ptr_sceAcmContextCreate)) return;
  if(sprx_dlsym(__handle, "jBgBjAj02R8", &__ptr_sceAcmContextDestroy)) return;
  if(sprx_dlsym(__handle, "u70oWo92SYQ", &__ptr_sceAcm_ConvReverb_SharedInput)) return;
  if(sprx_dlsym(__handle, "9nLbWmRDpa8", &__ptr_sceAcm_ConvReverb_SharedIr)) return;
  if(sprx_dlsym(__handle, "KovqaFbmtsM", &__ptr_sceAcm_FFT)) return;
  if(sprx_dlsym(__handle, "DR-ZCmvVR9Q", &__ptr_sceAcm_IFFT)) return;
  if(sprx_dlsym(__handle, "LA4RCNKnFjg", &__ptr_sceAcm_Panner)) return;
}

static void __attribute__((destructor(104)))
__destructor(void) {
  sprx_dlclose(__handle);
}
