/*
 This file was generated by genstub.py, do not edit manually!
*/

int sprx_dlsym(unsigned int handle, const char *nid, void *addr);
int sprx_dlopen(const char* libname, unsigned short *handle);
int sprx_dlclose(unsigned int handle);

static __attribute__ ((used)) void* __ptr_sceVoiceQoSConnect;
asm(".intel_syntax noprefix\n"
    ".global sceVoiceQoSConnect\n"
    ".type sceVoiceQoSConnect @function\n"
    "sceVoiceQoSConnect:\n"
    "jmp qword ptr [rip + __ptr_sceVoiceQoSConnect]\n");

static __attribute__ ((used)) void* __ptr_sceVoiceQoSCreateLocalEndpoint;
asm(".intel_syntax noprefix\n"
    ".global sceVoiceQoSCreateLocalEndpoint\n"
    ".type sceVoiceQoSCreateLocalEndpoint @function\n"
    "sceVoiceQoSCreateLocalEndpoint:\n"
    "jmp qword ptr [rip + __ptr_sceVoiceQoSCreateLocalEndpoint]\n");

static __attribute__ ((used)) void* __ptr_sceVoiceQoSCreateRemoteEndpoint;
asm(".intel_syntax noprefix\n"
    ".global sceVoiceQoSCreateRemoteEndpoint\n"
    ".type sceVoiceQoSCreateRemoteEndpoint @function\n"
    "sceVoiceQoSCreateRemoteEndpoint:\n"
    "jmp qword ptr [rip + __ptr_sceVoiceQoSCreateRemoteEndpoint]\n");

static __attribute__ ((used)) void* __ptr_sceVoiceQoSDebugGetStatus;
asm(".intel_syntax noprefix\n"
    ".global sceVoiceQoSDebugGetStatus\n"
    ".type sceVoiceQoSDebugGetStatus @function\n"
    "sceVoiceQoSDebugGetStatus:\n"
    "jmp qword ptr [rip + __ptr_sceVoiceQoSDebugGetStatus]\n");

static __attribute__ ((used)) void* __ptr_sceVoiceQoSDeleteLocalEndpoint;
asm(".intel_syntax noprefix\n"
    ".global sceVoiceQoSDeleteLocalEndpoint\n"
    ".type sceVoiceQoSDeleteLocalEndpoint @function\n"
    "sceVoiceQoSDeleteLocalEndpoint:\n"
    "jmp qword ptr [rip + __ptr_sceVoiceQoSDeleteLocalEndpoint]\n");

static __attribute__ ((used)) void* __ptr_sceVoiceQoSDeleteRemoteEndpoint;
asm(".intel_syntax noprefix\n"
    ".global sceVoiceQoSDeleteRemoteEndpoint\n"
    ".type sceVoiceQoSDeleteRemoteEndpoint @function\n"
    "sceVoiceQoSDeleteRemoteEndpoint:\n"
    "jmp qword ptr [rip + __ptr_sceVoiceQoSDeleteRemoteEndpoint]\n");

static __attribute__ ((used)) void* __ptr_sceVoiceQoSDisableChat;
asm(".intel_syntax noprefix\n"
    ".global sceVoiceQoSDisableChat\n"
    ".type sceVoiceQoSDisableChat @function\n"
    "sceVoiceQoSDisableChat:\n"
    "jmp qword ptr [rip + __ptr_sceVoiceQoSDisableChat]\n");

static __attribute__ ((used)) void* __ptr_sceVoiceQoSDisconnect;
asm(".intel_syntax noprefix\n"
    ".global sceVoiceQoSDisconnect\n"
    ".type sceVoiceQoSDisconnect @function\n"
    "sceVoiceQoSDisconnect:\n"
    "jmp qword ptr [rip + __ptr_sceVoiceQoSDisconnect]\n");

static __attribute__ ((used)) void* __ptr_sceVoiceQoSEnableChat;
asm(".intel_syntax noprefix\n"
    ".global sceVoiceQoSEnableChat\n"
    ".type sceVoiceQoSEnableChat @function\n"
    "sceVoiceQoSEnableChat:\n"
    "jmp qword ptr [rip + __ptr_sceVoiceQoSEnableChat]\n");

static __attribute__ ((used)) void* __ptr_sceVoiceQoSEnd;
asm(".intel_syntax noprefix\n"
    ".global sceVoiceQoSEnd\n"
    ".type sceVoiceQoSEnd @function\n"
    "sceVoiceQoSEnd:\n"
    "jmp qword ptr [rip + __ptr_sceVoiceQoSEnd]\n");

static __attribute__ ((used)) void* __ptr_sceVoiceQoSGetConnectionAttribute;
asm(".intel_syntax noprefix\n"
    ".global sceVoiceQoSGetConnectionAttribute\n"
    ".type sceVoiceQoSGetConnectionAttribute @function\n"
    "sceVoiceQoSGetConnectionAttribute:\n"
    "jmp qword ptr [rip + __ptr_sceVoiceQoSGetConnectionAttribute]\n");

static __attribute__ ((used)) void* __ptr_sceVoiceQoSGetLocalEndpoint;
asm(".intel_syntax noprefix\n"
    ".global sceVoiceQoSGetLocalEndpoint\n"
    ".type sceVoiceQoSGetLocalEndpoint @function\n"
    "sceVoiceQoSGetLocalEndpoint:\n"
    "jmp qword ptr [rip + __ptr_sceVoiceQoSGetLocalEndpoint]\n");

static __attribute__ ((used)) void* __ptr_sceVoiceQoSGetLocalEndpointAttribute;
asm(".intel_syntax noprefix\n"
    ".global sceVoiceQoSGetLocalEndpointAttribute\n"
    ".type sceVoiceQoSGetLocalEndpointAttribute @function\n"
    "sceVoiceQoSGetLocalEndpointAttribute:\n"
    "jmp qword ptr [rip + __ptr_sceVoiceQoSGetLocalEndpointAttribute]\n");

static __attribute__ ((used)) void* __ptr_sceVoiceQoSGetRemoteEndpoint;
asm(".intel_syntax noprefix\n"
    ".global sceVoiceQoSGetRemoteEndpoint\n"
    ".type sceVoiceQoSGetRemoteEndpoint @function\n"
    "sceVoiceQoSGetRemoteEndpoint:\n"
    "jmp qword ptr [rip + __ptr_sceVoiceQoSGetRemoteEndpoint]\n");

static __attribute__ ((used)) void* __ptr_sceVoiceQoSGetRemoteEndpointAttribute;
asm(".intel_syntax noprefix\n"
    ".global sceVoiceQoSGetRemoteEndpointAttribute\n"
    ".type sceVoiceQoSGetRemoteEndpointAttribute @function\n"
    "sceVoiceQoSGetRemoteEndpointAttribute:\n"
    "jmp qword ptr [rip + __ptr_sceVoiceQoSGetRemoteEndpointAttribute]\n");

static __attribute__ ((used)) void* __ptr_sceVoiceQoSGetStatus;
asm(".intel_syntax noprefix\n"
    ".global sceVoiceQoSGetStatus\n"
    ".type sceVoiceQoSGetStatus @function\n"
    "sceVoiceQoSGetStatus:\n"
    "jmp qword ptr [rip + __ptr_sceVoiceQoSGetStatus]\n");

static __attribute__ ((used)) void* __ptr_sceVoiceQoSInit;
asm(".intel_syntax noprefix\n"
    ".global sceVoiceQoSInit\n"
    ".type sceVoiceQoSInit @function\n"
    "sceVoiceQoSInit:\n"
    "jmp qword ptr [rip + __ptr_sceVoiceQoSInit]\n");

static __attribute__ ((used)) void* __ptr_sceVoiceQoSInitHQ;
asm(".intel_syntax noprefix\n"
    ".global sceVoiceQoSInitHQ\n"
    ".type sceVoiceQoSInitHQ @function\n"
    "sceVoiceQoSInitHQ:\n"
    "jmp qword ptr [rip + __ptr_sceVoiceQoSInitHQ]\n");

static __attribute__ ((used)) void* __ptr_sceVoiceQoSReadPacket;
asm(".intel_syntax noprefix\n"
    ".global sceVoiceQoSReadPacket\n"
    ".type sceVoiceQoSReadPacket @function\n"
    "sceVoiceQoSReadPacket:\n"
    "jmp qword ptr [rip + __ptr_sceVoiceQoSReadPacket]\n");

static __attribute__ ((used)) void* __ptr_sceVoiceQoSSetConnectionAttribute;
asm(".intel_syntax noprefix\n"
    ".global sceVoiceQoSSetConnectionAttribute\n"
    ".type sceVoiceQoSSetConnectionAttribute @function\n"
    "sceVoiceQoSSetConnectionAttribute:\n"
    "jmp qword ptr [rip + __ptr_sceVoiceQoSSetConnectionAttribute]\n");

static __attribute__ ((used)) void* __ptr_sceVoiceQoSSetLocalEndpointAttribute;
asm(".intel_syntax noprefix\n"
    ".global sceVoiceQoSSetLocalEndpointAttribute\n"
    ".type sceVoiceQoSSetLocalEndpointAttribute @function\n"
    "sceVoiceQoSSetLocalEndpointAttribute:\n"
    "jmp qword ptr [rip + __ptr_sceVoiceQoSSetLocalEndpointAttribute]\n");

static __attribute__ ((used)) void* __ptr_sceVoiceQoSSetRemoteEndpointAttribute;
asm(".intel_syntax noprefix\n"
    ".global sceVoiceQoSSetRemoteEndpointAttribute\n"
    ".type sceVoiceQoSSetRemoteEndpointAttribute @function\n"
    "sceVoiceQoSSetRemoteEndpointAttribute:\n"
    "jmp qword ptr [rip + __ptr_sceVoiceQoSSetRemoteEndpointAttribute]\n");

static __attribute__ ((used)) void* __ptr_sceVoiceQoSWritePacket;
asm(".intel_syntax noprefix\n"
    ".global sceVoiceQoSWritePacket\n"
    ".type sceVoiceQoSWritePacket @function\n"
    "sceVoiceQoSWritePacket:\n"
    "jmp qword ptr [rip + __ptr_sceVoiceQoSWritePacket]\n");

static unsigned short __handle = 0;
static void __attribute__((constructor(104)))
__constructor(void) {
  if(sprx_dlopen("libSceVoiceQoS", &__handle)) return;
  if(sprx_dlsym(__handle, "kLU6hhXsa2A", &__ptr_sceVoiceQoSConnect)) return;
  if(sprx_dlsym(__handle, "lvNClhNHzxI", &__ptr_sceVoiceQoSCreateLocalEndpoint)) return;
  if(sprx_dlsym(__handle, "iqQQW2cBmWU", &__ptr_sceVoiceQoSCreateRemoteEndpoint)) return;
  if(sprx_dlsym(__handle, "D7P8dL0ZKsI", &__ptr_sceVoiceQoSDebugGetStatus)) return;
  if(sprx_dlsym(__handle, "kE0kdvcHTiY", &__ptr_sceVoiceQoSDeleteLocalEndpoint)) return;
  if(sprx_dlsym(__handle, "H4zqFaDhHW4", &__ptr_sceVoiceQoSDeleteRemoteEndpoint)) return;
  if(sprx_dlsym(__handle, "8-voJZab+0E", &__ptr_sceVoiceQoSDisableChat)) return;
  if(sprx_dlsym(__handle, "j9Xt85krooc", &__ptr_sceVoiceQoSDisconnect)) return;
  if(sprx_dlsym(__handle, "2lOJJzw1t5o", &__ptr_sceVoiceQoSEnableChat)) return;
  if(sprx_dlsym(__handle, "ATRGkmbolVM", &__ptr_sceVoiceQoSEnd)) return;
  if(sprx_dlsym(__handle, "XmvdN3atbXY", &__ptr_sceVoiceQoSGetConnectionAttribute)) return;
  if(sprx_dlsym(__handle, "XPC8EyEuvyk", &__ptr_sceVoiceQoSGetLocalEndpoint)) return;
  if(sprx_dlsym(__handle, "eZu2RP0Ma3w", &__ptr_sceVoiceQoSGetLocalEndpointAttribute)) return;
  if(sprx_dlsym(__handle, "9tfy4+aDxrM", &__ptr_sceVoiceQoSGetRemoteEndpoint)) return;
  if(sprx_dlsym(__handle, "3vmrvQ4rvgs", &__ptr_sceVoiceQoSGetRemoteEndpointAttribute)) return;
  if(sprx_dlsym(__handle, "Trpt2QBZHCI", &__ptr_sceVoiceQoSGetStatus)) return;
  if(sprx_dlsym(__handle, "U8IfNl6-Css", &__ptr_sceVoiceQoSInit)) return;
  if(sprx_dlsym(__handle, "RY0c7tYVBiw", &__ptr_sceVoiceQoSInitHQ)) return;
  if(sprx_dlsym(__handle, "PWokFqab5q4", &__ptr_sceVoiceQoSReadPacket)) return;
  if(sprx_dlsym(__handle, "KCGOxg8iX7s", &__ptr_sceVoiceQoSSetConnectionAttribute)) return;
  if(sprx_dlsym(__handle, "F7wS7FbfumQ", &__ptr_sceVoiceQoSSetLocalEndpointAttribute)) return;
  if(sprx_dlsym(__handle, "cpC-zyHoMik", &__ptr_sceVoiceQoSSetRemoteEndpointAttribute)) return;
  if(sprx_dlsym(__handle, "SpxLratrO1Q", &__ptr_sceVoiceQoSWritePacket)) return;
}

static void __attribute__((destructor(104)))
__destructor(void) {
  sprx_dlclose(__handle);
}
