/*
 This file was generated by genstub.py, do not edit manually!
*/

int sprx_dlsym(unsigned int handle, const char *nid, void *addr);
int sprx_dlopen(const char* libname, unsigned short *handle);
int sprx_dlclose(unsigned int handle);

static __attribute__ ((used)) void* __ptr_sceVoiceConnectIPortToOPort;
asm(".intel_syntax noprefix\n"
    ".global sceVoiceConnectIPortToOPort\n"
    ".type sceVoiceConnectIPortToOPort @function\n"
    "sceVoiceConnectIPortToOPort:\n"
    "jmp qword ptr [rip + __ptr_sceVoiceConnectIPortToOPort]\n");

static __attribute__ ((used)) void* __ptr_sceVoiceCreatePort;
asm(".intel_syntax noprefix\n"
    ".global sceVoiceCreatePort\n"
    ".type sceVoiceCreatePort @function\n"
    "sceVoiceCreatePort:\n"
    "jmp qword ptr [rip + __ptr_sceVoiceCreatePort]\n");

static __attribute__ ((used)) void* __ptr_sceVoiceDeletePort;
asm(".intel_syntax noprefix\n"
    ".global sceVoiceDeletePort\n"
    ".type sceVoiceDeletePort @function\n"
    "sceVoiceDeletePort:\n"
    "jmp qword ptr [rip + __ptr_sceVoiceDeletePort]\n");

static __attribute__ ((used)) void* __ptr_sceVoiceDisableChat;
asm(".intel_syntax noprefix\n"
    ".global sceVoiceDisableChat\n"
    ".type sceVoiceDisableChat @function\n"
    "sceVoiceDisableChat:\n"
    "jmp qword ptr [rip + __ptr_sceVoiceDisableChat]\n");

static __attribute__ ((used)) void* __ptr_sceVoiceDisconnectIPortFromOPort;
asm(".intel_syntax noprefix\n"
    ".global sceVoiceDisconnectIPortFromOPort\n"
    ".type sceVoiceDisconnectIPortFromOPort @function\n"
    "sceVoiceDisconnectIPortFromOPort:\n"
    "jmp qword ptr [rip + __ptr_sceVoiceDisconnectIPortFromOPort]\n");

static __attribute__ ((used)) void* __ptr_sceVoiceEnableChat;
asm(".intel_syntax noprefix\n"
    ".global sceVoiceEnableChat\n"
    ".type sceVoiceEnableChat @function\n"
    "sceVoiceEnableChat:\n"
    "jmp qword ptr [rip + __ptr_sceVoiceEnableChat]\n");

static __attribute__ ((used)) void* __ptr_sceVoiceEnd;
asm(".intel_syntax noprefix\n"
    ".global sceVoiceEnd\n"
    ".type sceVoiceEnd @function\n"
    "sceVoiceEnd:\n"
    "jmp qword ptr [rip + __ptr_sceVoiceEnd]\n");

static __attribute__ ((used)) void* __ptr_sceVoiceGetBitRate;
asm(".intel_syntax noprefix\n"
    ".global sceVoiceGetBitRate\n"
    ".type sceVoiceGetBitRate @function\n"
    "sceVoiceGetBitRate:\n"
    "jmp qword ptr [rip + __ptr_sceVoiceGetBitRate]\n");

static __attribute__ ((used)) void* __ptr_sceVoiceGetMemorySize;
asm(".intel_syntax noprefix\n"
    ".global sceVoiceGetMemorySize\n"
    ".type sceVoiceGetMemorySize @function\n"
    "sceVoiceGetMemorySize:\n"
    "jmp qword ptr [rip + __ptr_sceVoiceGetMemorySize]\n");

static __attribute__ ((used)) void* __ptr_sceVoiceGetMuteFlag;
asm(".intel_syntax noprefix\n"
    ".global sceVoiceGetMuteFlag\n"
    ".type sceVoiceGetMuteFlag @function\n"
    "sceVoiceGetMuteFlag:\n"
    "jmp qword ptr [rip + __ptr_sceVoiceGetMuteFlag]\n");

static __attribute__ ((used)) void* __ptr_sceVoiceGetPortAttr;
asm(".intel_syntax noprefix\n"
    ".global sceVoiceGetPortAttr\n"
    ".type sceVoiceGetPortAttr @function\n"
    "sceVoiceGetPortAttr:\n"
    "jmp qword ptr [rip + __ptr_sceVoiceGetPortAttr]\n");

static __attribute__ ((used)) void* __ptr_sceVoiceGetPortInfo;
asm(".intel_syntax noprefix\n"
    ".global sceVoiceGetPortInfo\n"
    ".type sceVoiceGetPortInfo @function\n"
    "sceVoiceGetPortInfo:\n"
    "jmp qword ptr [rip + __ptr_sceVoiceGetPortInfo]\n");

static __attribute__ ((used)) void* __ptr_sceVoiceGetResourceInfo;
asm(".intel_syntax noprefix\n"
    ".global sceVoiceGetResourceInfo\n"
    ".type sceVoiceGetResourceInfo @function\n"
    "sceVoiceGetResourceInfo:\n"
    "jmp qword ptr [rip + __ptr_sceVoiceGetResourceInfo]\n");

static __attribute__ ((used)) void* __ptr_sceVoiceGetVolume;
asm(".intel_syntax noprefix\n"
    ".global sceVoiceGetVolume\n"
    ".type sceVoiceGetVolume @function\n"
    "sceVoiceGetVolume:\n"
    "jmp qword ptr [rip + __ptr_sceVoiceGetVolume]\n");

static __attribute__ ((used)) void* __ptr_sceVoiceInit;
asm(".intel_syntax noprefix\n"
    ".global sceVoiceInit\n"
    ".type sceVoiceInit @function\n"
    "sceVoiceInit:\n"
    "jmp qword ptr [rip + __ptr_sceVoiceInit]\n");

static __attribute__ ((used)) void* __ptr_sceVoiceInitHQ;
asm(".intel_syntax noprefix\n"
    ".global sceVoiceInitHQ\n"
    ".type sceVoiceInitHQ @function\n"
    "sceVoiceInitHQ:\n"
    "jmp qword ptr [rip + __ptr_sceVoiceInitHQ]\n");

static __attribute__ ((used)) void* __ptr_sceVoicePausePort;
asm(".intel_syntax noprefix\n"
    ".global sceVoicePausePort\n"
    ".type sceVoicePausePort @function\n"
    "sceVoicePausePort:\n"
    "jmp qword ptr [rip + __ptr_sceVoicePausePort]\n");

static __attribute__ ((used)) void* __ptr_sceVoicePausePortAll;
asm(".intel_syntax noprefix\n"
    ".global sceVoicePausePortAll\n"
    ".type sceVoicePausePortAll @function\n"
    "sceVoicePausePortAll:\n"
    "jmp qword ptr [rip + __ptr_sceVoicePausePortAll]\n");

static __attribute__ ((used)) void* __ptr_sceVoiceReadFromOPort;
asm(".intel_syntax noprefix\n"
    ".global sceVoiceReadFromOPort\n"
    ".type sceVoiceReadFromOPort @function\n"
    "sceVoiceReadFromOPort:\n"
    "jmp qword ptr [rip + __ptr_sceVoiceReadFromOPort]\n");

static __attribute__ ((used)) void* __ptr_sceVoiceResetPort;
asm(".intel_syntax noprefix\n"
    ".global sceVoiceResetPort\n"
    ".type sceVoiceResetPort @function\n"
    "sceVoiceResetPort:\n"
    "jmp qword ptr [rip + __ptr_sceVoiceResetPort]\n");

static __attribute__ ((used)) void* __ptr_sceVoiceResumePort;
asm(".intel_syntax noprefix\n"
    ".global sceVoiceResumePort\n"
    ".type sceVoiceResumePort @function\n"
    "sceVoiceResumePort:\n"
    "jmp qword ptr [rip + __ptr_sceVoiceResumePort]\n");

static __attribute__ ((used)) void* __ptr_sceVoiceResumePortAll;
asm(".intel_syntax noprefix\n"
    ".global sceVoiceResumePortAll\n"
    ".type sceVoiceResumePortAll @function\n"
    "sceVoiceResumePortAll:\n"
    "jmp qword ptr [rip + __ptr_sceVoiceResumePortAll]\n");

static __attribute__ ((used)) void* __ptr_sceVoiceSetBitRate;
asm(".intel_syntax noprefix\n"
    ".global sceVoiceSetBitRate\n"
    ".type sceVoiceSetBitRate @function\n"
    "sceVoiceSetBitRate:\n"
    "jmp qword ptr [rip + __ptr_sceVoiceSetBitRate]\n");

static __attribute__ ((used)) void* __ptr_sceVoiceSetMuteFlag;
asm(".intel_syntax noprefix\n"
    ".global sceVoiceSetMuteFlag\n"
    ".type sceVoiceSetMuteFlag @function\n"
    "sceVoiceSetMuteFlag:\n"
    "jmp qword ptr [rip + __ptr_sceVoiceSetMuteFlag]\n");

static __attribute__ ((used)) void* __ptr_sceVoiceSetMuteFlagAll;
asm(".intel_syntax noprefix\n"
    ".global sceVoiceSetMuteFlagAll\n"
    ".type sceVoiceSetMuteFlagAll @function\n"
    "sceVoiceSetMuteFlagAll:\n"
    "jmp qword ptr [rip + __ptr_sceVoiceSetMuteFlagAll]\n");

static __attribute__ ((used)) void* __ptr_sceVoiceSetThreadsParams;
asm(".intel_syntax noprefix\n"
    ".global sceVoiceSetThreadsParams\n"
    ".type sceVoiceSetThreadsParams @function\n"
    "sceVoiceSetThreadsParams:\n"
    "jmp qword ptr [rip + __ptr_sceVoiceSetThreadsParams]\n");

static __attribute__ ((used)) void* __ptr_sceVoiceSetVolume;
asm(".intel_syntax noprefix\n"
    ".global sceVoiceSetVolume\n"
    ".type sceVoiceSetVolume @function\n"
    "sceVoiceSetVolume:\n"
    "jmp qword ptr [rip + __ptr_sceVoiceSetVolume]\n");

static __attribute__ ((used)) void* __ptr_sceVoiceStart;
asm(".intel_syntax noprefix\n"
    ".global sceVoiceStart\n"
    ".type sceVoiceStart @function\n"
    "sceVoiceStart:\n"
    "jmp qword ptr [rip + __ptr_sceVoiceStart]\n");

static __attribute__ ((used)) void* __ptr_sceVoiceStop;
asm(".intel_syntax noprefix\n"
    ".global sceVoiceStop\n"
    ".type sceVoiceStop @function\n"
    "sceVoiceStop:\n"
    "jmp qword ptr [rip + __ptr_sceVoiceStop]\n");

static __attribute__ ((used)) void* __ptr_sceVoiceUpdatePort;
asm(".intel_syntax noprefix\n"
    ".global sceVoiceUpdatePort\n"
    ".type sceVoiceUpdatePort @function\n"
    "sceVoiceUpdatePort:\n"
    "jmp qword ptr [rip + __ptr_sceVoiceUpdatePort]\n");

static __attribute__ ((used)) void* __ptr_sceVoiceVADAdjustment;
asm(".intel_syntax noprefix\n"
    ".global sceVoiceVADAdjustment\n"
    ".type sceVoiceVADAdjustment @function\n"
    "sceVoiceVADAdjustment:\n"
    "jmp qword ptr [rip + __ptr_sceVoiceVADAdjustment]\n");

static __attribute__ ((used)) void* __ptr_sceVoiceVADPVTAdjustment;
asm(".intel_syntax noprefix\n"
    ".global sceVoiceVADPVTAdjustment\n"
    ".type sceVoiceVADPVTAdjustment @function\n"
    "sceVoiceVADPVTAdjustment:\n"
    "jmp qword ptr [rip + __ptr_sceVoiceVADPVTAdjustment]\n");

static __attribute__ ((used)) void* __ptr_sceVoiceVADSetVersion;
asm(".intel_syntax noprefix\n"
    ".global sceVoiceVADSetVersion\n"
    ".type sceVoiceVADSetVersion @function\n"
    "sceVoiceVADSetVersion:\n"
    "jmp qword ptr [rip + __ptr_sceVoiceVADSetVersion]\n");

static __attribute__ ((used)) void* __ptr_sceVoiceWriteToIPort;
asm(".intel_syntax noprefix\n"
    ".global sceVoiceWriteToIPort\n"
    ".type sceVoiceWriteToIPort @function\n"
    "sceVoiceWriteToIPort:\n"
    "jmp qword ptr [rip + __ptr_sceVoiceWriteToIPort]\n");

static unsigned short __handle = 0;
static void __attribute__((constructor(104)))
__constructor(void) {
  if(sprx_dlopen("libSceVoice", &__handle)) return;
  if(sprx_dlsym(__handle, "oV9GAdJ23Gw", &__ptr_sceVoiceConnectIPortToOPort)) return;
  if(sprx_dlsym(__handle, "nXpje5yNpaE", &__ptr_sceVoiceCreatePort)) return;
  if(sprx_dlsym(__handle, "b7kJI+nx2hg", &__ptr_sceVoiceDeletePort)) return;
  if(sprx_dlsym(__handle, "xHSNCLrQq3A", &__ptr_sceVoiceDisableChat)) return;
  if(sprx_dlsym(__handle, "ajVj3QG2um4", &__ptr_sceVoiceDisconnectIPortFromOPort)) return;
  if(sprx_dlsym(__handle, "lLkJVewQK68", &__ptr_sceVoiceEnableChat)) return;
  if(sprx_dlsym(__handle, "Oo0S5PH7FIQ", &__ptr_sceVoiceEnd)) return;
  if(sprx_dlsym(__handle, "cJLufzou6bc", &__ptr_sceVoiceGetBitRate)) return;
  if(sprx_dlsym(__handle, "4s3lpDzi0as", &__ptr_sceVoiceGetMemorySize)) return;
  if(sprx_dlsym(__handle, "Pc4z1QjForU", &__ptr_sceVoiceGetMuteFlag)) return;
  if(sprx_dlsym(__handle, "elcxZTEfHZM", &__ptr_sceVoiceGetPortAttr)) return;
  if(sprx_dlsym(__handle, "CrLqDwWLoXM", &__ptr_sceVoiceGetPortInfo)) return;
  if(sprx_dlsym(__handle, "Z6QV6j7igvE", &__ptr_sceVoiceGetResourceInfo)) return;
  if(sprx_dlsym(__handle, "jjkCjneOYSs", &__ptr_sceVoiceGetVolume)) return;
  if(sprx_dlsym(__handle, "9TrhuGzberQ", &__ptr_sceVoiceInit)) return;
  if(sprx_dlsym(__handle, "IPHvnM5+g04", &__ptr_sceVoiceInitHQ)) return;
  if(sprx_dlsym(__handle, "x0slGBQW+wY", &__ptr_sceVoicePausePort)) return;
  if(sprx_dlsym(__handle, "Dinob0yMRl8", &__ptr_sceVoicePausePortAll)) return;
  if(sprx_dlsym(__handle, "cQ6DGsQEjV4", &__ptr_sceVoiceReadFromOPort)) return;
  if(sprx_dlsym(__handle, "udAxvCePkUs", &__ptr_sceVoiceResetPort)) return;
  if(sprx_dlsym(__handle, "gAgN+HkiEzY", &__ptr_sceVoiceResumePort)) return;
  if(sprx_dlsym(__handle, "jbkJFmOZ9U0", &__ptr_sceVoiceResumePortAll)) return;
  if(sprx_dlsym(__handle, "TexwmOHQsDg", &__ptr_sceVoiceSetBitRate)) return;
  if(sprx_dlsym(__handle, "gwUynkEgNFY", &__ptr_sceVoiceSetMuteFlag)) return;
  if(sprx_dlsym(__handle, "oUha0S-Ij9Q", &__ptr_sceVoiceSetMuteFlagAll)) return;
  if(sprx_dlsym(__handle, "clyKUyi3RYU", &__ptr_sceVoiceSetThreadsParams)) return;
  if(sprx_dlsym(__handle, "QBFoAIjJoXQ", &__ptr_sceVoiceSetVolume)) return;
  if(sprx_dlsym(__handle, "54phPH2LZls", &__ptr_sceVoiceStart)) return;
  if(sprx_dlsym(__handle, "Ao2YNSA7-Qo", &__ptr_sceVoiceStop)) return;
  if(sprx_dlsym(__handle, "jSZNP7xJrcw", &__ptr_sceVoiceUpdatePort)) return;
  if(sprx_dlsym(__handle, "hg9T73LlRiU", &__ptr_sceVoiceVADAdjustment)) return;
  if(sprx_dlsym(__handle, "wXCMy4EwaLE", &__ptr_sceVoiceVADPVTAdjustment)) return;
  if(sprx_dlsym(__handle, "wFeAxEeEi-8", &__ptr_sceVoiceVADSetVersion)) return;
  if(sprx_dlsym(__handle, "YeJl6yDlhW0", &__ptr_sceVoiceWriteToIPort)) return;
}

static void __attribute__((destructor(104)))
__destructor(void) {
  sprx_dlclose(__handle);
}
