/*
 This file was generated by genstub.py, do not edit manually!
*/

int sprx_dlsym(unsigned int handle, const char *nid, void *addr);
int sprx_dlopen(const char* libname, unsigned short *handle);
int sprx_dlclose(unsigned int handle);

static __attribute__ ((used)) void* __ptr_sceRtcCheckValid;
asm(".intel_syntax noprefix\n"
    ".global sceRtcCheckValid\n"
    ".type sceRtcCheckValid @function\n"
    "sceRtcCheckValid:\n"
    "jmp qword ptr [rip + __ptr_sceRtcCheckValid]\n");

static __attribute__ ((used)) void* __ptr_sceRtcCompareTick;
asm(".intel_syntax noprefix\n"
    ".global sceRtcCompareTick\n"
    ".type sceRtcCompareTick @function\n"
    "sceRtcCompareTick:\n"
    "jmp qword ptr [rip + __ptr_sceRtcCompareTick]\n");

static __attribute__ ((used)) void* __ptr_sceRtcConvertLocalTimeToUtc;
asm(".intel_syntax noprefix\n"
    ".global sceRtcConvertLocalTimeToUtc\n"
    ".type sceRtcConvertLocalTimeToUtc @function\n"
    "sceRtcConvertLocalTimeToUtc:\n"
    "jmp qword ptr [rip + __ptr_sceRtcConvertLocalTimeToUtc]\n");

static __attribute__ ((used)) void* __ptr_sceRtcConvertUtcToLocalTime;
asm(".intel_syntax noprefix\n"
    ".global sceRtcConvertUtcToLocalTime\n"
    ".type sceRtcConvertUtcToLocalTime @function\n"
    "sceRtcConvertUtcToLocalTime:\n"
    "jmp qword ptr [rip + __ptr_sceRtcConvertUtcToLocalTime]\n");

static __attribute__ ((used)) void* __ptr_sceRtcEnd;
asm(".intel_syntax noprefix\n"
    ".global sceRtcEnd\n"
    ".type sceRtcEnd @function\n"
    "sceRtcEnd:\n"
    "jmp qword ptr [rip + __ptr_sceRtcEnd]\n");

static __attribute__ ((used)) void* __ptr_sceRtcFormatRFC2822;
asm(".intel_syntax noprefix\n"
    ".global sceRtcFormatRFC2822\n"
    ".type sceRtcFormatRFC2822 @function\n"
    "sceRtcFormatRFC2822:\n"
    "jmp qword ptr [rip + __ptr_sceRtcFormatRFC2822]\n");

static __attribute__ ((used)) void* __ptr_sceRtcFormatRFC2822LocalTime;
asm(".intel_syntax noprefix\n"
    ".global sceRtcFormatRFC2822LocalTime\n"
    ".type sceRtcFormatRFC2822LocalTime @function\n"
    "sceRtcFormatRFC2822LocalTime:\n"
    "jmp qword ptr [rip + __ptr_sceRtcFormatRFC2822LocalTime]\n");

static __attribute__ ((used)) void* __ptr_sceRtcFormatRFC3339;
asm(".intel_syntax noprefix\n"
    ".global sceRtcFormatRFC3339\n"
    ".type sceRtcFormatRFC3339 @function\n"
    "sceRtcFormatRFC3339:\n"
    "jmp qword ptr [rip + __ptr_sceRtcFormatRFC3339]\n");

static __attribute__ ((used)) void* __ptr_sceRtcFormatRFC3339LocalTime;
asm(".intel_syntax noprefix\n"
    ".global sceRtcFormatRFC3339LocalTime\n"
    ".type sceRtcFormatRFC3339LocalTime @function\n"
    "sceRtcFormatRFC3339LocalTime:\n"
    "jmp qword ptr [rip + __ptr_sceRtcFormatRFC3339LocalTime]\n");

static __attribute__ ((used)) void* __ptr_sceRtcFormatRFC3339Precise;
asm(".intel_syntax noprefix\n"
    ".global sceRtcFormatRFC3339Precise\n"
    ".type sceRtcFormatRFC3339Precise @function\n"
    "sceRtcFormatRFC3339Precise:\n"
    "jmp qword ptr [rip + __ptr_sceRtcFormatRFC3339Precise]\n");

static __attribute__ ((used)) void* __ptr_sceRtcFormatRFC3339PreciseLocalTime;
asm(".intel_syntax noprefix\n"
    ".global sceRtcFormatRFC3339PreciseLocalTime\n"
    ".type sceRtcFormatRFC3339PreciseLocalTime @function\n"
    "sceRtcFormatRFC3339PreciseLocalTime:\n"
    "jmp qword ptr [rip + __ptr_sceRtcFormatRFC3339PreciseLocalTime]\n");

static __attribute__ ((used)) void* __ptr_sceRtcGetCurrentAdNetworkTick;
asm(".intel_syntax noprefix\n"
    ".global sceRtcGetCurrentAdNetworkTick\n"
    ".type sceRtcGetCurrentAdNetworkTick @function\n"
    "sceRtcGetCurrentAdNetworkTick:\n"
    "jmp qword ptr [rip + __ptr_sceRtcGetCurrentAdNetworkTick]\n");

static __attribute__ ((used)) void* __ptr_sceRtcGetCurrentClock;
asm(".intel_syntax noprefix\n"
    ".global sceRtcGetCurrentClock\n"
    ".type sceRtcGetCurrentClock @function\n"
    "sceRtcGetCurrentClock:\n"
    "jmp qword ptr [rip + __ptr_sceRtcGetCurrentClock]\n");

static __attribute__ ((used)) void* __ptr_sceRtcGetCurrentClockLocalTime;
asm(".intel_syntax noprefix\n"
    ".global sceRtcGetCurrentClockLocalTime\n"
    ".type sceRtcGetCurrentClockLocalTime @function\n"
    "sceRtcGetCurrentClockLocalTime:\n"
    "jmp qword ptr [rip + __ptr_sceRtcGetCurrentClockLocalTime]\n");

static __attribute__ ((used)) void* __ptr_sceRtcGetCurrentDebugNetworkTick;
asm(".intel_syntax noprefix\n"
    ".global sceRtcGetCurrentDebugNetworkTick\n"
    ".type sceRtcGetCurrentDebugNetworkTick @function\n"
    "sceRtcGetCurrentDebugNetworkTick:\n"
    "jmp qword ptr [rip + __ptr_sceRtcGetCurrentDebugNetworkTick]\n");

static __attribute__ ((used)) void* __ptr_sceRtcGetCurrentNetworkTick;
asm(".intel_syntax noprefix\n"
    ".global sceRtcGetCurrentNetworkTick\n"
    ".type sceRtcGetCurrentNetworkTick @function\n"
    "sceRtcGetCurrentNetworkTick:\n"
    "jmp qword ptr [rip + __ptr_sceRtcGetCurrentNetworkTick]\n");

static __attribute__ ((used)) void* __ptr_sceRtcGetCurrentRawNetworkTick;
asm(".intel_syntax noprefix\n"
    ".global sceRtcGetCurrentRawNetworkTick\n"
    ".type sceRtcGetCurrentRawNetworkTick @function\n"
    "sceRtcGetCurrentRawNetworkTick:\n"
    "jmp qword ptr [rip + __ptr_sceRtcGetCurrentRawNetworkTick]\n");

static __attribute__ ((used)) void* __ptr_sceRtcGetCurrentTick;
asm(".intel_syntax noprefix\n"
    ".global sceRtcGetCurrentTick\n"
    ".type sceRtcGetCurrentTick @function\n"
    "sceRtcGetCurrentTick:\n"
    "jmp qword ptr [rip + __ptr_sceRtcGetCurrentTick]\n");

static __attribute__ ((used)) void* __ptr_sceRtcGetDayOfWeek;
asm(".intel_syntax noprefix\n"
    ".global sceRtcGetDayOfWeek\n"
    ".type sceRtcGetDayOfWeek @function\n"
    "sceRtcGetDayOfWeek:\n"
    "jmp qword ptr [rip + __ptr_sceRtcGetDayOfWeek]\n");

static __attribute__ ((used)) void* __ptr_sceRtcGetDaysInMonth;
asm(".intel_syntax noprefix\n"
    ".global sceRtcGetDaysInMonth\n"
    ".type sceRtcGetDaysInMonth @function\n"
    "sceRtcGetDaysInMonth:\n"
    "jmp qword ptr [rip + __ptr_sceRtcGetDaysInMonth]\n");

static __attribute__ ((used)) void* __ptr_sceRtcGetDosTime;
asm(".intel_syntax noprefix\n"
    ".global sceRtcGetDosTime\n"
    ".type sceRtcGetDosTime @function\n"
    "sceRtcGetDosTime:\n"
    "jmp qword ptr [rip + __ptr_sceRtcGetDosTime]\n");

static __attribute__ ((used)) void* __ptr_sceRtcGetTick;
asm(".intel_syntax noprefix\n"
    ".global sceRtcGetTick\n"
    ".type sceRtcGetTick @function\n"
    "sceRtcGetTick:\n"
    "jmp qword ptr [rip + __ptr_sceRtcGetTick]\n");

static __attribute__ ((used)) void* __ptr_sceRtcGetTickResolution;
asm(".intel_syntax noprefix\n"
    ".global sceRtcGetTickResolution\n"
    ".type sceRtcGetTickResolution @function\n"
    "sceRtcGetTickResolution:\n"
    "jmp qword ptr [rip + __ptr_sceRtcGetTickResolution]\n");

static __attribute__ ((used)) void* __ptr_sceRtcGetTime_t;
asm(".intel_syntax noprefix\n"
    ".global sceRtcGetTime_t\n"
    ".type sceRtcGetTime_t @function\n"
    "sceRtcGetTime_t:\n"
    "jmp qword ptr [rip + __ptr_sceRtcGetTime_t]\n");

static __attribute__ ((used)) void* __ptr_sceRtcGetWin32FileTime;
asm(".intel_syntax noprefix\n"
    ".global sceRtcGetWin32FileTime\n"
    ".type sceRtcGetWin32FileTime @function\n"
    "sceRtcGetWin32FileTime:\n"
    "jmp qword ptr [rip + __ptr_sceRtcGetWin32FileTime]\n");

static __attribute__ ((used)) void* __ptr_sceRtcInit;
asm(".intel_syntax noprefix\n"
    ".global sceRtcInit\n"
    ".type sceRtcInit @function\n"
    "sceRtcInit:\n"
    "jmp qword ptr [rip + __ptr_sceRtcInit]\n");

static __attribute__ ((used)) void* __ptr_sceRtcIsLeapYear;
asm(".intel_syntax noprefix\n"
    ".global sceRtcIsLeapYear\n"
    ".type sceRtcIsLeapYear @function\n"
    "sceRtcIsLeapYear:\n"
    "jmp qword ptr [rip + __ptr_sceRtcIsLeapYear]\n");

static __attribute__ ((used)) void* __ptr_sceRtcParseDateTime;
asm(".intel_syntax noprefix\n"
    ".global sceRtcParseDateTime\n"
    ".type sceRtcParseDateTime @function\n"
    "sceRtcParseDateTime:\n"
    "jmp qword ptr [rip + __ptr_sceRtcParseDateTime]\n");

static __attribute__ ((used)) void* __ptr_sceRtcParseRFC3339;
asm(".intel_syntax noprefix\n"
    ".global sceRtcParseRFC3339\n"
    ".type sceRtcParseRFC3339 @function\n"
    "sceRtcParseRFC3339:\n"
    "jmp qword ptr [rip + __ptr_sceRtcParseRFC3339]\n");

static __attribute__ ((used)) void* __ptr_sceRtcSetConf;
asm(".intel_syntax noprefix\n"
    ".global sceRtcSetConf\n"
    ".type sceRtcSetConf @function\n"
    "sceRtcSetConf:\n"
    "jmp qword ptr [rip + __ptr_sceRtcSetConf]\n");

static __attribute__ ((used)) void* __ptr_sceRtcSetCurrentAdNetworkTick;
asm(".intel_syntax noprefix\n"
    ".global sceRtcSetCurrentAdNetworkTick\n"
    ".type sceRtcSetCurrentAdNetworkTick @function\n"
    "sceRtcSetCurrentAdNetworkTick:\n"
    "jmp qword ptr [rip + __ptr_sceRtcSetCurrentAdNetworkTick]\n");

static __attribute__ ((used)) void* __ptr_sceRtcSetCurrentDebugNetworkTick;
asm(".intel_syntax noprefix\n"
    ".global sceRtcSetCurrentDebugNetworkTick\n"
    ".type sceRtcSetCurrentDebugNetworkTick @function\n"
    "sceRtcSetCurrentDebugNetworkTick:\n"
    "jmp qword ptr [rip + __ptr_sceRtcSetCurrentDebugNetworkTick]\n");

static __attribute__ ((used)) void* __ptr_sceRtcSetCurrentNetworkTick;
asm(".intel_syntax noprefix\n"
    ".global sceRtcSetCurrentNetworkTick\n"
    ".type sceRtcSetCurrentNetworkTick @function\n"
    "sceRtcSetCurrentNetworkTick:\n"
    "jmp qword ptr [rip + __ptr_sceRtcSetCurrentNetworkTick]\n");

static __attribute__ ((used)) void* __ptr_sceRtcSetCurrentTick;
asm(".intel_syntax noprefix\n"
    ".global sceRtcSetCurrentTick\n"
    ".type sceRtcSetCurrentTick @function\n"
    "sceRtcSetCurrentTick:\n"
    "jmp qword ptr [rip + __ptr_sceRtcSetCurrentTick]\n");

static __attribute__ ((used)) void* __ptr_sceRtcSetDosTime;
asm(".intel_syntax noprefix\n"
    ".global sceRtcSetDosTime\n"
    ".type sceRtcSetDosTime @function\n"
    "sceRtcSetDosTime:\n"
    "jmp qword ptr [rip + __ptr_sceRtcSetDosTime]\n");

static __attribute__ ((used)) void* __ptr_sceRtcSetTick;
asm(".intel_syntax noprefix\n"
    ".global sceRtcSetTick\n"
    ".type sceRtcSetTick @function\n"
    "sceRtcSetTick:\n"
    "jmp qword ptr [rip + __ptr_sceRtcSetTick]\n");

static __attribute__ ((used)) void* __ptr_sceRtcSetTime_t;
asm(".intel_syntax noprefix\n"
    ".global sceRtcSetTime_t\n"
    ".type sceRtcSetTime_t @function\n"
    "sceRtcSetTime_t:\n"
    "jmp qword ptr [rip + __ptr_sceRtcSetTime_t]\n");

static __attribute__ ((used)) void* __ptr_sceRtcSetWin32FileTime;
asm(".intel_syntax noprefix\n"
    ".global sceRtcSetWin32FileTime\n"
    ".type sceRtcSetWin32FileTime @function\n"
    "sceRtcSetWin32FileTime:\n"
    "jmp qword ptr [rip + __ptr_sceRtcSetWin32FileTime]\n");

static __attribute__ ((used)) void* __ptr_sceRtcTickAddDays;
asm(".intel_syntax noprefix\n"
    ".global sceRtcTickAddDays\n"
    ".type sceRtcTickAddDays @function\n"
    "sceRtcTickAddDays:\n"
    "jmp qword ptr [rip + __ptr_sceRtcTickAddDays]\n");

static __attribute__ ((used)) void* __ptr_sceRtcTickAddHours;
asm(".intel_syntax noprefix\n"
    ".global sceRtcTickAddHours\n"
    ".type sceRtcTickAddHours @function\n"
    "sceRtcTickAddHours:\n"
    "jmp qword ptr [rip + __ptr_sceRtcTickAddHours]\n");

static __attribute__ ((used)) void* __ptr_sceRtcTickAddMicroseconds;
asm(".intel_syntax noprefix\n"
    ".global sceRtcTickAddMicroseconds\n"
    ".type sceRtcTickAddMicroseconds @function\n"
    "sceRtcTickAddMicroseconds:\n"
    "jmp qword ptr [rip + __ptr_sceRtcTickAddMicroseconds]\n");

static __attribute__ ((used)) void* __ptr_sceRtcTickAddMinutes;
asm(".intel_syntax noprefix\n"
    ".global sceRtcTickAddMinutes\n"
    ".type sceRtcTickAddMinutes @function\n"
    "sceRtcTickAddMinutes:\n"
    "jmp qword ptr [rip + __ptr_sceRtcTickAddMinutes]\n");

static __attribute__ ((used)) void* __ptr_sceRtcTickAddMonths;
asm(".intel_syntax noprefix\n"
    ".global sceRtcTickAddMonths\n"
    ".type sceRtcTickAddMonths @function\n"
    "sceRtcTickAddMonths:\n"
    "jmp qword ptr [rip + __ptr_sceRtcTickAddMonths]\n");

static __attribute__ ((used)) void* __ptr_sceRtcTickAddSeconds;
asm(".intel_syntax noprefix\n"
    ".global sceRtcTickAddSeconds\n"
    ".type sceRtcTickAddSeconds @function\n"
    "sceRtcTickAddSeconds:\n"
    "jmp qword ptr [rip + __ptr_sceRtcTickAddSeconds]\n");

static __attribute__ ((used)) void* __ptr_sceRtcTickAddTicks;
asm(".intel_syntax noprefix\n"
    ".global sceRtcTickAddTicks\n"
    ".type sceRtcTickAddTicks @function\n"
    "sceRtcTickAddTicks:\n"
    "jmp qword ptr [rip + __ptr_sceRtcTickAddTicks]\n");

static __attribute__ ((used)) void* __ptr_sceRtcTickAddWeeks;
asm(".intel_syntax noprefix\n"
    ".global sceRtcTickAddWeeks\n"
    ".type sceRtcTickAddWeeks @function\n"
    "sceRtcTickAddWeeks:\n"
    "jmp qword ptr [rip + __ptr_sceRtcTickAddWeeks]\n");

static __attribute__ ((used)) void* __ptr_sceRtcTickAddYears;
asm(".intel_syntax noprefix\n"
    ".global sceRtcTickAddYears\n"
    ".type sceRtcTickAddYears @function\n"
    "sceRtcTickAddYears:\n"
    "jmp qword ptr [rip + __ptr_sceRtcTickAddYears]\n");

static unsigned short __handle = 0;
static void __attribute__((constructor(104)))
__constructor(void) {
  if(sprx_dlopen("libSceRtc", &__handle)) return;
  if(sprx_dlsym(__handle, "lPEBYdVX0XQ", &__ptr_sceRtcCheckValid)) return;
  if(sprx_dlsym(__handle, "fNaZ4DbzHAE", &__ptr_sceRtcCompareTick)) return;
  if(sprx_dlsym(__handle, "8Yr143yEnRo", &__ptr_sceRtcConvertLocalTimeToUtc)) return;
  if(sprx_dlsym(__handle, "M1TvFst-jrM", &__ptr_sceRtcConvertUtcToLocalTime)) return;
  if(sprx_dlsym(__handle, "8SljQx6pDP8", &__ptr_sceRtcEnd)) return;
  if(sprx_dlsym(__handle, "eiuobaF-hK4", &__ptr_sceRtcFormatRFC2822)) return;
  if(sprx_dlsym(__handle, "AxHBk3eat04", &__ptr_sceRtcFormatRFC2822LocalTime)) return;
  if(sprx_dlsym(__handle, "WJ3rqFwymew", &__ptr_sceRtcFormatRFC3339)) return;
  if(sprx_dlsym(__handle, "DwuHIlLGW8I", &__ptr_sceRtcFormatRFC3339LocalTime)) return;
  if(sprx_dlsym(__handle, "lja0nNPWojg", &__ptr_sceRtcFormatRFC3339Precise)) return;
  if(sprx_dlsym(__handle, "tOZ6fwwHZOA", &__ptr_sceRtcFormatRFC3339PreciseLocalTime)) return;
  if(sprx_dlsym(__handle, "LN3Zcb72Q0c", &__ptr_sceRtcGetCurrentAdNetworkTick)) return;
  if(sprx_dlsym(__handle, "8lfvnRMqwEM", &__ptr_sceRtcGetCurrentClock)) return;
  if(sprx_dlsym(__handle, "ZPD1YOKI+Kw", &__ptr_sceRtcGetCurrentClockLocalTime)) return;
  if(sprx_dlsym(__handle, "Ot1DE3gif84", &__ptr_sceRtcGetCurrentDebugNetworkTick)) return;
  if(sprx_dlsym(__handle, "zO9UL3qIINQ", &__ptr_sceRtcGetCurrentNetworkTick)) return;
  if(sprx_dlsym(__handle, "HWxHOdbM-Pg", &__ptr_sceRtcGetCurrentRawNetworkTick)) return;
  if(sprx_dlsym(__handle, "18B2NS1y9UU", &__ptr_sceRtcGetCurrentTick)) return;
  if(sprx_dlsym(__handle, "CyIK-i4XdgQ", &__ptr_sceRtcGetDayOfWeek)) return;
  if(sprx_dlsym(__handle, "3O7Ln8AqJ1o", &__ptr_sceRtcGetDaysInMonth)) return;
  if(sprx_dlsym(__handle, "E7AR4o7Ny7E", &__ptr_sceRtcGetDosTime)) return;
  if(sprx_dlsym(__handle, "8w-H19ip48I", &__ptr_sceRtcGetTick)) return;
  if(sprx_dlsym(__handle, "jMNwqYr4R-k", &__ptr_sceRtcGetTickResolution)) return;
  if(sprx_dlsym(__handle, "BtqmpTRXHgk", &__ptr_sceRtcGetTime_t)) return;
  if(sprx_dlsym(__handle, "jfRO0uTjtzA", &__ptr_sceRtcGetWin32FileTime)) return;
  if(sprx_dlsym(__handle, "LlodCMDbk3o", &__ptr_sceRtcInit)) return;
  if(sprx_dlsym(__handle, "Ug8pCwQvh0c", &__ptr_sceRtcIsLeapYear)) return;
  if(sprx_dlsym(__handle, "NxEI1KByvCI", &__ptr_sceRtcParseDateTime)) return;
  if(sprx_dlsym(__handle, "99bMGglFW3I", &__ptr_sceRtcParseRFC3339)) return;
  if(sprx_dlsym(__handle, "fFLgmNUpChg", &__ptr_sceRtcSetConf)) return;
  if(sprx_dlsym(__handle, "sV2tK+yOhBU", &__ptr_sceRtcSetCurrentAdNetworkTick)) return;
  if(sprx_dlsym(__handle, "VLDUPKmw5L8", &__ptr_sceRtcSetCurrentDebugNetworkTick)) return;
  if(sprx_dlsym(__handle, "qhDBtIo+auw", &__ptr_sceRtcSetCurrentNetworkTick)) return;
  if(sprx_dlsym(__handle, "d4fHLCGmY80", &__ptr_sceRtcSetCurrentTick)) return;
  if(sprx_dlsym(__handle, "aYPCd1cChyg", &__ptr_sceRtcSetDosTime)) return;
  if(sprx_dlsym(__handle, "ueega6v3GUw", &__ptr_sceRtcSetTick)) return;
  if(sprx_dlsym(__handle, "bDEVVP4bTjQ", &__ptr_sceRtcSetTime_t)) return;
  if(sprx_dlsym(__handle, "n5JiAJXsbcs", &__ptr_sceRtcSetWin32FileTime)) return;
  if(sprx_dlsym(__handle, "NR1J0N7L2xY", &__ptr_sceRtcTickAddDays)) return;
  if(sprx_dlsym(__handle, "MDc5cd8HfCA", &__ptr_sceRtcTickAddHours)) return;
  if(sprx_dlsym(__handle, "XPIiw58C+GM", &__ptr_sceRtcTickAddMicroseconds)) return;
  if(sprx_dlsym(__handle, "mn-tf4QiFzk", &__ptr_sceRtcTickAddMinutes)) return;
  if(sprx_dlsym(__handle, "CL6y9q-XbuQ", &__ptr_sceRtcTickAddMonths)) return;
  if(sprx_dlsym(__handle, "07O525HgICs", &__ptr_sceRtcTickAddSeconds)) return;
  if(sprx_dlsym(__handle, "AqVMssr52Rc", &__ptr_sceRtcTickAddTicks)) return;
  if(sprx_dlsym(__handle, "gI4t194c2W8", &__ptr_sceRtcTickAddWeeks)) return;
  if(sprx_dlsym(__handle, "-5y2uJ62qS8", &__ptr_sceRtcTickAddYears)) return;
}

static void __attribute__((destructor(104)))
__destructor(void) {
  sprx_dlclose(__handle);
}
