/*
 This file was generated by genstub.py, do not edit manually!
*/

int sprx_dlsym(unsigned int handle, const char *nid, void *addr);
int sprx_dlopen(const char* libname, unsigned short *handle);
int sprx_dlclose(unsigned int handle);

static __attribute__ ((used)) void* __ptr_sceAudioSystemSystemResume;
asm(".intel_syntax noprefix\n"
    ".global sceAudioSystemSystemResume\n"
    ".type sceAudioSystemSystemResume @function\n"
    "sceAudioSystemSystemResume:\n"
    "jmp qword ptr [rip + __ptr_sceAudioSystemSystemResume]\n");

static __attribute__ ((used)) void* __ptr_sceAudioSystemSystemSuspend;
asm(".intel_syntax noprefix\n"
    ".global sceAudioSystemSystemSuspend\n"
    ".type sceAudioSystemSystemSuspend @function\n"
    "sceAudioSystemSystemSuspend:\n"
    "jmp qword ptr [rip + __ptr_sceAudioSystemSystemSuspend]\n");

static unsigned short __handle = 0;
static void __attribute__((constructor(104)))
__constructor(void) {
  if(sprx_dlopen("libSceAudioSystem", &__handle)) return;
  if(sprx_dlsym(__handle, "I4oxnvdvQmk", &__ptr_sceAudioSystemSystemResume)) return;
  if(sprx_dlsym(__handle, "0E2eyiIG7wM", &__ptr_sceAudioSystemSystemSuspend)) return;
}

static void __attribute__((destructor(104)))
__destructor(void) {
  sprx_dlclose(__handle);
}
