/*
 This file was generated by genstub.py, do not edit manually!
*/

int sprx_dlsym(unsigned int handle, const char *nid, void *addr);
int sprx_dlopen(const char* libname, unsigned short *handle);
int sprx_dlclose(unsigned int handle);

static __attribute__ ((used)) void* __ptr_scePatchCheckerCancel;
asm(".intel_syntax noprefix\n"
    ".global scePatchCheckerCancel\n"
    ".type scePatchCheckerCancel @function\n"
    "scePatchCheckerCancel:\n"
    "jmp qword ptr [rip + __ptr_scePatchCheckerCancel]\n");

static __attribute__ ((used)) void* __ptr_scePatchCheckerCheckPatch;
asm(".intel_syntax noprefix\n"
    ".global scePatchCheckerCheckPatch\n"
    ".type scePatchCheckerCheckPatch @function\n"
    "scePatchCheckerCheckPatch:\n"
    "jmp qword ptr [rip + __ptr_scePatchCheckerCheckPatch]\n");

static __attribute__ ((used)) void* __ptr_scePatchCheckerCreateHandler;
asm(".intel_syntax noprefix\n"
    ".global scePatchCheckerCreateHandler\n"
    ".type scePatchCheckerCreateHandler @function\n"
    "scePatchCheckerCreateHandler:\n"
    "jmp qword ptr [rip + __ptr_scePatchCheckerCreateHandler]\n");

static __attribute__ ((used)) void* __ptr_scePatchCheckerDestroyHandler;
asm(".intel_syntax noprefix\n"
    ".global scePatchCheckerDestroyHandler\n"
    ".type scePatchCheckerDestroyHandler @function\n"
    "scePatchCheckerDestroyHandler:\n"
    "jmp qword ptr [rip + __ptr_scePatchCheckerDestroyHandler]\n");

static __attribute__ ((used)) void* __ptr_scePatchCheckerDisableAutoDownload;
asm(".intel_syntax noprefix\n"
    ".global scePatchCheckerDisableAutoDownload\n"
    ".type scePatchCheckerDisableAutoDownload @function\n"
    "scePatchCheckerDisableAutoDownload:\n"
    "jmp qword ptr [rip + __ptr_scePatchCheckerDisableAutoDownload]\n");

static __attribute__ ((used)) void* __ptr_scePatchCheckerEnableAutoDownload;
asm(".intel_syntax noprefix\n"
    ".global scePatchCheckerEnableAutoDownload\n"
    ".type scePatchCheckerEnableAutoDownload @function\n"
    "scePatchCheckerEnableAutoDownload:\n"
    "jmp qword ptr [rip + __ptr_scePatchCheckerEnableAutoDownload]\n");

static __attribute__ ((used)) void* __ptr_scePatchCheckerGetApplicableTick;
asm(".intel_syntax noprefix\n"
    ".global scePatchCheckerGetApplicableTick\n"
    ".type scePatchCheckerGetApplicableTick @function\n"
    "scePatchCheckerGetApplicableTick:\n"
    "jmp qword ptr [rip + __ptr_scePatchCheckerGetApplicableTick]\n");

static __attribute__ ((used)) void* __ptr_scePatchCheckerGetPackageInfo;
asm(".intel_syntax noprefix\n"
    ".global scePatchCheckerGetPackageInfo\n"
    ".type scePatchCheckerGetPackageInfo @function\n"
    "scePatchCheckerGetPackageInfo:\n"
    "jmp qword ptr [rip + __ptr_scePatchCheckerGetPackageInfo]\n");

static __attribute__ ((used)) void* __ptr_scePatchCheckerInitialize;
asm(".intel_syntax noprefix\n"
    ".global scePatchCheckerInitialize\n"
    ".type scePatchCheckerInitialize @function\n"
    "scePatchCheckerInitialize:\n"
    "jmp qword ptr [rip + __ptr_scePatchCheckerInitialize]\n");

static __attribute__ ((used)) void* __ptr_scePatchCheckerRequestCheckPatch;
asm(".intel_syntax noprefix\n"
    ".global scePatchCheckerRequestCheckPatch\n"
    ".type scePatchCheckerRequestCheckPatch @function\n"
    "scePatchCheckerRequestCheckPatch:\n"
    "jmp qword ptr [rip + __ptr_scePatchCheckerRequestCheckPatch]\n");

static __attribute__ ((used)) void* __ptr_scePatchCheckerRequestCheckPatchByType;
asm(".intel_syntax noprefix\n"
    ".global scePatchCheckerRequestCheckPatchByType\n"
    ".type scePatchCheckerRequestCheckPatchByType @function\n"
    "scePatchCheckerRequestCheckPatchByType:\n"
    "jmp qword ptr [rip + __ptr_scePatchCheckerRequestCheckPatchByType]\n");

static __attribute__ ((used)) void* __ptr_scePatchCheckerTerminate;
asm(".intel_syntax noprefix\n"
    ".global scePatchCheckerTerminate\n"
    ".type scePatchCheckerTerminate @function\n"
    "scePatchCheckerTerminate:\n"
    "jmp qword ptr [rip + __ptr_scePatchCheckerTerminate]\n");

static unsigned short __handle = 0;
static void __attribute__((constructor(104)))
__constructor(void) {
  if(sprx_dlopen("libScePatchCheckerClient", &__handle)) return;
  if(sprx_dlsym(__handle, "xTJYIk5zjF8", &__ptr_scePatchCheckerCancel)) return;
  if(sprx_dlsym(__handle, "Bm9eE0veFss", &__ptr_scePatchCheckerCheckPatch)) return;
  if(sprx_dlsym(__handle, "MHUY7dC9vrM", &__ptr_scePatchCheckerCreateHandler)) return;
  if(sprx_dlsym(__handle, "9s6ZwdTXAmc", &__ptr_scePatchCheckerDestroyHandler)) return;
  if(sprx_dlsym(__handle, "b4t2jOPTxts", &__ptr_scePatchCheckerDisableAutoDownload)) return;
  if(sprx_dlsym(__handle, "Ls3rKzckGXQ", &__ptr_scePatchCheckerEnableAutoDownload)) return;
  if(sprx_dlsym(__handle, "+hLkT-vIyQE", &__ptr_scePatchCheckerGetApplicableTick)) return;
  if(sprx_dlsym(__handle, "B6TZJJ+mf9Y", &__ptr_scePatchCheckerGetPackageInfo)) return;
  if(sprx_dlsym(__handle, "m8oc1t4Rp28", &__ptr_scePatchCheckerInitialize)) return;
  if(sprx_dlsym(__handle, "TlbTYydth54", &__ptr_scePatchCheckerRequestCheckPatch)) return;
  if(sprx_dlsym(__handle, "Kru1Y4HvomI", &__ptr_scePatchCheckerRequestCheckPatchByType)) return;
  if(sprx_dlsym(__handle, "rjXFQQQrE+k", &__ptr_scePatchCheckerTerminate)) return;
}

static void __attribute__((destructor(104)))
__destructor(void) {
  sprx_dlclose(__handle);
}
