/*
 This file was generated by genstub.py, do not edit manually!
*/

int sprx_dlsym(unsigned int handle, const char *nid, void *addr);
int sprx_dlopen(const char* libname, unsigned short *handle);
int sprx_dlclose(unsigned int handle);

static __attribute__ ((used)) void* __ptr_sceContentBinderEnd;
asm(".intel_syntax noprefix\n"
    ".global sceContentBinderEnd\n"
    ".type sceContentBinderEnd @function\n"
    "sceContentBinderEnd:\n"
    "jmp qword ptr [rip + __ptr_sceContentBinderEnd]\n");

static __attribute__ ((used)) void* __ptr_sceContentBinderGetNumOfDifference;
asm(".intel_syntax noprefix\n"
    ".global sceContentBinderGetNumOfDifference\n"
    ".type sceContentBinderGetNumOfDifference @function\n"
    "sceContentBinderGetNumOfDifference:\n"
    "jmp qword ptr [rip + __ptr_sceContentBinderGetNumOfDifference]\n");

static __attribute__ ((used)) void* __ptr_sceContentBinderInitialize;
asm(".intel_syntax noprefix\n"
    ".global sceContentBinderInitialize\n"
    ".type sceContentBinderInitialize @function\n"
    "sceContentBinderInitialize:\n"
    "jmp qword ptr [rip + __ptr_sceContentBinderInitialize]\n");

static __attribute__ ((used)) void* __ptr_sceContentBinderIsUpdated;
asm(".intel_syntax noprefix\n"
    ".global sceContentBinderIsUpdated\n"
    ".type sceContentBinderIsUpdated @function\n"
    "sceContentBinderIsUpdated:\n"
    "jmp qword ptr [rip + __ptr_sceContentBinderIsUpdated]\n");

static __attribute__ ((used)) void* __ptr_sceContentBinderReset;
asm(".intel_syntax noprefix\n"
    ".global sceContentBinderReset\n"
    ".type sceContentBinderReset @function\n"
    "sceContentBinderReset:\n"
    "jmp qword ptr [rip + __ptr_sceContentBinderReset]\n");

static __attribute__ ((used)) void* __ptr_sceContentBinderSearchDifference;
asm(".intel_syntax noprefix\n"
    ".global sceContentBinderSearchDifference\n"
    ".type sceContentBinderSearchDifference @function\n"
    "sceContentBinderSearchDifference:\n"
    "jmp qword ptr [rip + __ptr_sceContentBinderSearchDifference]\n");

static __attribute__ ((used)) void* __ptr_sceContentBinderStart;
asm(".intel_syntax noprefix\n"
    ".global sceContentBinderStart\n"
    ".type sceContentBinderStart @function\n"
    "sceContentBinderStart:\n"
    "jmp qword ptr [rip + __ptr_sceContentBinderStart]\n");

static __attribute__ ((used)) void* __ptr_sceContentBinderTerminate;
asm(".intel_syntax noprefix\n"
    ".global sceContentBinderTerminate\n"
    ".type sceContentBinderTerminate @function\n"
    "sceContentBinderTerminate:\n"
    "jmp qword ptr [rip + __ptr_sceContentBinderTerminate]\n");

static __attribute__ ((used)) void* __ptr_sceContentSearchCloseMetadata;
asm(".intel_syntax noprefix\n"
    ".global sceContentSearchCloseMetadata\n"
    ".type sceContentSearchCloseMetadata @function\n"
    "sceContentSearchCloseMetadata:\n"
    "jmp qword ptr [rip + __ptr_sceContentSearchCloseMetadata]\n");

static __attribute__ ((used)) void* __ptr_sceContentSearchGetApplicationLastUpdateId;
asm(".intel_syntax noprefix\n"
    ".global sceContentSearchGetApplicationLastUpdateId\n"
    ".type sceContentSearchGetApplicationLastUpdateId @function\n"
    "sceContentSearchGetApplicationLastUpdateId:\n"
    "jmp qword ptr [rip + __ptr_sceContentSearchGetApplicationLastUpdateId]\n");

static __attribute__ ((used)) void* __ptr_sceContentSearchGetContentLastUpdateId;
asm(".intel_syntax noprefix\n"
    ".global sceContentSearchGetContentLastUpdateId\n"
    ".type sceContentSearchGetContentLastUpdateId @function\n"
    "sceContentSearchGetContentLastUpdateId:\n"
    "jmp qword ptr [rip + __ptr_sceContentSearchGetContentLastUpdateId]\n");

static __attribute__ ((used)) void* __ptr_sceContentSearchGetMetadataFieldInfo;
asm(".intel_syntax noprefix\n"
    ".global sceContentSearchGetMetadataFieldInfo\n"
    ".type sceContentSearchGetMetadataFieldInfo @function\n"
    "sceContentSearchGetMetadataFieldInfo:\n"
    "jmp qword ptr [rip + __ptr_sceContentSearchGetMetadataFieldInfo]\n");

static __attribute__ ((used)) void* __ptr_sceContentSearchGetMetadataValue;
asm(".intel_syntax noprefix\n"
    ".global sceContentSearchGetMetadataValue\n"
    ".type sceContentSearchGetMetadataValue @function\n"
    "sceContentSearchGetMetadataValue:\n"
    "jmp qword ptr [rip + __ptr_sceContentSearchGetMetadataValue]\n");

static __attribute__ ((used)) void* __ptr_sceContentSearchGetMyApplicationIndex;
asm(".intel_syntax noprefix\n"
    ".global sceContentSearchGetMyApplicationIndex\n"
    ".type sceContentSearchGetMyApplicationIndex @function\n"
    "sceContentSearchGetMyApplicationIndex:\n"
    "jmp qword ptr [rip + __ptr_sceContentSearchGetMyApplicationIndex]\n");

static __attribute__ ((used)) void* __ptr_sceContentSearchGetNumOfApplication;
asm(".intel_syntax noprefix\n"
    ".global sceContentSearchGetNumOfApplication\n"
    ".type sceContentSearchGetNumOfApplication @function\n"
    "sceContentSearchGetNumOfApplication:\n"
    "jmp qword ptr [rip + __ptr_sceContentSearchGetNumOfApplication]\n");

static __attribute__ ((used)) void* __ptr_sceContentSearchGetNumOfContent;
asm(".intel_syntax noprefix\n"
    ".global sceContentSearchGetNumOfContent\n"
    ".type sceContentSearchGetNumOfContent @function\n"
    "sceContentSearchGetNumOfContent:\n"
    "jmp qword ptr [rip + __ptr_sceContentSearchGetNumOfContent]\n");

static __attribute__ ((used)) void* __ptr_sceContentSearchGetTotalContentSize;
asm(".intel_syntax noprefix\n"
    ".global sceContentSearchGetTotalContentSize\n"
    ".type sceContentSearchGetTotalContentSize @function\n"
    "sceContentSearchGetTotalContentSize:\n"
    "jmp qword ptr [rip + __ptr_sceContentSearchGetTotalContentSize]\n");

static __attribute__ ((used)) void* __ptr_sceContentSearchInit;
asm(".intel_syntax noprefix\n"
    ".global sceContentSearchInit\n"
    ".type sceContentSearchInit @function\n"
    "sceContentSearchInit:\n"
    "jmp qword ptr [rip + __ptr_sceContentSearchInit]\n");

static __attribute__ ((used)) void* __ptr_sceContentSearchOpenMetadata;
asm(".intel_syntax noprefix\n"
    ".global sceContentSearchOpenMetadata\n"
    ".type sceContentSearchOpenMetadata @function\n"
    "sceContentSearchOpenMetadata:\n"
    "jmp qword ptr [rip + __ptr_sceContentSearchOpenMetadata]\n");

static __attribute__ ((used)) void* __ptr_sceContentSearchOpenMetadataByContentId;
asm(".intel_syntax noprefix\n"
    ".global sceContentSearchOpenMetadataByContentId\n"
    ".type sceContentSearchOpenMetadataByContentId @function\n"
    "sceContentSearchOpenMetadataByContentId:\n"
    "jmp qword ptr [rip + __ptr_sceContentSearchOpenMetadataByContentId]\n");

static __attribute__ ((used)) void* __ptr_sceContentSearchSearchApplication;
asm(".intel_syntax noprefix\n"
    ".global sceContentSearchSearchApplication\n"
    ".type sceContentSearchSearchApplication @function\n"
    "sceContentSearchSearchApplication:\n"
    "jmp qword ptr [rip + __ptr_sceContentSearchSearchApplication]\n");

static __attribute__ ((used)) void* __ptr_sceContentSearchSearchContent;
asm(".intel_syntax noprefix\n"
    ".global sceContentSearchSearchContent\n"
    ".type sceContentSearchSearchContent @function\n"
    "sceContentSearchSearchContent:\n"
    "jmp qword ptr [rip + __ptr_sceContentSearchSearchContent]\n");

static __attribute__ ((used)) void* __ptr_sceContentSearchTerm;
asm(".intel_syntax noprefix\n"
    ".global sceContentSearchTerm\n"
    ".type sceContentSearchTerm @function\n"
    "sceContentSearchTerm:\n"
    "jmp qword ptr [rip + __ptr_sceContentSearchTerm]\n");

static unsigned short __handle = 0;
static void __attribute__((constructor(104)))
__constructor(void) {
  if(sprx_dlopen("libSceContentSearch", &__handle)) return;
  if(sprx_dlsym(__handle, "hvfrzWFz2aE", &__ptr_sceContentBinderEnd)) return;
  if(sprx_dlsym(__handle, "IElCGP1gobk", &__ptr_sceContentBinderGetNumOfDifference)) return;
  if(sprx_dlsym(__handle, "V5NUMrn5cEQ", &__ptr_sceContentBinderInitialize)) return;
  if(sprx_dlsym(__handle, "W4kZjfF08xU", &__ptr_sceContentBinderIsUpdated)) return;
  if(sprx_dlsym(__handle, "tzgPpLnmFbc", &__ptr_sceContentBinderReset)) return;
  if(sprx_dlsym(__handle, "gYr9dLq8Y10", &__ptr_sceContentBinderSearchDifference)) return;
  if(sprx_dlsym(__handle, "mlBEgk9o0SE", &__ptr_sceContentBinderStart)) return;
  if(sprx_dlsym(__handle, "XYm1wQQEDc0", &__ptr_sceContentBinderTerminate)) return;
  if(sprx_dlsym(__handle, "-YbpaF0XS-I", &__ptr_sceContentSearchCloseMetadata)) return;
  if(sprx_dlsym(__handle, "jGHBPci4dzU", &__ptr_sceContentSearchGetApplicationLastUpdateId)) return;
  if(sprx_dlsym(__handle, "PD5bnBTsv6Y", &__ptr_sceContentSearchGetContentLastUpdateId)) return;
  if(sprx_dlsym(__handle, "EbNufIY0Zvc", &__ptr_sceContentSearchGetMetadataFieldInfo)) return;
  if(sprx_dlsym(__handle, "ruNe-FgCzO8", &__ptr_sceContentSearchGetMetadataValue)) return;
  if(sprx_dlsym(__handle, "FRT4EYtZU1Y", &__ptr_sceContentSearchGetMyApplicationIndex)) return;
  if(sprx_dlsym(__handle, "BU0x8ye5-dI", &__ptr_sceContentSearchGetNumOfApplication)) return;
  if(sprx_dlsym(__handle, "o-RBPV0qr8c", &__ptr_sceContentSearchGetNumOfContent)) return;
  if(sprx_dlsym(__handle, "i2ZMZKwZpWs", &__ptr_sceContentSearchGetTotalContentSize)) return;
  if(sprx_dlsym(__handle, "dPj4ZtRcIWk", &__ptr_sceContentSearchInit)) return;
  if(sprx_dlsym(__handle, "G13HF1z-e4o", &__ptr_sceContentSearchOpenMetadata)) return;
  if(sprx_dlsym(__handle, "bjAlYWwRTJA", &__ptr_sceContentSearchOpenMetadataByContentId)) return;
  if(sprx_dlsym(__handle, "m-S3-C-USvs", &__ptr_sceContentSearchSearchApplication)) return;
  if(sprx_dlsym(__handle, "TEW3IKxYfXc", &__ptr_sceContentSearchSearchContent)) return;
  if(sprx_dlsym(__handle, "1xSZodB2geA", &__ptr_sceContentSearchTerm)) return;
}

static void __attribute__((destructor(104)))
__destructor(void) {
  sprx_dlclose(__handle);
}
