/*
 This file was generated by genstub.py, do not edit manually!
*/

int sprx_dlsym(unsigned int handle, const char *nid, void *addr);
int sprx_dlopen(const char* libname, unsigned short *handle);
int sprx_dlclose(unsigned int handle);

static __attribute__ ((used)) void* __ptr__Z5dummyv;
asm(".intel_syntax noprefix\n"
    ".global _Z5dummyv\n"
    ".type _Z5dummyv @function\n"
    "_Z5dummyv:\n"
    "jmp qword ptr [rip + __ptr__Z5dummyv]\n");

static __attribute__ ((used)) void* __ptr_sceWkFontConfigGetAttr;
asm(".intel_syntax noprefix\n"
    ".global sceWkFontConfigGetAttr\n"
    ".type sceWkFontConfigGetAttr @function\n"
    "sceWkFontConfigGetAttr:\n"
    "jmp qword ptr [rip + __ptr_sceWkFontConfigGetAttr]\n");

static __attribute__ ((used)) void* __ptr_sceWkFontConfigGetFont;
asm(".intel_syntax noprefix\n"
    ".global sceWkFontConfigGetFont\n"
    ".type sceWkFontConfigGetFont @function\n"
    "sceWkFontConfigGetFont:\n"
    "jmp qword ptr [rip + __ptr_sceWkFontConfigGetFont]\n");

static __attribute__ ((used)) void* __ptr_sceWkFontConfigGetFontFromFontName;
asm(".intel_syntax noprefix\n"
    ".global sceWkFontConfigGetFontFromFontName\n"
    ".type sceWkFontConfigGetFontFromFontName @function\n"
    "sceWkFontConfigGetFontFromFontName:\n"
    "jmp qword ptr [rip + __ptr_sceWkFontConfigGetFontFromFontName]\n");

static __attribute__ ((used)) void* __ptr_sceWkFontConfigGetFontName;
asm(".intel_syntax noprefix\n"
    ".global sceWkFontConfigGetFontName\n"
    ".type sceWkFontConfigGetFontName @function\n"
    "sceWkFontConfigGetFontName:\n"
    "jmp qword ptr [rip + __ptr_sceWkFontConfigGetFontName]\n");

static __attribute__ ((used)) void* __ptr_sceWkFontConfigGetFontPath;
asm(".intel_syntax noprefix\n"
    ".global sceWkFontConfigGetFontPath\n"
    ".type sceWkFontConfigGetFontPath @function\n"
    "sceWkFontConfigGetFontPath:\n"
    "jmp qword ptr [rip + __ptr_sceWkFontConfigGetFontPath]\n");

static unsigned short __handle = 0;
static void __attribute__((constructor(104)))
__constructor(void) {
  if(sprx_dlopen("libSceWkFontConfig", &__handle)) return;
  if(sprx_dlsym(__handle, "AS45QoYHjc4", &__ptr__Z5dummyv)) return;
  if(sprx_dlsym(__handle, "xfw0+A2aiWE", &__ptr_sceWkFontConfigGetAttr)) return;
  if(sprx_dlsym(__handle, "uBjfcMAhIJs", &__ptr_sceWkFontConfigGetFont)) return;
  if(sprx_dlsym(__handle, "n3MYEpevnMo", &__ptr_sceWkFontConfigGetFontFromFontName)) return;
  if(sprx_dlsym(__handle, "8jNGivweX70", &__ptr_sceWkFontConfigGetFontName)) return;
  if(sprx_dlsym(__handle, "HlPrXSZTbS0", &__ptr_sceWkFontConfigGetFontPath)) return;
}

static void __attribute__((destructor(104)))
__destructor(void) {
  sprx_dlclose(__handle);
}
