/*
 This file was generated by genstub.py, do not edit manually!
*/

int sprx_dlsym(unsigned int handle, const char *nid, void *addr);
int sprx_dlopen(const char* libname, unsigned short *handle);
int sprx_dlclose(unsigned int handle);

static __attribute__ ((used)) void* __ptr_sceDepth2GetImage;
asm(".intel_syntax noprefix\n"
    ".global sceDepth2GetImage\n"
    ".type sceDepth2GetImage @function\n"
    "sceDepth2GetImage:\n"
    "jmp qword ptr [rip + __ptr_sceDepth2GetImage]\n");

static __attribute__ ((used)) void* __ptr_sceDepth2Initialize;
asm(".intel_syntax noprefix\n"
    ".global sceDepth2Initialize\n"
    ".type sceDepth2Initialize @function\n"
    "sceDepth2Initialize:\n"
    "jmp qword ptr [rip + __ptr_sceDepth2Initialize]\n");

static __attribute__ ((used)) void* __ptr_sceDepth2QueryMemory;
asm(".intel_syntax noprefix\n"
    ".global sceDepth2QueryMemory\n"
    ".type sceDepth2QueryMemory @function\n"
    "sceDepth2QueryMemory:\n"
    "jmp qword ptr [rip + __ptr_sceDepth2QueryMemory]\n");

static __attribute__ ((used)) void* __ptr_sceDepth2SaveInternalBuffers;
asm(".intel_syntax noprefix\n"
    ".global sceDepth2SaveInternalBuffers\n"
    ".type sceDepth2SaveInternalBuffers @function\n"
    "sceDepth2SaveInternalBuffers:\n"
    "jmp qword ptr [rip + __ptr_sceDepth2SaveInternalBuffers]\n");

static __attribute__ ((used)) void* __ptr_sceDepth2SetCameraFactoryCalibrationData;
asm(".intel_syntax noprefix\n"
    ".global sceDepth2SetCameraFactoryCalibrationData\n"
    ".type sceDepth2SetCameraFactoryCalibrationData @function\n"
    "sceDepth2SetCameraFactoryCalibrationData:\n"
    "jmp qword ptr [rip + __ptr_sceDepth2SetCameraFactoryCalibrationData]\n");

static __attribute__ ((used)) void* __ptr_sceDepth2SetCommand;
asm(".intel_syntax noprefix\n"
    ".global sceDepth2SetCommand\n"
    ".type sceDepth2SetCommand @function\n"
    "sceDepth2SetCommand:\n"
    "jmp qword ptr [rip + __ptr_sceDepth2SetCommand]\n");

static __attribute__ ((used)) void* __ptr_sceDepth2SetRoi;
asm(".intel_syntax noprefix\n"
    ".global sceDepth2SetRoi\n"
    ".type sceDepth2SetRoi @function\n"
    "sceDepth2SetRoi:\n"
    "jmp qword ptr [rip + __ptr_sceDepth2SetRoi]\n");

static __attribute__ ((used)) void* __ptr_sceDepth2Submit;
asm(".intel_syntax noprefix\n"
    ".global sceDepth2Submit\n"
    ".type sceDepth2Submit @function\n"
    "sceDepth2Submit:\n"
    "jmp qword ptr [rip + __ptr_sceDepth2Submit]\n");

static __attribute__ ((used)) void* __ptr_sceDepth2Terminate;
asm(".intel_syntax noprefix\n"
    ".global sceDepth2Terminate\n"
    ".type sceDepth2Terminate @function\n"
    "sceDepth2Terminate:\n"
    "jmp qword ptr [rip + __ptr_sceDepth2Terminate]\n");

static __attribute__ ((used)) void* __ptr_sceDepth2WaitAndExecutePostProcess;
asm(".intel_syntax noprefix\n"
    ".global sceDepth2WaitAndExecutePostProcess\n"
    ".type sceDepth2WaitAndExecutePostProcess @function\n"
    "sceDepth2WaitAndExecutePostProcess:\n"
    "jmp qword ptr [rip + __ptr_sceDepth2WaitAndExecutePostProcess]\n");

static unsigned short __handle = 0;
static void __attribute__((constructor(104)))
__constructor(void) {
  if(sprx_dlopen("libSceDepth2", &__handle)) return;
  if(sprx_dlsym(__handle, "ssOcL1iqcTE", &__ptr_sceDepth2GetImage)) return;
  if(sprx_dlsym(__handle, "WpgesOm4xX8", &__ptr_sceDepth2Initialize)) return;
  if(sprx_dlsym(__handle, "JG-Dc43R4pM", &__ptr_sceDepth2QueryMemory)) return;
  if(sprx_dlsym(__handle, "RUtAryHv2fI", &__ptr_sceDepth2SaveInternalBuffers)) return;
  if(sprx_dlsym(__handle, "xszTt3hOPcA", &__ptr_sceDepth2SetCameraFactoryCalibrationData)) return;
  if(sprx_dlsym(__handle, "o7OQzFuXJ28", &__ptr_sceDepth2SetCommand)) return;
  if(sprx_dlsym(__handle, "WIlLwVKWows", &__ptr_sceDepth2SetRoi)) return;
  if(sprx_dlsym(__handle, "UUQSk5-w9gU", &__ptr_sceDepth2Submit)) return;
  if(sprx_dlsym(__handle, "ot9Mw6ofb74", &__ptr_sceDepth2Terminate)) return;
  if(sprx_dlsym(__handle, "2gMXO8S2qik", &__ptr_sceDepth2WaitAndExecutePostProcess)) return;
}

static void __attribute__((destructor(104)))
__destructor(void) {
  sprx_dlclose(__handle);
}
