/*
 This file was generated by genstub.py, do not edit manually!
*/

int sprx_dlsym(unsigned int handle, const char *nid, void *addr);
int sprx_dlopen(const char* libname, unsigned short *handle);
int sprx_dlclose(unsigned int handle);

static __attribute__ ((used)) void* __ptr_scePadClose;
asm(".intel_syntax noprefix\n"
    ".global scePadClose\n"
    ".type scePadClose @function\n"
    "scePadClose:\n"
    "jmp qword ptr [rip + __ptr_scePadClose]\n");

static __attribute__ ((used)) void* __ptr_scePadConnectPort;
asm(".intel_syntax noprefix\n"
    ".global scePadConnectPort\n"
    ".type scePadConnectPort @function\n"
    "scePadConnectPort:\n"
    "jmp qword ptr [rip + __ptr_scePadConnectPort]\n");

static __attribute__ ((used)) void* __ptr_scePadDeviceClassGetExtendedInformation;
asm(".intel_syntax noprefix\n"
    ".global scePadDeviceClassGetExtendedInformation\n"
    ".type scePadDeviceClassGetExtendedInformation @function\n"
    "scePadDeviceClassGetExtendedInformation:\n"
    "jmp qword ptr [rip + __ptr_scePadDeviceClassGetExtendedInformation]\n");

static __attribute__ ((used)) void* __ptr_scePadDeviceClassParseData;
asm(".intel_syntax noprefix\n"
    ".global scePadDeviceClassParseData\n"
    ".type scePadDeviceClassParseData @function\n"
    "scePadDeviceClassParseData:\n"
    "jmp qword ptr [rip + __ptr_scePadDeviceClassParseData]\n");

static __attribute__ ((used)) void* __ptr_scePadDeviceOpen;
asm(".intel_syntax noprefix\n"
    ".global scePadDeviceOpen\n"
    ".type scePadDeviceOpen @function\n"
    "scePadDeviceOpen:\n"
    "jmp qword ptr [rip + __ptr_scePadDeviceOpen]\n");

static __attribute__ ((used)) void* __ptr_scePadDisableTriggerEffect;
asm(".intel_syntax noprefix\n"
    ".global scePadDisableTriggerEffect\n"
    ".type scePadDisableTriggerEffect @function\n"
    "scePadDisableTriggerEffect:\n"
    "jmp qword ptr [rip + __ptr_scePadDisableTriggerEffect]\n");

static __attribute__ ((used)) void* __ptr_scePadDisableVibration;
asm(".intel_syntax noprefix\n"
    ".global scePadDisableVibration\n"
    ".type scePadDisableVibration @function\n"
    "scePadDisableVibration:\n"
    "jmp qword ptr [rip + __ptr_scePadDisableVibration]\n");

static __attribute__ ((used)) void* __ptr_scePadDisconnectDevice;
asm(".intel_syntax noprefix\n"
    ".global scePadDisconnectDevice\n"
    ".type scePadDisconnectDevice @function\n"
    "scePadDisconnectDevice:\n"
    "jmp qword ptr [rip + __ptr_scePadDisconnectDevice]\n");

static __attribute__ ((used)) void* __ptr_scePadDisconnectPort;
asm(".intel_syntax noprefix\n"
    ".global scePadDisconnectPort\n"
    ".type scePadDisconnectPort @function\n"
    "scePadDisconnectPort:\n"
    "jmp qword ptr [rip + __ptr_scePadDisconnectPort]\n");

static __attribute__ ((used)) void* __ptr_scePadEnableAutoDetect;
asm(".intel_syntax noprefix\n"
    ".global scePadEnableAutoDetect\n"
    ".type scePadEnableAutoDetect @function\n"
    "scePadEnableAutoDetect:\n"
    "jmp qword ptr [rip + __ptr_scePadEnableAutoDetect]\n");

static __attribute__ ((used)) void* __ptr_scePadEnableExtensionPort;
asm(".intel_syntax noprefix\n"
    ".global scePadEnableExtensionPort\n"
    ".type scePadEnableExtensionPort @function\n"
    "scePadEnableExtensionPort:\n"
    "jmp qword ptr [rip + __ptr_scePadEnableExtensionPort]\n");

static __attribute__ ((used)) void* __ptr_scePadEnableSpecificDeviceClass;
asm(".intel_syntax noprefix\n"
    ".global scePadEnableSpecificDeviceClass\n"
    ".type scePadEnableSpecificDeviceClass @function\n"
    "scePadEnableSpecificDeviceClass:\n"
    "jmp qword ptr [rip + __ptr_scePadEnableSpecificDeviceClass]\n");

static __attribute__ ((used)) void* __ptr_scePadEnableUsbConnection;
asm(".intel_syntax noprefix\n"
    ".global scePadEnableUsbConnection\n"
    ".type scePadEnableUsbConnection @function\n"
    "scePadEnableUsbConnection:\n"
    "jmp qword ptr [rip + __ptr_scePadEnableUsbConnection]\n");

static __attribute__ ((used)) void* __ptr_scePadGetActiveTime;
asm(".intel_syntax noprefix\n"
    ".global scePadGetActiveTime\n"
    ".type scePadGetActiveTime @function\n"
    "scePadGetActiveTime:\n"
    "jmp qword ptr [rip + __ptr_scePadGetActiveTime]\n");

static __attribute__ ((used)) void* __ptr_scePadGetBluetoothAddress;
asm(".intel_syntax noprefix\n"
    ".global scePadGetBluetoothAddress\n"
    ".type scePadGetBluetoothAddress @function\n"
    "scePadGetBluetoothAddress:\n"
    "jmp qword ptr [rip + __ptr_scePadGetBluetoothAddress]\n");

static __attribute__ ((used)) void* __ptr_scePadGetCapability;
asm(".intel_syntax noprefix\n"
    ".global scePadGetCapability\n"
    ".type scePadGetCapability @function\n"
    "scePadGetCapability:\n"
    "jmp qword ptr [rip + __ptr_scePadGetCapability]\n");

static __attribute__ ((used)) void* __ptr_scePadGetControllerInformation;
asm(".intel_syntax noprefix\n"
    ".global scePadGetControllerInformation\n"
    ".type scePadGetControllerInformation @function\n"
    "scePadGetControllerInformation:\n"
    "jmp qword ptr [rip + __ptr_scePadGetControllerInformation]\n");

static __attribute__ ((used)) void* __ptr_scePadGetDataInternal;
asm(".intel_syntax noprefix\n"
    ".global scePadGetDataInternal\n"
    ".type scePadGetDataInternal @function\n"
    "scePadGetDataInternal:\n"
    "jmp qword ptr [rip + __ptr_scePadGetDataInternal]\n");

static __attribute__ ((used)) void* __ptr_scePadGetDeviceId;
asm(".intel_syntax noprefix\n"
    ".global scePadGetDeviceId\n"
    ".type scePadGetDeviceId @function\n"
    "scePadGetDeviceId:\n"
    "jmp qword ptr [rip + __ptr_scePadGetDeviceId]\n");

static __attribute__ ((used)) void* __ptr_scePadGetDeviceInfo;
asm(".intel_syntax noprefix\n"
    ".global scePadGetDeviceInfo\n"
    ".type scePadGetDeviceInfo @function\n"
    "scePadGetDeviceInfo:\n"
    "jmp qword ptr [rip + __ptr_scePadGetDeviceInfo]\n");

static __attribute__ ((used)) void* __ptr_scePadGetExtControllerInformation;
asm(".intel_syntax noprefix\n"
    ".global scePadGetExtControllerInformation\n"
    ".type scePadGetExtControllerInformation @function\n"
    "scePadGetExtControllerInformation:\n"
    "jmp qword ptr [rip + __ptr_scePadGetExtControllerInformation]\n");

static __attribute__ ((used)) void* __ptr_scePadGetExtensionUnitInfo;
asm(".intel_syntax noprefix\n"
    ".global scePadGetExtensionUnitInfo\n"
    ".type scePadGetExtensionUnitInfo @function\n"
    "scePadGetExtensionUnitInfo:\n"
    "jmp qword ptr [rip + __ptr_scePadGetExtensionUnitInfo]\n");

static __attribute__ ((used)) void* __ptr_scePadGetFeatureReport;
asm(".intel_syntax noprefix\n"
    ".global scePadGetFeatureReport\n"
    ".type scePadGetFeatureReport @function\n"
    "scePadGetFeatureReport:\n"
    "jmp qword ptr [rip + __ptr_scePadGetFeatureReport]\n");

static __attribute__ ((used)) void* __ptr_scePadGetFeatureReport2;
asm(".intel_syntax noprefix\n"
    ".global scePadGetFeatureReport2\n"
    ".type scePadGetFeatureReport2 @function\n"
    "scePadGetFeatureReport2:\n"
    "jmp qword ptr [rip + __ptr_scePadGetFeatureReport2]\n");

static __attribute__ ((used)) void* __ptr_scePadGetHandle;
asm(".intel_syntax noprefix\n"
    ".global scePadGetHandle\n"
    ".type scePadGetHandle @function\n"
    "scePadGetHandle:\n"
    "jmp qword ptr [rip + __ptr_scePadGetHandle]\n");

static __attribute__ ((used)) void* __ptr_scePadGetIdleCount;
asm(".intel_syntax noprefix\n"
    ".global scePadGetIdleCount\n"
    ".type scePadGetIdleCount @function\n"
    "scePadGetIdleCount:\n"
    "jmp qword ptr [rip + __ptr_scePadGetIdleCount]\n");

static __attribute__ ((used)) void* __ptr_scePadGetInfo;
asm(".intel_syntax noprefix\n"
    ".global scePadGetInfo\n"
    ".type scePadGetInfo @function\n"
    "scePadGetInfo:\n"
    "jmp qword ptr [rip + __ptr_scePadGetInfo]\n");

static __attribute__ ((used)) void* __ptr_scePadGetInfoByPortType;
asm(".intel_syntax noprefix\n"
    ".global scePadGetInfoByPortType\n"
    ".type scePadGetInfoByPortType @function\n"
    "scePadGetInfoByPortType:\n"
    "jmp qword ptr [rip + __ptr_scePadGetInfoByPortType]\n");

static __attribute__ ((used)) void* __ptr_scePadGetLicenseControllerInformation;
asm(".intel_syntax noprefix\n"
    ".global scePadGetLicenseControllerInformation\n"
    ".type scePadGetLicenseControllerInformation @function\n"
    "scePadGetLicenseControllerInformation:\n"
    "jmp qword ptr [rip + __ptr_scePadGetLicenseControllerInformation]\n");

static __attribute__ ((used)) void* __ptr_scePadGetMotionSensorPosition;
asm(".intel_syntax noprefix\n"
    ".global scePadGetMotionSensorPosition\n"
    ".type scePadGetMotionSensorPosition @function\n"
    "scePadGetMotionSensorPosition:\n"
    "jmp qword ptr [rip + __ptr_scePadGetMotionSensorPosition]\n");

static __attribute__ ((used)) void* __ptr_scePadGetMotionTimerUnit;
asm(".intel_syntax noprefix\n"
    ".global scePadGetMotionTimerUnit\n"
    ".type scePadGetMotionTimerUnit @function\n"
    "scePadGetMotionTimerUnit:\n"
    "jmp qword ptr [rip + __ptr_scePadGetMotionTimerUnit]\n");

static __attribute__ ((used)) void* __ptr_scePadGetSphereRadius;
asm(".intel_syntax noprefix\n"
    ".global scePadGetSphereRadius\n"
    ".type scePadGetSphereRadius @function\n"
    "scePadGetSphereRadius:\n"
    "jmp qword ptr [rip + __ptr_scePadGetSphereRadius]\n");

static __attribute__ ((used)) void* __ptr_scePadGetTriggerEffectState;
asm(".intel_syntax noprefix\n"
    ".global scePadGetTriggerEffectState\n"
    ".type scePadGetTriggerEffectState @function\n"
    "scePadGetTriggerEffectState:\n"
    "jmp qword ptr [rip + __ptr_scePadGetTriggerEffectState]\n");

static __attribute__ ((used)) void* __ptr_scePadGetVersionInfo;
asm(".intel_syntax noprefix\n"
    ".global scePadGetVersionInfo\n"
    ".type scePadGetVersionInfo @function\n"
    "scePadGetVersionInfo:\n"
    "jmp qword ptr [rip + __ptr_scePadGetVersionInfo]\n");

static __attribute__ ((used)) void* __ptr_scePadInit;
asm(".intel_syntax noprefix\n"
    ".global scePadInit\n"
    ".type scePadInit @function\n"
    "scePadInit:\n"
    "jmp qword ptr [rip + __ptr_scePadInit]\n");

static __attribute__ ((used)) void* __ptr_scePadIsBlasterConnected;
asm(".intel_syntax noprefix\n"
    ".global scePadIsBlasterConnected\n"
    ".type scePadIsBlasterConnected @function\n"
    "scePadIsBlasterConnected:\n"
    "jmp qword ptr [rip + __ptr_scePadIsBlasterConnected]\n");

static __attribute__ ((used)) void* __ptr_scePadIsDS4Connected;
asm(".intel_syntax noprefix\n"
    ".global scePadIsDS4Connected\n"
    ".type scePadIsDS4Connected @function\n"
    "scePadIsDS4Connected:\n"
    "jmp qword ptr [rip + __ptr_scePadIsDS4Connected]\n");

static __attribute__ ((used)) void* __ptr_scePadIsLightBarBaseBrightnessControllable;
asm(".intel_syntax noprefix\n"
    ".global scePadIsLightBarBaseBrightnessControllable\n"
    ".type scePadIsLightBarBaseBrightnessControllable @function\n"
    "scePadIsLightBarBaseBrightnessControllable:\n"
    "jmp qword ptr [rip + __ptr_scePadIsLightBarBaseBrightnessControllable]\n");

static __attribute__ ((used)) void* __ptr_scePadIsMoveConnected;
asm(".intel_syntax noprefix\n"
    ".global scePadIsMoveConnected\n"
    ".type scePadIsMoveConnected @function\n"
    "scePadIsMoveConnected:\n"
    "jmp qword ptr [rip + __ptr_scePadIsMoveConnected]\n");

static __attribute__ ((used)) void* __ptr_scePadIsMoveReproductionModel;
asm(".intel_syntax noprefix\n"
    ".global scePadIsMoveReproductionModel\n"
    ".type scePadIsMoveReproductionModel @function\n"
    "scePadIsMoveReproductionModel:\n"
    "jmp qword ptr [rip + __ptr_scePadIsMoveReproductionModel]\n");

static __attribute__ ((used)) void* __ptr_scePadIsValidHandle;
asm(".intel_syntax noprefix\n"
    ".global scePadIsValidHandle\n"
    ".type scePadIsValidHandle @function\n"
    "scePadIsValidHandle:\n"
    "jmp qword ptr [rip + __ptr_scePadIsValidHandle]\n");

static __attribute__ ((used)) void* __ptr_scePadLastLotusButtonData;
asm(".intel_syntax noprefix\n"
    ".global scePadLastLotusButtonData\n"
    ".type scePadLastLotusButtonData @function\n"
    "scePadLastLotusButtonData:\n"
    "jmp qword ptr [rip + __ptr_scePadLastLotusButtonData]\n");

static __attribute__ ((used)) void* __ptr_scePadMbusInit;
asm(".intel_syntax noprefix\n"
    ".global scePadMbusInit\n"
    ".type scePadMbusInit @function\n"
    "scePadMbusInit:\n"
    "jmp qword ptr [rip + __ptr_scePadMbusInit]\n");

static __attribute__ ((used)) void* __ptr_scePadMbusTerm;
asm(".intel_syntax noprefix\n"
    ".global scePadMbusTerm\n"
    ".type scePadMbusTerm @function\n"
    "scePadMbusTerm:\n"
    "jmp qword ptr [rip + __ptr_scePadMbusTerm]\n");

static __attribute__ ((used)) void* __ptr_scePadOpen;
asm(".intel_syntax noprefix\n"
    ".global scePadOpen\n"
    ".type scePadOpen @function\n"
    "scePadOpen:\n"
    "jmp qword ptr [rip + __ptr_scePadOpen]\n");

static __attribute__ ((used)) void* __ptr_scePadOpenExt;
asm(".intel_syntax noprefix\n"
    ".global scePadOpenExt\n"
    ".type scePadOpenExt @function\n"
    "scePadOpenExt:\n"
    "jmp qword ptr [rip + __ptr_scePadOpenExt]\n");

static __attribute__ ((used)) void* __ptr_scePadOpenExt2;
asm(".intel_syntax noprefix\n"
    ".global scePadOpenExt2\n"
    ".type scePadOpenExt2 @function\n"
    "scePadOpenExt2:\n"
    "jmp qword ptr [rip + __ptr_scePadOpenExt2]\n");

static __attribute__ ((used)) void* __ptr_scePadOutputReport;
asm(".intel_syntax noprefix\n"
    ".global scePadOutputReport\n"
    ".type scePadOutputReport @function\n"
    "scePadOutputReport:\n"
    "jmp qword ptr [rip + __ptr_scePadOutputReport]\n");

static __attribute__ ((used)) void* __ptr_scePadRead;
asm(".intel_syntax noprefix\n"
    ".global scePadRead\n"
    ".type scePadRead @function\n"
    "scePadRead:\n"
    "jmp qword ptr [rip + __ptr_scePadRead]\n");

static __attribute__ ((used)) void* __ptr_scePadReadBlasterForTracker;
asm(".intel_syntax noprefix\n"
    ".global scePadReadBlasterForTracker\n"
    ".type scePadReadBlasterForTracker @function\n"
    "scePadReadBlasterForTracker:\n"
    "jmp qword ptr [rip + __ptr_scePadReadBlasterForTracker]\n");

static __attribute__ ((used)) void* __ptr_scePadReadExt;
asm(".intel_syntax noprefix\n"
    ".global scePadReadExt\n"
    ".type scePadReadExt @function\n"
    "scePadReadExt:\n"
    "jmp qword ptr [rip + __ptr_scePadReadExt]\n");

static __attribute__ ((used)) void* __ptr_scePadReadForTracker;
asm(".intel_syntax noprefix\n"
    ".global scePadReadForTracker\n"
    ".type scePadReadForTracker @function\n"
    "scePadReadForTracker:\n"
    "jmp qword ptr [rip + __ptr_scePadReadForTracker]\n");

static __attribute__ ((used)) void* __ptr_scePadReadHistory;
asm(".intel_syntax noprefix\n"
    ".global scePadReadHistory\n"
    ".type scePadReadHistory @function\n"
    "scePadReadHistory:\n"
    "jmp qword ptr [rip + __ptr_scePadReadHistory]\n");

static __attribute__ ((used)) void* __ptr_scePadReadState;
asm(".intel_syntax noprefix\n"
    ".global scePadReadState\n"
    ".type scePadReadState @function\n"
    "scePadReadState:\n"
    "jmp qword ptr [rip + __ptr_scePadReadState]\n");

static __attribute__ ((used)) void* __ptr_scePadReadStateExt;
asm(".intel_syntax noprefix\n"
    ".global scePadReadStateExt\n"
    ".type scePadReadStateExt @function\n"
    "scePadReadStateExt:\n"
    "jmp qword ptr [rip + __ptr_scePadReadStateExt]\n");

static __attribute__ ((used)) void* __ptr_scePadRemoteControlInsertData;
asm(".intel_syntax noprefix\n"
    ".global scePadRemoteControlInsertData\n"
    ".type scePadRemoteControlInsertData @function\n"
    "scePadRemoteControlInsertData:\n"
    "jmp qword ptr [rip + __ptr_scePadRemoteControlInsertData]\n");

static __attribute__ ((used)) void* __ptr_scePadResetLightBar;
asm(".intel_syntax noprefix\n"
    ".global scePadResetLightBar\n"
    ".type scePadResetLightBar @function\n"
    "scePadResetLightBar:\n"
    "jmp qword ptr [rip + __ptr_scePadResetLightBar]\n");

static __attribute__ ((used)) void* __ptr_scePadResetLightBarAll;
asm(".intel_syntax noprefix\n"
    ".global scePadResetLightBarAll\n"
    ".type scePadResetLightBarAll @function\n"
    "scePadResetLightBarAll:\n"
    "jmp qword ptr [rip + __ptr_scePadResetLightBarAll]\n");

static __attribute__ ((used)) void* __ptr_scePadResetLightBarAllByPortType;
asm(".intel_syntax noprefix\n"
    ".global scePadResetLightBarAllByPortType\n"
    ".type scePadResetLightBarAllByPortType @function\n"
    "scePadResetLightBarAllByPortType:\n"
    "jmp qword ptr [rip + __ptr_scePadResetLightBarAllByPortType]\n");

static __attribute__ ((used)) void* __ptr_scePadResetOrientation;
asm(".intel_syntax noprefix\n"
    ".global scePadResetOrientation\n"
    ".type scePadResetOrientation @function\n"
    "scePadResetOrientation:\n"
    "jmp qword ptr [rip + __ptr_scePadResetOrientation]\n");

static __attribute__ ((used)) void* __ptr_scePadResetOrientationForTracker;
asm(".intel_syntax noprefix\n"
    ".global scePadResetOrientationForTracker\n"
    ".type scePadResetOrientationForTracker @function\n"
    "scePadResetOrientationForTracker:\n"
    "jmp qword ptr [rip + __ptr_scePadResetOrientationForTracker]\n");

static __attribute__ ((used)) void* __ptr_scePadSetAngularVelocityDeadbandState;
asm(".intel_syntax noprefix\n"
    ".global scePadSetAngularVelocityDeadbandState\n"
    ".type scePadSetAngularVelocityDeadbandState @function\n"
    "scePadSetAngularVelocityDeadbandState:\n"
    "jmp qword ptr [rip + __ptr_scePadSetAngularVelocityDeadbandState]\n");

static __attribute__ ((used)) void* __ptr_scePadSetAutoPowerOffCount;
asm(".intel_syntax noprefix\n"
    ".global scePadSetAutoPowerOffCount\n"
    ".type scePadSetAutoPowerOffCount @function\n"
    "scePadSetAutoPowerOffCount:\n"
    "jmp qword ptr [rip + __ptr_scePadSetAutoPowerOffCount]\n");

static __attribute__ ((used)) void* __ptr_scePadSetButtonRemappingInfo;
asm(".intel_syntax noprefix\n"
    ".global scePadSetButtonRemappingInfo\n"
    ".type scePadSetButtonRemappingInfo @function\n"
    "scePadSetButtonRemappingInfo:\n"
    "jmp qword ptr [rip + __ptr_scePadSetButtonRemappingInfo]\n");

static __attribute__ ((used)) void* __ptr_scePadSetExtensionReport;
asm(".intel_syntax noprefix\n"
    ".global scePadSetExtensionReport\n"
    ".type scePadSetExtensionReport @function\n"
    "scePadSetExtensionReport:\n"
    "jmp qword ptr [rip + __ptr_scePadSetExtensionReport]\n");

static __attribute__ ((used)) void* __ptr_scePadSetFeatureReport;
asm(".intel_syntax noprefix\n"
    ".global scePadSetFeatureReport\n"
    ".type scePadSetFeatureReport @function\n"
    "scePadSetFeatureReport:\n"
    "jmp qword ptr [rip + __ptr_scePadSetFeatureReport]\n");

static __attribute__ ((used)) void* __ptr_scePadSetFeatureReport2;
asm(".intel_syntax noprefix\n"
    ".global scePadSetFeatureReport2\n"
    ".type scePadSetFeatureReport2 @function\n"
    "scePadSetFeatureReport2:\n"
    "jmp qword ptr [rip + __ptr_scePadSetFeatureReport2]\n");

static __attribute__ ((used)) void* __ptr_scePadSetForceIntercepted;
asm(".intel_syntax noprefix\n"
    ".global scePadSetForceIntercepted\n"
    ".type scePadSetForceIntercepted @function\n"
    "scePadSetForceIntercepted:\n"
    "jmp qword ptr [rip + __ptr_scePadSetForceIntercepted]\n");

static __attribute__ ((used)) void* __ptr_scePadSetLightBar;
asm(".intel_syntax noprefix\n"
    ".global scePadSetLightBar\n"
    ".type scePadSetLightBar @function\n"
    "scePadSetLightBar:\n"
    "jmp qword ptr [rip + __ptr_scePadSetLightBar]\n");

static __attribute__ ((used)) void* __ptr_scePadSetLightBarBaseBrightness;
asm(".intel_syntax noprefix\n"
    ".global scePadSetLightBarBaseBrightness\n"
    ".type scePadSetLightBarBaseBrightness @function\n"
    "scePadSetLightBarBaseBrightness:\n"
    "jmp qword ptr [rip + __ptr_scePadSetLightBarBaseBrightness]\n");

static __attribute__ ((used)) void* __ptr_scePadSetLightBarBlinking;
asm(".intel_syntax noprefix\n"
    ".global scePadSetLightBarBlinking\n"
    ".type scePadSetLightBarBlinking @function\n"
    "scePadSetLightBarBlinking:\n"
    "jmp qword ptr [rip + __ptr_scePadSetLightBarBlinking]\n");

static __attribute__ ((used)) void* __ptr_scePadSetLightBarForTracker;
asm(".intel_syntax noprefix\n"
    ".global scePadSetLightBarForTracker\n"
    ".type scePadSetLightBarForTracker @function\n"
    "scePadSetLightBarForTracker:\n"
    "jmp qword ptr [rip + __ptr_scePadSetLightBarForTracker]\n");

static __attribute__ ((used)) void* __ptr_scePadSetLoginUserNumber;
asm(".intel_syntax noprefix\n"
    ".global scePadSetLoginUserNumber\n"
    ".type scePadSetLoginUserNumber @function\n"
    "scePadSetLoginUserNumber:\n"
    "jmp qword ptr [rip + __ptr_scePadSetLoginUserNumber]\n");

static __attribute__ ((used)) void* __ptr_scePadSetMotionSensorState;
asm(".intel_syntax noprefix\n"
    ".global scePadSetMotionSensorState\n"
    ".type scePadSetMotionSensorState @function\n"
    "scePadSetMotionSensorState:\n"
    "jmp qword ptr [rip + __ptr_scePadSetMotionSensorState]\n");

static __attribute__ ((used)) void* __ptr_scePadSetProcessFocus;
asm(".intel_syntax noprefix\n"
    ".global scePadSetProcessFocus\n"
    ".type scePadSetProcessFocus @function\n"
    "scePadSetProcessFocus:\n"
    "jmp qword ptr [rip + __ptr_scePadSetProcessFocus]\n");

static __attribute__ ((used)) void* __ptr_scePadSetProcessPrivilege;
asm(".intel_syntax noprefix\n"
    ".global scePadSetProcessPrivilege\n"
    ".type scePadSetProcessPrivilege @function\n"
    "scePadSetProcessPrivilege:\n"
    "jmp qword ptr [rip + __ptr_scePadSetProcessPrivilege]\n");

static __attribute__ ((used)) void* __ptr_scePadSetProcessPrivilegeOfButtonRemapping;
asm(".intel_syntax noprefix\n"
    ".global scePadSetProcessPrivilegeOfButtonRemapping\n"
    ".type scePadSetProcessPrivilegeOfButtonRemapping @function\n"
    "scePadSetProcessPrivilegeOfButtonRemapping:\n"
    "jmp qword ptr [rip + __ptr_scePadSetProcessPrivilegeOfButtonRemapping]\n");

static __attribute__ ((used)) void* __ptr_scePadSetShareButtonMaskForRemotePlay;
asm(".intel_syntax noprefix\n"
    ".global scePadSetShareButtonMaskForRemotePlay\n"
    ".type scePadSetShareButtonMaskForRemotePlay @function\n"
    "scePadSetShareButtonMaskForRemotePlay:\n"
    "jmp qword ptr [rip + __ptr_scePadSetShareButtonMaskForRemotePlay]\n");

static __attribute__ ((used)) void* __ptr_scePadSetTiltCorrectionState;
asm(".intel_syntax noprefix\n"
    ".global scePadSetTiltCorrectionState\n"
    ".type scePadSetTiltCorrectionState @function\n"
    "scePadSetTiltCorrectionState:\n"
    "jmp qword ptr [rip + __ptr_scePadSetTiltCorrectionState]\n");

static __attribute__ ((used)) void* __ptr_scePadSetTriggerEffect;
asm(".intel_syntax noprefix\n"
    ".global scePadSetTriggerEffect\n"
    ".type scePadSetTriggerEffect @function\n"
    "scePadSetTriggerEffect:\n"
    "jmp qword ptr [rip + __ptr_scePadSetTriggerEffect]\n");

static __attribute__ ((used)) void* __ptr_scePadSetUserColor;
asm(".intel_syntax noprefix\n"
    ".global scePadSetUserColor\n"
    ".type scePadSetUserColor @function\n"
    "scePadSetUserColor:\n"
    "jmp qword ptr [rip + __ptr_scePadSetUserColor]\n");

static __attribute__ ((used)) void* __ptr_scePadSetUserNumber;
asm(".intel_syntax noprefix\n"
    ".global scePadSetUserNumber\n"
    ".type scePadSetUserNumber @function\n"
    "scePadSetUserNumber:\n"
    "jmp qword ptr [rip + __ptr_scePadSetUserNumber]\n");

static __attribute__ ((used)) void* __ptr_scePadSetVibration;
asm(".intel_syntax noprefix\n"
    ".global scePadSetVibration\n"
    ".type scePadSetVibration @function\n"
    "scePadSetVibration:\n"
    "jmp qword ptr [rip + __ptr_scePadSetVibration]\n");

static __attribute__ ((used)) void* __ptr_scePadSetVibrationForce;
asm(".intel_syntax noprefix\n"
    ".global scePadSetVibrationForce\n"
    ".type scePadSetVibrationForce @function\n"
    "scePadSetVibrationForce:\n"
    "jmp qword ptr [rip + __ptr_scePadSetVibrationForce]\n");

static __attribute__ ((used)) void* __ptr_scePadSetVibrationMode;
asm(".intel_syntax noprefix\n"
    ".global scePadSetVibrationMode\n"
    ".type scePadSetVibrationMode @function\n"
    "scePadSetVibrationMode:\n"
    "jmp qword ptr [rip + __ptr_scePadSetVibrationMode]\n");

static __attribute__ ((used)) void* __ptr_scePadSetVibrationTriggerEffectWeakWhileEmbeddedMicInUse;
asm(".intel_syntax noprefix\n"
    ".global scePadSetVibrationTriggerEffectWeakWhileEmbeddedMicInUse\n"
    ".type scePadSetVibrationTriggerEffectWeakWhileEmbeddedMicInUse @function\n"
    "scePadSetVibrationTriggerEffectWeakWhileEmbeddedMicInUse:\n"
    "jmp qword ptr [rip + __ptr_scePadSetVibrationTriggerEffectWeakWhileEmbeddedMicInUse]\n");

static __attribute__ ((used)) void* __ptr_scePadSetVrTrackingMode;
asm(".intel_syntax noprefix\n"
    ".global scePadSetVrTrackingMode\n"
    ".type scePadSetVrTrackingMode @function\n"
    "scePadSetVrTrackingMode:\n"
    "jmp qword ptr [rip + __ptr_scePadSetVrTrackingMode]\n");

static __attribute__ ((used)) void* __ptr_scePadShareOutputData;
asm(".intel_syntax noprefix\n"
    ".global scePadShareOutputData\n"
    ".type scePadShareOutputData @function\n"
    "scePadShareOutputData:\n"
    "jmp qword ptr [rip + __ptr_scePadShareOutputData]\n");

static __attribute__ ((used)) void* __ptr_scePadStartRecording;
asm(".intel_syntax noprefix\n"
    ".global scePadStartRecording\n"
    ".type scePadStartRecording @function\n"
    "scePadStartRecording:\n"
    "jmp qword ptr [rip + __ptr_scePadStartRecording]\n");

static __attribute__ ((used)) void* __ptr_scePadStopRecording;
asm(".intel_syntax noprefix\n"
    ".global scePadStopRecording\n"
    ".type scePadStopRecording @function\n"
    "scePadStopRecording:\n"
    "jmp qword ptr [rip + __ptr_scePadStopRecording]\n");

static __attribute__ ((used)) void* __ptr_scePadSwitchConnection;
asm(".intel_syntax noprefix\n"
    ".global scePadSwitchConnection\n"
    ".type scePadSwitchConnection @function\n"
    "scePadSwitchConnection:\n"
    "jmp qword ptr [rip + __ptr_scePadSwitchConnection]\n");

static __attribute__ ((used)) void* __ptr_scePadVertualDeviceAddDevice;
asm(".intel_syntax noprefix\n"
    ".global scePadVertualDeviceAddDevice\n"
    ".type scePadVertualDeviceAddDevice @function\n"
    "scePadVertualDeviceAddDevice:\n"
    "jmp qword ptr [rip + __ptr_scePadVertualDeviceAddDevice]\n");

static __attribute__ ((used)) void* __ptr_scePadVirtualDeviceAddDevice;
asm(".intel_syntax noprefix\n"
    ".global scePadVirtualDeviceAddDevice\n"
    ".type scePadVirtualDeviceAddDevice @function\n"
    "scePadVirtualDeviceAddDevice:\n"
    "jmp qword ptr [rip + __ptr_scePadVirtualDeviceAddDevice]\n");

static __attribute__ ((used)) void* __ptr_scePadVirtualDeviceDeleteDevice;
asm(".intel_syntax noprefix\n"
    ".global scePadVirtualDeviceDeleteDevice\n"
    ".type scePadVirtualDeviceDeleteDevice @function\n"
    "scePadVirtualDeviceDeleteDevice:\n"
    "jmp qword ptr [rip + __ptr_scePadVirtualDeviceDeleteDevice]\n");

static __attribute__ ((used)) void* __ptr_scePadVirtualDeviceDisableButtonRemapping;
asm(".intel_syntax noprefix\n"
    ".global scePadVirtualDeviceDisableButtonRemapping\n"
    ".type scePadVirtualDeviceDisableButtonRemapping @function\n"
    "scePadVirtualDeviceDisableButtonRemapping:\n"
    "jmp qword ptr [rip + __ptr_scePadVirtualDeviceDisableButtonRemapping]\n");

static __attribute__ ((used)) void* __ptr_scePadVirtualDeviceGetRemoteSetting;
asm(".intel_syntax noprefix\n"
    ".global scePadVirtualDeviceGetRemoteSetting\n"
    ".type scePadVirtualDeviceGetRemoteSetting @function\n"
    "scePadVirtualDeviceGetRemoteSetting:\n"
    "jmp qword ptr [rip + __ptr_scePadVirtualDeviceGetRemoteSetting]\n");

static __attribute__ ((used)) void* __ptr_scePadVirtualDeviceInsertData;
asm(".intel_syntax noprefix\n"
    ".global scePadVirtualDeviceInsertData\n"
    ".type scePadVirtualDeviceInsertData @function\n"
    "scePadVirtualDeviceInsertData:\n"
    "jmp qword ptr [rip + __ptr_scePadVirtualDeviceInsertData]\n");

static __attribute__ ((used)) void* __ptr_scePadVrControllerGetDeviceInformation;
asm(".intel_syntax noprefix\n"
    ".global scePadVrControllerGetDeviceInformation\n"
    ".type scePadVrControllerGetDeviceInformation @function\n"
    "scePadVrControllerGetDeviceInformation:\n"
    "jmp qword ptr [rip + __ptr_scePadVrControllerGetDeviceInformation]\n");

static __attribute__ ((used)) void* __ptr_scePadVrControllerRead;
asm(".intel_syntax noprefix\n"
    ".global scePadVrControllerRead\n"
    ".type scePadVrControllerRead @function\n"
    "scePadVrControllerRead:\n"
    "jmp qword ptr [rip + __ptr_scePadVrControllerRead]\n");

static __attribute__ ((used)) void* __ptr_scePadVrControllerReadState;
asm(".intel_syntax noprefix\n"
    ".global scePadVrControllerReadState\n"
    ".type scePadVrControllerReadState @function\n"
    "scePadVrControllerReadState:\n"
    "jmp qword ptr [rip + __ptr_scePadVrControllerReadState]\n");

static unsigned short __handle = 0;
static void __attribute__((constructor(104)))
__constructor(void) {
  if(sprx_dlopen("libScePad", &__handle)) return;
  if(sprx_dlsym(__handle, "6ncge5+l5Qs", &__ptr_scePadClose)) return;
  if(sprx_dlsym(__handle, "kazv1NzSB8c", &__ptr_scePadConnectPort)) return;
  if(sprx_dlsym(__handle, "AcslpN1jHR8", &__ptr_scePadDeviceClassGetExtendedInformation)) return;
  if(sprx_dlsym(__handle, "IHPqcbc0zCA", &__ptr_scePadDeviceClassParseData)) return;
  if(sprx_dlsym(__handle, "d7bXuEBycDI", &__ptr_scePadDeviceOpen)) return;
  if(sprx_dlsym(__handle, "OjTEJo7cfRE", &__ptr_scePadDisableTriggerEffect)) return;
  if(sprx_dlsym(__handle, "0aziJjRZxqQ", &__ptr_scePadDisableVibration)) return;
  if(sprx_dlsym(__handle, "pnZXireDoeI", &__ptr_scePadDisconnectDevice)) return;
  if(sprx_dlsym(__handle, "9ez71nWSvD0", &__ptr_scePadDisconnectPort)) return;
  if(sprx_dlsym(__handle, "77ooWxGOIVs", &__ptr_scePadEnableAutoDetect)) return;
  if(sprx_dlsym(__handle, "+cE4Jx431wc", &__ptr_scePadEnableExtensionPort)) return;
  if(sprx_dlsym(__handle, "E1KEw5XMGQQ", &__ptr_scePadEnableSpecificDeviceClass)) return;
  if(sprx_dlsym(__handle, "DD-KiRLBqkQ", &__ptr_scePadEnableUsbConnection)) return;
  if(sprx_dlsym(__handle, "k0RJXTO3SbQ", &__ptr_scePadGetActiveTime)) return;
  if(sprx_dlsym(__handle, "Q66U8FdrMaw", &__ptr_scePadGetBluetoothAddress)) return;
  if(sprx_dlsym(__handle, "qtasqbvwgV4", &__ptr_scePadGetCapability)) return;
  if(sprx_dlsym(__handle, "gjP9-KQzoUk", &__ptr_scePadGetControllerInformation)) return;
  if(sprx_dlsym(__handle, "Uq6LgTJEmQs", &__ptr_scePadGetDataInternal)) return;
  if(sprx_dlsym(__handle, "hDgisSGkOgw", &__ptr_scePadGetDeviceId)) return;
  if(sprx_dlsym(__handle, "4rS5zG7RFaM", &__ptr_scePadGetDeviceInfo)) return;
  if(sprx_dlsym(__handle, "hGbf2QTBmqc", &__ptr_scePadGetExtControllerInformation)) return;
  if(sprx_dlsym(__handle, "1DmZjZAuzEM", &__ptr_scePadGetExtensionUnitInfo)) return;
  if(sprx_dlsym(__handle, "PZSoY8j0Pko", &__ptr_scePadGetFeatureReport)) return;
  if(sprx_dlsym(__handle, "B36fgKhpfUE", &__ptr_scePadGetFeatureReport2)) return;
  if(sprx_dlsym(__handle, "u1GRHp+oWoY", &__ptr_scePadGetHandle)) return;
  if(sprx_dlsym(__handle, "kiA9bZhbnAg", &__ptr_scePadGetIdleCount)) return;
  if(sprx_dlsym(__handle, "1Odcw19nADw", &__ptr_scePadGetInfo)) return;
  if(sprx_dlsym(__handle, "4x5Im8pr0-4", &__ptr_scePadGetInfoByPortType)) return;
  if(sprx_dlsym(__handle, "vegw8qax5MI", &__ptr_scePadGetLicenseControllerInformation)) return;
  if(sprx_dlsym(__handle, "WPIB7zBWxVE", &__ptr_scePadGetMotionSensorPosition)) return;
  if(sprx_dlsym(__handle, "k4+nDV9vbT0", &__ptr_scePadGetMotionTimerUnit)) return;
  if(sprx_dlsym(__handle, "do-JDWX+zRs", &__ptr_scePadGetSphereRadius)) return;
  if(sprx_dlsym(__handle, "znaWI0gpuo8", &__ptr_scePadGetTriggerEffectState)) return;
  if(sprx_dlsym(__handle, "QuOaoOcSOw0", &__ptr_scePadGetVersionInfo)) return;
  if(sprx_dlsym(__handle, "hv1luiJrqQM", &__ptr_scePadInit)) return;
  if(sprx_dlsym(__handle, "bi0WNvZ1nug", &__ptr_scePadIsBlasterConnected)) return;
  if(sprx_dlsym(__handle, "mEC+xJKyIjQ", &__ptr_scePadIsDS4Connected)) return;
  if(sprx_dlsym(__handle, "d2Qk-i8wGak", &__ptr_scePadIsLightBarBaseBrightnessControllable)) return;
  if(sprx_dlsym(__handle, "4y9RNPSBsqg", &__ptr_scePadIsMoveConnected)) return;
  if(sprx_dlsym(__handle, "9e56uLgk5y0", &__ptr_scePadIsMoveReproductionModel)) return;
  if(sprx_dlsym(__handle, "pFTi-yOrVeQ", &__ptr_scePadIsValidHandle)) return;
  if(sprx_dlsym(__handle, "F9iDGS9ddCM", &__ptr_scePadLastLotusButtonData)) return;
  if(sprx_dlsym(__handle, "CfwUlQtCFi4", &__ptr_scePadMbusInit)) return;
  if(sprx_dlsym(__handle, "s7CvzS+9ZIs", &__ptr_scePadMbusTerm)) return;
  if(sprx_dlsym(__handle, "xk0AcarP3V4", &__ptr_scePadOpen)) return;
  if(sprx_dlsym(__handle, "WFIiSfXGUq8", &__ptr_scePadOpenExt)) return;
  if(sprx_dlsym(__handle, "71E9e6n+2R8", &__ptr_scePadOpenExt2)) return;
  if(sprx_dlsym(__handle, "DrUu8cPrje8", &__ptr_scePadOutputReport)) return;
  if(sprx_dlsym(__handle, "q1cHNfGycLI", &__ptr_scePadRead)) return;
  if(sprx_dlsym(__handle, "fm1r2vv5+OU", &__ptr_scePadReadBlasterForTracker)) return;
  if(sprx_dlsym(__handle, "QjwkT2Ycmew", &__ptr_scePadReadExt)) return;
  if(sprx_dlsym(__handle, "2NhkFTRnXHk", &__ptr_scePadReadForTracker)) return;
  if(sprx_dlsym(__handle, "3u4M8ck9vJM", &__ptr_scePadReadHistory)) return;
  if(sprx_dlsym(__handle, "YndgXqQVV7c", &__ptr_scePadReadState)) return;
  if(sprx_dlsym(__handle, "5Wf4q349s+Q", &__ptr_scePadReadStateExt)) return;
  if(sprx_dlsym(__handle, "D6ovvSecedE", &__ptr_scePadRemoteControlInsertData)) return;
  if(sprx_dlsym(__handle, "DscD1i9HX1w", &__ptr_scePadResetLightBar)) return;
  if(sprx_dlsym(__handle, "+4c9xRLmiXQ", &__ptr_scePadResetLightBarAll)) return;
  if(sprx_dlsym(__handle, "+Yp6+orqf1M", &__ptr_scePadResetLightBarAllByPortType)) return;
  if(sprx_dlsym(__handle, "rIZnR6eSpvk", &__ptr_scePadResetOrientation)) return;
  if(sprx_dlsym(__handle, "jbAqAvLEP4A", &__ptr_scePadResetOrientationForTracker)) return;
  if(sprx_dlsym(__handle, "r44mAxdSG+U", &__ptr_scePadSetAngularVelocityDeadbandState)) return;
  if(sprx_dlsym(__handle, "ew647HuKi2Y", &__ptr_scePadSetAutoPowerOffCount)) return;
  if(sprx_dlsym(__handle, "MbTt1EHYCTg", &__ptr_scePadSetButtonRemappingInfo)) return;
  if(sprx_dlsym(__handle, "bsbHFI0bl5s", &__ptr_scePadSetExtensionReport)) return;
  if(sprx_dlsym(__handle, "xqgVCEflEDY", &__ptr_scePadSetFeatureReport)) return;
  if(sprx_dlsym(__handle, "PNceMgBgrIQ", &__ptr_scePadSetFeatureReport2)) return;
  if(sprx_dlsym(__handle, "lrjFx4xWnY8", &__ptr_scePadSetForceIntercepted)) return;
  if(sprx_dlsym(__handle, "RR4novUEENY", &__ptr_scePadSetLightBar)) return;
  if(sprx_dlsym(__handle, "dhQXEvmrVNQ", &__ptr_scePadSetLightBarBaseBrightness)) return;
  if(sprx_dlsym(__handle, "etaQhgPHDRY", &__ptr_scePadSetLightBarBlinking)) return;
  if(sprx_dlsym(__handle, "iHuOWdvQVpg", &__ptr_scePadSetLightBarForTracker)) return;
  if(sprx_dlsym(__handle, "o-6Y99a8dKU", &__ptr_scePadSetLoginUserNumber)) return;
  if(sprx_dlsym(__handle, "clVvL4ZDntw", &__ptr_scePadSetMotionSensorState)) return;
  if(sprx_dlsym(__handle, "flYYxek1wy8", &__ptr_scePadSetProcessFocus)) return;
  if(sprx_dlsym(__handle, "DmBx8K+jDWw", &__ptr_scePadSetProcessPrivilege)) return;
  if(sprx_dlsym(__handle, "FbxEpTRDou8", &__ptr_scePadSetProcessPrivilegeOfButtonRemapping)) return;
  if(sprx_dlsym(__handle, "yah8Bk4TcYY", &__ptr_scePadSetShareButtonMaskForRemotePlay)) return;
  if(sprx_dlsym(__handle, "vDLMoJLde8I", &__ptr_scePadSetTiltCorrectionState)) return;
  if(sprx_dlsym(__handle, "2JgFB2n9oUM", &__ptr_scePadSetTriggerEffect)) return;
  if(sprx_dlsym(__handle, "z+GEemoTxOo", &__ptr_scePadSetUserColor)) return;
  if(sprx_dlsym(__handle, "iOqpYvGEo6A", &__ptr_scePadSetUserNumber)) return;
  if(sprx_dlsym(__handle, "yFVnOdGxvZY", &__ptr_scePadSetVibration)) return;
  if(sprx_dlsym(__handle, "8BOObG94-tc", &__ptr_scePadSetVibrationForce)) return;
  if(sprx_dlsym(__handle, "W2G-yoyMF5U", &__ptr_scePadSetVibrationMode)) return;
  if(sprx_dlsym(__handle, "Yq0zOH7YNOM", &__ptr_scePadSetVibrationTriggerEffectWeakWhileEmbeddedMicInUse)) return;
  if(sprx_dlsym(__handle, "--jrY4SHfm8", &__ptr_scePadSetVrTrackingMode)) return;
  if(sprx_dlsym(__handle, "zFJ35q3RVnY", &__ptr_scePadShareOutputData)) return;
  if(sprx_dlsym(__handle, "80XdmVYsNPA", &__ptr_scePadStartRecording)) return;
  if(sprx_dlsym(__handle, "gAHvg6JPIic", &__ptr_scePadStopRecording)) return;
  if(sprx_dlsym(__handle, "Oi7FzRWFr0Y", &__ptr_scePadSwitchConnection)) return;
  if(sprx_dlsym(__handle, "0MB5x-ieRGI", &__ptr_scePadVertualDeviceAddDevice)) return;
  if(sprx_dlsym(__handle, "N7tpsjWQ87s", &__ptr_scePadVirtualDeviceAddDevice)) return;
  if(sprx_dlsym(__handle, "PFec14-UhEQ", &__ptr_scePadVirtualDeviceDeleteDevice)) return;
  if(sprx_dlsym(__handle, "pjPCronWdxI", &__ptr_scePadVirtualDeviceDisableButtonRemapping)) return;
  if(sprx_dlsym(__handle, "LKXfw7VJYqg", &__ptr_scePadVirtualDeviceGetRemoteSetting)) return;
  if(sprx_dlsym(__handle, "IWOyO5jKuZg", &__ptr_scePadVirtualDeviceInsertData)) return;
  if(sprx_dlsym(__handle, "mbJHDdjhVeY", &__ptr_scePadVrControllerGetDeviceInformation)) return;
  if(sprx_dlsym(__handle, "306mCg0ibh8", &__ptr_scePadVrControllerRead)) return;
  if(sprx_dlsym(__handle, "iA-DdobUen8", &__ptr_scePadVrControllerReadState)) return;
}

static void __attribute__((destructor(104)))
__destructor(void) {
  sprx_dlclose(__handle);
}
