/*
 This file was generated by genstub.py, do not edit manually!
*/

int sprx_dlsym(unsigned int handle, const char *nid, void *addr);
int sprx_dlopen(const char* libname, unsigned short *handle);
int sprx_dlclose(unsigned int handle);

static __attribute__ ((used)) void* __ptr_sceFontAttachDeviceCacheBuffer;
asm(".intel_syntax noprefix\n"
    ".global sceFontAttachDeviceCacheBuffer\n"
    ".type sceFontAttachDeviceCacheBuffer @function\n"
    "sceFontAttachDeviceCacheBuffer:\n"
    "jmp qword ptr [rip + __ptr_sceFontAttachDeviceCacheBuffer]\n");

static __attribute__ ((used)) void* __ptr_sceFontBindRenderer;
asm(".intel_syntax noprefix\n"
    ".global sceFontBindRenderer\n"
    ".type sceFontBindRenderer @function\n"
    "sceFontBindRenderer:\n"
    "jmp qword ptr [rip + __ptr_sceFontBindRenderer]\n");

static __attribute__ ((used)) void* __ptr_sceFontCharacterGetBidiLevel;
asm(".intel_syntax noprefix\n"
    ".global sceFontCharacterGetBidiLevel\n"
    ".type sceFontCharacterGetBidiLevel @function\n"
    "sceFontCharacterGetBidiLevel:\n"
    "jmp qword ptr [rip + __ptr_sceFontCharacterGetBidiLevel]\n");

static __attribute__ ((used)) void* __ptr_sceFontCharacterGetSyllableStringState;
asm(".intel_syntax noprefix\n"
    ".global sceFontCharacterGetSyllableStringState\n"
    ".type sceFontCharacterGetSyllableStringState @function\n"
    "sceFontCharacterGetSyllableStringState:\n"
    "jmp qword ptr [rip + __ptr_sceFontCharacterGetSyllableStringState]\n");

static __attribute__ ((used)) void* __ptr_sceFontCharacterGetTextFontCode;
asm(".intel_syntax noprefix\n"
    ".global sceFontCharacterGetTextFontCode\n"
    ".type sceFontCharacterGetTextFontCode @function\n"
    "sceFontCharacterGetTextFontCode:\n"
    "jmp qword ptr [rip + __ptr_sceFontCharacterGetTextFontCode]\n");

static __attribute__ ((used)) void* __ptr_sceFontCharacterGetTextOrder;
asm(".intel_syntax noprefix\n"
    ".global sceFontCharacterGetTextOrder\n"
    ".type sceFontCharacterGetTextOrder @function\n"
    "sceFontCharacterGetTextOrder:\n"
    "jmp qword ptr [rip + __ptr_sceFontCharacterGetTextOrder]\n");

static __attribute__ ((used)) void* __ptr_sceFontCharacterLooksFormatCharacters;
asm(".intel_syntax noprefix\n"
    ".global sceFontCharacterLooksFormatCharacters\n"
    ".type sceFontCharacterLooksFormatCharacters @function\n"
    "sceFontCharacterLooksFormatCharacters:\n"
    "jmp qword ptr [rip + __ptr_sceFontCharacterLooksFormatCharacters]\n");

static __attribute__ ((used)) void* __ptr_sceFontCharacterLooksWhiteSpace;
asm(".intel_syntax noprefix\n"
    ".global sceFontCharacterLooksWhiteSpace\n"
    ".type sceFontCharacterLooksWhiteSpace @function\n"
    "sceFontCharacterLooksWhiteSpace:\n"
    "jmp qword ptr [rip + __ptr_sceFontCharacterLooksWhiteSpace]\n");

static __attribute__ ((used)) void* __ptr_sceFontCharacterRefersTextBack;
asm(".intel_syntax noprefix\n"
    ".global sceFontCharacterRefersTextBack\n"
    ".type sceFontCharacterRefersTextBack @function\n"
    "sceFontCharacterRefersTextBack:\n"
    "jmp qword ptr [rip + __ptr_sceFontCharacterRefersTextBack]\n");

static __attribute__ ((used)) void* __ptr_sceFontCharacterRefersTextNext;
asm(".intel_syntax noprefix\n"
    ".global sceFontCharacterRefersTextNext\n"
    ".type sceFontCharacterRefersTextNext @function\n"
    "sceFontCharacterRefersTextNext:\n"
    "jmp qword ptr [rip + __ptr_sceFontCharacterRefersTextNext]\n");

static __attribute__ ((used)) void* __ptr_sceFontCharactersRefersTextCodes;
asm(".intel_syntax noprefix\n"
    ".global sceFontCharactersRefersTextCodes\n"
    ".type sceFontCharactersRefersTextCodes @function\n"
    "sceFontCharactersRefersTextCodes:\n"
    "jmp qword ptr [rip + __ptr_sceFontCharactersRefersTextCodes]\n");

static __attribute__ ((used)) void* __ptr_sceFontClearDeviceCache;
asm(".intel_syntax noprefix\n"
    ".global sceFontClearDeviceCache\n"
    ".type sceFontClearDeviceCache @function\n"
    "sceFontClearDeviceCache:\n"
    "jmp qword ptr [rip + __ptr_sceFontClearDeviceCache]\n");

static __attribute__ ((used)) void* __ptr_sceFontCloseFont;
asm(".intel_syntax noprefix\n"
    ".global sceFontCloseFont\n"
    ".type sceFontCloseFont @function\n"
    "sceFontCloseFont:\n"
    "jmp qword ptr [rip + __ptr_sceFontCloseFont]\n");

static __attribute__ ((used)) void* __ptr_sceFontControl;
asm(".intel_syntax noprefix\n"
    ".global sceFontControl\n"
    ".type sceFontControl @function\n"
    "sceFontControl:\n"
    "jmp qword ptr [rip + __ptr_sceFontControl]\n");

static __attribute__ ((used)) void* __ptr_sceFontCreateLibrary;
asm(".intel_syntax noprefix\n"
    ".global sceFontCreateLibrary\n"
    ".type sceFontCreateLibrary @function\n"
    "sceFontCreateLibrary:\n"
    "jmp qword ptr [rip + __ptr_sceFontCreateLibrary]\n");

static __attribute__ ((used)) void* __ptr_sceFontCreateLibraryWithEdition;
asm(".intel_syntax noprefix\n"
    ".global sceFontCreateLibraryWithEdition\n"
    ".type sceFontCreateLibraryWithEdition @function\n"
    "sceFontCreateLibraryWithEdition:\n"
    "jmp qword ptr [rip + __ptr_sceFontCreateLibraryWithEdition]\n");

static __attribute__ ((used)) void* __ptr_sceFontCreateRenderer;
asm(".intel_syntax noprefix\n"
    ".global sceFontCreateRenderer\n"
    ".type sceFontCreateRenderer @function\n"
    "sceFontCreateRenderer:\n"
    "jmp qword ptr [rip + __ptr_sceFontCreateRenderer]\n");

static __attribute__ ((used)) void* __ptr_sceFontCreateRendererWithEdition;
asm(".intel_syntax noprefix\n"
    ".global sceFontCreateRendererWithEdition\n"
    ".type sceFontCreateRendererWithEdition @function\n"
    "sceFontCreateRendererWithEdition:\n"
    "jmp qword ptr [rip + __ptr_sceFontCreateRendererWithEdition]\n");

static __attribute__ ((used)) void* __ptr_sceFontCreateString;
asm(".intel_syntax noprefix\n"
    ".global sceFontCreateString\n"
    ".type sceFontCreateString @function\n"
    "sceFontCreateString:\n"
    "jmp qword ptr [rip + __ptr_sceFontCreateString]\n");

static __attribute__ ((used)) void* __ptr_sceFontCreateWords;
asm(".intel_syntax noprefix\n"
    ".global sceFontCreateWords\n"
    ".type sceFontCreateWords @function\n"
    "sceFontCreateWords:\n"
    "jmp qword ptr [rip + __ptr_sceFontCreateWords]\n");

static __attribute__ ((used)) void* __ptr_sceFontCreateWritingLine;
asm(".intel_syntax noprefix\n"
    ".global sceFontCreateWritingLine\n"
    ".type sceFontCreateWritingLine @function\n"
    "sceFontCreateWritingLine:\n"
    "jmp qword ptr [rip + __ptr_sceFontCreateWritingLine]\n");

static __attribute__ ((used)) void* __ptr_sceFontDefineAttribute;
asm(".intel_syntax noprefix\n"
    ".global sceFontDefineAttribute\n"
    ".type sceFontDefineAttribute @function\n"
    "sceFontDefineAttribute:\n"
    "jmp qword ptr [rip + __ptr_sceFontDefineAttribute]\n");

static __attribute__ ((used)) void* __ptr_sceFontDeleteGlyph;
asm(".intel_syntax noprefix\n"
    ".global sceFontDeleteGlyph\n"
    ".type sceFontDeleteGlyph @function\n"
    "sceFontDeleteGlyph:\n"
    "jmp qword ptr [rip + __ptr_sceFontDeleteGlyph]\n");

static __attribute__ ((used)) void* __ptr_sceFontDestroyLibrary;
asm(".intel_syntax noprefix\n"
    ".global sceFontDestroyLibrary\n"
    ".type sceFontDestroyLibrary @function\n"
    "sceFontDestroyLibrary:\n"
    "jmp qword ptr [rip + __ptr_sceFontDestroyLibrary]\n");

static __attribute__ ((used)) void* __ptr_sceFontDestroyRenderer;
asm(".intel_syntax noprefix\n"
    ".global sceFontDestroyRenderer\n"
    ".type sceFontDestroyRenderer @function\n"
    "sceFontDestroyRenderer:\n"
    "jmp qword ptr [rip + __ptr_sceFontDestroyRenderer]\n");

static __attribute__ ((used)) void* __ptr_sceFontDestroyString;
asm(".intel_syntax noprefix\n"
    ".global sceFontDestroyString\n"
    ".type sceFontDestroyString @function\n"
    "sceFontDestroyString:\n"
    "jmp qword ptr [rip + __ptr_sceFontDestroyString]\n");

static __attribute__ ((used)) void* __ptr_sceFontDestroyWords;
asm(".intel_syntax noprefix\n"
    ".global sceFontDestroyWords\n"
    ".type sceFontDestroyWords @function\n"
    "sceFontDestroyWords:\n"
    "jmp qword ptr [rip + __ptr_sceFontDestroyWords]\n");

static __attribute__ ((used)) void* __ptr_sceFontDestroyWritingLine;
asm(".intel_syntax noprefix\n"
    ".global sceFontDestroyWritingLine\n"
    ".type sceFontDestroyWritingLine @function\n"
    "sceFontDestroyWritingLine:\n"
    "jmp qword ptr [rip + __ptr_sceFontDestroyWritingLine]\n");

static __attribute__ ((used)) void* __ptr_sceFontDettachDeviceCacheBuffer;
asm(".intel_syntax noprefix\n"
    ".global sceFontDettachDeviceCacheBuffer\n"
    ".type sceFontDettachDeviceCacheBuffer @function\n"
    "sceFontDettachDeviceCacheBuffer:\n"
    "jmp qword ptr [rip + __ptr_sceFontDettachDeviceCacheBuffer]\n");

static __attribute__ ((used)) void* __ptr_sceFontGenerateCharGlyph;
asm(".intel_syntax noprefix\n"
    ".global sceFontGenerateCharGlyph\n"
    ".type sceFontGenerateCharGlyph @function\n"
    "sceFontGenerateCharGlyph:\n"
    "jmp qword ptr [rip + __ptr_sceFontGenerateCharGlyph]\n");

static __attribute__ ((used)) void* __ptr_sceFontGetAttribute;
asm(".intel_syntax noprefix\n"
    ".global sceFontGetAttribute\n"
    ".type sceFontGetAttribute @function\n"
    "sceFontGetAttribute:\n"
    "jmp qword ptr [rip + __ptr_sceFontGetAttribute]\n");

static __attribute__ ((used)) void* __ptr_sceFontGetCharGlyphCode;
asm(".intel_syntax noprefix\n"
    ".global sceFontGetCharGlyphCode\n"
    ".type sceFontGetCharGlyphCode @function\n"
    "sceFontGetCharGlyphCode:\n"
    "jmp qword ptr [rip + __ptr_sceFontGetCharGlyphCode]\n");

static __attribute__ ((used)) void* __ptr_sceFontGetCharGlyphMetrics;
asm(".intel_syntax noprefix\n"
    ".global sceFontGetCharGlyphMetrics\n"
    ".type sceFontGetCharGlyphMetrics @function\n"
    "sceFontGetCharGlyphMetrics:\n"
    "jmp qword ptr [rip + __ptr_sceFontGetCharGlyphMetrics]\n");

static __attribute__ ((used)) void* __ptr_sceFontGetEffectSlant;
asm(".intel_syntax noprefix\n"
    ".global sceFontGetEffectSlant\n"
    ".type sceFontGetEffectSlant @function\n"
    "sceFontGetEffectSlant:\n"
    "jmp qword ptr [rip + __ptr_sceFontGetEffectSlant]\n");

static __attribute__ ((used)) void* __ptr_sceFontGetEffectWeight;
asm(".intel_syntax noprefix\n"
    ".global sceFontGetEffectWeight\n"
    ".type sceFontGetEffectWeight @function\n"
    "sceFontGetEffectWeight:\n"
    "jmp qword ptr [rip + __ptr_sceFontGetEffectWeight]\n");

static __attribute__ ((used)) void* __ptr_sceFontGetFontGlyphsCount;
asm(".intel_syntax noprefix\n"
    ".global sceFontGetFontGlyphsCount\n"
    ".type sceFontGetFontGlyphsCount @function\n"
    "sceFontGetFontGlyphsCount:\n"
    "jmp qword ptr [rip + __ptr_sceFontGetFontGlyphsCount]\n");

static __attribute__ ((used)) void* __ptr_sceFontGetFontGlyphsOutlineProfile;
asm(".intel_syntax noprefix\n"
    ".global sceFontGetFontGlyphsOutlineProfile\n"
    ".type sceFontGetFontGlyphsOutlineProfile @function\n"
    "sceFontGetFontGlyphsOutlineProfile:\n"
    "jmp qword ptr [rip + __ptr_sceFontGetFontGlyphsOutlineProfile]\n");

static __attribute__ ((used)) void* __ptr_sceFontGetFontMetrics;
asm(".intel_syntax noprefix\n"
    ".global sceFontGetFontMetrics\n"
    ".type sceFontGetFontMetrics @function\n"
    "sceFontGetFontMetrics:\n"
    "jmp qword ptr [rip + __ptr_sceFontGetFontMetrics]\n");

static __attribute__ ((used)) void* __ptr_sceFontGetFontResolution;
asm(".intel_syntax noprefix\n"
    ".global sceFontGetFontResolution\n"
    ".type sceFontGetFontResolution @function\n"
    "sceFontGetFontResolution:\n"
    "jmp qword ptr [rip + __ptr_sceFontGetFontResolution]\n");

static __attribute__ ((used)) void* __ptr_sceFontGetFontStyleInformation;
asm(".intel_syntax noprefix\n"
    ".global sceFontGetFontStyleInformation\n"
    ".type sceFontGetFontStyleInformation @function\n"
    "sceFontGetFontStyleInformation:\n"
    "jmp qword ptr [rip + __ptr_sceFontGetFontStyleInformation]\n");

static __attribute__ ((used)) void* __ptr_sceFontGetGlyphExpandBufferState;
asm(".intel_syntax noprefix\n"
    ".global sceFontGetGlyphExpandBufferState\n"
    ".type sceFontGetGlyphExpandBufferState @function\n"
    "sceFontGetGlyphExpandBufferState:\n"
    "jmp qword ptr [rip + __ptr_sceFontGetGlyphExpandBufferState]\n");

static __attribute__ ((used)) void* __ptr_sceFontGetHorizontalLayout;
asm(".intel_syntax noprefix\n"
    ".global sceFontGetHorizontalLayout\n"
    ".type sceFontGetHorizontalLayout @function\n"
    "sceFontGetHorizontalLayout:\n"
    "jmp qword ptr [rip + __ptr_sceFontGetHorizontalLayout]\n");

static __attribute__ ((used)) void* __ptr_sceFontGetKerning;
asm(".intel_syntax noprefix\n"
    ".global sceFontGetKerning\n"
    ".type sceFontGetKerning @function\n"
    "sceFontGetKerning:\n"
    "jmp qword ptr [rip + __ptr_sceFontGetKerning]\n");

static __attribute__ ((used)) void* __ptr_sceFontGetLibrary;
asm(".intel_syntax noprefix\n"
    ".global sceFontGetLibrary\n"
    ".type sceFontGetLibrary @function\n"
    "sceFontGetLibrary:\n"
    "jmp qword ptr [rip + __ptr_sceFontGetLibrary]\n");

static __attribute__ ((used)) void* __ptr_sceFontGetPixelResolution;
asm(".intel_syntax noprefix\n"
    ".global sceFontGetPixelResolution\n"
    ".type sceFontGetPixelResolution @function\n"
    "sceFontGetPixelResolution:\n"
    "jmp qword ptr [rip + __ptr_sceFontGetPixelResolution]\n");

static __attribute__ ((used)) void* __ptr_sceFontGetRenderCharGlyphMetrics;
asm(".intel_syntax noprefix\n"
    ".global sceFontGetRenderCharGlyphMetrics\n"
    ".type sceFontGetRenderCharGlyphMetrics @function\n"
    "sceFontGetRenderCharGlyphMetrics:\n"
    "jmp qword ptr [rip + __ptr_sceFontGetRenderCharGlyphMetrics]\n");

static __attribute__ ((used)) void* __ptr_sceFontGetRenderEffectSlant;
asm(".intel_syntax noprefix\n"
    ".global sceFontGetRenderEffectSlant\n"
    ".type sceFontGetRenderEffectSlant @function\n"
    "sceFontGetRenderEffectSlant:\n"
    "jmp qword ptr [rip + __ptr_sceFontGetRenderEffectSlant]\n");

static __attribute__ ((used)) void* __ptr_sceFontGetRenderEffectWeight;
asm(".intel_syntax noprefix\n"
    ".global sceFontGetRenderEffectWeight\n"
    ".type sceFontGetRenderEffectWeight @function\n"
    "sceFontGetRenderEffectWeight:\n"
    "jmp qword ptr [rip + __ptr_sceFontGetRenderEffectWeight]\n");

static __attribute__ ((used)) void* __ptr_sceFontGetRenderScalePixel;
asm(".intel_syntax noprefix\n"
    ".global sceFontGetRenderScalePixel\n"
    ".type sceFontGetRenderScalePixel @function\n"
    "sceFontGetRenderScalePixel:\n"
    "jmp qword ptr [rip + __ptr_sceFontGetRenderScalePixel]\n");

static __attribute__ ((used)) void* __ptr_sceFontGetRenderScalePoint;
asm(".intel_syntax noprefix\n"
    ".global sceFontGetRenderScalePoint\n"
    ".type sceFontGetRenderScalePoint @function\n"
    "sceFontGetRenderScalePoint:\n"
    "jmp qword ptr [rip + __ptr_sceFontGetRenderScalePoint]\n");

static __attribute__ ((used)) void* __ptr_sceFontGetRenderScaledKerning;
asm(".intel_syntax noprefix\n"
    ".global sceFontGetRenderScaledKerning\n"
    ".type sceFontGetRenderScaledKerning @function\n"
    "sceFontGetRenderScaledKerning:\n"
    "jmp qword ptr [rip + __ptr_sceFontGetRenderScaledKerning]\n");

static __attribute__ ((used)) void* __ptr_sceFontGetResolutionDpi;
asm(".intel_syntax noprefix\n"
    ".global sceFontGetResolutionDpi\n"
    ".type sceFontGetResolutionDpi @function\n"
    "sceFontGetResolutionDpi:\n"
    "jmp qword ptr [rip + __ptr_sceFontGetResolutionDpi]\n");

static __attribute__ ((used)) void* __ptr_sceFontGetScalePixel;
asm(".intel_syntax noprefix\n"
    ".global sceFontGetScalePixel\n"
    ".type sceFontGetScalePixel @function\n"
    "sceFontGetScalePixel:\n"
    "jmp qword ptr [rip + __ptr_sceFontGetScalePixel]\n");

static __attribute__ ((used)) void* __ptr_sceFontGetScalePoint;
asm(".intel_syntax noprefix\n"
    ".global sceFontGetScalePoint\n"
    ".type sceFontGetScalePoint @function\n"
    "sceFontGetScalePoint:\n"
    "jmp qword ptr [rip + __ptr_sceFontGetScalePoint]\n");

static __attribute__ ((used)) void* __ptr_sceFontGetScriptLanguage;
asm(".intel_syntax noprefix\n"
    ".global sceFontGetScriptLanguage\n"
    ".type sceFontGetScriptLanguage @function\n"
    "sceFontGetScriptLanguage:\n"
    "jmp qword ptr [rip + __ptr_sceFontGetScriptLanguage]\n");

static __attribute__ ((used)) void* __ptr_sceFontGetTypographicDesign;
asm(".intel_syntax noprefix\n"
    ".global sceFontGetTypographicDesign\n"
    ".type sceFontGetTypographicDesign @function\n"
    "sceFontGetTypographicDesign:\n"
    "jmp qword ptr [rip + __ptr_sceFontGetTypographicDesign]\n");

static __attribute__ ((used)) void* __ptr_sceFontGetVerticalLayout;
asm(".intel_syntax noprefix\n"
    ".global sceFontGetVerticalLayout\n"
    ".type sceFontGetVerticalLayout @function\n"
    "sceFontGetVerticalLayout:\n"
    "jmp qword ptr [rip + __ptr_sceFontGetVerticalLayout]\n");

static __attribute__ ((used)) void* __ptr_sceFontGlyphDefineAttribute;
asm(".intel_syntax noprefix\n"
    ".global sceFontGlyphDefineAttribute\n"
    ".type sceFontGlyphDefineAttribute @function\n"
    "sceFontGlyphDefineAttribute:\n"
    "jmp qword ptr [rip + __ptr_sceFontGlyphDefineAttribute]\n");

static __attribute__ ((used)) void* __ptr_sceFontGlyphGetAttribute;
asm(".intel_syntax noprefix\n"
    ".global sceFontGlyphGetAttribute\n"
    ".type sceFontGlyphGetAttribute @function\n"
    "sceFontGlyphGetAttribute:\n"
    "jmp qword ptr [rip + __ptr_sceFontGlyphGetAttribute]\n");

static __attribute__ ((used)) void* __ptr_sceFontGlyphGetGlyphForm;
asm(".intel_syntax noprefix\n"
    ".global sceFontGlyphGetGlyphForm\n"
    ".type sceFontGlyphGetGlyphForm @function\n"
    "sceFontGlyphGetGlyphForm:\n"
    "jmp qword ptr [rip + __ptr_sceFontGlyphGetGlyphForm]\n");

static __attribute__ ((used)) void* __ptr_sceFontGlyphGetMetricsForm;
asm(".intel_syntax noprefix\n"
    ".global sceFontGlyphGetMetricsForm\n"
    ".type sceFontGlyphGetMetricsForm @function\n"
    "sceFontGlyphGetMetricsForm:\n"
    "jmp qword ptr [rip + __ptr_sceFontGlyphGetMetricsForm]\n");

static __attribute__ ((used)) void* __ptr_sceFontGlyphRefersMetrics;
asm(".intel_syntax noprefix\n"
    ".global sceFontGlyphRefersMetrics\n"
    ".type sceFontGlyphRefersMetrics @function\n"
    "sceFontGlyphRefersMetrics:\n"
    "jmp qword ptr [rip + __ptr_sceFontGlyphRefersMetrics]\n");

static __attribute__ ((used)) void* __ptr_sceFontGlyphRefersMetricsHorizontal;
asm(".intel_syntax noprefix\n"
    ".global sceFontGlyphRefersMetricsHorizontal\n"
    ".type sceFontGlyphRefersMetricsHorizontal @function\n"
    "sceFontGlyphRefersMetricsHorizontal:\n"
    "jmp qword ptr [rip + __ptr_sceFontGlyphRefersMetricsHorizontal]\n");

static __attribute__ ((used)) void* __ptr_sceFontGlyphRefersMetricsHorizontalAdvance;
asm(".intel_syntax noprefix\n"
    ".global sceFontGlyphRefersMetricsHorizontalAdvance\n"
    ".type sceFontGlyphRefersMetricsHorizontalAdvance @function\n"
    "sceFontGlyphRefersMetricsHorizontalAdvance:\n"
    "jmp qword ptr [rip + __ptr_sceFontGlyphRefersMetricsHorizontalAdvance]\n");

static __attribute__ ((used)) void* __ptr_sceFontGlyphRefersMetricsHorizontalX;
asm(".intel_syntax noprefix\n"
    ".global sceFontGlyphRefersMetricsHorizontalX\n"
    ".type sceFontGlyphRefersMetricsHorizontalX @function\n"
    "sceFontGlyphRefersMetricsHorizontalX:\n"
    "jmp qword ptr [rip + __ptr_sceFontGlyphRefersMetricsHorizontalX]\n");

static __attribute__ ((used)) void* __ptr_sceFontGlyphRefersOutline;
asm(".intel_syntax noprefix\n"
    ".global sceFontGlyphRefersOutline\n"
    ".type sceFontGlyphRefersOutline @function\n"
    "sceFontGlyphRefersOutline:\n"
    "jmp qword ptr [rip + __ptr_sceFontGlyphRefersOutline]\n");

static __attribute__ ((used)) void* __ptr_sceFontGlyphRenderImage;
asm(".intel_syntax noprefix\n"
    ".global sceFontGlyphRenderImage\n"
    ".type sceFontGlyphRenderImage @function\n"
    "sceFontGlyphRenderImage:\n"
    "jmp qword ptr [rip + __ptr_sceFontGlyphRenderImage]\n");

static __attribute__ ((used)) void* __ptr_sceFontGlyphRenderImageHorizontal;
asm(".intel_syntax noprefix\n"
    ".global sceFontGlyphRenderImageHorizontal\n"
    ".type sceFontGlyphRenderImageHorizontal @function\n"
    "sceFontGlyphRenderImageHorizontal:\n"
    "jmp qword ptr [rip + __ptr_sceFontGlyphRenderImageHorizontal]\n");

static __attribute__ ((used)) void* __ptr_sceFontGlyphRenderImageVertical;
asm(".intel_syntax noprefix\n"
    ".global sceFontGlyphRenderImageVertical\n"
    ".type sceFontGlyphRenderImageVertical @function\n"
    "sceFontGlyphRenderImageVertical:\n"
    "jmp qword ptr [rip + __ptr_sceFontGlyphRenderImageVertical]\n");

static __attribute__ ((used)) void* __ptr_sceFontMemoryInit;
asm(".intel_syntax noprefix\n"
    ".global sceFontMemoryInit\n"
    ".type sceFontMemoryInit @function\n"
    "sceFontMemoryInit:\n"
    "jmp qword ptr [rip + __ptr_sceFontMemoryInit]\n");

static __attribute__ ((used)) void* __ptr_sceFontMemoryTerm;
asm(".intel_syntax noprefix\n"
    ".global sceFontMemoryTerm\n"
    ".type sceFontMemoryTerm @function\n"
    "sceFontMemoryTerm:\n"
    "jmp qword ptr [rip + __ptr_sceFontMemoryTerm]\n");

static __attribute__ ((used)) void* __ptr_sceFontOpenFontFile;
asm(".intel_syntax noprefix\n"
    ".global sceFontOpenFontFile\n"
    ".type sceFontOpenFontFile @function\n"
    "sceFontOpenFontFile:\n"
    "jmp qword ptr [rip + __ptr_sceFontOpenFontFile]\n");

static __attribute__ ((used)) void* __ptr_sceFontOpenFontInstance;
asm(".intel_syntax noprefix\n"
    ".global sceFontOpenFontInstance\n"
    ".type sceFontOpenFontInstance @function\n"
    "sceFontOpenFontInstance:\n"
    "jmp qword ptr [rip + __ptr_sceFontOpenFontInstance]\n");

static __attribute__ ((used)) void* __ptr_sceFontOpenFontMemory;
asm(".intel_syntax noprefix\n"
    ".global sceFontOpenFontMemory\n"
    ".type sceFontOpenFontMemory @function\n"
    "sceFontOpenFontMemory:\n"
    "jmp qword ptr [rip + __ptr_sceFontOpenFontMemory]\n");

static __attribute__ ((used)) void* __ptr_sceFontOpenFontSet;
asm(".intel_syntax noprefix\n"
    ".global sceFontOpenFontSet\n"
    ".type sceFontOpenFontSet @function\n"
    "sceFontOpenFontSet:\n"
    "jmp qword ptr [rip + __ptr_sceFontOpenFontSet]\n");

static __attribute__ ((used)) void* __ptr_sceFontRebindRenderer;
asm(".intel_syntax noprefix\n"
    ".global sceFontRebindRenderer\n"
    ".type sceFontRebindRenderer @function\n"
    "sceFontRebindRenderer:\n"
    "jmp qword ptr [rip + __ptr_sceFontRebindRenderer]\n");

static __attribute__ ((used)) void* __ptr_sceFontRenderCharGlyphImage;
asm(".intel_syntax noprefix\n"
    ".global sceFontRenderCharGlyphImage\n"
    ".type sceFontRenderCharGlyphImage @function\n"
    "sceFontRenderCharGlyphImage:\n"
    "jmp qword ptr [rip + __ptr_sceFontRenderCharGlyphImage]\n");

static __attribute__ ((used)) void* __ptr_sceFontRenderCharGlyphImageHorizontal;
asm(".intel_syntax noprefix\n"
    ".global sceFontRenderCharGlyphImageHorizontal\n"
    ".type sceFontRenderCharGlyphImageHorizontal @function\n"
    "sceFontRenderCharGlyphImageHorizontal:\n"
    "jmp qword ptr [rip + __ptr_sceFontRenderCharGlyphImageHorizontal]\n");

static __attribute__ ((used)) void* __ptr_sceFontRenderCharGlyphImageVertical;
asm(".intel_syntax noprefix\n"
    ".global sceFontRenderCharGlyphImageVertical\n"
    ".type sceFontRenderCharGlyphImageVertical @function\n"
    "sceFontRenderCharGlyphImageVertical:\n"
    "jmp qword ptr [rip + __ptr_sceFontRenderCharGlyphImageVertical]\n");

static __attribute__ ((used)) void* __ptr_sceFontRenderSurfaceInit;
asm(".intel_syntax noprefix\n"
    ".global sceFontRenderSurfaceInit\n"
    ".type sceFontRenderSurfaceInit @function\n"
    "sceFontRenderSurfaceInit:\n"
    "jmp qword ptr [rip + __ptr_sceFontRenderSurfaceInit]\n");

static __attribute__ ((used)) void* __ptr_sceFontRenderSurfaceSetScissor;
asm(".intel_syntax noprefix\n"
    ".global sceFontRenderSurfaceSetScissor\n"
    ".type sceFontRenderSurfaceSetScissor @function\n"
    "sceFontRenderSurfaceSetScissor:\n"
    "jmp qword ptr [rip + __ptr_sceFontRenderSurfaceSetScissor]\n");

static __attribute__ ((used)) void* __ptr_sceFontRenderSurfaceSetStyleFrame;
asm(".intel_syntax noprefix\n"
    ".global sceFontRenderSurfaceSetStyleFrame\n"
    ".type sceFontRenderSurfaceSetStyleFrame @function\n"
    "sceFontRenderSurfaceSetStyleFrame:\n"
    "jmp qword ptr [rip + __ptr_sceFontRenderSurfaceSetStyleFrame]\n");

static __attribute__ ((used)) void* __ptr_sceFontRendererGetOutlineBufferSize;
asm(".intel_syntax noprefix\n"
    ".global sceFontRendererGetOutlineBufferSize\n"
    ".type sceFontRendererGetOutlineBufferSize @function\n"
    "sceFontRendererGetOutlineBufferSize:\n"
    "jmp qword ptr [rip + __ptr_sceFontRendererGetOutlineBufferSize]\n");

static __attribute__ ((used)) void* __ptr_sceFontRendererResetOutlineBuffer;
asm(".intel_syntax noprefix\n"
    ".global sceFontRendererResetOutlineBuffer\n"
    ".type sceFontRendererResetOutlineBuffer @function\n"
    "sceFontRendererResetOutlineBuffer:\n"
    "jmp qword ptr [rip + __ptr_sceFontRendererResetOutlineBuffer]\n");

static __attribute__ ((used)) void* __ptr_sceFontRendererSetOutlineBufferPolicy;
asm(".intel_syntax noprefix\n"
    ".global sceFontRendererSetOutlineBufferPolicy\n"
    ".type sceFontRendererSetOutlineBufferPolicy @function\n"
    "sceFontRendererSetOutlineBufferPolicy:\n"
    "jmp qword ptr [rip + __ptr_sceFontRendererSetOutlineBufferPolicy]\n");

static __attribute__ ((used)) void* __ptr_sceFontSetEffectSlant;
asm(".intel_syntax noprefix\n"
    ".global sceFontSetEffectSlant\n"
    ".type sceFontSetEffectSlant @function\n"
    "sceFontSetEffectSlant:\n"
    "jmp qword ptr [rip + __ptr_sceFontSetEffectSlant]\n");

static __attribute__ ((used)) void* __ptr_sceFontSetEffectWeight;
asm(".intel_syntax noprefix\n"
    ".global sceFontSetEffectWeight\n"
    ".type sceFontSetEffectWeight @function\n"
    "sceFontSetEffectWeight:\n"
    "jmp qword ptr [rip + __ptr_sceFontSetEffectWeight]\n");

static __attribute__ ((used)) void* __ptr_sceFontSetFontsOpenMode;
asm(".intel_syntax noprefix\n"
    ".global sceFontSetFontsOpenMode\n"
    ".type sceFontSetFontsOpenMode @function\n"
    "sceFontSetFontsOpenMode:\n"
    "jmp qword ptr [rip + __ptr_sceFontSetFontsOpenMode]\n");

static __attribute__ ((used)) void* __ptr_sceFontSetResolutionDpi;
asm(".intel_syntax noprefix\n"
    ".global sceFontSetResolutionDpi\n"
    ".type sceFontSetResolutionDpi @function\n"
    "sceFontSetResolutionDpi:\n"
    "jmp qword ptr [rip + __ptr_sceFontSetResolutionDpi]\n");

static __attribute__ ((used)) void* __ptr_sceFontSetScalePixel;
asm(".intel_syntax noprefix\n"
    ".global sceFontSetScalePixel\n"
    ".type sceFontSetScalePixel @function\n"
    "sceFontSetScalePixel:\n"
    "jmp qword ptr [rip + __ptr_sceFontSetScalePixel]\n");

static __attribute__ ((used)) void* __ptr_sceFontSetScalePoint;
asm(".intel_syntax noprefix\n"
    ".global sceFontSetScalePoint\n"
    ".type sceFontSetScalePoint @function\n"
    "sceFontSetScalePoint:\n"
    "jmp qword ptr [rip + __ptr_sceFontSetScalePoint]\n");

static __attribute__ ((used)) void* __ptr_sceFontSetScriptLanguage;
asm(".intel_syntax noprefix\n"
    ".global sceFontSetScriptLanguage\n"
    ".type sceFontSetScriptLanguage @function\n"
    "sceFontSetScriptLanguage:\n"
    "jmp qword ptr [rip + __ptr_sceFontSetScriptLanguage]\n");

static __attribute__ ((used)) void* __ptr_sceFontSetTypographicDesign;
asm(".intel_syntax noprefix\n"
    ".global sceFontSetTypographicDesign\n"
    ".type sceFontSetTypographicDesign @function\n"
    "sceFontSetTypographicDesign:\n"
    "jmp qword ptr [rip + __ptr_sceFontSetTypographicDesign]\n");

static __attribute__ ((used)) void* __ptr_sceFontSetupRenderEffectSlant;
asm(".intel_syntax noprefix\n"
    ".global sceFontSetupRenderEffectSlant\n"
    ".type sceFontSetupRenderEffectSlant @function\n"
    "sceFontSetupRenderEffectSlant:\n"
    "jmp qword ptr [rip + __ptr_sceFontSetupRenderEffectSlant]\n");

static __attribute__ ((used)) void* __ptr_sceFontSetupRenderEffectWeight;
asm(".intel_syntax noprefix\n"
    ".global sceFontSetupRenderEffectWeight\n"
    ".type sceFontSetupRenderEffectWeight @function\n"
    "sceFontSetupRenderEffectWeight:\n"
    "jmp qword ptr [rip + __ptr_sceFontSetupRenderEffectWeight]\n");

static __attribute__ ((used)) void* __ptr_sceFontSetupRenderScalePixel;
asm(".intel_syntax noprefix\n"
    ".global sceFontSetupRenderScalePixel\n"
    ".type sceFontSetupRenderScalePixel @function\n"
    "sceFontSetupRenderScalePixel:\n"
    "jmp qword ptr [rip + __ptr_sceFontSetupRenderScalePixel]\n");

static __attribute__ ((used)) void* __ptr_sceFontSetupRenderScalePoint;
asm(".intel_syntax noprefix\n"
    ".global sceFontSetupRenderScalePoint\n"
    ".type sceFontSetupRenderScalePoint @function\n"
    "sceFontSetupRenderScalePoint:\n"
    "jmp qword ptr [rip + __ptr_sceFontSetupRenderScalePoint]\n");

static __attribute__ ((used)) void* __ptr_sceFontStringGetTerminateCode;
asm(".intel_syntax noprefix\n"
    ".global sceFontStringGetTerminateCode\n"
    ".type sceFontStringGetTerminateCode @function\n"
    "sceFontStringGetTerminateCode:\n"
    "jmp qword ptr [rip + __ptr_sceFontStringGetTerminateCode]\n");

static __attribute__ ((used)) void* __ptr_sceFontStringGetTerminateOrder;
asm(".intel_syntax noprefix\n"
    ".global sceFontStringGetTerminateOrder\n"
    ".type sceFontStringGetTerminateOrder @function\n"
    "sceFontStringGetTerminateOrder:\n"
    "jmp qword ptr [rip + __ptr_sceFontStringGetTerminateOrder]\n");

static __attribute__ ((used)) void* __ptr_sceFontStringGetWritingForm;
asm(".intel_syntax noprefix\n"
    ".global sceFontStringGetWritingForm\n"
    ".type sceFontStringGetWritingForm @function\n"
    "sceFontStringGetWritingForm:\n"
    "jmp qword ptr [rip + __ptr_sceFontStringGetWritingForm]\n");

static __attribute__ ((used)) void* __ptr_sceFontStringRefersRenderCharacters;
asm(".intel_syntax noprefix\n"
    ".global sceFontStringRefersRenderCharacters\n"
    ".type sceFontStringRefersRenderCharacters @function\n"
    "sceFontStringRefersRenderCharacters:\n"
    "jmp qword ptr [rip + __ptr_sceFontStringRefersRenderCharacters]\n");

static __attribute__ ((used)) void* __ptr_sceFontStringRefersTextCharacters;
asm(".intel_syntax noprefix\n"
    ".global sceFontStringRefersTextCharacters\n"
    ".type sceFontStringRefersTextCharacters @function\n"
    "sceFontStringRefersTextCharacters:\n"
    "jmp qword ptr [rip + __ptr_sceFontStringRefersTextCharacters]\n");

static __attribute__ ((used)) void* __ptr_sceFontStyleFrameGetEffectSlant;
asm(".intel_syntax noprefix\n"
    ".global sceFontStyleFrameGetEffectSlant\n"
    ".type sceFontStyleFrameGetEffectSlant @function\n"
    "sceFontStyleFrameGetEffectSlant:\n"
    "jmp qword ptr [rip + __ptr_sceFontStyleFrameGetEffectSlant]\n");

static __attribute__ ((used)) void* __ptr_sceFontStyleFrameGetEffectWeight;
asm(".intel_syntax noprefix\n"
    ".global sceFontStyleFrameGetEffectWeight\n"
    ".type sceFontStyleFrameGetEffectWeight @function\n"
    "sceFontStyleFrameGetEffectWeight:\n"
    "jmp qword ptr [rip + __ptr_sceFontStyleFrameGetEffectWeight]\n");

static __attribute__ ((used)) void* __ptr_sceFontStyleFrameGetResolutionDpi;
asm(".intel_syntax noprefix\n"
    ".global sceFontStyleFrameGetResolutionDpi\n"
    ".type sceFontStyleFrameGetResolutionDpi @function\n"
    "sceFontStyleFrameGetResolutionDpi:\n"
    "jmp qword ptr [rip + __ptr_sceFontStyleFrameGetResolutionDpi]\n");

static __attribute__ ((used)) void* __ptr_sceFontStyleFrameGetScalePixel;
asm(".intel_syntax noprefix\n"
    ".global sceFontStyleFrameGetScalePixel\n"
    ".type sceFontStyleFrameGetScalePixel @function\n"
    "sceFontStyleFrameGetScalePixel:\n"
    "jmp qword ptr [rip + __ptr_sceFontStyleFrameGetScalePixel]\n");

static __attribute__ ((used)) void* __ptr_sceFontStyleFrameGetScalePoint;
asm(".intel_syntax noprefix\n"
    ".global sceFontStyleFrameGetScalePoint\n"
    ".type sceFontStyleFrameGetScalePoint @function\n"
    "sceFontStyleFrameGetScalePoint:\n"
    "jmp qword ptr [rip + __ptr_sceFontStyleFrameGetScalePoint]\n");

static __attribute__ ((used)) void* __ptr_sceFontStyleFrameInit;
asm(".intel_syntax noprefix\n"
    ".global sceFontStyleFrameInit\n"
    ".type sceFontStyleFrameInit @function\n"
    "sceFontStyleFrameInit:\n"
    "jmp qword ptr [rip + __ptr_sceFontStyleFrameInit]\n");

static __attribute__ ((used)) void* __ptr_sceFontStyleFrameSetEffectSlant;
asm(".intel_syntax noprefix\n"
    ".global sceFontStyleFrameSetEffectSlant\n"
    ".type sceFontStyleFrameSetEffectSlant @function\n"
    "sceFontStyleFrameSetEffectSlant:\n"
    "jmp qword ptr [rip + __ptr_sceFontStyleFrameSetEffectSlant]\n");

static __attribute__ ((used)) void* __ptr_sceFontStyleFrameSetEffectWeight;
asm(".intel_syntax noprefix\n"
    ".global sceFontStyleFrameSetEffectWeight\n"
    ".type sceFontStyleFrameSetEffectWeight @function\n"
    "sceFontStyleFrameSetEffectWeight:\n"
    "jmp qword ptr [rip + __ptr_sceFontStyleFrameSetEffectWeight]\n");

static __attribute__ ((used)) void* __ptr_sceFontStyleFrameSetResolutionDpi;
asm(".intel_syntax noprefix\n"
    ".global sceFontStyleFrameSetResolutionDpi\n"
    ".type sceFontStyleFrameSetResolutionDpi @function\n"
    "sceFontStyleFrameSetResolutionDpi:\n"
    "jmp qword ptr [rip + __ptr_sceFontStyleFrameSetResolutionDpi]\n");

static __attribute__ ((used)) void* __ptr_sceFontStyleFrameSetScalePixel;
asm(".intel_syntax noprefix\n"
    ".global sceFontStyleFrameSetScalePixel\n"
    ".type sceFontStyleFrameSetScalePixel @function\n"
    "sceFontStyleFrameSetScalePixel:\n"
    "jmp qword ptr [rip + __ptr_sceFontStyleFrameSetScalePixel]\n");

static __attribute__ ((used)) void* __ptr_sceFontStyleFrameSetScalePoint;
asm(".intel_syntax noprefix\n"
    ".global sceFontStyleFrameSetScalePoint\n"
    ".type sceFontStyleFrameSetScalePoint @function\n"
    "sceFontStyleFrameSetScalePoint:\n"
    "jmp qword ptr [rip + __ptr_sceFontStyleFrameSetScalePoint]\n");

static __attribute__ ((used)) void* __ptr_sceFontStyleFrameUnsetEffectSlant;
asm(".intel_syntax noprefix\n"
    ".global sceFontStyleFrameUnsetEffectSlant\n"
    ".type sceFontStyleFrameUnsetEffectSlant @function\n"
    "sceFontStyleFrameUnsetEffectSlant:\n"
    "jmp qword ptr [rip + __ptr_sceFontStyleFrameUnsetEffectSlant]\n");

static __attribute__ ((used)) void* __ptr_sceFontStyleFrameUnsetEffectWeight;
asm(".intel_syntax noprefix\n"
    ".global sceFontStyleFrameUnsetEffectWeight\n"
    ".type sceFontStyleFrameUnsetEffectWeight @function\n"
    "sceFontStyleFrameUnsetEffectWeight:\n"
    "jmp qword ptr [rip + __ptr_sceFontStyleFrameUnsetEffectWeight]\n");

static __attribute__ ((used)) void* __ptr_sceFontStyleFrameUnsetScale;
asm(".intel_syntax noprefix\n"
    ".global sceFontStyleFrameUnsetScale\n"
    ".type sceFontStyleFrameUnsetScale @function\n"
    "sceFontStyleFrameUnsetScale:\n"
    "jmp qword ptr [rip + __ptr_sceFontStyleFrameUnsetScale]\n");

static __attribute__ ((used)) void* __ptr_sceFontSupportExternalFonts;
asm(".intel_syntax noprefix\n"
    ".global sceFontSupportExternalFonts\n"
    ".type sceFontSupportExternalFonts @function\n"
    "sceFontSupportExternalFonts:\n"
    "jmp qword ptr [rip + __ptr_sceFontSupportExternalFonts]\n");

static __attribute__ ((used)) void* __ptr_sceFontSupportSystemFonts;
asm(".intel_syntax noprefix\n"
    ".global sceFontSupportSystemFonts\n"
    ".type sceFontSupportSystemFonts @function\n"
    "sceFontSupportSystemFonts:\n"
    "jmp qword ptr [rip + __ptr_sceFontSupportSystemFonts]\n");

static __attribute__ ((used)) void* __ptr_sceFontTextCodesStepBack;
asm(".intel_syntax noprefix\n"
    ".global sceFontTextCodesStepBack\n"
    ".type sceFontTextCodesStepBack @function\n"
    "sceFontTextCodesStepBack:\n"
    "jmp qword ptr [rip + __ptr_sceFontTextCodesStepBack]\n");

static __attribute__ ((used)) void* __ptr_sceFontTextCodesStepNext;
asm(".intel_syntax noprefix\n"
    ".global sceFontTextCodesStepNext\n"
    ".type sceFontTextCodesStepNext @function\n"
    "sceFontTextCodesStepNext:\n"
    "jmp qword ptr [rip + __ptr_sceFontTextCodesStepNext]\n");

static __attribute__ ((used)) void* __ptr_sceFontTextSourceInit;
asm(".intel_syntax noprefix\n"
    ".global sceFontTextSourceInit\n"
    ".type sceFontTextSourceInit @function\n"
    "sceFontTextSourceInit:\n"
    "jmp qword ptr [rip + __ptr_sceFontTextSourceInit]\n");

static __attribute__ ((used)) void* __ptr_sceFontTextSourceRewind;
asm(".intel_syntax noprefix\n"
    ".global sceFontTextSourceRewind\n"
    ".type sceFontTextSourceRewind @function\n"
    "sceFontTextSourceRewind:\n"
    "jmp qword ptr [rip + __ptr_sceFontTextSourceRewind]\n");

static __attribute__ ((used)) void* __ptr_sceFontTextSourceSetDefaultFont;
asm(".intel_syntax noprefix\n"
    ".global sceFontTextSourceSetDefaultFont\n"
    ".type sceFontTextSourceSetDefaultFont @function\n"
    "sceFontTextSourceSetDefaultFont:\n"
    "jmp qword ptr [rip + __ptr_sceFontTextSourceSetDefaultFont]\n");

static __attribute__ ((used)) void* __ptr_sceFontTextSourceSetWritingForm;
asm(".intel_syntax noprefix\n"
    ".global sceFontTextSourceSetWritingForm\n"
    ".type sceFontTextSourceSetWritingForm @function\n"
    "sceFontTextSourceSetWritingForm:\n"
    "jmp qword ptr [rip + __ptr_sceFontTextSourceSetWritingForm]\n");

static __attribute__ ((used)) void* __ptr_sceFontUnbindRenderer;
asm(".intel_syntax noprefix\n"
    ".global sceFontUnbindRenderer\n"
    ".type sceFontUnbindRenderer @function\n"
    "sceFontUnbindRenderer:\n"
    "jmp qword ptr [rip + __ptr_sceFontUnbindRenderer]\n");

static __attribute__ ((used)) void* __ptr_sceFontWordsFindWordCharacters;
asm(".intel_syntax noprefix\n"
    ".global sceFontWordsFindWordCharacters\n"
    ".type sceFontWordsFindWordCharacters @function\n"
    "sceFontWordsFindWordCharacters:\n"
    "jmp qword ptr [rip + __ptr_sceFontWordsFindWordCharacters]\n");

static __attribute__ ((used)) void* __ptr_sceFontWritingGetRenderMetrics;
asm(".intel_syntax noprefix\n"
    ".global sceFontWritingGetRenderMetrics\n"
    ".type sceFontWritingGetRenderMetrics @function\n"
    "sceFontWritingGetRenderMetrics:\n"
    "jmp qword ptr [rip + __ptr_sceFontWritingGetRenderMetrics]\n");

static __attribute__ ((used)) void* __ptr_sceFontWritingInit;
asm(".intel_syntax noprefix\n"
    ".global sceFontWritingInit\n"
    ".type sceFontWritingInit @function\n"
    "sceFontWritingInit:\n"
    "jmp qword ptr [rip + __ptr_sceFontWritingInit]\n");

static __attribute__ ((used)) void* __ptr_sceFontWritingLineClear;
asm(".intel_syntax noprefix\n"
    ".global sceFontWritingLineClear\n"
    ".type sceFontWritingLineClear @function\n"
    "sceFontWritingLineClear:\n"
    "jmp qword ptr [rip + __ptr_sceFontWritingLineClear]\n");

static __attribute__ ((used)) void* __ptr_sceFontWritingLineGetOrderingSpace;
asm(".intel_syntax noprefix\n"
    ".global sceFontWritingLineGetOrderingSpace\n"
    ".type sceFontWritingLineGetOrderingSpace @function\n"
    "sceFontWritingLineGetOrderingSpace:\n"
    "jmp qword ptr [rip + __ptr_sceFontWritingLineGetOrderingSpace]\n");

static __attribute__ ((used)) void* __ptr_sceFontWritingLineGetRenderMetrics;
asm(".intel_syntax noprefix\n"
    ".global sceFontWritingLineGetRenderMetrics\n"
    ".type sceFontWritingLineGetRenderMetrics @function\n"
    "sceFontWritingLineGetRenderMetrics:\n"
    "jmp qword ptr [rip + __ptr_sceFontWritingLineGetRenderMetrics]\n");

static __attribute__ ((used)) void* __ptr_sceFontWritingLineRefersRenderStep;
asm(".intel_syntax noprefix\n"
    ".global sceFontWritingLineRefersRenderStep\n"
    ".type sceFontWritingLineRefersRenderStep @function\n"
    "sceFontWritingLineRefersRenderStep:\n"
    "jmp qword ptr [rip + __ptr_sceFontWritingLineRefersRenderStep]\n");

static __attribute__ ((used)) void* __ptr_sceFontWritingLineWritesOrder;
asm(".intel_syntax noprefix\n"
    ".global sceFontWritingLineWritesOrder\n"
    ".type sceFontWritingLineWritesOrder @function\n"
    "sceFontWritingLineWritesOrder:\n"
    "jmp qword ptr [rip + __ptr_sceFontWritingLineWritesOrder]\n");

static __attribute__ ((used)) void* __ptr_sceFontWritingRefersRenderStep;
asm(".intel_syntax noprefix\n"
    ".global sceFontWritingRefersRenderStep\n"
    ".type sceFontWritingRefersRenderStep @function\n"
    "sceFontWritingRefersRenderStep:\n"
    "jmp qword ptr [rip + __ptr_sceFontWritingRefersRenderStep]\n");

static __attribute__ ((used)) void* __ptr_sceFontWritingRefersRenderStepCharacter;
asm(".intel_syntax noprefix\n"
    ".global sceFontWritingRefersRenderStepCharacter\n"
    ".type sceFontWritingRefersRenderStepCharacter @function\n"
    "sceFontWritingRefersRenderStepCharacter:\n"
    "jmp qword ptr [rip + __ptr_sceFontWritingRefersRenderStepCharacter]\n");

static __attribute__ ((used)) void* __ptr_sceFontWritingSetMaskInvisible;
asm(".intel_syntax noprefix\n"
    ".global sceFontWritingSetMaskInvisible\n"
    ".type sceFontWritingSetMaskInvisible @function\n"
    "sceFontWritingSetMaskInvisible:\n"
    "jmp qword ptr [rip + __ptr_sceFontWritingSetMaskInvisible]\n");

static unsigned short __handle = 0;
static void __attribute__((constructor(104)))
__constructor(void) {
  if(sprx_dlopen("libSceFont.native", &__handle)) return;
  if(sprx_dlsym(__handle, "CUKn5pX-NVY", &__ptr_sceFontAttachDeviceCacheBuffer)) return;
  if(sprx_dlsym(__handle, "3OdRkSjOcog", &__ptr_sceFontBindRenderer)) return;
  if(sprx_dlsym(__handle, "6DFUkCwQLa8", &__ptr_sceFontCharacterGetBidiLevel)) return;
  if(sprx_dlsym(__handle, "coCrV6IWplE", &__ptr_sceFontCharacterGetSyllableStringState)) return;
  if(sprx_dlsym(__handle, "zN3+nuA0SFQ", &__ptr_sceFontCharacterGetTextFontCode)) return;
  if(sprx_dlsym(__handle, "mxgmMj-Mq-o", &__ptr_sceFontCharacterGetTextOrder)) return;
  if(sprx_dlsym(__handle, "-P6X35Rq2-E", &__ptr_sceFontCharacterLooksFormatCharacters)) return;
  if(sprx_dlsym(__handle, "SaRlqtqaCew", &__ptr_sceFontCharacterLooksWhiteSpace)) return;
  if(sprx_dlsym(__handle, "6Gqlv5KdTbU", &__ptr_sceFontCharacterRefersTextBack)) return;
  if(sprx_dlsym(__handle, "BkjBP+YC19w", &__ptr_sceFontCharacterRefersTextNext)) return;
  if(sprx_dlsym(__handle, "lVSR5ftvNag", &__ptr_sceFontCharactersRefersTextCodes)) return;
  if(sprx_dlsym(__handle, "I9R5VC6eZWo", &__ptr_sceFontClearDeviceCache)) return;
  if(sprx_dlsym(__handle, "vzHs3C8lWJk", &__ptr_sceFontCloseFont)) return;
  if(sprx_dlsym(__handle, "MpKSBaYKluo", &__ptr_sceFontControl)) return;
  if(sprx_dlsym(__handle, "nWrfPI4Okmg", &__ptr_sceFontCreateLibrary)) return;
  if(sprx_dlsym(__handle, "n590hj5Oe-k", &__ptr_sceFontCreateLibraryWithEdition)) return;
  if(sprx_dlsym(__handle, "u5fZd3KZcs0", &__ptr_sceFontCreateRenderer)) return;
  if(sprx_dlsym(__handle, "WaSFJoRWXaI", &__ptr_sceFontCreateRendererWithEdition)) return;
  if(sprx_dlsym(__handle, "MO24vDhmS4E", &__ptr_sceFontCreateString)) return;
  if(sprx_dlsym(__handle, "cYrMGk1wrMA", &__ptr_sceFontCreateWords)) return;
  if(sprx_dlsym(__handle, "7rogx92EEyc", &__ptr_sceFontCreateWritingLine)) return;
  if(sprx_dlsym(__handle, "8h-SOB-asgk", &__ptr_sceFontDefineAttribute)) return;
  if(sprx_dlsym(__handle, "LHDoRWVFGqk", &__ptr_sceFontDeleteGlyph)) return;
  if(sprx_dlsym(__handle, "FXP359ygujs", &__ptr_sceFontDestroyLibrary)) return;
  if(sprx_dlsym(__handle, "exAxkyVLt0s", &__ptr_sceFontDestroyRenderer)) return;
  if(sprx_dlsym(__handle, "SSCaczu2aMQ", &__ptr_sceFontDestroyString)) return;
  if(sprx_dlsym(__handle, "hWE4AwNixqY", &__ptr_sceFontDestroyWords)) return;
  if(sprx_dlsym(__handle, "PEjv7CVDRYs", &__ptr_sceFontDestroyWritingLine)) return;
  if(sprx_dlsym(__handle, "UuY-OJF+f0k", &__ptr_sceFontDettachDeviceCacheBuffer)) return;
  if(sprx_dlsym(__handle, "C-4Qw5Srlyw", &__ptr_sceFontGenerateCharGlyph)) return;
  if(sprx_dlsym(__handle, "5kx49CAlO-M", &__ptr_sceFontGetAttribute)) return;
  if(sprx_dlsym(__handle, "OINC0X9HGBY", &__ptr_sceFontGetCharGlyphCode)) return;
  if(sprx_dlsym(__handle, "L97d+3OgMlE", &__ptr_sceFontGetCharGlyphMetrics)) return;
  if(sprx_dlsym(__handle, "ynSqYL8VpoA", &__ptr_sceFontGetEffectSlant)) return;
  if(sprx_dlsym(__handle, "d7dDgRY+Bzw", &__ptr_sceFontGetEffectWeight)) return;
  if(sprx_dlsym(__handle, "ZB8xRemRRG8", &__ptr_sceFontGetFontGlyphsCount)) return;
  if(sprx_dlsym(__handle, "4X14YSK4Ldk", &__ptr_sceFontGetFontGlyphsOutlineProfile)) return;
  if(sprx_dlsym(__handle, "eb9S3zNlV5o", &__ptr_sceFontGetFontMetrics)) return;
  if(sprx_dlsym(__handle, "tiIlroGki+g", &__ptr_sceFontGetFontResolution)) return;
  if(sprx_dlsym(__handle, "3hVv3SNoL6E", &__ptr_sceFontGetFontStyleInformation)) return;
  if(sprx_dlsym(__handle, "gVQpMBuB7fE", &__ptr_sceFontGetGlyphExpandBufferState)) return;
  if(sprx_dlsym(__handle, "imxVx8lm+KM", &__ptr_sceFontGetHorizontalLayout)) return;
  if(sprx_dlsym(__handle, "sDuhHGNhHvE", &__ptr_sceFontGetKerning)) return;
  if(sprx_dlsym(__handle, "LzmHDnlcwfQ", &__ptr_sceFontGetLibrary)) return;
  if(sprx_dlsym(__handle, "BozJej5T6fs", &__ptr_sceFontGetPixelResolution)) return;
  if(sprx_dlsym(__handle, "IQtleGLL5pQ", &__ptr_sceFontGetRenderCharGlyphMetrics)) return;
  if(sprx_dlsym(__handle, "Gqa5Pp7y4MU", &__ptr_sceFontGetRenderEffectSlant)) return;
  if(sprx_dlsym(__handle, "woOjHrkjIYg", &__ptr_sceFontGetRenderEffectWeight)) return;
  if(sprx_dlsym(__handle, "EY38A01lq2k", &__ptr_sceFontGetRenderScalePixel)) return;
  if(sprx_dlsym(__handle, "FEafYUcxEGo", &__ptr_sceFontGetRenderScalePoint)) return;
  if(sprx_dlsym(__handle, "ryPlnDDI3rU", &__ptr_sceFontGetRenderScaledKerning)) return;
  if(sprx_dlsym(__handle, "8REoLjNGCpM", &__ptr_sceFontGetResolutionDpi)) return;
  if(sprx_dlsym(__handle, "CkVmLoCNN-8", &__ptr_sceFontGetScalePixel)) return;
  if(sprx_dlsym(__handle, "GoF2bhB7LYk", &__ptr_sceFontGetScalePoint)) return;
  if(sprx_dlsym(__handle, "IrXeG0Lc6nA", &__ptr_sceFontGetScriptLanguage)) return;
  if(sprx_dlsym(__handle, "7-miUT6pNQw", &__ptr_sceFontGetTypographicDesign)) return;
  if(sprx_dlsym(__handle, "3BrWWFU+4ts", &__ptr_sceFontGetVerticalLayout)) return;
  if(sprx_dlsym(__handle, "8-zmgsxkBek", &__ptr_sceFontGlyphDefineAttribute)) return;
  if(sprx_dlsym(__handle, "oO33Uex4Ui0", &__ptr_sceFontGlyphGetAttribute)) return;
  if(sprx_dlsym(__handle, "PXlA0M8ax40", &__ptr_sceFontGlyphGetGlyphForm)) return;
  if(sprx_dlsym(__handle, "XUfSWpLhrUw", &__ptr_sceFontGlyphGetMetricsForm)) return;
  if(sprx_dlsym(__handle, "ntrc3bEWlvQ", &__ptr_sceFontGlyphRefersMetrics)) return;
  if(sprx_dlsym(__handle, "9kTbF59TjLs", &__ptr_sceFontGlyphRefersMetricsHorizontal)) return;
  if(sprx_dlsym(__handle, "nJavPEdMDvM", &__ptr_sceFontGlyphRefersMetricsHorizontalAdvance)) return;
  if(sprx_dlsym(__handle, "JCnVgZgcucs", &__ptr_sceFontGlyphRefersMetricsHorizontalX)) return;
  if(sprx_dlsym(__handle, "R1T4i+DOhNY", &__ptr_sceFontGlyphRefersOutline)) return;
  if(sprx_dlsym(__handle, "RmkXfBcZnrM", &__ptr_sceFontGlyphRenderImage)) return;
  if(sprx_dlsym(__handle, "r4KEihtwxGs", &__ptr_sceFontGlyphRenderImageHorizontal)) return;
  if(sprx_dlsym(__handle, "n22d-HIdmMg", &__ptr_sceFontGlyphRenderImageVertical)) return;
  if(sprx_dlsym(__handle, "whrS4oksXc4", &__ptr_sceFontMemoryInit)) return;
  if(sprx_dlsym(__handle, "h6hIgxXEiEc", &__ptr_sceFontMemoryTerm)) return;
  if(sprx_dlsym(__handle, "RvXyHMUiLhE", &__ptr_sceFontOpenFontFile)) return;
  if(sprx_dlsym(__handle, "JzCH3SCFnAU", &__ptr_sceFontOpenFontInstance)) return;
  if(sprx_dlsym(__handle, "KXUpebrFk1U", &__ptr_sceFontOpenFontMemory)) return;
  if(sprx_dlsym(__handle, "cKYtVmeSTcw", &__ptr_sceFontOpenFontSet)) return;
  if(sprx_dlsym(__handle, "Z2cdsqJH+5k", &__ptr_sceFontRebindRenderer)) return;
  if(sprx_dlsym(__handle, "3G4zhgKuxE8", &__ptr_sceFontRenderCharGlyphImage)) return;
  if(sprx_dlsym(__handle, "kAenWy1Zw5o", &__ptr_sceFontRenderCharGlyphImageHorizontal)) return;
  if(sprx_dlsym(__handle, "i6UNdSig1uE", &__ptr_sceFontRenderCharGlyphImageVertical)) return;
  if(sprx_dlsym(__handle, "gdUCnU0gHdI", &__ptr_sceFontRenderSurfaceInit)) return;
  if(sprx_dlsym(__handle, "vRxf4d0ulPs", &__ptr_sceFontRenderSurfaceSetScissor)) return;
  if(sprx_dlsym(__handle, "0hr-w30SjiI", &__ptr_sceFontRenderSurfaceSetStyleFrame)) return;
  if(sprx_dlsym(__handle, "amcmrY62BD4", &__ptr_sceFontRendererGetOutlineBufferSize)) return;
  if(sprx_dlsym(__handle, "ai6AfGrBs4o", &__ptr_sceFontRendererResetOutlineBuffer)) return;
  if(sprx_dlsym(__handle, "ydF+WuH0fAk", &__ptr_sceFontRendererSetOutlineBufferPolicy)) return;
  if(sprx_dlsym(__handle, "TMtqoFQjjbA", &__ptr_sceFontSetEffectSlant)) return;
  if(sprx_dlsym(__handle, "v0phZwa4R5o", &__ptr_sceFontSetEffectWeight)) return;
  if(sprx_dlsym(__handle, "kihFGYJee7o", &__ptr_sceFontSetFontsOpenMode)) return;
  if(sprx_dlsym(__handle, "I1acwR7Qp8E", &__ptr_sceFontSetResolutionDpi)) return;
  if(sprx_dlsym(__handle, "N1EBMeGhf7E", &__ptr_sceFontSetScalePixel)) return;
  if(sprx_dlsym(__handle, "sw65+7wXCKE", &__ptr_sceFontSetScalePoint)) return;
  if(sprx_dlsym(__handle, "PxSR9UfJ+SQ", &__ptr_sceFontSetScriptLanguage)) return;
  if(sprx_dlsym(__handle, "SnsZua35ngs", &__ptr_sceFontSetTypographicDesign)) return;
  if(sprx_dlsym(__handle, "lz9y9UFO2UU", &__ptr_sceFontSetupRenderEffectSlant)) return;
  if(sprx_dlsym(__handle, "XIGorvLusDQ", &__ptr_sceFontSetupRenderEffectWeight)) return;
  if(sprx_dlsym(__handle, "6vGCkkQJOcI", &__ptr_sceFontSetupRenderScalePixel)) return;
  if(sprx_dlsym(__handle, "nMZid4oDfi4", &__ptr_sceFontSetupRenderScalePoint)) return;
  if(sprx_dlsym(__handle, "ObkDGDBsVtw", &__ptr_sceFontStringGetTerminateCode)) return;
  if(sprx_dlsym(__handle, "+B-xlbiWDJ4", &__ptr_sceFontStringGetTerminateOrder)) return;
  if(sprx_dlsym(__handle, "o1vIEHeb6tw", &__ptr_sceFontStringGetWritingForm)) return;
  if(sprx_dlsym(__handle, "hq5LffQjz-s", &__ptr_sceFontStringRefersRenderCharacters)) return;
  if(sprx_dlsym(__handle, "Avv7OApgCJk", &__ptr_sceFontStringRefersTextCharacters)) return;
  if(sprx_dlsym(__handle, "lOfduYnjgbo", &__ptr_sceFontStyleFrameGetEffectSlant)) return;
  if(sprx_dlsym(__handle, "HIUdjR-+Wl8", &__ptr_sceFontStyleFrameGetEffectWeight)) return;
  if(sprx_dlsym(__handle, "VSw18Aqzl0U", &__ptr_sceFontStyleFrameGetResolutionDpi)) return;
  if(sprx_dlsym(__handle, "2QfqfeLblbg", &__ptr_sceFontStyleFrameGetScalePixel)) return;
  if(sprx_dlsym(__handle, "7x2xKiiB7MA", &__ptr_sceFontStyleFrameGetScalePoint)) return;
  if(sprx_dlsym(__handle, "la2AOWnHEAc", &__ptr_sceFontStyleFrameInit)) return;
  if(sprx_dlsym(__handle, "394sckksiCU", &__ptr_sceFontStyleFrameSetEffectSlant)) return;
  if(sprx_dlsym(__handle, "faw77-pEBmU", &__ptr_sceFontStyleFrameSetEffectWeight)) return;
  if(sprx_dlsym(__handle, "dB4-3Wdwls8", &__ptr_sceFontStyleFrameSetResolutionDpi)) return;
  if(sprx_dlsym(__handle, "da4rQ4-+p-4", &__ptr_sceFontStyleFrameSetScalePixel)) return;
  if(sprx_dlsym(__handle, "O997laxY-Ys", &__ptr_sceFontStyleFrameSetScalePoint)) return;
  if(sprx_dlsym(__handle, "dUmABkAnVgk", &__ptr_sceFontStyleFrameUnsetEffectSlant)) return;
  if(sprx_dlsym(__handle, "hwsuXgmKdaw", &__ptr_sceFontStyleFrameUnsetEffectWeight)) return;
  if(sprx_dlsym(__handle, "bePC0L0vQWY", &__ptr_sceFontStyleFrameUnsetScale)) return;
  if(sprx_dlsym(__handle, "mz2iTY0MK4A", &__ptr_sceFontSupportExternalFonts)) return;
  if(sprx_dlsym(__handle, "SsRbbCiWoGw", &__ptr_sceFontSupportSystemFonts)) return;
  if(sprx_dlsym(__handle, "IPoYwwlMx-g", &__ptr_sceFontTextCodesStepBack)) return;
  if(sprx_dlsym(__handle, "olSmXY+XP1E", &__ptr_sceFontTextCodesStepNext)) return;
  if(sprx_dlsym(__handle, "oaJ1BpN2FQk", &__ptr_sceFontTextSourceInit)) return;
  if(sprx_dlsym(__handle, "VRFd3diReec", &__ptr_sceFontTextSourceRewind)) return;
  if(sprx_dlsym(__handle, "eCRMCSk96NU", &__ptr_sceFontTextSourceSetDefaultFont)) return;
  if(sprx_dlsym(__handle, "OqQKX0h5COw", &__ptr_sceFontTextSourceSetWritingForm)) return;
  if(sprx_dlsym(__handle, "1QjhKxrsOB8", &__ptr_sceFontUnbindRenderer)) return;
  if(sprx_dlsym(__handle, "H-FNq8isKE0", &__ptr_sceFontWordsFindWordCharacters)) return;
  if(sprx_dlsym(__handle, "fljdejMcG1c", &__ptr_sceFontWritingGetRenderMetrics)) return;
  if(sprx_dlsym(__handle, "fD5rqhEXKYQ", &__ptr_sceFontWritingInit)) return;
  if(sprx_dlsym(__handle, "1+DgKL0haWQ", &__ptr_sceFontWritingLineClear)) return;
  if(sprx_dlsym(__handle, "JQKWIsS9joE", &__ptr_sceFontWritingLineGetOrderingSpace)) return;
  if(sprx_dlsym(__handle, "nlU2VnfpqTM", &__ptr_sceFontWritingLineGetRenderMetrics)) return;
  if(sprx_dlsym(__handle, "+FYcYefsVX0", &__ptr_sceFontWritingLineRefersRenderStep)) return;
  if(sprx_dlsym(__handle, "wyKFUOWdu3Q", &__ptr_sceFontWritingLineWritesOrder)) return;
  if(sprx_dlsym(__handle, "W-2WOXEHGck", &__ptr_sceFontWritingRefersRenderStep)) return;
  if(sprx_dlsym(__handle, "f4Onl7efPEY", &__ptr_sceFontWritingRefersRenderStepCharacter)) return;
  if(sprx_dlsym(__handle, "BbCZjJizU4A", &__ptr_sceFontWritingSetMaskInvisible)) return;
}

static void __attribute__((destructor(104)))
__destructor(void) {
  sprx_dlclose(__handle);
}
