/*
 This file was generated by genstub.py, do not edit manually!
*/

int sprx_dlsym(unsigned int handle, const char *nid, void *addr);
int sprx_dlopen(const char* libname, unsigned short *handle);
int sprx_dlclose(unsigned int handle);

static __attribute__ ((used)) void* __ptr_sceSystemGestureAppendTouchRecognizer;
asm(".intel_syntax noprefix\n"
    ".global sceSystemGestureAppendTouchRecognizer\n"
    ".type sceSystemGestureAppendTouchRecognizer @function\n"
    "sceSystemGestureAppendTouchRecognizer:\n"
    "jmp qword ptr [rip + __ptr_sceSystemGestureAppendTouchRecognizer]\n");

static __attribute__ ((used)) void* __ptr_sceSystemGestureClose;
asm(".intel_syntax noprefix\n"
    ".global sceSystemGestureClose\n"
    ".type sceSystemGestureClose @function\n"
    "sceSystemGestureClose:\n"
    "jmp qword ptr [rip + __ptr_sceSystemGestureClose]\n");

static __attribute__ ((used)) void* __ptr_sceSystemGestureCreateTouchRecognizer;
asm(".intel_syntax noprefix\n"
    ".global sceSystemGestureCreateTouchRecognizer\n"
    ".type sceSystemGestureCreateTouchRecognizer @function\n"
    "sceSystemGestureCreateTouchRecognizer:\n"
    "jmp qword ptr [rip + __ptr_sceSystemGestureCreateTouchRecognizer]\n");

static __attribute__ ((used)) void* __ptr_sceSystemGestureDebugGetVersion;
asm(".intel_syntax noprefix\n"
    ".global sceSystemGestureDebugGetVersion\n"
    ".type sceSystemGestureDebugGetVersion @function\n"
    "sceSystemGestureDebugGetVersion:\n"
    "jmp qword ptr [rip + __ptr_sceSystemGestureDebugGetVersion]\n");

static __attribute__ ((used)) void* __ptr_sceSystemGestureFinalizePrimitiveTouchRecognizer;
asm(".intel_syntax noprefix\n"
    ".global sceSystemGestureFinalizePrimitiveTouchRecognizer\n"
    ".type sceSystemGestureFinalizePrimitiveTouchRecognizer @function\n"
    "sceSystemGestureFinalizePrimitiveTouchRecognizer:\n"
    "jmp qword ptr [rip + __ptr_sceSystemGestureFinalizePrimitiveTouchRecognizer]\n");

static __attribute__ ((used)) void* __ptr_sceSystemGestureGetPrimitiveTouchEventByIndex;
asm(".intel_syntax noprefix\n"
    ".global sceSystemGestureGetPrimitiveTouchEventByIndex\n"
    ".type sceSystemGestureGetPrimitiveTouchEventByIndex @function\n"
    "sceSystemGestureGetPrimitiveTouchEventByIndex:\n"
    "jmp qword ptr [rip + __ptr_sceSystemGestureGetPrimitiveTouchEventByIndex]\n");

static __attribute__ ((used)) void* __ptr_sceSystemGestureGetPrimitiveTouchEventByPrimitiveID;
asm(".intel_syntax noprefix\n"
    ".global sceSystemGestureGetPrimitiveTouchEventByPrimitiveID\n"
    ".type sceSystemGestureGetPrimitiveTouchEventByPrimitiveID @function\n"
    "sceSystemGestureGetPrimitiveTouchEventByPrimitiveID:\n"
    "jmp qword ptr [rip + __ptr_sceSystemGestureGetPrimitiveTouchEventByPrimitiveID]\n");

static __attribute__ ((used)) void* __ptr_sceSystemGestureGetPrimitiveTouchEvents;
asm(".intel_syntax noprefix\n"
    ".global sceSystemGestureGetPrimitiveTouchEvents\n"
    ".type sceSystemGestureGetPrimitiveTouchEvents @function\n"
    "sceSystemGestureGetPrimitiveTouchEvents:\n"
    "jmp qword ptr [rip + __ptr_sceSystemGestureGetPrimitiveTouchEvents]\n");

static __attribute__ ((used)) void* __ptr_sceSystemGestureGetPrimitiveTouchEventsCount;
asm(".intel_syntax noprefix\n"
    ".global sceSystemGestureGetPrimitiveTouchEventsCount\n"
    ".type sceSystemGestureGetPrimitiveTouchEventsCount @function\n"
    "sceSystemGestureGetPrimitiveTouchEventsCount:\n"
    "jmp qword ptr [rip + __ptr_sceSystemGestureGetPrimitiveTouchEventsCount]\n");

static __attribute__ ((used)) void* __ptr_sceSystemGestureGetTouchEventByEventID;
asm(".intel_syntax noprefix\n"
    ".global sceSystemGestureGetTouchEventByEventID\n"
    ".type sceSystemGestureGetTouchEventByEventID @function\n"
    "sceSystemGestureGetTouchEventByEventID:\n"
    "jmp qword ptr [rip + __ptr_sceSystemGestureGetTouchEventByEventID]\n");

static __attribute__ ((used)) void* __ptr_sceSystemGestureGetTouchEventByIndex;
asm(".intel_syntax noprefix\n"
    ".global sceSystemGestureGetTouchEventByIndex\n"
    ".type sceSystemGestureGetTouchEventByIndex @function\n"
    "sceSystemGestureGetTouchEventByIndex:\n"
    "jmp qword ptr [rip + __ptr_sceSystemGestureGetTouchEventByIndex]\n");

static __attribute__ ((used)) void* __ptr_sceSystemGestureGetTouchEvents;
asm(".intel_syntax noprefix\n"
    ".global sceSystemGestureGetTouchEvents\n"
    ".type sceSystemGestureGetTouchEvents @function\n"
    "sceSystemGestureGetTouchEvents:\n"
    "jmp qword ptr [rip + __ptr_sceSystemGestureGetTouchEvents]\n");

static __attribute__ ((used)) void* __ptr_sceSystemGestureGetTouchEventsCount;
asm(".intel_syntax noprefix\n"
    ".global sceSystemGestureGetTouchEventsCount\n"
    ".type sceSystemGestureGetTouchEventsCount @function\n"
    "sceSystemGestureGetTouchEventsCount:\n"
    "jmp qword ptr [rip + __ptr_sceSystemGestureGetTouchEventsCount]\n");

static __attribute__ ((used)) void* __ptr_sceSystemGestureGetTouchRecognizerInformation;
asm(".intel_syntax noprefix\n"
    ".global sceSystemGestureGetTouchRecognizerInformation\n"
    ".type sceSystemGestureGetTouchRecognizerInformation @function\n"
    "sceSystemGestureGetTouchRecognizerInformation:\n"
    "jmp qword ptr [rip + __ptr_sceSystemGestureGetTouchRecognizerInformation]\n");

static __attribute__ ((used)) void* __ptr_sceSystemGestureInitializePrimitiveTouchRecognizer;
asm(".intel_syntax noprefix\n"
    ".global sceSystemGestureInitializePrimitiveTouchRecognizer\n"
    ".type sceSystemGestureInitializePrimitiveTouchRecognizer @function\n"
    "sceSystemGestureInitializePrimitiveTouchRecognizer:\n"
    "jmp qword ptr [rip + __ptr_sceSystemGestureInitializePrimitiveTouchRecognizer]\n");

static __attribute__ ((used)) void* __ptr_sceSystemGestureOpen;
asm(".intel_syntax noprefix\n"
    ".global sceSystemGestureOpen\n"
    ".type sceSystemGestureOpen @function\n"
    "sceSystemGestureOpen:\n"
    "jmp qword ptr [rip + __ptr_sceSystemGestureOpen]\n");

static __attribute__ ((used)) void* __ptr_sceSystemGestureRemoveTouchRecognizer;
asm(".intel_syntax noprefix\n"
    ".global sceSystemGestureRemoveTouchRecognizer\n"
    ".type sceSystemGestureRemoveTouchRecognizer @function\n"
    "sceSystemGestureRemoveTouchRecognizer:\n"
    "jmp qword ptr [rip + __ptr_sceSystemGestureRemoveTouchRecognizer]\n");

static __attribute__ ((used)) void* __ptr_sceSystemGestureResetPrimitiveTouchRecognizer;
asm(".intel_syntax noprefix\n"
    ".global sceSystemGestureResetPrimitiveTouchRecognizer\n"
    ".type sceSystemGestureResetPrimitiveTouchRecognizer @function\n"
    "sceSystemGestureResetPrimitiveTouchRecognizer:\n"
    "jmp qword ptr [rip + __ptr_sceSystemGestureResetPrimitiveTouchRecognizer]\n");

static __attribute__ ((used)) void* __ptr_sceSystemGestureResetTouchRecognizer;
asm(".intel_syntax noprefix\n"
    ".global sceSystemGestureResetTouchRecognizer\n"
    ".type sceSystemGestureResetTouchRecognizer @function\n"
    "sceSystemGestureResetTouchRecognizer:\n"
    "jmp qword ptr [rip + __ptr_sceSystemGestureResetTouchRecognizer]\n");

static __attribute__ ((used)) void* __ptr_sceSystemGestureUpdateAllTouchRecognizer;
asm(".intel_syntax noprefix\n"
    ".global sceSystemGestureUpdateAllTouchRecognizer\n"
    ".type sceSystemGestureUpdateAllTouchRecognizer @function\n"
    "sceSystemGestureUpdateAllTouchRecognizer:\n"
    "jmp qword ptr [rip + __ptr_sceSystemGestureUpdateAllTouchRecognizer]\n");

static __attribute__ ((used)) void* __ptr_sceSystemGestureUpdatePrimitiveTouchRecognizer;
asm(".intel_syntax noprefix\n"
    ".global sceSystemGestureUpdatePrimitiveTouchRecognizer\n"
    ".type sceSystemGestureUpdatePrimitiveTouchRecognizer @function\n"
    "sceSystemGestureUpdatePrimitiveTouchRecognizer:\n"
    "jmp qword ptr [rip + __ptr_sceSystemGestureUpdatePrimitiveTouchRecognizer]\n");

static __attribute__ ((used)) void* __ptr_sceSystemGestureUpdateTouchRecognizer;
asm(".intel_syntax noprefix\n"
    ".global sceSystemGestureUpdateTouchRecognizer\n"
    ".type sceSystemGestureUpdateTouchRecognizer @function\n"
    "sceSystemGestureUpdateTouchRecognizer:\n"
    "jmp qword ptr [rip + __ptr_sceSystemGestureUpdateTouchRecognizer]\n");

static __attribute__ ((used)) void* __ptr_sceSystemGestureUpdateTouchRecognizerRectangle;
asm(".intel_syntax noprefix\n"
    ".global sceSystemGestureUpdateTouchRecognizerRectangle\n"
    ".type sceSystemGestureUpdateTouchRecognizerRectangle @function\n"
    "sceSystemGestureUpdateTouchRecognizerRectangle:\n"
    "jmp qword ptr [rip + __ptr_sceSystemGestureUpdateTouchRecognizerRectangle]\n");

static unsigned short __handle = 0;
static void __attribute__((constructor(104)))
__constructor(void) {
  if(sprx_dlopen("libSceSystemGesture", &__handle)) return;
  if(sprx_dlsym(__handle, "1MMK0W-kMgA", &__ptr_sceSystemGestureAppendTouchRecognizer)) return;
  if(sprx_dlsym(__handle, "j4yXIA2jJ68", &__ptr_sceSystemGestureClose)) return;
  if(sprx_dlsym(__handle, "FWF8zkhr854", &__ptr_sceSystemGestureCreateTouchRecognizer)) return;
  if(sprx_dlsym(__handle, "-Caws0X3+bY", &__ptr_sceSystemGestureDebugGetVersion)) return;
  if(sprx_dlsym(__handle, "3QYCmMlOlCY", &__ptr_sceSystemGestureFinalizePrimitiveTouchRecognizer)) return;
  if(sprx_dlsym(__handle, "KAeP0+cQPVU", &__ptr_sceSystemGestureGetPrimitiveTouchEventByIndex)) return;
  if(sprx_dlsym(__handle, "yBaQ0h9m1NM", &__ptr_sceSystemGestureGetPrimitiveTouchEventByPrimitiveID)) return;
  if(sprx_dlsym(__handle, "L8YmemOeSNY", &__ptr_sceSystemGestureGetPrimitiveTouchEvents)) return;
  if(sprx_dlsym(__handle, "JhwByySf9FY", &__ptr_sceSystemGestureGetPrimitiveTouchEventsCount)) return;
  if(sprx_dlsym(__handle, "lpsXm7tzeoc", &__ptr_sceSystemGestureGetTouchEventByEventID)) return;
  if(sprx_dlsym(__handle, "TSKvgSz5ChU", &__ptr_sceSystemGestureGetTouchEventByIndex)) return;
  if(sprx_dlsym(__handle, "fLTseA7XiWY", &__ptr_sceSystemGestureGetTouchEvents)) return;
  if(sprx_dlsym(__handle, "h8uongcBNVs", &__ptr_sceSystemGestureGetTouchEventsCount)) return;
  if(sprx_dlsym(__handle, "0KrW5eMnrwY", &__ptr_sceSystemGestureGetTouchRecognizerInformation)) return;
  if(sprx_dlsym(__handle, "3pcAvmwKCvM", &__ptr_sceSystemGestureInitializePrimitiveTouchRecognizer)) return;
  if(sprx_dlsym(__handle, "qpo-mEOwje0", &__ptr_sceSystemGestureOpen)) return;
  if(sprx_dlsym(__handle, "ELvBVG-LKT0", &__ptr_sceSystemGestureRemoveTouchRecognizer)) return;
  if(sprx_dlsym(__handle, "o11J529VaAE", &__ptr_sceSystemGestureResetPrimitiveTouchRecognizer)) return;
  if(sprx_dlsym(__handle, "oBuH3zFWYIg", &__ptr_sceSystemGestureResetTouchRecognizer)) return;
  if(sprx_dlsym(__handle, "wPJGwI2RM2I", &__ptr_sceSystemGestureUpdateAllTouchRecognizer)) return;
  if(sprx_dlsym(__handle, "GgFMb22sbbI", &__ptr_sceSystemGestureUpdatePrimitiveTouchRecognizer)) return;
  if(sprx_dlsym(__handle, "j4h82CQWENo", &__ptr_sceSystemGestureUpdateTouchRecognizer)) return;
  if(sprx_dlsym(__handle, "4WOA1eTx3V8", &__ptr_sceSystemGestureUpdateTouchRecognizerRectangle)) return;
}

static void __attribute__((destructor(104)))
__destructor(void) {
  sprx_dlclose(__handle);
}
