/*
 This file was generated by genstub.py, do not edit manually!
*/

int sprx_dlsym(unsigned int handle, const char *nid, void *addr);
int sprx_dlopen(const char* libname, unsigned short *handle);
int sprx_dlclose(unsigned int handle);

static __attribute__ ((used)) void* __ptr_sceUpsrvGetCompletedTaskId;
asm(".intel_syntax noprefix\n"
    ".global sceUpsrvGetCompletedTaskId\n"
    ".type sceUpsrvGetCompletedTaskId @function\n"
    "sceUpsrvGetCompletedTaskId:\n"
    "jmp qword ptr [rip + __ptr_sceUpsrvGetCompletedTaskId]\n");

static __attribute__ ((used)) void* __ptr_sceUpsrvGetRebootFlag;
asm(".intel_syntax noprefix\n"
    ".global sceUpsrvGetRebootFlag\n"
    ".type sceUpsrvGetRebootFlag @function\n"
    "sceUpsrvGetRebootFlag:\n"
    "jmp qword ptr [rip + __ptr_sceUpsrvGetRebootFlag]\n");

static __attribute__ ((used)) void* __ptr_sceUpsrvGetSystemExUpdateTaskState;
asm(".intel_syntax noprefix\n"
    ".global sceUpsrvGetSystemExUpdateTaskState\n"
    ".type sceUpsrvGetSystemExUpdateTaskState @function\n"
    "sceUpsrvGetSystemExUpdateTaskState:\n"
    "jmp qword ptr [rip + __ptr_sceUpsrvGetSystemExUpdateTaskState]\n");

static __attribute__ ((used)) void* __ptr_sceUpsrvInitialize;
asm(".intel_syntax noprefix\n"
    ".global sceUpsrvInitialize\n"
    ".type sceUpsrvInitialize @function\n"
    "sceUpsrvInitialize:\n"
    "jmp qword ptr [rip + __ptr_sceUpsrvInitialize]\n");

static __attribute__ ((used)) void* __ptr_sceUpsrvPostErrorLog;
asm(".intel_syntax noprefix\n"
    ".global sceUpsrvPostErrorLog\n"
    ".type sceUpsrvPostErrorLog @function\n"
    "sceUpsrvPostErrorLog:\n"
    "jmp qword ptr [rip + __ptr_sceUpsrvPostErrorLog]\n");

static __attribute__ ((used)) void* __ptr_sceUpsrvResumePausedTask;
asm(".intel_syntax noprefix\n"
    ".global sceUpsrvResumePausedTask\n"
    ".type sceUpsrvResumePausedTask @function\n"
    "sceUpsrvResumePausedTask:\n"
    "jmp qword ptr [rip + __ptr_sceUpsrvResumePausedTask]\n");

static __attribute__ ((used)) void* __ptr_sceUpsrvSetFakeVersion;
asm(".intel_syntax noprefix\n"
    ".global sceUpsrvSetFakeVersion\n"
    ".type sceUpsrvSetFakeVersion @function\n"
    "sceUpsrvSetFakeVersion:\n"
    "jmp qword ptr [rip + __ptr_sceUpsrvSetFakeVersion]\n");

static __attribute__ ((used)) void* __ptr_sceUpsrvStartUpdateSession;
asm(".intel_syntax noprefix\n"
    ".global sceUpsrvStartUpdateSession\n"
    ".type sceUpsrvStartUpdateSession @function\n"
    "sceUpsrvStartUpdateSession:\n"
    "jmp qword ptr [rip + __ptr_sceUpsrvStartUpdateSession]\n");

static __attribute__ ((used)) void* __ptr_sceUpsrvSwitchSystemExBank;
asm(".intel_syntax noprefix\n"
    ".global sceUpsrvSwitchSystemExBank\n"
    ".type sceUpsrvSwitchSystemExBank @function\n"
    "sceUpsrvSwitchSystemExBank:\n"
    "jmp qword ptr [rip + __ptr_sceUpsrvSwitchSystemExBank]\n");

static __attribute__ ((used)) void* __ptr_sceUpsrvSwitchSystemExBankWithoutVerify;
asm(".intel_syntax noprefix\n"
    ".global sceUpsrvSwitchSystemExBankWithoutVerify\n"
    ".type sceUpsrvSwitchSystemExBankWithoutVerify @function\n"
    "sceUpsrvSwitchSystemExBankWithoutVerify:\n"
    "jmp qword ptr [rip + __ptr_sceUpsrvSwitchSystemExBankWithoutVerify]\n");

static __attribute__ ((used)) void* __ptr_sceUpsrvTerminate;
asm(".intel_syntax noprefix\n"
    ".global sceUpsrvTerminate\n"
    ".type sceUpsrvTerminate @function\n"
    "sceUpsrvTerminate:\n"
    "jmp qword ptr [rip + __ptr_sceUpsrvTerminate]\n");

static __attribute__ ((used)) void* __ptr_sceUpsrvUpdateCancelBDUpdate;
asm(".intel_syntax noprefix\n"
    ".global sceUpsrvUpdateCancelBDUpdate\n"
    ".type sceUpsrvUpdateCancelBDUpdate @function\n"
    "sceUpsrvUpdateCancelBDUpdate:\n"
    "jmp qword ptr [rip + __ptr_sceUpsrvUpdateCancelBDUpdate]\n");

static __attribute__ ((used)) void* __ptr_sceUpsrvUpdateCheckCancel;
asm(".intel_syntax noprefix\n"
    ".global sceUpsrvUpdateCheckCancel\n"
    ".type sceUpsrvUpdateCheckCancel @function\n"
    "sceUpsrvUpdateCheckCancel:\n"
    "jmp qword ptr [rip + __ptr_sceUpsrvUpdateCheckCancel]\n");

static __attribute__ ((used)) void* __ptr_sceUpsrvUpdateCheckCreateHandler;
asm(".intel_syntax noprefix\n"
    ".global sceUpsrvUpdateCheckCreateHandler\n"
    ".type sceUpsrvUpdateCheckCreateHandler @function\n"
    "sceUpsrvUpdateCheckCreateHandler:\n"
    "jmp qword ptr [rip + __ptr_sceUpsrvUpdateCheckCreateHandler]\n");

static __attribute__ ((used)) void* __ptr_sceUpsrvUpdateCheckDestroyHandler;
asm(".intel_syntax noprefix\n"
    ".global sceUpsrvUpdateCheckDestroyHandler\n"
    ".type sceUpsrvUpdateCheckDestroyHandler @function\n"
    "sceUpsrvUpdateCheckDestroyHandler:\n"
    "jmp qword ptr [rip + __ptr_sceUpsrvUpdateCheckDestroyHandler]\n");

static __attribute__ ((used)) void* __ptr_sceUpsrvUpdateCheckDoCheckSystem;
asm(".intel_syntax noprefix\n"
    ".global sceUpsrvUpdateCheckDoCheckSystem\n"
    ".type sceUpsrvUpdateCheckDoCheckSystem @function\n"
    "sceUpsrvUpdateCheckDoCheckSystem:\n"
    "jmp qword ptr [rip + __ptr_sceUpsrvUpdateCheckDoCheckSystem]\n");

static __attribute__ ((used)) void* __ptr_sceUpsrvUpdateCheckDoCheckSystemForDevKit;
asm(".intel_syntax noprefix\n"
    ".global sceUpsrvUpdateCheckDoCheckSystemForDevKit\n"
    ".type sceUpsrvUpdateCheckDoCheckSystemForDevKit @function\n"
    "sceUpsrvUpdateCheckDoCheckSystemForDevKit:\n"
    "jmp qword ptr [rip + __ptr_sceUpsrvUpdateCheckDoCheckSystemForDevKit]\n");

static __attribute__ ((used)) void* __ptr_sceUpsrvUpdateCheckDoCheckSystemForSettings;
asm(".intel_syntax noprefix\n"
    ".global sceUpsrvUpdateCheckDoCheckSystemForSettings\n"
    ".type sceUpsrvUpdateCheckDoCheckSystemForSettings @function\n"
    "sceUpsrvUpdateCheckDoCheckSystemForSettings:\n"
    "jmp qword ptr [rip + __ptr_sceUpsrvUpdateCheckDoCheckSystemForSettings]\n");

static __attribute__ ((used)) void* __ptr_sceUpsrvUpdateCheckDoCheckSystemWithPupInfo;
asm(".intel_syntax noprefix\n"
    ".global sceUpsrvUpdateCheckDoCheckSystemWithPupInfo\n"
    ".type sceUpsrvUpdateCheckDoCheckSystemWithPupInfo @function\n"
    "sceUpsrvUpdateCheckDoCheckSystemWithPupInfo:\n"
    "jmp qword ptr [rip + __ptr_sceUpsrvUpdateCheckDoCheckSystemWithPupInfo]\n");

static __attribute__ ((used)) void* __ptr_sceUpsrvUpdateCreateUpdateTask;
asm(".intel_syntax noprefix\n"
    ".global sceUpsrvUpdateCreateUpdateTask\n"
    ".type sceUpsrvUpdateCreateUpdateTask @function\n"
    "sceUpsrvUpdateCreateUpdateTask:\n"
    "jmp qword ptr [rip + __ptr_sceUpsrvUpdateCreateUpdateTask]\n");

static __attribute__ ((used)) void* __ptr_sceUpsrvUpdateDestroyUpdateTask;
asm(".intel_syntax noprefix\n"
    ".global sceUpsrvUpdateDestroyUpdateTask\n"
    ".type sceUpsrvUpdateDestroyUpdateTask @function\n"
    "sceUpsrvUpdateDestroyUpdateTask:\n"
    "jmp qword ptr [rip + __ptr_sceUpsrvUpdateDestroyUpdateTask]\n");

static __attribute__ ((used)) void* __ptr_sceUpsrvUpdateDoCheckBootUpdate;
asm(".intel_syntax noprefix\n"
    ".global sceUpsrvUpdateDoCheckBootUpdate\n"
    ".type sceUpsrvUpdateDoCheckBootUpdate @function\n"
    "sceUpsrvUpdateDoCheckBootUpdate:\n"
    "jmp qword ptr [rip + __ptr_sceUpsrvUpdateDoCheckBootUpdate]\n");

static __attribute__ ((used)) void* __ptr_sceUpsrvUpdateDoUpdateSystemEx;
asm(".intel_syntax noprefix\n"
    ".global sceUpsrvUpdateDoUpdateSystemEx\n"
    ".type sceUpsrvUpdateDoUpdateSystemEx @function\n"
    "sceUpsrvUpdateDoUpdateSystemEx:\n"
    "jmp qword ptr [rip + __ptr_sceUpsrvUpdateDoUpdateSystemEx]\n");

static __attribute__ ((used)) void* __ptr_sceUpsrvUpdateDoUpdateWithEntitlement;
asm(".intel_syntax noprefix\n"
    ".global sceUpsrvUpdateDoUpdateWithEntitlement\n"
    ".type sceUpsrvUpdateDoUpdateWithEntitlement @function\n"
    "sceUpsrvUpdateDoUpdateWithEntitlement:\n"
    "jmp qword ptr [rip + __ptr_sceUpsrvUpdateDoUpdateWithEntitlement]\n");

static __attribute__ ((used)) void* __ptr_sceUpsrvUpdateDoUpdateWithPupInfo;
asm(".intel_syntax noprefix\n"
    ".global sceUpsrvUpdateDoUpdateWithPupInfo\n"
    ".type sceUpsrvUpdateDoUpdateWithPupInfo @function\n"
    "sceUpsrvUpdateDoUpdateWithPupInfo:\n"
    "jmp qword ptr [rip + __ptr_sceUpsrvUpdateDoUpdateWithPupInfo]\n");

static __attribute__ ((used)) void* __ptr_sceUpsrvUpdateDoUpdateWithPupPath2;
asm(".intel_syntax noprefix\n"
    ".global sceUpsrvUpdateDoUpdateWithPupPath2\n"
    ".type sceUpsrvUpdateDoUpdateWithPupPath2 @function\n"
    "sceUpsrvUpdateDoUpdateWithPupPath2:\n"
    "jmp qword ptr [rip + __ptr_sceUpsrvUpdateDoUpdateWithPupPath2]\n");

static __attribute__ ((used)) void* __ptr_sceUpsrvUpdateGetBetaAgreementUrl;
asm(".intel_syntax noprefix\n"
    ".global sceUpsrvUpdateGetBetaAgreementUrl\n"
    ".type sceUpsrvUpdateGetBetaAgreementUrl @function\n"
    "sceUpsrvUpdateGetBetaAgreementUrl:\n"
    "jmp qword ptr [rip + __ptr_sceUpsrvUpdateGetBetaAgreementUrl]\n");

static __attribute__ ((used)) void* __ptr_sceUpsrvUpdateGetEulaDisplay;
asm(".intel_syntax noprefix\n"
    ".global sceUpsrvUpdateGetEulaDisplay\n"
    ".type sceUpsrvUpdateGetEulaDisplay @function\n"
    "sceUpsrvUpdateGetEulaDisplay:\n"
    "jmp qword ptr [rip + __ptr_sceUpsrvUpdateGetEulaDisplay]\n");

static __attribute__ ((used)) void* __ptr_sceUpsrvUpdateGetEulaStr;
asm(".intel_syntax noprefix\n"
    ".global sceUpsrvUpdateGetEulaStr\n"
    ".type sceUpsrvUpdateGetEulaStr @function\n"
    "sceUpsrvUpdateGetEulaStr:\n"
    "jmp qword ptr [rip + __ptr_sceUpsrvUpdateGetEulaStr]\n");

static __attribute__ ((used)) void* __ptr_sceUpsrvUpdateGetEulaStrLen;
asm(".intel_syntax noprefix\n"
    ".global sceUpsrvUpdateGetEulaStrLen\n"
    ".type sceUpsrvUpdateGetEulaStrLen @function\n"
    "sceUpsrvUpdateGetEulaStrLen:\n"
    "jmp qword ptr [rip + __ptr_sceUpsrvUpdateGetEulaStrLen]\n");

static __attribute__ ((used)) void* __ptr_sceUpsrvUpdateGetFeatureListUrl;
asm(".intel_syntax noprefix\n"
    ".global sceUpsrvUpdateGetFeatureListUrl\n"
    ".type sceUpsrvUpdateGetFeatureListUrl @function\n"
    "sceUpsrvUpdateGetFeatureListUrl:\n"
    "jmp qword ptr [rip + __ptr_sceUpsrvUpdateGetFeatureListUrl]\n");

static __attribute__ ((used)) void* __ptr_sceUpsrvUpdateGetFeatureListUrlForSystemExUpdate;
asm(".intel_syntax noprefix\n"
    ".global sceUpsrvUpdateGetFeatureListUrlForSystemExUpdate\n"
    ".type sceUpsrvUpdateGetFeatureListUrlForSystemExUpdate @function\n"
    "sceUpsrvUpdateGetFeatureListUrlForSystemExUpdate:\n"
    "jmp qword ptr [rip + __ptr_sceUpsrvUpdateGetFeatureListUrlForSystemExUpdate]\n");

static __attribute__ ((used)) void* __ptr_sceUpsrvUpdateGetFeatureListUrlForUpdate;
asm(".intel_syntax noprefix\n"
    ".global sceUpsrvUpdateGetFeatureListUrlForUpdate\n"
    ".type sceUpsrvUpdateGetFeatureListUrlForUpdate @function\n"
    "sceUpsrvUpdateGetFeatureListUrlForUpdate:\n"
    "jmp qword ptr [rip + __ptr_sceUpsrvUpdateGetFeatureListUrlForUpdate]\n");

static __attribute__ ((used)) void* __ptr_sceUpsrvUpdateGetImageWritingProgress;
asm(".intel_syntax noprefix\n"
    ".global sceUpsrvUpdateGetImageWritingProgress\n"
    ".type sceUpsrvUpdateGetImageWritingProgress @function\n"
    "sceUpsrvUpdateGetImageWritingProgress:\n"
    "jmp qword ptr [rip + __ptr_sceUpsrvUpdateGetImageWritingProgress]\n");

static __attribute__ ((used)) void* __ptr_sceUpsrvUpdateGetProgress;
asm(".intel_syntax noprefix\n"
    ".global sceUpsrvUpdateGetProgress\n"
    ".type sceUpsrvUpdateGetProgress @function\n"
    "sceUpsrvUpdateGetProgress:\n"
    "jmp qword ptr [rip + __ptr_sceUpsrvUpdateGetProgress]\n");

static __attribute__ ((used)) void* __ptr_sceUpsrvUpdateGetUpdateTaskInfo;
asm(".intel_syntax noprefix\n"
    ".global sceUpsrvUpdateGetUpdateTaskInfo\n"
    ".type sceUpsrvUpdateGetUpdateTaskInfo @function\n"
    "sceUpsrvUpdateGetUpdateTaskInfo:\n"
    "jmp qword ptr [rip + __ptr_sceUpsrvUpdateGetUpdateTaskInfo]\n");

static __attribute__ ((used)) void* __ptr_sceUpsrvUpdateGetUpdateTaskMgrInfo;
asm(".intel_syntax noprefix\n"
    ".global sceUpsrvUpdateGetUpdateTaskMgrInfo\n"
    ".type sceUpsrvUpdateGetUpdateTaskMgrInfo @function\n"
    "sceUpsrvUpdateGetUpdateTaskMgrInfo:\n"
    "jmp qword ptr [rip + __ptr_sceUpsrvUpdateGetUpdateTaskMgrInfo]\n");

static __attribute__ ((used)) void* __ptr_sceUpsrvUpdateSetEulaAccept;
asm(".intel_syntax noprefix\n"
    ".global sceUpsrvUpdateSetEulaAccept\n"
    ".type sceUpsrvUpdateSetEulaAccept @function\n"
    "sceUpsrvUpdateSetEulaAccept:\n"
    "jmp qword ptr [rip + __ptr_sceUpsrvUpdateSetEulaAccept]\n");

static __attribute__ ((used)) void* __ptr_sceUpsrvUpdateStartUpdateTask;
asm(".intel_syntax noprefix\n"
    ".global sceUpsrvUpdateStartUpdateTask\n"
    ".type sceUpsrvUpdateStartUpdateTask @function\n"
    "sceUpsrvUpdateStartUpdateTask:\n"
    "jmp qword ptr [rip + __ptr_sceUpsrvUpdateStartUpdateTask]\n");

static __attribute__ ((used)) void* __ptr_sceUpsrvVerifySystemExBank;
asm(".intel_syntax noprefix\n"
    ".global sceUpsrvVerifySystemExBank\n"
    ".type sceUpsrvVerifySystemExBank @function\n"
    "sceUpsrvVerifySystemExBank:\n"
    "jmp qword ptr [rip + __ptr_sceUpsrvVerifySystemExBank]\n");

static unsigned short __handle = 0;
static void __attribute__((constructor(104)))
__constructor(void) {
  if(sprx_dlopen("libSceUpdateService", &__handle)) return;
  if(sprx_dlsym(__handle, "TvLOxBx5J-Q", &__ptr_sceUpsrvGetCompletedTaskId)) return;
  if(sprx_dlsym(__handle, "rb+XR5iVTV0", &__ptr_sceUpsrvGetRebootFlag)) return;
  if(sprx_dlsym(__handle, "TIr3rnF-1RA", &__ptr_sceUpsrvGetSystemExUpdateTaskState)) return;
  if(sprx_dlsym(__handle, "IOC0zyNzTM0", &__ptr_sceUpsrvInitialize)) return;
  if(sprx_dlsym(__handle, "1wMKF3L2PXU", &__ptr_sceUpsrvPostErrorLog)) return;
  if(sprx_dlsym(__handle, "oVgyCJCrGcY", &__ptr_sceUpsrvResumePausedTask)) return;
  if(sprx_dlsym(__handle, "lOitg3BrGSw", &__ptr_sceUpsrvSetFakeVersion)) return;
  if(sprx_dlsym(__handle, "Bh-+3oc6euE", &__ptr_sceUpsrvStartUpdateSession)) return;
  if(sprx_dlsym(__handle, "p9bBXbQwjqY", &__ptr_sceUpsrvSwitchSystemExBank)) return;
  if(sprx_dlsym(__handle, "jPd1vzuldfM", &__ptr_sceUpsrvSwitchSystemExBankWithoutVerify)) return;
  if(sprx_dlsym(__handle, "z6eXJFh2VAE", &__ptr_sceUpsrvTerminate)) return;
  if(sprx_dlsym(__handle, "7krELEpl+Y0", &__ptr_sceUpsrvUpdateCancelBDUpdate)) return;
  if(sprx_dlsym(__handle, "Ayjio+cfSFA", &__ptr_sceUpsrvUpdateCheckCancel)) return;
  if(sprx_dlsym(__handle, "H+3rEYCIICE", &__ptr_sceUpsrvUpdateCheckCreateHandler)) return;
  if(sprx_dlsym(__handle, "CweVdHVfxDQ", &__ptr_sceUpsrvUpdateCheckDestroyHandler)) return;
  if(sprx_dlsym(__handle, "aosLBGaeOtw", &__ptr_sceUpsrvUpdateCheckDoCheckSystem)) return;
  if(sprx_dlsym(__handle, "CoTbY7roruU", &__ptr_sceUpsrvUpdateCheckDoCheckSystemForDevKit)) return;
  if(sprx_dlsym(__handle, "fh09rY0ltb8", &__ptr_sceUpsrvUpdateCheckDoCheckSystemForSettings)) return;
  if(sprx_dlsym(__handle, "NqCD8n5dq+Y", &__ptr_sceUpsrvUpdateCheckDoCheckSystemWithPupInfo)) return;
  if(sprx_dlsym(__handle, "glX67PWaF-g", &__ptr_sceUpsrvUpdateCreateUpdateTask)) return;
  if(sprx_dlsym(__handle, "aYBAAH7Gfws", &__ptr_sceUpsrvUpdateDestroyUpdateTask)) return;
  if(sprx_dlsym(__handle, "dsC4xos42zM", &__ptr_sceUpsrvUpdateDoCheckBootUpdate)) return;
  if(sprx_dlsym(__handle, "sYSfAewkXkU", &__ptr_sceUpsrvUpdateDoUpdateSystemEx)) return;
  if(sprx_dlsym(__handle, "pMqmEivov4M", &__ptr_sceUpsrvUpdateDoUpdateWithEntitlement)) return;
  if(sprx_dlsym(__handle, "z3HMx6djzdM", &__ptr_sceUpsrvUpdateDoUpdateWithPupInfo)) return;
  if(sprx_dlsym(__handle, "dtV1Zqx4jU0", &__ptr_sceUpsrvUpdateDoUpdateWithPupPath2)) return;
  if(sprx_dlsym(__handle, "WhilT63upyA", &__ptr_sceUpsrvUpdateGetBetaAgreementUrl)) return;
  if(sprx_dlsym(__handle, "2CeEvU+2VzY", &__ptr_sceUpsrvUpdateGetEulaDisplay)) return;
  if(sprx_dlsym(__handle, "gW9NKRTJrvE", &__ptr_sceUpsrvUpdateGetEulaStr)) return;
  if(sprx_dlsym(__handle, "M7FIVsvMulQ", &__ptr_sceUpsrvUpdateGetEulaStrLen)) return;
  if(sprx_dlsym(__handle, "d1dupKoGH1Q", &__ptr_sceUpsrvUpdateGetFeatureListUrl)) return;
  if(sprx_dlsym(__handle, "8gps121HPSU", &__ptr_sceUpsrvUpdateGetFeatureListUrlForSystemExUpdate)) return;
  if(sprx_dlsym(__handle, "EZqxQRb1foc", &__ptr_sceUpsrvUpdateGetFeatureListUrlForUpdate)) return;
  if(sprx_dlsym(__handle, "eU-ln60CLMs", &__ptr_sceUpsrvUpdateGetImageWritingProgress)) return;
  if(sprx_dlsym(__handle, "IVd2CCSrXzY", &__ptr_sceUpsrvUpdateGetProgress)) return;
  if(sprx_dlsym(__handle, "b-w9zKxBi7E", &__ptr_sceUpsrvUpdateGetUpdateTaskInfo)) return;
  if(sprx_dlsym(__handle, "UrN6mFAbgbA", &__ptr_sceUpsrvUpdateGetUpdateTaskMgrInfo)) return;
  if(sprx_dlsym(__handle, "Ycun7TYB2+Q", &__ptr_sceUpsrvUpdateSetEulaAccept)) return;
  if(sprx_dlsym(__handle, "W+-F1p6av2g", &__ptr_sceUpsrvUpdateStartUpdateTask)) return;
  if(sprx_dlsym(__handle, "-3KN5+5cUf8", &__ptr_sceUpsrvVerifySystemExBank)) return;
}

static void __attribute__((destructor(104)))
__destructor(void) {
  sprx_dlclose(__handle);
}
