/*
 This file was generated by genstub.py, do not edit manually!
*/

int sprx_dlsym(unsigned int handle, const char *nid, void *addr);
int sprx_dlopen(const char* libname, unsigned short *handle);
int sprx_dlclose(unsigned int handle);

static __attribute__ ((used)) void* __ptr_sceSysUtilSendAddressingSystemNotification;
asm(".intel_syntax noprefix\n"
    ".global sceSysUtilSendAddressingSystemNotification\n"
    ".type sceSysUtilSendAddressingSystemNotification @function\n"
    "sceSysUtilSendAddressingSystemNotification:\n"
    "jmp qword ptr [rip + __ptr_sceSysUtilSendAddressingSystemNotification]\n");

static __attribute__ ((used)) void* __ptr_sceSysUtilSendAddressingSystemNotificationWithDeviceId;
asm(".intel_syntax noprefix\n"
    ".global sceSysUtilSendAddressingSystemNotificationWithDeviceId\n"
    ".type sceSysUtilSendAddressingSystemNotificationWithDeviceId @function\n"
    "sceSysUtilSendAddressingSystemNotificationWithDeviceId:\n"
    "jmp qword ptr [rip + __ptr_sceSysUtilSendAddressingSystemNotificationWithDeviceId]\n");

static __attribute__ ((used)) void* __ptr_sceSysUtilSendAddressingSystemNotificationWithUserId;
asm(".intel_syntax noprefix\n"
    ".global sceSysUtilSendAddressingSystemNotificationWithUserId\n"
    ".type sceSysUtilSendAddressingSystemNotificationWithUserId @function\n"
    "sceSysUtilSendAddressingSystemNotificationWithUserId:\n"
    "jmp qword ptr [rip + __ptr_sceSysUtilSendAddressingSystemNotificationWithUserId]\n");

static __attribute__ ((used)) void* __ptr_sceSysUtilSendAddressingSystemNotificationWithUserName;
asm(".intel_syntax noprefix\n"
    ".global sceSysUtilSendAddressingSystemNotificationWithUserName\n"
    ".type sceSysUtilSendAddressingSystemNotificationWithUserName @function\n"
    "sceSysUtilSendAddressingSystemNotificationWithUserName:\n"
    "jmp qword ptr [rip + __ptr_sceSysUtilSendAddressingSystemNotificationWithUserName]\n");

static __attribute__ ((used)) void* __ptr_sceSysUtilSendNotificationRequest;
asm(".intel_syntax noprefix\n"
    ".global sceSysUtilSendNotificationRequest\n"
    ".type sceSysUtilSendNotificationRequest @function\n"
    "sceSysUtilSendNotificationRequest:\n"
    "jmp qword ptr [rip + __ptr_sceSysUtilSendNotificationRequest]\n");

static __attribute__ ((used)) void* __ptr_sceSysUtilSendNpDebugNotificationRequest;
asm(".intel_syntax noprefix\n"
    ".global sceSysUtilSendNpDebugNotificationRequest\n"
    ".type sceSysUtilSendNpDebugNotificationRequest @function\n"
    "sceSysUtilSendNpDebugNotificationRequest:\n"
    "jmp qword ptr [rip + __ptr_sceSysUtilSendNpDebugNotificationRequest]\n");

static __attribute__ ((used)) void* __ptr_sceSysUtilSendSystemNotification;
asm(".intel_syntax noprefix\n"
    ".global sceSysUtilSendSystemNotification\n"
    ".type sceSysUtilSendSystemNotification @function\n"
    "sceSysUtilSendSystemNotification:\n"
    "jmp qword ptr [rip + __ptr_sceSysUtilSendSystemNotification]\n");

static __attribute__ ((used)) void* __ptr_sceSysUtilSendSystemNotification2;
asm(".intel_syntax noprefix\n"
    ".global sceSysUtilSendSystemNotification2\n"
    ".type sceSysUtilSendSystemNotification2 @function\n"
    "sceSysUtilSendSystemNotification2:\n"
    "jmp qword ptr [rip + __ptr_sceSysUtilSendSystemNotification2]\n");

static __attribute__ ((used)) void* __ptr_sceSysUtilSendSystemNotificationParamInit;
asm(".intel_syntax noprefix\n"
    ".global sceSysUtilSendSystemNotificationParamInit\n"
    ".type sceSysUtilSendSystemNotificationParamInit @function\n"
    "sceSysUtilSendSystemNotificationParamInit:\n"
    "jmp qword ptr [rip + __ptr_sceSysUtilSendSystemNotificationParamInit]\n");

static __attribute__ ((used)) void* __ptr_sceSysUtilSendSystemNotificationWithAppId;
asm(".intel_syntax noprefix\n"
    ".global sceSysUtilSendSystemNotificationWithAppId\n"
    ".type sceSysUtilSendSystemNotificationWithAppId @function\n"
    "sceSysUtilSendSystemNotificationWithAppId:\n"
    "jmp qword ptr [rip + __ptr_sceSysUtilSendSystemNotificationWithAppId]\n");

static __attribute__ ((used)) void* __ptr_sceSysUtilSendSystemNotificationWithAppInfo;
asm(".intel_syntax noprefix\n"
    ".global sceSysUtilSendSystemNotificationWithAppInfo\n"
    ".type sceSysUtilSendSystemNotificationWithAppInfo @function\n"
    "sceSysUtilSendSystemNotificationWithAppInfo:\n"
    "jmp qword ptr [rip + __ptr_sceSysUtilSendSystemNotificationWithAppInfo]\n");

static __attribute__ ((used)) void* __ptr_sceSysUtilSendSystemNotificationWithAppName;
asm(".intel_syntax noprefix\n"
    ".global sceSysUtilSendSystemNotificationWithAppName\n"
    ".type sceSysUtilSendSystemNotificationWithAppName @function\n"
    "sceSysUtilSendSystemNotificationWithAppName:\n"
    "jmp qword ptr [rip + __ptr_sceSysUtilSendSystemNotificationWithAppName]\n");

static __attribute__ ((used)) void* __ptr_sceSysUtilSendSystemNotificationWithAppNameRelatedToUser;
asm(".intel_syntax noprefix\n"
    ".global sceSysUtilSendSystemNotificationWithAppNameRelatedToUser\n"
    ".type sceSysUtilSendSystemNotificationWithAppNameRelatedToUser @function\n"
    "sceSysUtilSendSystemNotificationWithAppNameRelatedToUser:\n"
    "jmp qword ptr [rip + __ptr_sceSysUtilSendSystemNotificationWithAppNameRelatedToUser]\n");

static __attribute__ ((used)) void* __ptr_sceSysUtilSendSystemNotificationWithDeviceId;
asm(".intel_syntax noprefix\n"
    ".global sceSysUtilSendSystemNotificationWithDeviceId\n"
    ".type sceSysUtilSendSystemNotificationWithDeviceId @function\n"
    "sceSysUtilSendSystemNotificationWithDeviceId:\n"
    "jmp qword ptr [rip + __ptr_sceSysUtilSendSystemNotificationWithDeviceId]\n");

static __attribute__ ((used)) void* __ptr_sceSysUtilSendSystemNotificationWithDeviceIdRelatedToUser;
asm(".intel_syntax noprefix\n"
    ".global sceSysUtilSendSystemNotificationWithDeviceIdRelatedToUser\n"
    ".type sceSysUtilSendSystemNotificationWithDeviceIdRelatedToUser @function\n"
    "sceSysUtilSendSystemNotificationWithDeviceIdRelatedToUser:\n"
    "jmp qword ptr [rip + __ptr_sceSysUtilSendSystemNotificationWithDeviceIdRelatedToUser]\n");

static __attribute__ ((used)) void* __ptr_sceSysUtilSendSystemNotificationWithErrorCode;
asm(".intel_syntax noprefix\n"
    ".global sceSysUtilSendSystemNotificationWithErrorCode\n"
    ".type sceSysUtilSendSystemNotificationWithErrorCode @function\n"
    "sceSysUtilSendSystemNotificationWithErrorCode:\n"
    "jmp qword ptr [rip + __ptr_sceSysUtilSendSystemNotificationWithErrorCode]\n");

static __attribute__ ((used)) void* __ptr_sceSysUtilSendSystemNotificationWithParams;
asm(".intel_syntax noprefix\n"
    ".global sceSysUtilSendSystemNotificationWithParams\n"
    ".type sceSysUtilSendSystemNotificationWithParams @function\n"
    "sceSysUtilSendSystemNotificationWithParams:\n"
    "jmp qword ptr [rip + __ptr_sceSysUtilSendSystemNotificationWithParams]\n");

static __attribute__ ((used)) void* __ptr_sceSysUtilSendSystemNotificationWithText;
asm(".intel_syntax noprefix\n"
    ".global sceSysUtilSendSystemNotificationWithText\n"
    ".type sceSysUtilSendSystemNotificationWithText @function\n"
    "sceSysUtilSendSystemNotificationWithText:\n"
    "jmp qword ptr [rip + __ptr_sceSysUtilSendSystemNotificationWithText]\n");

static __attribute__ ((used)) void* __ptr_sceSysUtilSendSystemNotificationWithTextRelatedToUser;
asm(".intel_syntax noprefix\n"
    ".global sceSysUtilSendSystemNotificationWithTextRelatedToUser\n"
    ".type sceSysUtilSendSystemNotificationWithTextRelatedToUser @function\n"
    "sceSysUtilSendSystemNotificationWithTextRelatedToUser:\n"
    "jmp qword ptr [rip + __ptr_sceSysUtilSendSystemNotificationWithTextRelatedToUser]\n");

static __attribute__ ((used)) void* __ptr_sceSysUtilSendSystemNotificationWithUserId;
asm(".intel_syntax noprefix\n"
    ".global sceSysUtilSendSystemNotificationWithUserId\n"
    ".type sceSysUtilSendSystemNotificationWithUserId @function\n"
    "sceSysUtilSendSystemNotificationWithUserId:\n"
    "jmp qword ptr [rip + __ptr_sceSysUtilSendSystemNotificationWithUserId]\n");

static __attribute__ ((used)) void* __ptr_sceSysUtilSendSystemNotificationWithUserName;
asm(".intel_syntax noprefix\n"
    ".global sceSysUtilSendSystemNotificationWithUserName\n"
    ".type sceSysUtilSendSystemNotificationWithUserName @function\n"
    "sceSysUtilSendSystemNotificationWithUserName:\n"
    "jmp qword ptr [rip + __ptr_sceSysUtilSendSystemNotificationWithUserName]\n");

static __attribute__ ((used)) void* __ptr_sceSysUtilSendSystemNotificationWithUserNameInfo;
asm(".intel_syntax noprefix\n"
    ".global sceSysUtilSendSystemNotificationWithUserNameInfo\n"
    ".type sceSysUtilSendSystemNotificationWithUserNameInfo @function\n"
    "sceSysUtilSendSystemNotificationWithUserNameInfo:\n"
    "jmp qword ptr [rip + __ptr_sceSysUtilSendSystemNotificationWithUserNameInfo]\n");

static __attribute__ ((used)) void* __ptr_sceSysUtilSendTrcCheckNotificationRequest;
asm(".intel_syntax noprefix\n"
    ".global sceSysUtilSendTrcCheckNotificationRequest\n"
    ".type sceSysUtilSendTrcCheckNotificationRequest @function\n"
    "sceSysUtilSendTrcCheckNotificationRequest:\n"
    "jmp qword ptr [rip + __ptr_sceSysUtilSendTrcCheckNotificationRequest]\n");

static __attribute__ ((used)) void* __ptr_sceSysUtilSendWebDebugNotificationRequest;
asm(".intel_syntax noprefix\n"
    ".global sceSysUtilSendWebDebugNotificationRequest\n"
    ".type sceSysUtilSendWebDebugNotificationRequest @function\n"
    "sceSysUtilSendWebDebugNotificationRequest:\n"
    "jmp qword ptr [rip + __ptr_sceSysUtilSendWebDebugNotificationRequest]\n");

static unsigned short __handle = 0;
static void __attribute__((constructor(104)))
__constructor(void) {
  if(sprx_dlopen("libSceSysUtil", &__handle)) return;
  if(sprx_dlsym(__handle, "TnvxGzkFmbo", &__ptr_sceSysUtilSendAddressingSystemNotification)) return;
  if(sprx_dlsym(__handle, "yKfATNkQZdc", &__ptr_sceSysUtilSendAddressingSystemNotificationWithDeviceId)) return;
  if(sprx_dlsym(__handle, "BgOJY0UvOQ4", &__ptr_sceSysUtilSendAddressingSystemNotificationWithUserId)) return;
  if(sprx_dlsym(__handle, "VHGBWkTe0Jg", &__ptr_sceSysUtilSendAddressingSystemNotificationWithUserName)) return;
  if(sprx_dlsym(__handle, "AAk6w60xP3A", &__ptr_sceSysUtilSendNotificationRequest)) return;
  if(sprx_dlsym(__handle, "Eu7QNB9x1r0", &__ptr_sceSysUtilSendNpDebugNotificationRequest)) return;
  if(sprx_dlsym(__handle, "jTNAhVZ-5Nc", &__ptr_sceSysUtilSendSystemNotification)) return;
  if(sprx_dlsym(__handle, "f21DEbadT98", &__ptr_sceSysUtilSendSystemNotification2)) return;
  if(sprx_dlsym(__handle, "-+7YODtoVLM", &__ptr_sceSysUtilSendSystemNotificationParamInit)) return;
  if(sprx_dlsym(__handle, "KQxuDpbldZs", &__ptr_sceSysUtilSendSystemNotificationWithAppId)) return;
  if(sprx_dlsym(__handle, "3vHcGnZpiN8", &__ptr_sceSysUtilSendSystemNotificationWithAppInfo)) return;
  if(sprx_dlsym(__handle, "N4AToF3po08", &__ptr_sceSysUtilSendSystemNotificationWithAppName)) return;
  if(sprx_dlsym(__handle, "+RZFlwV4k3I", &__ptr_sceSysUtilSendSystemNotificationWithAppNameRelatedToUser)) return;
  if(sprx_dlsym(__handle, "SxYUo6o6mjo", &__ptr_sceSysUtilSendSystemNotificationWithDeviceId)) return;
  if(sprx_dlsym(__handle, "ISeIA7PBwyc", &__ptr_sceSysUtilSendSystemNotificationWithDeviceIdRelatedToUser)) return;
  if(sprx_dlsym(__handle, "iSlI1LKy7Bg", &__ptr_sceSysUtilSendSystemNotificationWithErrorCode)) return;
  if(sprx_dlsym(__handle, "AodT6gE5Qpk", &__ptr_sceSysUtilSendSystemNotificationWithParams)) return;
  if(sprx_dlsym(__handle, "Btgtlzfk9EQ", &__ptr_sceSysUtilSendSystemNotificationWithText)) return;
  if(sprx_dlsym(__handle, "HJyZ8CZGVoY", &__ptr_sceSysUtilSendSystemNotificationWithTextRelatedToUser)) return;
  if(sprx_dlsym(__handle, "YbAfwT8fO7Q", &__ptr_sceSysUtilSendSystemNotificationWithUserId)) return;
  if(sprx_dlsym(__handle, "DC2NSz1IDyk", &__ptr_sceSysUtilSendSystemNotificationWithUserName)) return;
  if(sprx_dlsym(__handle, "Kl9aRhwtXBM", &__ptr_sceSysUtilSendSystemNotificationWithUserNameInfo)) return;
  if(sprx_dlsym(__handle, "-0FdPC78x7U", &__ptr_sceSysUtilSendTrcCheckNotificationRequest)) return;
  if(sprx_dlsym(__handle, "V+TVN7J5JbA", &__ptr_sceSysUtilSendWebDebugNotificationRequest)) return;
}

static void __attribute__((destructor(104)))
__destructor(void) {
  sprx_dlclose(__handle);
}
