/*
 This file was generated by genstub.py, do not edit manually!
*/

int sprx_dlsym(unsigned int handle, const char *nid, void *addr);
int sprx_dlopen(const char* libname, unsigned short *handle);
int sprx_dlclose(unsigned int handle);

static __attribute__ ((used)) void* __ptr_sceVideodecCreateDecoder;
asm(".intel_syntax noprefix\n"
    ".global sceVideodecCreateDecoder\n"
    ".type sceVideodecCreateDecoder @function\n"
    "sceVideodecCreateDecoder:\n"
    "jmp qword ptr [rip + __ptr_sceVideodecCreateDecoder]\n");

static __attribute__ ((used)) void* __ptr_sceVideodecDecode;
asm(".intel_syntax noprefix\n"
    ".global sceVideodecDecode\n"
    ".type sceVideodecDecode @function\n"
    "sceVideodecDecode:\n"
    "jmp qword ptr [rip + __ptr_sceVideodecDecode]\n");

static __attribute__ ((used)) void* __ptr_sceVideodecDeleteDecoder;
asm(".intel_syntax noprefix\n"
    ".global sceVideodecDeleteDecoder\n"
    ".type sceVideodecDeleteDecoder @function\n"
    "sceVideodecDeleteDecoder:\n"
    "jmp qword ptr [rip + __ptr_sceVideodecDeleteDecoder]\n");

static __attribute__ ((used)) void* __ptr_sceVideodecFlush;
asm(".intel_syntax noprefix\n"
    ".global sceVideodecFlush\n"
    ".type sceVideodecFlush @function\n"
    "sceVideodecFlush:\n"
    "jmp qword ptr [rip + __ptr_sceVideodecFlush]\n");

static __attribute__ ((used)) void* __ptr_sceVideodecMapMemory;
asm(".intel_syntax noprefix\n"
    ".global sceVideodecMapMemory\n"
    ".type sceVideodecMapMemory @function\n"
    "sceVideodecMapMemory:\n"
    "jmp qword ptr [rip + __ptr_sceVideodecMapMemory]\n");

static __attribute__ ((used)) void* __ptr_sceVideodecQueryResourceInfo;
asm(".intel_syntax noprefix\n"
    ".global sceVideodecQueryResourceInfo\n"
    ".type sceVideodecQueryResourceInfo @function\n"
    "sceVideodecQueryResourceInfo:\n"
    "jmp qword ptr [rip + __ptr_sceVideodecQueryResourceInfo]\n");

static __attribute__ ((used)) void* __ptr_sceVideodecReset;
asm(".intel_syntax noprefix\n"
    ".global sceVideodecReset\n"
    ".type sceVideodecReset @function\n"
    "sceVideodecReset:\n"
    "jmp qword ptr [rip + __ptr_sceVideodecReset]\n");

static unsigned short __handle = 0;
static void __attribute__((constructor(104)))
__constructor(void) {
  if(sprx_dlopen("libSceVideodec", &__handle)) return;
  if(sprx_dlsym(__handle, "qkgRiwHyheU", &__ptr_sceVideodecCreateDecoder)) return;
  if(sprx_dlsym(__handle, "q0W5GJMovMs", &__ptr_sceVideodecDecode)) return;
  if(sprx_dlsym(__handle, "U0kpGF1cl90", &__ptr_sceVideodecDeleteDecoder)) return;
  if(sprx_dlsym(__handle, "jeigLlKdp5I", &__ptr_sceVideodecFlush)) return;
  if(sprx_dlsym(__handle, "kg+lH0V61hM", &__ptr_sceVideodecMapMemory)) return;
  if(sprx_dlsym(__handle, "leCAscipfFY", &__ptr_sceVideodecQueryResourceInfo)) return;
  if(sprx_dlsym(__handle, "f8AgDv-1X8A", &__ptr_sceVideodecReset)) return;
}

static void __attribute__((destructor(104)))
__destructor(void) {
  sprx_dlclose(__handle);
}
