/*
 This file was generated by genstub.py, do not edit manually!
*/

int sprx_dlsym(unsigned int handle, const char *nid, void *addr);
int sprx_dlopen(const char* libname, unsigned short *handle);
int sprx_dlclose(unsigned int handle);

static __attribute__ ((used)) void* __ptr_sceVideoRecordingClose;
asm(".intel_syntax noprefix\n"
    ".global sceVideoRecordingClose\n"
    ".type sceVideoRecordingClose @function\n"
    "sceVideoRecordingClose:\n"
    "jmp qword ptr [rip + __ptr_sceVideoRecordingClose]\n");

static __attribute__ ((used)) void* __ptr_sceVideoRecordingCopyBGRAtoNV12;
asm(".intel_syntax noprefix\n"
    ".global sceVideoRecordingCopyBGRAtoNV12\n"
    ".type sceVideoRecordingCopyBGRAtoNV12 @function\n"
    "sceVideoRecordingCopyBGRAtoNV12:\n"
    "jmp qword ptr [rip + __ptr_sceVideoRecordingCopyBGRAtoNV12]\n");

static __attribute__ ((used)) void* __ptr_sceVideoRecordingGetInfo;
asm(".intel_syntax noprefix\n"
    ".global sceVideoRecordingGetInfo\n"
    ".type sceVideoRecordingGetInfo @function\n"
    "sceVideoRecordingGetInfo:\n"
    "jmp qword ptr [rip + __ptr_sceVideoRecordingGetInfo]\n");

static __attribute__ ((used)) void* __ptr_sceVideoRecordingGetStatus;
asm(".intel_syntax noprefix\n"
    ".global sceVideoRecordingGetStatus\n"
    ".type sceVideoRecordingGetStatus @function\n"
    "sceVideoRecordingGetStatus:\n"
    "jmp qword ptr [rip + __ptr_sceVideoRecordingGetStatus]\n");

static __attribute__ ((used)) void* __ptr_sceVideoRecordingInit;
asm(".intel_syntax noprefix\n"
    ".global sceVideoRecordingInit\n"
    ".type sceVideoRecordingInit @function\n"
    "sceVideoRecordingInit:\n"
    "jmp qword ptr [rip + __ptr_sceVideoRecordingInit]\n");

static __attribute__ ((used)) void* __ptr_sceVideoRecordingOpen;
asm(".intel_syntax noprefix\n"
    ".global sceVideoRecordingOpen\n"
    ".type sceVideoRecordingOpen @function\n"
    "sceVideoRecordingOpen:\n"
    "jmp qword ptr [rip + __ptr_sceVideoRecordingOpen]\n");

static __attribute__ ((used)) void* __ptr_sceVideoRecordingOpen2;
asm(".intel_syntax noprefix\n"
    ".global sceVideoRecordingOpen2\n"
    ".type sceVideoRecordingOpen2 @function\n"
    "sceVideoRecordingOpen2:\n"
    "jmp qword ptr [rip + __ptr_sceVideoRecordingOpen2]\n");

static __attribute__ ((used)) void* __ptr_sceVideoRecordingQueryHddSize2;
asm(".intel_syntax noprefix\n"
    ".global sceVideoRecordingQueryHddSize2\n"
    ".type sceVideoRecordingQueryHddSize2 @function\n"
    "sceVideoRecordingQueryHddSize2:\n"
    "jmp qword ptr [rip + __ptr_sceVideoRecordingQueryHddSize2]\n");

static __attribute__ ((used)) void* __ptr_sceVideoRecordingQueryMemSize;
asm(".intel_syntax noprefix\n"
    ".global sceVideoRecordingQueryMemSize\n"
    ".type sceVideoRecordingQueryMemSize @function\n"
    "sceVideoRecordingQueryMemSize:\n"
    "jmp qword ptr [rip + __ptr_sceVideoRecordingQueryMemSize]\n");

static __attribute__ ((used)) void* __ptr_sceVideoRecordingQueryMemSize2;
asm(".intel_syntax noprefix\n"
    ".global sceVideoRecordingQueryMemSize2\n"
    ".type sceVideoRecordingQueryMemSize2 @function\n"
    "sceVideoRecordingQueryMemSize2:\n"
    "jmp qword ptr [rip + __ptr_sceVideoRecordingQueryMemSize2]\n");

static __attribute__ ((used)) void* __ptr_sceVideoRecordingSetInfo;
asm(".intel_syntax noprefix\n"
    ".global sceVideoRecordingSetInfo\n"
    ".type sceVideoRecordingSetInfo @function\n"
    "sceVideoRecordingSetInfo:\n"
    "jmp qword ptr [rip + __ptr_sceVideoRecordingSetInfo]\n");

static __attribute__ ((used)) void* __ptr_sceVideoRecordingStart;
asm(".intel_syntax noprefix\n"
    ".global sceVideoRecordingStart\n"
    ".type sceVideoRecordingStart @function\n"
    "sceVideoRecordingStart:\n"
    "jmp qword ptr [rip + __ptr_sceVideoRecordingStart]\n");

static __attribute__ ((used)) void* __ptr_sceVideoRecordingStop;
asm(".intel_syntax noprefix\n"
    ".global sceVideoRecordingStop\n"
    ".type sceVideoRecordingStop @function\n"
    "sceVideoRecordingStop:\n"
    "jmp qword ptr [rip + __ptr_sceVideoRecordingStop]\n");

static __attribute__ ((used)) void* __ptr_sceVideoRecordingTerm;
asm(".intel_syntax noprefix\n"
    ".global sceVideoRecordingTerm\n"
    ".type sceVideoRecordingTerm @function\n"
    "sceVideoRecordingTerm:\n"
    "jmp qword ptr [rip + __ptr_sceVideoRecordingTerm]\n");

static unsigned short __handle = 0;
static void __attribute__((constructor(104)))
__constructor(void) {
  if(sprx_dlopen("libSceVideoRecording", &__handle)) return;
  if(sprx_dlsym(__handle, "KHvkPQJDMLk", &__ptr_sceVideoRecordingClose)) return;
  if(sprx_dlsym(__handle, "QNg8KGixrzg", &__ptr_sceVideoRecordingCopyBGRAtoNV12)) return;
  if(sprx_dlsym(__handle, "sA6+5XdbqMA", &__ptr_sceVideoRecordingGetInfo)) return;
  if(sprx_dlsym(__handle, "fZJQzFK4Gv4", &__ptr_sceVideoRecordingGetStatus)) return;
  if(sprx_dlsym(__handle, "RXXBl6-iimo", &__ptr_sceVideoRecordingInit)) return;
  if(sprx_dlsym(__handle, "7QoTYzVuzto", &__ptr_sceVideoRecordingOpen)) return;
  if(sprx_dlsym(__handle, "s28dalBwp2g", &__ptr_sceVideoRecordingOpen2)) return;
  if(sprx_dlsym(__handle, "qOmh6HvHhSs", &__ptr_sceVideoRecordingQueryHddSize2)) return;
  if(sprx_dlsym(__handle, "ZvWzS2wTIMc", &__ptr_sceVideoRecordingQueryMemSize)) return;
  if(sprx_dlsym(__handle, "bGYkY6q3bIw", &__ptr_sceVideoRecordingQueryMemSize2)) return;
  if(sprx_dlsym(__handle, "Fc8qxlKINYQ", &__ptr_sceVideoRecordingSetInfo)) return;
  if(sprx_dlsym(__handle, "tWoe9IlGAhs", &__ptr_sceVideoRecordingStart)) return;
  if(sprx_dlsym(__handle, "OOFxrMY+mfI", &__ptr_sceVideoRecordingStop)) return;
  if(sprx_dlsym(__handle, "gWZikoR+g9g", &__ptr_sceVideoRecordingTerm)) return;
}

static void __attribute__((destructor(104)))
__destructor(void) {
  sprx_dlclose(__handle);
}
