/*
 This file was generated by genstub.py, do not edit manually!
*/

int sprx_dlsym(unsigned int handle, const char *nid, void *addr);
int sprx_dlopen(const char* libname, unsigned short *handle);
int sprx_dlclose(unsigned int handle);

static __attribute__ ((used)) void* __ptr_MvpHttpAbort;
asm(".intel_syntax noprefix\n"
    ".global MvpHttpAbort\n"
    ".type MvpHttpAbort @function\n"
    "MvpHttpAbort:\n"
    "jmp qword ptr [rip + __ptr_MvpHttpAbort]\n");

static __attribute__ ((used)) void* __ptr_MvpHttpDeInit;
asm(".intel_syntax noprefix\n"
    ".global MvpHttpDeInit\n"
    ".type MvpHttpDeInit @function\n"
    "MvpHttpDeInit:\n"
    "jmp qword ptr [rip + __ptr_MvpHttpDeInit]\n");

static __attribute__ ((used)) void* __ptr_MvpHttpGet;
asm(".intel_syntax noprefix\n"
    ".global MvpHttpGet\n"
    ".type MvpHttpGet @function\n"
    "MvpHttpGet:\n"
    "jmp qword ptr [rip + __ptr_MvpHttpGet]\n");

static __attribute__ ((used)) void* __ptr_MvpHttpGetLastError;
asm(".intel_syntax noprefix\n"
    ".global MvpHttpGetLastError\n"
    ".type MvpHttpGetLastError @function\n"
    "MvpHttpGetLastError:\n"
    "jmp qword ptr [rip + __ptr_MvpHttpGetLastError]\n");

static __attribute__ ((used)) void* __ptr_MvpHttpHead;
asm(".intel_syntax noprefix\n"
    ".global MvpHttpHead\n"
    ".type MvpHttpHead @function\n"
    "MvpHttpHead:\n"
    "jmp qword ptr [rip + __ptr_MvpHttpHead]\n");

static __attribute__ ((used)) void* __ptr_MvpHttpHeadCleanup;
asm(".intel_syntax noprefix\n"
    ".global MvpHttpHeadCleanup\n"
    ".type MvpHttpHeadCleanup @function\n"
    "MvpHttpHeadCleanup:\n"
    "jmp qword ptr [rip + __ptr_MvpHttpHeadCleanup]\n");

static __attribute__ ((used)) void* __ptr_MvpHttpInit;
asm(".intel_syntax noprefix\n"
    ".global MvpHttpInit\n"
    ".type MvpHttpInit @function\n"
    "MvpHttpInit:\n"
    "jmp qword ptr [rip + __ptr_MvpHttpInit]\n");

static __attribute__ ((used)) void* __ptr_MvpHttpPost;
asm(".intel_syntax noprefix\n"
    ".global MvpHttpPost\n"
    ".type MvpHttpPost @function\n"
    "MvpHttpPost:\n"
    "jmp qword ptr [rip + __ptr_MvpHttpPost]\n");

static __attribute__ ((used)) void* __ptr_MvpHttpSetCert;
asm(".intel_syntax noprefix\n"
    ".global MvpHttpSetCert\n"
    ".type MvpHttpSetCert @function\n"
    "MvpHttpSetCert:\n"
    "jmp qword ptr [rip + __ptr_MvpHttpSetCert]\n");

static __attribute__ ((used)) void* __ptr_MvpHttpSetRecvTimeout;
asm(".intel_syntax noprefix\n"
    ".global MvpHttpSetRecvTimeout\n"
    ".type MvpHttpSetRecvTimeout @function\n"
    "MvpHttpSetRecvTimeout:\n"
    "jmp qword ptr [rip + __ptr_MvpHttpSetRecvTimeout]\n");

static __attribute__ ((used)) void* __ptr_MvpHttpSetRedirectCb;
asm(".intel_syntax noprefix\n"
    ".global MvpHttpSetRedirectCb\n"
    ".type MvpHttpSetRedirectCb @function\n"
    "MvpHttpSetRedirectCb:\n"
    "jmp qword ptr [rip + __ptr_MvpHttpSetRedirectCb]\n");

static __attribute__ ((used)) void* __ptr_sceTsCloseFile;
asm(".intel_syntax noprefix\n"
    ".global sceTsCloseFile\n"
    ".type sceTsCloseFile @function\n"
    "sceTsCloseFile:\n"
    "jmp qword ptr [rip + __ptr_sceTsCloseFile]\n");

static __attribute__ ((used)) void* __ptr_sceTsDisableRepresentation;
asm(".intel_syntax noprefix\n"
    ".global sceTsDisableRepresentation\n"
    ".type sceTsDisableRepresentation @function\n"
    "sceTsDisableRepresentation:\n"
    "jmp qword ptr [rip + __ptr_sceTsDisableRepresentation]\n");

static __attribute__ ((used)) void* __ptr_sceTsEnableRepresentation;
asm(".intel_syntax noprefix\n"
    ".global sceTsEnableRepresentation\n"
    ".type sceTsEnableRepresentation @function\n"
    "sceTsEnableRepresentation:\n"
    "jmp qword ptr [rip + __ptr_sceTsEnableRepresentation]\n");

static __attribute__ ((used)) void* __ptr_sceTsEnableStream;
asm(".intel_syntax noprefix\n"
    ".global sceTsEnableStream\n"
    ".type sceTsEnableStream @function\n"
    "sceTsEnableStream:\n"
    "jmp qword ptr [rip + __ptr_sceTsEnableStream]\n");

static __attribute__ ((used)) void* __ptr_sceTsGetAvailableBW;
asm(".intel_syntax noprefix\n"
    ".global sceTsGetAvailableBW\n"
    ".type sceTsGetAvailableBW @function\n"
    "sceTsGetAvailableBW:\n"
    "jmp qword ptr [rip + __ptr_sceTsGetAvailableBW]\n");

static __attribute__ ((used)) void* __ptr_sceTsGetLiveStatus;
asm(".intel_syntax noprefix\n"
    ".global sceTsGetLiveStatus\n"
    ".type sceTsGetLiveStatus @function\n"
    "sceTsGetLiveStatus:\n"
    "jmp qword ptr [rip + __ptr_sceTsGetLiveStatus]\n");

static __attribute__ ((used)) void* __ptr_sceTsGetNextAuInfo;
asm(".intel_syntax noprefix\n"
    ".global sceTsGetNextAuInfo\n"
    ".type sceTsGetNextAuInfo @function\n"
    "sceTsGetNextAuInfo:\n"
    "jmp qword ptr [rip + __ptr_sceTsGetNextAuInfo]\n");

static __attribute__ ((used)) void* __ptr_sceTsGetNextUnitData;
asm(".intel_syntax noprefix\n"
    ".global sceTsGetNextUnitData\n"
    ".type sceTsGetNextUnitData @function\n"
    "sceTsGetNextUnitData:\n"
    "jmp qword ptr [rip + __ptr_sceTsGetNextUnitData]\n");

static __attribute__ ((used)) void* __ptr_sceTsGetRepresentationCount;
asm(".intel_syntax noprefix\n"
    ".global sceTsGetRepresentationCount\n"
    ".type sceTsGetRepresentationCount @function\n"
    "sceTsGetRepresentationCount:\n"
    "jmp qword ptr [rip + __ptr_sceTsGetRepresentationCount]\n");

static __attribute__ ((used)) void* __ptr_sceTsGetRepresentationInfo;
asm(".intel_syntax noprefix\n"
    ".global sceTsGetRepresentationInfo\n"
    ".type sceTsGetRepresentationInfo @function\n"
    "sceTsGetRepresentationInfo:\n"
    "jmp qword ptr [rip + __ptr_sceTsGetRepresentationInfo]\n");

static __attribute__ ((used)) void* __ptr_sceTsGetSeekWindow;
asm(".intel_syntax noprefix\n"
    ".global sceTsGetSeekWindow\n"
    ".type sceTsGetSeekWindow @function\n"
    "sceTsGetSeekWindow:\n"
    "jmp qword ptr [rip + __ptr_sceTsGetSeekWindow]\n");

static __attribute__ ((used)) void* __ptr_sceTsGetStreamInfo;
asm(".intel_syntax noprefix\n"
    ".global sceTsGetStreamInfo\n"
    ".type sceTsGetStreamInfo @function\n"
    "sceTsGetStreamInfo:\n"
    "jmp qword ptr [rip + __ptr_sceTsGetStreamInfo]\n");

static __attribute__ ((used)) void* __ptr_sceTsGetUrlEncryptionType;
asm(".intel_syntax noprefix\n"
    ".global sceTsGetUrlEncryptionType\n"
    ".type sceTsGetUrlEncryptionType @function\n"
    "sceTsGetUrlEncryptionType:\n"
    "jmp qword ptr [rip + __ptr_sceTsGetUrlEncryptionType]\n");

static __attribute__ ((used)) void* __ptr_sceTsJumpPTS;
asm(".intel_syntax noprefix\n"
    ".global sceTsJumpPTS\n"
    ".type sceTsJumpPTS @function\n"
    "sceTsJumpPTS:\n"
    "jmp qword ptr [rip + __ptr_sceTsJumpPTS]\n");

static __attribute__ ((used)) void* __ptr_sceTsOpenFile;
asm(".intel_syntax noprefix\n"
    ".global sceTsOpenFile\n"
    ".type sceTsOpenFile @function\n"
    "sceTsOpenFile:\n"
    "jmp qword ptr [rip + __ptr_sceTsOpenFile]\n");

static __attribute__ ((used)) void* __ptr_sceTsOpenFileEx;
asm(".intel_syntax noprefix\n"
    ".global sceTsOpenFileEx\n"
    ".type sceTsOpenFileEx @function\n"
    "sceTsOpenFileEx:\n"
    "jmp qword ptr [rip + __ptr_sceTsOpenFileEx]\n");

static __attribute__ ((used)) void* __ptr_sceTsReleaseBuffer;
asm(".intel_syntax noprefix\n"
    ".global sceTsReleaseBuffer\n"
    ".type sceTsReleaseBuffer @function\n"
    "sceTsReleaseBuffer:\n"
    "jmp qword ptr [rip + __ptr_sceTsReleaseBuffer]\n");

static __attribute__ ((used)) void* __ptr_sceTsRepresentationIsEnabled;
asm(".intel_syntax noprefix\n"
    ".global sceTsRepresentationIsEnabled\n"
    ".type sceTsRepresentationIsEnabled @function\n"
    "sceTsRepresentationIsEnabled:\n"
    "jmp qword ptr [rip + __ptr_sceTsRepresentationIsEnabled]\n");

static __attribute__ ((used)) void* __ptr_sceTsSetAvailableBW;
asm(".intel_syntax noprefix\n"
    ".global sceTsSetAvailableBW\n"
    ".type sceTsSetAvailableBW @function\n"
    "sceTsSetAvailableBW:\n"
    "jmp qword ptr [rip + __ptr_sceTsSetAvailableBW]\n");

static __attribute__ ((used)) void* __ptr_sceTsSetStartingBW;
asm(".intel_syntax noprefix\n"
    ".global sceTsSetStartingBW\n"
    ".type sceTsSetStartingBW @function\n"
    "sceTsSetStartingBW:\n"
    "jmp qword ptr [rip + __ptr_sceTsSetStartingBW]\n");

static __attribute__ ((used)) void* __ptr_sceTsStartFileStreaming;
asm(".intel_syntax noprefix\n"
    ".global sceTsStartFileStreaming\n"
    ".type sceTsStartFileStreaming @function\n"
    "sceTsStartFileStreaming:\n"
    "jmp qword ptr [rip + __ptr_sceTsStartFileStreaming]\n");

static __attribute__ ((used)) void* __ptr_sceTsStopFileStreaming;
asm(".intel_syntax noprefix\n"
    ".global sceTsStopFileStreaming\n"
    ".type sceTsStopFileStreaming @function\n"
    "sceTsStopFileStreaming:\n"
    "jmp qword ptr [rip + __ptr_sceTsStopFileStreaming]\n");

static unsigned short __handle = 0;
static void __attribute__((constructor(104)))
__constructor(void) {
  if(sprx_dlopen("libSceAvPlayerStreaming", &__handle)) return;
  if(sprx_dlsym(__handle, "HxtyQSJ7YO0", &__ptr_MvpHttpAbort)) return;
  if(sprx_dlsym(__handle, "ZNxejqPUqoY", &__ptr_MvpHttpDeInit)) return;
  if(sprx_dlsym(__handle, "RCrjO1lzNRU", &__ptr_MvpHttpGet)) return;
  if(sprx_dlsym(__handle, "Z0rxzUY3XM0", &__ptr_MvpHttpGetLastError)) return;
  if(sprx_dlsym(__handle, "DoqNy-ZXJw8", &__ptr_MvpHttpHead)) return;
  if(sprx_dlsym(__handle, "ib0ufVZWjjA", &__ptr_MvpHttpHeadCleanup)) return;
  if(sprx_dlsym(__handle, "zmW9l9-fo9A", &__ptr_MvpHttpInit)) return;
  if(sprx_dlsym(__handle, "eFb8g7ecEaA", &__ptr_MvpHttpPost)) return;
  if(sprx_dlsym(__handle, "1nkU7nUON5k", &__ptr_MvpHttpSetCert)) return;
  if(sprx_dlsym(__handle, "io8Sy3FgnqE", &__ptr_MvpHttpSetRecvTimeout)) return;
  if(sprx_dlsym(__handle, "vnENYAh8TbM", &__ptr_MvpHttpSetRedirectCb)) return;
  if(sprx_dlsym(__handle, "MZbcWoK2x6s", &__ptr_sceTsCloseFile)) return;
  if(sprx_dlsym(__handle, "x5crCoykxlM", &__ptr_sceTsDisableRepresentation)) return;
  if(sprx_dlsym(__handle, "pyoZ0o2qhgE", &__ptr_sceTsEnableRepresentation)) return;
  if(sprx_dlsym(__handle, "mD3OeD3UdZk", &__ptr_sceTsEnableStream)) return;
  if(sprx_dlsym(__handle, "Q5py3m4I8SA", &__ptr_sceTsGetAvailableBW)) return;
  if(sprx_dlsym(__handle, "eKxoV8TKYy4", &__ptr_sceTsGetLiveStatus)) return;
  if(sprx_dlsym(__handle, "tgPoC4+mOy4", &__ptr_sceTsGetNextAuInfo)) return;
  if(sprx_dlsym(__handle, "5d1ETCfqFnA", &__ptr_sceTsGetNextUnitData)) return;
  if(sprx_dlsym(__handle, "rnjsFB0Fqps", &__ptr_sceTsGetRepresentationCount)) return;
  if(sprx_dlsym(__handle, "CBX4+UX-tG4", &__ptr_sceTsGetRepresentationInfo)) return;
  if(sprx_dlsym(__handle, "OEzZq+ThEio", &__ptr_sceTsGetSeekWindow)) return;
  if(sprx_dlsym(__handle, "HTQKxIObCrs", &__ptr_sceTsGetStreamInfo)) return;
  if(sprx_dlsym(__handle, "pXYlucRhimU", &__ptr_sceTsGetUrlEncryptionType)) return;
  if(sprx_dlsym(__handle, "jyGoZLZlG-M", &__ptr_sceTsJumpPTS)) return;
  if(sprx_dlsym(__handle, "j2in3S4xf+0", &__ptr_sceTsOpenFile)) return;
  if(sprx_dlsym(__handle, "I4Dpeom1P6Y", &__ptr_sceTsOpenFileEx)) return;
  if(sprx_dlsym(__handle, "6gT5JU72smg", &__ptr_sceTsReleaseBuffer)) return;
  if(sprx_dlsym(__handle, "nNCXg4kNpuc", &__ptr_sceTsRepresentationIsEnabled)) return;
  if(sprx_dlsym(__handle, "ARai7ZRDpHs", &__ptr_sceTsSetAvailableBW)) return;
  if(sprx_dlsym(__handle, "amNUtF1PF-w", &__ptr_sceTsSetStartingBW)) return;
  if(sprx_dlsym(__handle, "aQwNhI19JpE", &__ptr_sceTsStartFileStreaming)) return;
  if(sprx_dlsym(__handle, "buBHKGLpYr4", &__ptr_sceTsStopFileStreaming)) return;
}

static void __attribute__((destructor(104)))
__destructor(void) {
  sprx_dlclose(__handle);
}
