/*
 This file was generated by genstub.py, do not edit manually!
*/

int sprx_dlsym(unsigned int handle, const char *nid, void *addr);
int sprx_dlopen(const char* libname, unsigned short *handle);
int sprx_dlclose(unsigned int handle);

static __attribute__ ((used)) void* __ptr_sceDtsEncCreateEncoder;
asm(".intel_syntax noprefix\n"
    ".global sceDtsEncCreateEncoder\n"
    ".type sceDtsEncCreateEncoder @function\n"
    "sceDtsEncCreateEncoder:\n"
    "jmp qword ptr [rip + __ptr_sceDtsEncCreateEncoder]\n");

static __attribute__ ((used)) void* __ptr_sceDtsEncDeleteEncoder;
asm(".intel_syntax noprefix\n"
    ".global sceDtsEncDeleteEncoder\n"
    ".type sceDtsEncDeleteEncoder @function\n"
    "sceDtsEncDeleteEncoder:\n"
    "jmp qword ptr [rip + __ptr_sceDtsEncDeleteEncoder]\n");

static __attribute__ ((used)) void* __ptr_sceDtsEncEncode;
asm(".intel_syntax noprefix\n"
    ".global sceDtsEncEncode\n"
    ".type sceDtsEncEncode @function\n"
    "sceDtsEncEncode:\n"
    "jmp qword ptr [rip + __ptr_sceDtsEncEncode]\n");

static __attribute__ ((used)) void* __ptr_sceDtsEncEncodeAsync;
asm(".intel_syntax noprefix\n"
    ".global sceDtsEncEncodeAsync\n"
    ".type sceDtsEncEncodeAsync @function\n"
    "sceDtsEncEncodeAsync:\n"
    "jmp qword ptr [rip + __ptr_sceDtsEncEncodeAsync]\n");

static __attribute__ ((used)) void* __ptr_sceDtsEncFlush;
asm(".intel_syntax noprefix\n"
    ".global sceDtsEncFlush\n"
    ".type sceDtsEncFlush @function\n"
    "sceDtsEncFlush:\n"
    "jmp qword ptr [rip + __ptr_sceDtsEncFlush]\n");

static __attribute__ ((used)) void* __ptr_sceDtsEncIsEncoding;
asm(".intel_syntax noprefix\n"
    ".global sceDtsEncIsEncoding\n"
    ".type sceDtsEncIsEncoding @function\n"
    "sceDtsEncIsEncoding:\n"
    "jmp qword ptr [rip + __ptr_sceDtsEncIsEncoding]\n");

static __attribute__ ((used)) void* __ptr_sceDtsEncWaitEncode;
asm(".intel_syntax noprefix\n"
    ".global sceDtsEncWaitEncode\n"
    ".type sceDtsEncWaitEncode @function\n"
    "sceDtsEncWaitEncode:\n"
    "jmp qword ptr [rip + __ptr_sceDtsEncWaitEncode]\n");

static unsigned short __handle = 0;
static void __attribute__((constructor(104)))
__constructor(void) {
  if(sprx_dlopen("libSceDtsEnc", &__handle)) return;
  if(sprx_dlsym(__handle, "vjjqXVUcU8w", &__ptr_sceDtsEncCreateEncoder)) return;
  if(sprx_dlsym(__handle, "Dd9-iAuMyis", &__ptr_sceDtsEncDeleteEncoder)) return;
  if(sprx_dlsym(__handle, "jm5stx2t4Ao", &__ptr_sceDtsEncEncode)) return;
  if(sprx_dlsym(__handle, "jx5qjwQWSRU", &__ptr_sceDtsEncEncodeAsync)) return;
  if(sprx_dlsym(__handle, "76NVW6T2AUg", &__ptr_sceDtsEncFlush)) return;
  if(sprx_dlsym(__handle, "Ctd9i+9hFu4", &__ptr_sceDtsEncIsEncoding)) return;
  if(sprx_dlsym(__handle, "ZAFfvaw5eNA", &__ptr_sceDtsEncWaitEncode)) return;
}

static void __attribute__((destructor(104)))
__destructor(void) {
  sprx_dlclose(__handle);
}
