/*
 This file was generated by genstub.py, do not edit manually!
*/

int sprx_dlsym(unsigned int handle, const char *nid, void *addr);
int sprx_dlopen(const char* libname, unsigned short *handle);
int sprx_dlclose(unsigned int handle);

static __attribute__ ((used)) void* __ptr_scePsmUtilFinalize;
asm(".intel_syntax noprefix\n"
    ".global scePsmUtilFinalize\n"
    ".type scePsmUtilFinalize @function\n"
    "scePsmUtilFinalize:\n"
    "jmp qword ptr [rip + __ptr_scePsmUtilFinalize]\n");

static __attribute__ ((used)) void* __ptr_scePsmUtilGetPsmIniFile;
asm(".intel_syntax noprefix\n"
    ".global scePsmUtilGetPsmIniFile\n"
    ".type scePsmUtilGetPsmIniFile @function\n"
    "scePsmUtilGetPsmIniFile:\n"
    "jmp qword ptr [rip + __ptr_scePsmUtilGetPsmIniFile]\n");

static __attribute__ ((used)) void* __ptr_scePsmUtilInitialize;
asm(".intel_syntax noprefix\n"
    ".global scePsmUtilInitialize\n"
    ".type scePsmUtilInitialize @function\n"
    "scePsmUtilInitialize:\n"
    "jmp qword ptr [rip + __ptr_scePsmUtilInitialize]\n");

static __attribute__ ((used)) void* __ptr_scePsmUtilRegisterCallbacks;
asm(".intel_syntax noprefix\n"
    ".global scePsmUtilRegisterCallbacks\n"
    ".type scePsmUtilRegisterCallbacks @function\n"
    "scePsmUtilRegisterCallbacks:\n"
    "jmp qword ptr [rip + __ptr_scePsmUtilRegisterCallbacks]\n");

static unsigned short __handle = 0;
static void __attribute__((constructor(104)))
__constructor(void) {
  if(sprx_dlopen("libScePsmUtil", &__handle)) return;
  if(sprx_dlsym(__handle, "5U6NRSMS9QU", &__ptr_scePsmUtilFinalize)) return;
  if(sprx_dlsym(__handle, "6gapC-97PpU", &__ptr_scePsmUtilGetPsmIniFile)) return;
  if(sprx_dlsym(__handle, "psLU09dc2Vc", &__ptr_scePsmUtilInitialize)) return;
  if(sprx_dlsym(__handle, "+arkFfg6uxw", &__ptr_scePsmUtilRegisterCallbacks)) return;
}

static void __attribute__((destructor(104)))
__destructor(void) {
  sprx_dlclose(__handle);
}
