/*
 This file was generated by genstub.py, do not edit manually!
*/

int sprx_dlsym(unsigned int handle, const char *nid, void *addr);
int sprx_dlopen(const char* libname, unsigned short *handle);
int sprx_dlclose(unsigned int handle);

static __attribute__ ((used)) void* __ptr_sceGnmAddEqEvent;
asm(".intel_syntax noprefix\n"
    ".global sceGnmAddEqEvent\n"
    ".type sceGnmAddEqEvent @function\n"
    "sceGnmAddEqEvent:\n"
    "jmp qword ptr [rip + __ptr_sceGnmAddEqEvent]\n");

static __attribute__ ((used)) void* __ptr_sceGnmAreSubmitsAllowed;
asm(".intel_syntax noprefix\n"
    ".global sceGnmAreSubmitsAllowed\n"
    ".type sceGnmAreSubmitsAllowed @function\n"
    "sceGnmAreSubmitsAllowed:\n"
    "jmp qword ptr [rip + __ptr_sceGnmAreSubmitsAllowed]\n");

static __attribute__ ((used)) void* __ptr_sceGnmBeginWorkload;
asm(".intel_syntax noprefix\n"
    ".global sceGnmBeginWorkload\n"
    ".type sceGnmBeginWorkload @function\n"
    "sceGnmBeginWorkload:\n"
    "jmp qword ptr [rip + __ptr_sceGnmBeginWorkload]\n");

static __attribute__ ((used)) void* __ptr_sceGnmComputeWaitOnAddress;
asm(".intel_syntax noprefix\n"
    ".global sceGnmComputeWaitOnAddress\n"
    ".type sceGnmComputeWaitOnAddress @function\n"
    "sceGnmComputeWaitOnAddress:\n"
    "jmp qword ptr [rip + __ptr_sceGnmComputeWaitOnAddress]\n");

static __attribute__ ((used)) void* __ptr_sceGnmComputeWaitSemaphore;
asm(".intel_syntax noprefix\n"
    ".global sceGnmComputeWaitSemaphore\n"
    ".type sceGnmComputeWaitSemaphore @function\n"
    "sceGnmComputeWaitSemaphore:\n"
    "jmp qword ptr [rip + __ptr_sceGnmComputeWaitSemaphore]\n");

static __attribute__ ((used)) void* __ptr_sceGnmCreateWorkloadStream;
asm(".intel_syntax noprefix\n"
    ".global sceGnmCreateWorkloadStream\n"
    ".type sceGnmCreateWorkloadStream @function\n"
    "sceGnmCreateWorkloadStream:\n"
    "jmp qword ptr [rip + __ptr_sceGnmCreateWorkloadStream]\n");

static __attribute__ ((used)) void* __ptr_sceGnmDebugHardwareStatus;
asm(".intel_syntax noprefix\n"
    ".global sceGnmDebugHardwareStatus\n"
    ".type sceGnmDebugHardwareStatus @function\n"
    "sceGnmDebugHardwareStatus:\n"
    "jmp qword ptr [rip + __ptr_sceGnmDebugHardwareStatus]\n");

static __attribute__ ((used)) void* __ptr_sceGnmDebugModuleReset;
asm(".intel_syntax noprefix\n"
    ".global sceGnmDebugModuleReset\n"
    ".type sceGnmDebugModuleReset @function\n"
    "sceGnmDebugModuleReset:\n"
    "jmp qword ptr [rip + __ptr_sceGnmDebugModuleReset]\n");

static __attribute__ ((used)) void* __ptr_sceGnmDebugReset;
asm(".intel_syntax noprefix\n"
    ".global sceGnmDebugReset\n"
    ".type sceGnmDebugReset @function\n"
    "sceGnmDebugReset:\n"
    "jmp qword ptr [rip + __ptr_sceGnmDebugReset]\n");

static __attribute__ ((used)) void* __ptr_sceGnmDeleteEqEvent;
asm(".intel_syntax noprefix\n"
    ".global sceGnmDeleteEqEvent\n"
    ".type sceGnmDeleteEqEvent @function\n"
    "sceGnmDeleteEqEvent:\n"
    "jmp qword ptr [rip + __ptr_sceGnmDeleteEqEvent]\n");

static __attribute__ ((used)) void* __ptr_sceGnmDestroyWorkloadStream;
asm(".intel_syntax noprefix\n"
    ".global sceGnmDestroyWorkloadStream\n"
    ".type sceGnmDestroyWorkloadStream @function\n"
    "sceGnmDestroyWorkloadStream:\n"
    "jmp qword ptr [rip + __ptr_sceGnmDestroyWorkloadStream]\n");

static __attribute__ ((used)) void* __ptr_sceGnmDingDong;
asm(".intel_syntax noprefix\n"
    ".global sceGnmDingDong\n"
    ".type sceGnmDingDong @function\n"
    "sceGnmDingDong:\n"
    "jmp qword ptr [rip + __ptr_sceGnmDingDong]\n");

static __attribute__ ((used)) void* __ptr_sceGnmDingDongForWorkload;
asm(".intel_syntax noprefix\n"
    ".global sceGnmDingDongForWorkload\n"
    ".type sceGnmDingDongForWorkload @function\n"
    "sceGnmDingDongForWorkload:\n"
    "jmp qword ptr [rip + __ptr_sceGnmDingDongForWorkload]\n");

static __attribute__ ((used)) void* __ptr_sceGnmDisableMipStatsReport;
asm(".intel_syntax noprefix\n"
    ".global sceGnmDisableMipStatsReport\n"
    ".type sceGnmDisableMipStatsReport @function\n"
    "sceGnmDisableMipStatsReport:\n"
    "jmp qword ptr [rip + __ptr_sceGnmDisableMipStatsReport]\n");

static __attribute__ ((used)) void* __ptr_sceGnmDispatchDirect;
asm(".intel_syntax noprefix\n"
    ".global sceGnmDispatchDirect\n"
    ".type sceGnmDispatchDirect @function\n"
    "sceGnmDispatchDirect:\n"
    "jmp qword ptr [rip + __ptr_sceGnmDispatchDirect]\n");

static __attribute__ ((used)) void* __ptr_sceGnmDispatchIndirect;
asm(".intel_syntax noprefix\n"
    ".global sceGnmDispatchIndirect\n"
    ".type sceGnmDispatchIndirect @function\n"
    "sceGnmDispatchIndirect:\n"
    "jmp qword ptr [rip + __ptr_sceGnmDispatchIndirect]\n");

static __attribute__ ((used)) void* __ptr_sceGnmDispatchIndirectOnMec;
asm(".intel_syntax noprefix\n"
    ".global sceGnmDispatchIndirectOnMec\n"
    ".type sceGnmDispatchIndirectOnMec @function\n"
    "sceGnmDispatchIndirectOnMec:\n"
    "jmp qword ptr [rip + __ptr_sceGnmDispatchIndirectOnMec]\n");

static __attribute__ ((used)) void* __ptr_sceGnmDispatchInitDefaultHardwareState;
asm(".intel_syntax noprefix\n"
    ".global sceGnmDispatchInitDefaultHardwareState\n"
    ".type sceGnmDispatchInitDefaultHardwareState @function\n"
    "sceGnmDispatchInitDefaultHardwareState:\n"
    "jmp qword ptr [rip + __ptr_sceGnmDispatchInitDefaultHardwareState]\n");

static __attribute__ ((used)) void* __ptr_sceGnmDrawIndex;
asm(".intel_syntax noprefix\n"
    ".global sceGnmDrawIndex\n"
    ".type sceGnmDrawIndex @function\n"
    "sceGnmDrawIndex:\n"
    "jmp qword ptr [rip + __ptr_sceGnmDrawIndex]\n");

static __attribute__ ((used)) void* __ptr_sceGnmDrawIndexAuto;
asm(".intel_syntax noprefix\n"
    ".global sceGnmDrawIndexAuto\n"
    ".type sceGnmDrawIndexAuto @function\n"
    "sceGnmDrawIndexAuto:\n"
    "jmp qword ptr [rip + __ptr_sceGnmDrawIndexAuto]\n");

static __attribute__ ((used)) void* __ptr_sceGnmDrawIndexIndirect;
asm(".intel_syntax noprefix\n"
    ".global sceGnmDrawIndexIndirect\n"
    ".type sceGnmDrawIndexIndirect @function\n"
    "sceGnmDrawIndexIndirect:\n"
    "jmp qword ptr [rip + __ptr_sceGnmDrawIndexIndirect]\n");

static __attribute__ ((used)) void* __ptr_sceGnmDrawIndexIndirectCountMulti;
asm(".intel_syntax noprefix\n"
    ".global sceGnmDrawIndexIndirectCountMulti\n"
    ".type sceGnmDrawIndexIndirectCountMulti @function\n"
    "sceGnmDrawIndexIndirectCountMulti:\n"
    "jmp qword ptr [rip + __ptr_sceGnmDrawIndexIndirectCountMulti]\n");

static __attribute__ ((used)) void* __ptr_sceGnmDrawIndexIndirectMulti;
asm(".intel_syntax noprefix\n"
    ".global sceGnmDrawIndexIndirectMulti\n"
    ".type sceGnmDrawIndexIndirectMulti @function\n"
    "sceGnmDrawIndexIndirectMulti:\n"
    "jmp qword ptr [rip + __ptr_sceGnmDrawIndexIndirectMulti]\n");

static __attribute__ ((used)) void* __ptr_sceGnmDrawIndexMultiInstanced;
asm(".intel_syntax noprefix\n"
    ".global sceGnmDrawIndexMultiInstanced\n"
    ".type sceGnmDrawIndexMultiInstanced @function\n"
    "sceGnmDrawIndexMultiInstanced:\n"
    "jmp qword ptr [rip + __ptr_sceGnmDrawIndexMultiInstanced]\n");

static __attribute__ ((used)) void* __ptr_sceGnmDrawIndexOffset;
asm(".intel_syntax noprefix\n"
    ".global sceGnmDrawIndexOffset\n"
    ".type sceGnmDrawIndexOffset @function\n"
    "sceGnmDrawIndexOffset:\n"
    "jmp qword ptr [rip + __ptr_sceGnmDrawIndexOffset]\n");

static __attribute__ ((used)) void* __ptr_sceGnmDrawIndirect;
asm(".intel_syntax noprefix\n"
    ".global sceGnmDrawIndirect\n"
    ".type sceGnmDrawIndirect @function\n"
    "sceGnmDrawIndirect:\n"
    "jmp qword ptr [rip + __ptr_sceGnmDrawIndirect]\n");

static __attribute__ ((used)) void* __ptr_sceGnmDrawIndirectCountMulti;
asm(".intel_syntax noprefix\n"
    ".global sceGnmDrawIndirectCountMulti\n"
    ".type sceGnmDrawIndirectCountMulti @function\n"
    "sceGnmDrawIndirectCountMulti:\n"
    "jmp qword ptr [rip + __ptr_sceGnmDrawIndirectCountMulti]\n");

static __attribute__ ((used)) void* __ptr_sceGnmDrawIndirectMulti;
asm(".intel_syntax noprefix\n"
    ".global sceGnmDrawIndirectMulti\n"
    ".type sceGnmDrawIndirectMulti @function\n"
    "sceGnmDrawIndirectMulti:\n"
    "jmp qword ptr [rip + __ptr_sceGnmDrawIndirectMulti]\n");

static __attribute__ ((used)) void* __ptr_sceGnmDrawInitDefaultHardwareState;
asm(".intel_syntax noprefix\n"
    ".global sceGnmDrawInitDefaultHardwareState\n"
    ".type sceGnmDrawInitDefaultHardwareState @function\n"
    "sceGnmDrawInitDefaultHardwareState:\n"
    "jmp qword ptr [rip + __ptr_sceGnmDrawInitDefaultHardwareState]\n");

static __attribute__ ((used)) void* __ptr_sceGnmDrawInitDefaultHardwareState175;
asm(".intel_syntax noprefix\n"
    ".global sceGnmDrawInitDefaultHardwareState175\n"
    ".type sceGnmDrawInitDefaultHardwareState175 @function\n"
    "sceGnmDrawInitDefaultHardwareState175:\n"
    "jmp qword ptr [rip + __ptr_sceGnmDrawInitDefaultHardwareState175]\n");

static __attribute__ ((used)) void* __ptr_sceGnmDrawInitDefaultHardwareState200;
asm(".intel_syntax noprefix\n"
    ".global sceGnmDrawInitDefaultHardwareState200\n"
    ".type sceGnmDrawInitDefaultHardwareState200 @function\n"
    "sceGnmDrawInitDefaultHardwareState200:\n"
    "jmp qword ptr [rip + __ptr_sceGnmDrawInitDefaultHardwareState200]\n");

static __attribute__ ((used)) void* __ptr_sceGnmDrawInitDefaultHardwareState350;
asm(".intel_syntax noprefix\n"
    ".global sceGnmDrawInitDefaultHardwareState350\n"
    ".type sceGnmDrawInitDefaultHardwareState350 @function\n"
    "sceGnmDrawInitDefaultHardwareState350:\n"
    "jmp qword ptr [rip + __ptr_sceGnmDrawInitDefaultHardwareState350]\n");

static __attribute__ ((used)) void* __ptr_sceGnmDrawInitToDefaultContextState;
asm(".intel_syntax noprefix\n"
    ".global sceGnmDrawInitToDefaultContextState\n"
    ".type sceGnmDrawInitToDefaultContextState @function\n"
    "sceGnmDrawInitToDefaultContextState:\n"
    "jmp qword ptr [rip + __ptr_sceGnmDrawInitToDefaultContextState]\n");

static __attribute__ ((used)) void* __ptr_sceGnmDrawInitToDefaultContextState400;
asm(".intel_syntax noprefix\n"
    ".global sceGnmDrawInitToDefaultContextState400\n"
    ".type sceGnmDrawInitToDefaultContextState400 @function\n"
    "sceGnmDrawInitToDefaultContextState400:\n"
    "jmp qword ptr [rip + __ptr_sceGnmDrawInitToDefaultContextState400]\n");

static __attribute__ ((used)) void* __ptr_sceGnmDrawInitToDefaultContextStateInternalCommand;
asm(".intel_syntax noprefix\n"
    ".global sceGnmDrawInitToDefaultContextStateInternalCommand\n"
    ".type sceGnmDrawInitToDefaultContextStateInternalCommand @function\n"
    "sceGnmDrawInitToDefaultContextStateInternalCommand:\n"
    "jmp qword ptr [rip + __ptr_sceGnmDrawInitToDefaultContextStateInternalCommand]\n");

static __attribute__ ((used)) void* __ptr_sceGnmDrawInitToDefaultContextStateInternalSize;
asm(".intel_syntax noprefix\n"
    ".global sceGnmDrawInitToDefaultContextStateInternalSize\n"
    ".type sceGnmDrawInitToDefaultContextStateInternalSize @function\n"
    "sceGnmDrawInitToDefaultContextStateInternalSize:\n"
    "jmp qword ptr [rip + __ptr_sceGnmDrawInitToDefaultContextStateInternalSize]\n");

static __attribute__ ((used)) void* __ptr_sceGnmDrawOpaqueAuto;
asm(".intel_syntax noprefix\n"
    ".global sceGnmDrawOpaqueAuto\n"
    ".type sceGnmDrawOpaqueAuto @function\n"
    "sceGnmDrawOpaqueAuto:\n"
    "jmp qword ptr [rip + __ptr_sceGnmDrawOpaqueAuto]\n");

static __attribute__ ((used)) void* __ptr_sceGnmDriverCaptureInProgress;
asm(".intel_syntax noprefix\n"
    ".global sceGnmDriverCaptureInProgress\n"
    ".type sceGnmDriverCaptureInProgress @function\n"
    "sceGnmDriverCaptureInProgress:\n"
    "jmp qword ptr [rip + __ptr_sceGnmDriverCaptureInProgress]\n");

static __attribute__ ((used)) void* __ptr_sceGnmDriverInternalRetrieveGnmInterface;
asm(".intel_syntax noprefix\n"
    ".global sceGnmDriverInternalRetrieveGnmInterface\n"
    ".type sceGnmDriverInternalRetrieveGnmInterface @function\n"
    "sceGnmDriverInternalRetrieveGnmInterface:\n"
    "jmp qword ptr [rip + __ptr_sceGnmDriverInternalRetrieveGnmInterface]\n");

static __attribute__ ((used)) void* __ptr_sceGnmDriverInternalRetrieveGnmInterfaceForGpuDebugger;
asm(".intel_syntax noprefix\n"
    ".global sceGnmDriverInternalRetrieveGnmInterfaceForGpuDebugger\n"
    ".type sceGnmDriverInternalRetrieveGnmInterfaceForGpuDebugger @function\n"
    "sceGnmDriverInternalRetrieveGnmInterfaceForGpuDebugger:\n"
    "jmp qword ptr [rip + __ptr_sceGnmDriverInternalRetrieveGnmInterfaceForGpuDebugger]\n");

static __attribute__ ((used)) void* __ptr_sceGnmDriverInternalRetrieveGnmInterfaceForReplay;
asm(".intel_syntax noprefix\n"
    ".global sceGnmDriverInternalRetrieveGnmInterfaceForReplay\n"
    ".type sceGnmDriverInternalRetrieveGnmInterfaceForReplay @function\n"
    "sceGnmDriverInternalRetrieveGnmInterfaceForReplay:\n"
    "jmp qword ptr [rip + __ptr_sceGnmDriverInternalRetrieveGnmInterfaceForReplay]\n");

static __attribute__ ((used)) void* __ptr_sceGnmDriverInternalRetrieveGnmInterfaceForResourceRegistration;
asm(".intel_syntax noprefix\n"
    ".global sceGnmDriverInternalRetrieveGnmInterfaceForResourceRegistration\n"
    ".type sceGnmDriverInternalRetrieveGnmInterfaceForResourceRegistration @function\n"
    "sceGnmDriverInternalRetrieveGnmInterfaceForResourceRegistration:\n"
    "jmp qword ptr [rip + __ptr_sceGnmDriverInternalRetrieveGnmInterfaceForResourceRegistration]\n");

static __attribute__ ((used)) void* __ptr_sceGnmDriverInternalRetrieveGnmInterfaceForValidation;
asm(".intel_syntax noprefix\n"
    ".global sceGnmDriverInternalRetrieveGnmInterfaceForValidation\n"
    ".type sceGnmDriverInternalRetrieveGnmInterfaceForValidation @function\n"
    "sceGnmDriverInternalRetrieveGnmInterfaceForValidation:\n"
    "jmp qword ptr [rip + __ptr_sceGnmDriverInternalRetrieveGnmInterfaceForValidation]\n");

static __attribute__ ((used)) void* __ptr_sceGnmDriverInternalVirtualQuery;
asm(".intel_syntax noprefix\n"
    ".global sceGnmDriverInternalVirtualQuery\n"
    ".type sceGnmDriverInternalVirtualQuery @function\n"
    "sceGnmDriverInternalVirtualQuery:\n"
    "jmp qword ptr [rip + __ptr_sceGnmDriverInternalVirtualQuery]\n");

static __attribute__ ((used)) void* __ptr_sceGnmDriverTraceInProgress;
asm(".intel_syntax noprefix\n"
    ".global sceGnmDriverTraceInProgress\n"
    ".type sceGnmDriverTraceInProgress @function\n"
    "sceGnmDriverTraceInProgress:\n"
    "jmp qword ptr [rip + __ptr_sceGnmDriverTraceInProgress]\n");

static __attribute__ ((used)) void* __ptr_sceGnmDriverTriggerCapture;
asm(".intel_syntax noprefix\n"
    ".global sceGnmDriverTriggerCapture\n"
    ".type sceGnmDriverTriggerCapture @function\n"
    "sceGnmDriverTriggerCapture:\n"
    "jmp qword ptr [rip + __ptr_sceGnmDriverTriggerCapture]\n");

static __attribute__ ((used)) void* __ptr_sceGnmEndWorkload;
asm(".intel_syntax noprefix\n"
    ".global sceGnmEndWorkload\n"
    ".type sceGnmEndWorkload @function\n"
    "sceGnmEndWorkload:\n"
    "jmp qword ptr [rip + __ptr_sceGnmEndWorkload]\n");

static __attribute__ ((used)) void* __ptr_sceGnmFindResources;
asm(".intel_syntax noprefix\n"
    ".global sceGnmFindResources\n"
    ".type sceGnmFindResources @function\n"
    "sceGnmFindResources:\n"
    "jmp qword ptr [rip + __ptr_sceGnmFindResources]\n");

static __attribute__ ((used)) void* __ptr_sceGnmFindResourcesPublic;
asm(".intel_syntax noprefix\n"
    ".global sceGnmFindResourcesPublic\n"
    ".type sceGnmFindResourcesPublic @function\n"
    "sceGnmFindResourcesPublic:\n"
    "jmp qword ptr [rip + __ptr_sceGnmFindResourcesPublic]\n");

static __attribute__ ((used)) void* __ptr_sceGnmFlushGarlic;
asm(".intel_syntax noprefix\n"
    ".global sceGnmFlushGarlic\n"
    ".type sceGnmFlushGarlic @function\n"
    "sceGnmFlushGarlic:\n"
    "jmp qword ptr [rip + __ptr_sceGnmFlushGarlic]\n");

static __attribute__ ((used)) void* __ptr_sceGnmGetCoredumpAddress;
asm(".intel_syntax noprefix\n"
    ".global sceGnmGetCoredumpAddress\n"
    ".type sceGnmGetCoredumpAddress @function\n"
    "sceGnmGetCoredumpAddress:\n"
    "jmp qword ptr [rip + __ptr_sceGnmGetCoredumpAddress]\n");

static __attribute__ ((used)) void* __ptr_sceGnmGetCoredumpMode;
asm(".intel_syntax noprefix\n"
    ".global sceGnmGetCoredumpMode\n"
    ".type sceGnmGetCoredumpMode @function\n"
    "sceGnmGetCoredumpMode:\n"
    "jmp qword ptr [rip + __ptr_sceGnmGetCoredumpMode]\n");

static __attribute__ ((used)) void* __ptr_sceGnmGetCoredumpProtectionFaultTimestamp;
asm(".intel_syntax noprefix\n"
    ".global sceGnmGetCoredumpProtectionFaultTimestamp\n"
    ".type sceGnmGetCoredumpProtectionFaultTimestamp @function\n"
    "sceGnmGetCoredumpProtectionFaultTimestamp:\n"
    "jmp qword ptr [rip + __ptr_sceGnmGetCoredumpProtectionFaultTimestamp]\n");

static __attribute__ ((used)) void* __ptr_sceGnmGetDbgGcHandle;
asm(".intel_syntax noprefix\n"
    ".global sceGnmGetDbgGcHandle\n"
    ".type sceGnmGetDbgGcHandle @function\n"
    "sceGnmGetDbgGcHandle:\n"
    "jmp qword ptr [rip + __ptr_sceGnmGetDbgGcHandle]\n");

static __attribute__ ((used)) void* __ptr_sceGnmGetEqEventType;
asm(".intel_syntax noprefix\n"
    ".global sceGnmGetEqEventType\n"
    ".type sceGnmGetEqEventType @function\n"
    "sceGnmGetEqEventType:\n"
    "jmp qword ptr [rip + __ptr_sceGnmGetEqEventType]\n");

static __attribute__ ((used)) void* __ptr_sceGnmGetEqTimeStamp;
asm(".intel_syntax noprefix\n"
    ".global sceGnmGetEqTimeStamp\n"
    ".type sceGnmGetEqTimeStamp @function\n"
    "sceGnmGetEqTimeStamp:\n"
    "jmp qword ptr [rip + __ptr_sceGnmGetEqTimeStamp]\n");

static __attribute__ ((used)) void* __ptr_sceGnmGetGpuBlockStatus;
asm(".intel_syntax noprefix\n"
    ".global sceGnmGetGpuBlockStatus\n"
    ".type sceGnmGetGpuBlockStatus @function\n"
    "sceGnmGetGpuBlockStatus:\n"
    "jmp qword ptr [rip + __ptr_sceGnmGetGpuBlockStatus]\n");

static __attribute__ ((used)) void* __ptr_sceGnmGetGpuCoreClockFrequency;
asm(".intel_syntax noprefix\n"
    ".global sceGnmGetGpuCoreClockFrequency\n"
    ".type sceGnmGetGpuCoreClockFrequency @function\n"
    "sceGnmGetGpuCoreClockFrequency:\n"
    "jmp qword ptr [rip + __ptr_sceGnmGetGpuCoreClockFrequency]\n");

static __attribute__ ((used)) void* __ptr_sceGnmGetGpuInfoStatus;
asm(".intel_syntax noprefix\n"
    ".global sceGnmGetGpuInfoStatus\n"
    ".type sceGnmGetGpuInfoStatus @function\n"
    "sceGnmGetGpuInfoStatus:\n"
    "jmp qword ptr [rip + __ptr_sceGnmGetGpuInfoStatus]\n");

static __attribute__ ((used)) void* __ptr_sceGnmGetLastWaitedAddress;
asm(".intel_syntax noprefix\n"
    ".global sceGnmGetLastWaitedAddress\n"
    ".type sceGnmGetLastWaitedAddress @function\n"
    "sceGnmGetLastWaitedAddress:\n"
    "jmp qword ptr [rip + __ptr_sceGnmGetLastWaitedAddress]\n");

static __attribute__ ((used)) void* __ptr_sceGnmGetNumTcaUnits;
asm(".intel_syntax noprefix\n"
    ".global sceGnmGetNumTcaUnits\n"
    ".type sceGnmGetNumTcaUnits @function\n"
    "sceGnmGetNumTcaUnits:\n"
    "jmp qword ptr [rip + __ptr_sceGnmGetNumTcaUnits]\n");

static __attribute__ ((used)) void* __ptr_sceGnmGetOffChipTessellationBufferSize;
asm(".intel_syntax noprefix\n"
    ".global sceGnmGetOffChipTessellationBufferSize\n"
    ".type sceGnmGetOffChipTessellationBufferSize @function\n"
    "sceGnmGetOffChipTessellationBufferSize:\n"
    "jmp qword ptr [rip + __ptr_sceGnmGetOffChipTessellationBufferSize]\n");

static __attribute__ ((used)) void* __ptr_sceGnmGetOwnerName;
asm(".intel_syntax noprefix\n"
    ".global sceGnmGetOwnerName\n"
    ".type sceGnmGetOwnerName @function\n"
    "sceGnmGetOwnerName:\n"
    "jmp qword ptr [rip + __ptr_sceGnmGetOwnerName]\n");

static __attribute__ ((used)) void* __ptr_sceGnmGetPhysicalCounterFromVirtualized;
asm(".intel_syntax noprefix\n"
    ".global sceGnmGetPhysicalCounterFromVirtualized\n"
    ".type sceGnmGetPhysicalCounterFromVirtualized @function\n"
    "sceGnmGetPhysicalCounterFromVirtualized:\n"
    "jmp qword ptr [rip + __ptr_sceGnmGetPhysicalCounterFromVirtualized]\n");

static __attribute__ ((used)) void* __ptr_sceGnmGetProtectionFaultTimeStamp;
asm(".intel_syntax noprefix\n"
    ".global sceGnmGetProtectionFaultTimeStamp\n"
    ".type sceGnmGetProtectionFaultTimeStamp @function\n"
    "sceGnmGetProtectionFaultTimeStamp:\n"
    "jmp qword ptr [rip + __ptr_sceGnmGetProtectionFaultTimeStamp]\n");

static __attribute__ ((used)) void* __ptr_sceGnmGetResourceBaseAddressAndSizeInBytes;
asm(".intel_syntax noprefix\n"
    ".global sceGnmGetResourceBaseAddressAndSizeInBytes\n"
    ".type sceGnmGetResourceBaseAddressAndSizeInBytes @function\n"
    "sceGnmGetResourceBaseAddressAndSizeInBytes:\n"
    "jmp qword ptr [rip + __ptr_sceGnmGetResourceBaseAddressAndSizeInBytes]\n");

static __attribute__ ((used)) void* __ptr_sceGnmGetResourceName;
asm(".intel_syntax noprefix\n"
    ".global sceGnmGetResourceName\n"
    ".type sceGnmGetResourceName @function\n"
    "sceGnmGetResourceName:\n"
    "jmp qword ptr [rip + __ptr_sceGnmGetResourceName]\n");

static __attribute__ ((used)) void* __ptr_sceGnmGetResourceRegistrationBuffers;
asm(".intel_syntax noprefix\n"
    ".global sceGnmGetResourceRegistrationBuffers\n"
    ".type sceGnmGetResourceRegistrationBuffers @function\n"
    "sceGnmGetResourceRegistrationBuffers:\n"
    "jmp qword ptr [rip + __ptr_sceGnmGetResourceRegistrationBuffers]\n");

static __attribute__ ((used)) void* __ptr_sceGnmGetResourceShaderGuid;
asm(".intel_syntax noprefix\n"
    ".global sceGnmGetResourceShaderGuid\n"
    ".type sceGnmGetResourceShaderGuid @function\n"
    "sceGnmGetResourceShaderGuid:\n"
    "jmp qword ptr [rip + __ptr_sceGnmGetResourceShaderGuid]\n");

static __attribute__ ((used)) void* __ptr_sceGnmGetResourceType;
asm(".intel_syntax noprefix\n"
    ".global sceGnmGetResourceType\n"
    ".type sceGnmGetResourceType @function\n"
    "sceGnmGetResourceType:\n"
    "jmp qword ptr [rip + __ptr_sceGnmGetResourceType]\n");

static __attribute__ ((used)) void* __ptr_sceGnmGetResourceUserData;
asm(".intel_syntax noprefix\n"
    ".global sceGnmGetResourceUserData\n"
    ".type sceGnmGetResourceUserData @function\n"
    "sceGnmGetResourceUserData:\n"
    "jmp qword ptr [rip + __ptr_sceGnmGetResourceUserData]\n");

static __attribute__ ((used)) void* __ptr_sceGnmGetShaderProgramBaseAddress;
asm(".intel_syntax noprefix\n"
    ".global sceGnmGetShaderProgramBaseAddress\n"
    ".type sceGnmGetShaderProgramBaseAddress @function\n"
    "sceGnmGetShaderProgramBaseAddress:\n"
    "jmp qword ptr [rip + __ptr_sceGnmGetShaderProgramBaseAddress]\n");

static __attribute__ ((used)) void* __ptr_sceGnmGetShaderStatus;
asm(".intel_syntax noprefix\n"
    ".global sceGnmGetShaderStatus\n"
    ".type sceGnmGetShaderStatus @function\n"
    "sceGnmGetShaderStatus:\n"
    "jmp qword ptr [rip + __ptr_sceGnmGetShaderStatus]\n");

static __attribute__ ((used)) void* __ptr_sceGnmGetTheTessellationFactorRingBufferBaseAddress;
asm(".intel_syntax noprefix\n"
    ".global sceGnmGetTheTessellationFactorRingBufferBaseAddress\n"
    ".type sceGnmGetTheTessellationFactorRingBufferBaseAddress @function\n"
    "sceGnmGetTheTessellationFactorRingBufferBaseAddress:\n"
    "jmp qword ptr [rip + __ptr_sceGnmGetTheTessellationFactorRingBufferBaseAddress]\n");

static __attribute__ ((used)) void* __ptr_sceGnmGpuPaDebugEnter;
asm(".intel_syntax noprefix\n"
    ".global sceGnmGpuPaDebugEnter\n"
    ".type sceGnmGpuPaDebugEnter @function\n"
    "sceGnmGpuPaDebugEnter:\n"
    "jmp qword ptr [rip + __ptr_sceGnmGpuPaDebugEnter]\n");

static __attribute__ ((used)) void* __ptr_sceGnmGpuPaDebugLeave;
asm(".intel_syntax noprefix\n"
    ".global sceGnmGpuPaDebugLeave\n"
    ".type sceGnmGpuPaDebugLeave @function\n"
    "sceGnmGpuPaDebugLeave:\n"
    "jmp qword ptr [rip + __ptr_sceGnmGpuPaDebugLeave]\n");

static __attribute__ ((used)) void* __ptr_sceGnmInsertDingDongMarker;
asm(".intel_syntax noprefix\n"
    ".global sceGnmInsertDingDongMarker\n"
    ".type sceGnmInsertDingDongMarker @function\n"
    "sceGnmInsertDingDongMarker:\n"
    "jmp qword ptr [rip + __ptr_sceGnmInsertDingDongMarker]\n");

static __attribute__ ((used)) void* __ptr_sceGnmInsertPopMarker;
asm(".intel_syntax noprefix\n"
    ".global sceGnmInsertPopMarker\n"
    ".type sceGnmInsertPopMarker @function\n"
    "sceGnmInsertPopMarker:\n"
    "jmp qword ptr [rip + __ptr_sceGnmInsertPopMarker]\n");

static __attribute__ ((used)) void* __ptr_sceGnmInsertPushColorMarker;
asm(".intel_syntax noprefix\n"
    ".global sceGnmInsertPushColorMarker\n"
    ".type sceGnmInsertPushColorMarker @function\n"
    "sceGnmInsertPushColorMarker:\n"
    "jmp qword ptr [rip + __ptr_sceGnmInsertPushColorMarker]\n");

static __attribute__ ((used)) void* __ptr_sceGnmInsertPushMarker;
asm(".intel_syntax noprefix\n"
    ".global sceGnmInsertPushMarker\n"
    ".type sceGnmInsertPushMarker @function\n"
    "sceGnmInsertPushMarker:\n"
    "jmp qword ptr [rip + __ptr_sceGnmInsertPushMarker]\n");

static __attribute__ ((used)) void* __ptr_sceGnmInsertSetColorMarker;
asm(".intel_syntax noprefix\n"
    ".global sceGnmInsertSetColorMarker\n"
    ".type sceGnmInsertSetColorMarker @function\n"
    "sceGnmInsertSetColorMarker:\n"
    "jmp qword ptr [rip + __ptr_sceGnmInsertSetColorMarker]\n");

static __attribute__ ((used)) void* __ptr_sceGnmInsertSetMarker;
asm(".intel_syntax noprefix\n"
    ".global sceGnmInsertSetMarker\n"
    ".type sceGnmInsertSetMarker @function\n"
    "sceGnmInsertSetMarker:\n"
    "jmp qword ptr [rip + __ptr_sceGnmInsertSetMarker]\n");

static __attribute__ ((used)) void* __ptr_sceGnmInsertThreadTraceMarker;
asm(".intel_syntax noprefix\n"
    ".global sceGnmInsertThreadTraceMarker\n"
    ".type sceGnmInsertThreadTraceMarker @function\n"
    "sceGnmInsertThreadTraceMarker:\n"
    "jmp qword ptr [rip + __ptr_sceGnmInsertThreadTraceMarker]\n");

static __attribute__ ((used)) void* __ptr_sceGnmInsertWaitFlipDone;
asm(".intel_syntax noprefix\n"
    ".global sceGnmInsertWaitFlipDone\n"
    ".type sceGnmInsertWaitFlipDone @function\n"
    "sceGnmInsertWaitFlipDone:\n"
    "jmp qword ptr [rip + __ptr_sceGnmInsertWaitFlipDone]\n");

static __attribute__ ((used)) void* __ptr_sceGnmIsCoredumpValid;
asm(".intel_syntax noprefix\n"
    ".global sceGnmIsCoredumpValid\n"
    ".type sceGnmIsCoredumpValid @function\n"
    "sceGnmIsCoredumpValid:\n"
    "jmp qword ptr [rip + __ptr_sceGnmIsCoredumpValid]\n");

static __attribute__ ((used)) void* __ptr_sceGnmIsUserPaEnabled;
asm(".intel_syntax noprefix\n"
    ".global sceGnmIsUserPaEnabled\n"
    ".type sceGnmIsUserPaEnabled @function\n"
    "sceGnmIsUserPaEnabled:\n"
    "jmp qword ptr [rip + __ptr_sceGnmIsUserPaEnabled]\n");

static __attribute__ ((used)) void* __ptr_sceGnmLogicalCuIndexToPhysicalCuIndex;
asm(".intel_syntax noprefix\n"
    ".global sceGnmLogicalCuIndexToPhysicalCuIndex\n"
    ".type sceGnmLogicalCuIndexToPhysicalCuIndex @function\n"
    "sceGnmLogicalCuIndexToPhysicalCuIndex:\n"
    "jmp qword ptr [rip + __ptr_sceGnmLogicalCuIndexToPhysicalCuIndex]\n");

static __attribute__ ((used)) void* __ptr_sceGnmLogicalCuMaskToPhysicalCuMask;
asm(".intel_syntax noprefix\n"
    ".global sceGnmLogicalCuMaskToPhysicalCuMask\n"
    ".type sceGnmLogicalCuMaskToPhysicalCuMask @function\n"
    "sceGnmLogicalCuMaskToPhysicalCuMask:\n"
    "jmp qword ptr [rip + __ptr_sceGnmLogicalCuMaskToPhysicalCuMask]\n");

static __attribute__ ((used)) void* __ptr_sceGnmLogicalTcaUnitToPhysical;
asm(".intel_syntax noprefix\n"
    ".global sceGnmLogicalTcaUnitToPhysical\n"
    ".type sceGnmLogicalTcaUnitToPhysical @function\n"
    "sceGnmLogicalTcaUnitToPhysical:\n"
    "jmp qword ptr [rip + __ptr_sceGnmLogicalTcaUnitToPhysical]\n");

static __attribute__ ((used)) void* __ptr_sceGnmMapComputeQueue;
asm(".intel_syntax noprefix\n"
    ".global sceGnmMapComputeQueue\n"
    ".type sceGnmMapComputeQueue @function\n"
    "sceGnmMapComputeQueue:\n"
    "jmp qword ptr [rip + __ptr_sceGnmMapComputeQueue]\n");

static __attribute__ ((used)) void* __ptr_sceGnmMapComputeQueueWithPriority;
asm(".intel_syntax noprefix\n"
    ".global sceGnmMapComputeQueueWithPriority\n"
    ".type sceGnmMapComputeQueueWithPriority @function\n"
    "sceGnmMapComputeQueueWithPriority:\n"
    "jmp qword ptr [rip + __ptr_sceGnmMapComputeQueueWithPriority]\n");

static __attribute__ ((used)) void* __ptr_sceGnmPaDisableFlipCallbacks;
asm(".intel_syntax noprefix\n"
    ".global sceGnmPaDisableFlipCallbacks\n"
    ".type sceGnmPaDisableFlipCallbacks @function\n"
    "sceGnmPaDisableFlipCallbacks:\n"
    "jmp qword ptr [rip + __ptr_sceGnmPaDisableFlipCallbacks]\n");

static __attribute__ ((used)) void* __ptr_sceGnmPaEnableFlipCallbacks;
asm(".intel_syntax noprefix\n"
    ".global sceGnmPaEnableFlipCallbacks\n"
    ".type sceGnmPaEnableFlipCallbacks @function\n"
    "sceGnmPaEnableFlipCallbacks:\n"
    "jmp qword ptr [rip + __ptr_sceGnmPaEnableFlipCallbacks]\n");

static __attribute__ ((used)) void* __ptr_sceGnmPaHeartbeat;
asm(".intel_syntax noprefix\n"
    ".global sceGnmPaHeartbeat\n"
    ".type sceGnmPaHeartbeat @function\n"
    "sceGnmPaHeartbeat:\n"
    "jmp qword ptr [rip + __ptr_sceGnmPaHeartbeat]\n");

static __attribute__ ((used)) void* __ptr_sceGnmQueryResourceRegistrationUserMemoryRequirements;
asm(".intel_syntax noprefix\n"
    ".global sceGnmQueryResourceRegistrationUserMemoryRequirements\n"
    ".type sceGnmQueryResourceRegistrationUserMemoryRequirements @function\n"
    "sceGnmQueryResourceRegistrationUserMemoryRequirements:\n"
    "jmp qword ptr [rip + __ptr_sceGnmQueryResourceRegistrationUserMemoryRequirements]\n");

static __attribute__ ((used)) void* __ptr_sceGnmRaiseUserExceptionEvent;
asm(".intel_syntax noprefix\n"
    ".global sceGnmRaiseUserExceptionEvent\n"
    ".type sceGnmRaiseUserExceptionEvent @function\n"
    "sceGnmRaiseUserExceptionEvent:\n"
    "jmp qword ptr [rip + __ptr_sceGnmRaiseUserExceptionEvent]\n");

static __attribute__ ((used)) void* __ptr_sceGnmRegisterGdsResource;
asm(".intel_syntax noprefix\n"
    ".global sceGnmRegisterGdsResource\n"
    ".type sceGnmRegisterGdsResource @function\n"
    "sceGnmRegisterGdsResource:\n"
    "jmp qword ptr [rip + __ptr_sceGnmRegisterGdsResource]\n");

static __attribute__ ((used)) void* __ptr_sceGnmRegisterGnmLiveCallbackConfig;
asm(".intel_syntax noprefix\n"
    ".global sceGnmRegisterGnmLiveCallbackConfig\n"
    ".type sceGnmRegisterGnmLiveCallbackConfig @function\n"
    "sceGnmRegisterGnmLiveCallbackConfig:\n"
    "jmp qword ptr [rip + __ptr_sceGnmRegisterGnmLiveCallbackConfig]\n");

static __attribute__ ((used)) void* __ptr_sceGnmRegisterOwner;
asm(".intel_syntax noprefix\n"
    ".global sceGnmRegisterOwner\n"
    ".type sceGnmRegisterOwner @function\n"
    "sceGnmRegisterOwner:\n"
    "jmp qword ptr [rip + __ptr_sceGnmRegisterOwner]\n");

static __attribute__ ((used)) void* __ptr_sceGnmRegisterOwnerForSystem;
asm(".intel_syntax noprefix\n"
    ".global sceGnmRegisterOwnerForSystem\n"
    ".type sceGnmRegisterOwnerForSystem @function\n"
    "sceGnmRegisterOwnerForSystem:\n"
    "jmp qword ptr [rip + __ptr_sceGnmRegisterOwnerForSystem]\n");

static __attribute__ ((used)) void* __ptr_sceGnmRegisterResource;
asm(".intel_syntax noprefix\n"
    ".global sceGnmRegisterResource\n"
    ".type sceGnmRegisterResource @function\n"
    "sceGnmRegisterResource:\n"
    "jmp qword ptr [rip + __ptr_sceGnmRegisterResource]\n");

static __attribute__ ((used)) void* __ptr_sceGnmRequestFlipAndSubmitDone;
asm(".intel_syntax noprefix\n"
    ".global sceGnmRequestFlipAndSubmitDone\n"
    ".type sceGnmRequestFlipAndSubmitDone @function\n"
    "sceGnmRequestFlipAndSubmitDone:\n"
    "jmp qword ptr [rip + __ptr_sceGnmRequestFlipAndSubmitDone]\n");

static __attribute__ ((used)) void* __ptr_sceGnmRequestFlipAndSubmitDoneForWorkload;
asm(".intel_syntax noprefix\n"
    ".global sceGnmRequestFlipAndSubmitDoneForWorkload\n"
    ".type sceGnmRequestFlipAndSubmitDoneForWorkload @function\n"
    "sceGnmRequestFlipAndSubmitDoneForWorkload:\n"
    "jmp qword ptr [rip + __ptr_sceGnmRequestFlipAndSubmitDoneForWorkload]\n");

static __attribute__ ((used)) void* __ptr_sceGnmRequestMipStatsReportAndReset;
asm(".intel_syntax noprefix\n"
    ".global sceGnmRequestMipStatsReportAndReset\n"
    ".type sceGnmRequestMipStatsReportAndReset @function\n"
    "sceGnmRequestMipStatsReportAndReset:\n"
    "jmp qword ptr [rip + __ptr_sceGnmRequestMipStatsReportAndReset]\n");

static __attribute__ ((used)) void* __ptr_sceGnmResetVgtControl;
asm(".intel_syntax noprefix\n"
    ".global sceGnmResetVgtControl\n"
    ".type sceGnmResetVgtControl @function\n"
    "sceGnmResetVgtControl:\n"
    "jmp qword ptr [rip + __ptr_sceGnmResetVgtControl]\n");

static __attribute__ ((used)) void* __ptr_sceGnmSdmaClose;
asm(".intel_syntax noprefix\n"
    ".global sceGnmSdmaClose\n"
    ".type sceGnmSdmaClose @function\n"
    "sceGnmSdmaClose:\n"
    "jmp qword ptr [rip + __ptr_sceGnmSdmaClose]\n");

static __attribute__ ((used)) void* __ptr_sceGnmSdmaConstFill;
asm(".intel_syntax noprefix\n"
    ".global sceGnmSdmaConstFill\n"
    ".type sceGnmSdmaConstFill @function\n"
    "sceGnmSdmaConstFill:\n"
    "jmp qword ptr [rip + __ptr_sceGnmSdmaConstFill]\n");

static __attribute__ ((used)) void* __ptr_sceGnmSdmaCopyLinear;
asm(".intel_syntax noprefix\n"
    ".global sceGnmSdmaCopyLinear\n"
    ".type sceGnmSdmaCopyLinear @function\n"
    "sceGnmSdmaCopyLinear:\n"
    "jmp qword ptr [rip + __ptr_sceGnmSdmaCopyLinear]\n");

static __attribute__ ((used)) void* __ptr_sceGnmSdmaCopyTiled;
asm(".intel_syntax noprefix\n"
    ".global sceGnmSdmaCopyTiled\n"
    ".type sceGnmSdmaCopyTiled @function\n"
    "sceGnmSdmaCopyTiled:\n"
    "jmp qword ptr [rip + __ptr_sceGnmSdmaCopyTiled]\n");

static __attribute__ ((used)) void* __ptr_sceGnmSdmaCopyWindow;
asm(".intel_syntax noprefix\n"
    ".global sceGnmSdmaCopyWindow\n"
    ".type sceGnmSdmaCopyWindow @function\n"
    "sceGnmSdmaCopyWindow:\n"
    "jmp qword ptr [rip + __ptr_sceGnmSdmaCopyWindow]\n");

static __attribute__ ((used)) void* __ptr_sceGnmSdmaFlush;
asm(".intel_syntax noprefix\n"
    ".global sceGnmSdmaFlush\n"
    ".type sceGnmSdmaFlush @function\n"
    "sceGnmSdmaFlush:\n"
    "jmp qword ptr [rip + __ptr_sceGnmSdmaFlush]\n");

static __attribute__ ((used)) void* __ptr_sceGnmSdmaGetMinCmdSize;
asm(".intel_syntax noprefix\n"
    ".global sceGnmSdmaGetMinCmdSize\n"
    ".type sceGnmSdmaGetMinCmdSize @function\n"
    "sceGnmSdmaGetMinCmdSize:\n"
    "jmp qword ptr [rip + __ptr_sceGnmSdmaGetMinCmdSize]\n");

static __attribute__ ((used)) void* __ptr_sceGnmSdmaOpen;
asm(".intel_syntax noprefix\n"
    ".global sceGnmSdmaOpen\n"
    ".type sceGnmSdmaOpen @function\n"
    "sceGnmSdmaOpen:\n"
    "jmp qword ptr [rip + __ptr_sceGnmSdmaOpen]\n");

static __attribute__ ((used)) void* __ptr_sceGnmSetCsShader;
asm(".intel_syntax noprefix\n"
    ".global sceGnmSetCsShader\n"
    ".type sceGnmSetCsShader @function\n"
    "sceGnmSetCsShader:\n"
    "jmp qword ptr [rip + __ptr_sceGnmSetCsShader]\n");

static __attribute__ ((used)) void* __ptr_sceGnmSetCsShaderWithModifier;
asm(".intel_syntax noprefix\n"
    ".global sceGnmSetCsShaderWithModifier\n"
    ".type sceGnmSetCsShaderWithModifier @function\n"
    "sceGnmSetCsShaderWithModifier:\n"
    "jmp qword ptr [rip + __ptr_sceGnmSetCsShaderWithModifier]\n");

static __attribute__ ((used)) void* __ptr_sceGnmSetEmbeddedPsShader;
asm(".intel_syntax noprefix\n"
    ".global sceGnmSetEmbeddedPsShader\n"
    ".type sceGnmSetEmbeddedPsShader @function\n"
    "sceGnmSetEmbeddedPsShader:\n"
    "jmp qword ptr [rip + __ptr_sceGnmSetEmbeddedPsShader]\n");

static __attribute__ ((used)) void* __ptr_sceGnmSetEmbeddedVsShader;
asm(".intel_syntax noprefix\n"
    ".global sceGnmSetEmbeddedVsShader\n"
    ".type sceGnmSetEmbeddedVsShader @function\n"
    "sceGnmSetEmbeddedVsShader:\n"
    "jmp qword ptr [rip + __ptr_sceGnmSetEmbeddedVsShader]\n");

static __attribute__ ((used)) void* __ptr_sceGnmSetEsShader;
asm(".intel_syntax noprefix\n"
    ".global sceGnmSetEsShader\n"
    ".type sceGnmSetEsShader @function\n"
    "sceGnmSetEsShader:\n"
    "jmp qword ptr [rip + __ptr_sceGnmSetEsShader]\n");

static __attribute__ ((used)) void* __ptr_sceGnmSetGsRingSizes;
asm(".intel_syntax noprefix\n"
    ".global sceGnmSetGsRingSizes\n"
    ".type sceGnmSetGsRingSizes @function\n"
    "sceGnmSetGsRingSizes:\n"
    "jmp qword ptr [rip + __ptr_sceGnmSetGsRingSizes]\n");

static __attribute__ ((used)) void* __ptr_sceGnmSetGsShader;
asm(".intel_syntax noprefix\n"
    ".global sceGnmSetGsShader\n"
    ".type sceGnmSetGsShader @function\n"
    "sceGnmSetGsShader:\n"
    "jmp qword ptr [rip + __ptr_sceGnmSetGsShader]\n");

static __attribute__ ((used)) void* __ptr_sceGnmSetHsShader;
asm(".intel_syntax noprefix\n"
    ".global sceGnmSetHsShader\n"
    ".type sceGnmSetHsShader @function\n"
    "sceGnmSetHsShader:\n"
    "jmp qword ptr [rip + __ptr_sceGnmSetHsShader]\n");

static __attribute__ ((used)) void* __ptr_sceGnmSetLsShader;
asm(".intel_syntax noprefix\n"
    ".global sceGnmSetLsShader\n"
    ".type sceGnmSetLsShader @function\n"
    "sceGnmSetLsShader:\n"
    "jmp qword ptr [rip + __ptr_sceGnmSetLsShader]\n");

static __attribute__ ((used)) void* __ptr_sceGnmSetPsShader;
asm(".intel_syntax noprefix\n"
    ".global sceGnmSetPsShader\n"
    ".type sceGnmSetPsShader @function\n"
    "sceGnmSetPsShader:\n"
    "jmp qword ptr [rip + __ptr_sceGnmSetPsShader]\n");

static __attribute__ ((used)) void* __ptr_sceGnmSetPsShader350;
asm(".intel_syntax noprefix\n"
    ".global sceGnmSetPsShader350\n"
    ".type sceGnmSetPsShader350 @function\n"
    "sceGnmSetPsShader350:\n"
    "jmp qword ptr [rip + __ptr_sceGnmSetPsShader350]\n");

static __attribute__ ((used)) void* __ptr_sceGnmSetResourceRegistrationUserMemory;
asm(".intel_syntax noprefix\n"
    ".global sceGnmSetResourceRegistrationUserMemory\n"
    ".type sceGnmSetResourceRegistrationUserMemory @function\n"
    "sceGnmSetResourceRegistrationUserMemory:\n"
    "jmp qword ptr [rip + __ptr_sceGnmSetResourceRegistrationUserMemory]\n");

static __attribute__ ((used)) void* __ptr_sceGnmSetResourceUserData;
asm(".intel_syntax noprefix\n"
    ".global sceGnmSetResourceUserData\n"
    ".type sceGnmSetResourceUserData @function\n"
    "sceGnmSetResourceUserData:\n"
    "jmp qword ptr [rip + __ptr_sceGnmSetResourceUserData]\n");

static __attribute__ ((used)) void* __ptr_sceGnmSetSpiEnableSqCounters;
asm(".intel_syntax noprefix\n"
    ".global sceGnmSetSpiEnableSqCounters\n"
    ".type sceGnmSetSpiEnableSqCounters @function\n"
    "sceGnmSetSpiEnableSqCounters:\n"
    "jmp qword ptr [rip + __ptr_sceGnmSetSpiEnableSqCounters]\n");

static __attribute__ ((used)) void* __ptr_sceGnmSetSpiEnableSqCountersForUnitInstance;
asm(".intel_syntax noprefix\n"
    ".global sceGnmSetSpiEnableSqCountersForUnitInstance\n"
    ".type sceGnmSetSpiEnableSqCountersForUnitInstance @function\n"
    "sceGnmSetSpiEnableSqCountersForUnitInstance:\n"
    "jmp qword ptr [rip + __ptr_sceGnmSetSpiEnableSqCountersForUnitInstance]\n");

static __attribute__ ((used)) void* __ptr_sceGnmSetVgtControl;
asm(".intel_syntax noprefix\n"
    ".global sceGnmSetVgtControl\n"
    ".type sceGnmSetVgtControl @function\n"
    "sceGnmSetVgtControl:\n"
    "jmp qword ptr [rip + __ptr_sceGnmSetVgtControl]\n");

static __attribute__ ((used)) void* __ptr_sceGnmSetVsShader;
asm(".intel_syntax noprefix\n"
    ".global sceGnmSetVsShader\n"
    ".type sceGnmSetVsShader @function\n"
    "sceGnmSetVsShader:\n"
    "jmp qword ptr [rip + __ptr_sceGnmSetVsShader]\n");

static __attribute__ ((used)) void* __ptr_sceGnmSetWaveLimitMultiplier;
asm(".intel_syntax noprefix\n"
    ".global sceGnmSetWaveLimitMultiplier\n"
    ".type sceGnmSetWaveLimitMultiplier @function\n"
    "sceGnmSetWaveLimitMultiplier:\n"
    "jmp qword ptr [rip + __ptr_sceGnmSetWaveLimitMultiplier]\n");

static __attribute__ ((used)) void* __ptr_sceGnmSetWaveLimitMultipliers;
asm(".intel_syntax noprefix\n"
    ".global sceGnmSetWaveLimitMultipliers\n"
    ".type sceGnmSetWaveLimitMultipliers @function\n"
    "sceGnmSetWaveLimitMultipliers:\n"
    "jmp qword ptr [rip + __ptr_sceGnmSetWaveLimitMultipliers]\n");

static __attribute__ ((used)) void* __ptr_sceGnmSetupMipStatsReport;
asm(".intel_syntax noprefix\n"
    ".global sceGnmSetupMipStatsReport\n"
    ".type sceGnmSetupMipStatsReport @function\n"
    "sceGnmSetupMipStatsReport:\n"
    "jmp qword ptr [rip + __ptr_sceGnmSetupMipStatsReport]\n");

static __attribute__ ((used)) void* __ptr_sceGnmSubmitAndFlipCommandBuffers;
asm(".intel_syntax noprefix\n"
    ".global sceGnmSubmitAndFlipCommandBuffers\n"
    ".type sceGnmSubmitAndFlipCommandBuffers @function\n"
    "sceGnmSubmitAndFlipCommandBuffers:\n"
    "jmp qword ptr [rip + __ptr_sceGnmSubmitAndFlipCommandBuffers]\n");

static __attribute__ ((used)) void* __ptr_sceGnmSubmitAndFlipCommandBuffersForWorkload;
asm(".intel_syntax noprefix\n"
    ".global sceGnmSubmitAndFlipCommandBuffersForWorkload\n"
    ".type sceGnmSubmitAndFlipCommandBuffersForWorkload @function\n"
    "sceGnmSubmitAndFlipCommandBuffersForWorkload:\n"
    "jmp qword ptr [rip + __ptr_sceGnmSubmitAndFlipCommandBuffersForWorkload]\n");

static __attribute__ ((used)) void* __ptr_sceGnmSubmitCommandBuffers;
asm(".intel_syntax noprefix\n"
    ".global sceGnmSubmitCommandBuffers\n"
    ".type sceGnmSubmitCommandBuffers @function\n"
    "sceGnmSubmitCommandBuffers:\n"
    "jmp qword ptr [rip + __ptr_sceGnmSubmitCommandBuffers]\n");

static __attribute__ ((used)) void* __ptr_sceGnmSubmitCommandBuffersForWorkload;
asm(".intel_syntax noprefix\n"
    ".global sceGnmSubmitCommandBuffersForWorkload\n"
    ".type sceGnmSubmitCommandBuffersForWorkload @function\n"
    "sceGnmSubmitCommandBuffersForWorkload:\n"
    "jmp qword ptr [rip + __ptr_sceGnmSubmitCommandBuffersForWorkload]\n");

static __attribute__ ((used)) void* __ptr_sceGnmSubmitDone;
asm(".intel_syntax noprefix\n"
    ".global sceGnmSubmitDone\n"
    ".type sceGnmSubmitDone @function\n"
    "sceGnmSubmitDone:\n"
    "jmp qword ptr [rip + __ptr_sceGnmSubmitDone]\n");

static __attribute__ ((used)) void* __ptr_sceGnmUnmapComputeQueue;
asm(".intel_syntax noprefix\n"
    ".global sceGnmUnmapComputeQueue\n"
    ".type sceGnmUnmapComputeQueue @function\n"
    "sceGnmUnmapComputeQueue:\n"
    "jmp qword ptr [rip + __ptr_sceGnmUnmapComputeQueue]\n");

static __attribute__ ((used)) void* __ptr_sceGnmUnregisterAllResourcesForOwner;
asm(".intel_syntax noprefix\n"
    ".global sceGnmUnregisterAllResourcesForOwner\n"
    ".type sceGnmUnregisterAllResourcesForOwner @function\n"
    "sceGnmUnregisterAllResourcesForOwner:\n"
    "jmp qword ptr [rip + __ptr_sceGnmUnregisterAllResourcesForOwner]\n");

static __attribute__ ((used)) void* __ptr_sceGnmUnregisterOwnerAndResources;
asm(".intel_syntax noprefix\n"
    ".global sceGnmUnregisterOwnerAndResources\n"
    ".type sceGnmUnregisterOwnerAndResources @function\n"
    "sceGnmUnregisterOwnerAndResources:\n"
    "jmp qword ptr [rip + __ptr_sceGnmUnregisterOwnerAndResources]\n");

static __attribute__ ((used)) void* __ptr_sceGnmUnregisterResource;
asm(".intel_syntax noprefix\n"
    ".global sceGnmUnregisterResource\n"
    ".type sceGnmUnregisterResource @function\n"
    "sceGnmUnregisterResource:\n"
    "jmp qword ptr [rip + __ptr_sceGnmUnregisterResource]\n");

static __attribute__ ((used)) void* __ptr_sceGnmUpdateGsShader;
asm(".intel_syntax noprefix\n"
    ".global sceGnmUpdateGsShader\n"
    ".type sceGnmUpdateGsShader @function\n"
    "sceGnmUpdateGsShader:\n"
    "jmp qword ptr [rip + __ptr_sceGnmUpdateGsShader]\n");

static __attribute__ ((used)) void* __ptr_sceGnmUpdateHsShader;
asm(".intel_syntax noprefix\n"
    ".global sceGnmUpdateHsShader\n"
    ".type sceGnmUpdateHsShader @function\n"
    "sceGnmUpdateHsShader:\n"
    "jmp qword ptr [rip + __ptr_sceGnmUpdateHsShader]\n");

static __attribute__ ((used)) void* __ptr_sceGnmUpdatePsShader;
asm(".intel_syntax noprefix\n"
    ".global sceGnmUpdatePsShader\n"
    ".type sceGnmUpdatePsShader @function\n"
    "sceGnmUpdatePsShader:\n"
    "jmp qword ptr [rip + __ptr_sceGnmUpdatePsShader]\n");

static __attribute__ ((used)) void* __ptr_sceGnmUpdatePsShader350;
asm(".intel_syntax noprefix\n"
    ".global sceGnmUpdatePsShader350\n"
    ".type sceGnmUpdatePsShader350 @function\n"
    "sceGnmUpdatePsShader350:\n"
    "jmp qword ptr [rip + __ptr_sceGnmUpdatePsShader350]\n");

static __attribute__ ((used)) void* __ptr_sceGnmUpdateVsShader;
asm(".intel_syntax noprefix\n"
    ".global sceGnmUpdateVsShader\n"
    ".type sceGnmUpdateVsShader @function\n"
    "sceGnmUpdateVsShader:\n"
    "jmp qword ptr [rip + __ptr_sceGnmUpdateVsShader]\n");

static __attribute__ ((used)) void* __ptr_sceGnmValidateCommandBuffers;
asm(".intel_syntax noprefix\n"
    ".global sceGnmValidateCommandBuffers\n"
    ".type sceGnmValidateCommandBuffers @function\n"
    "sceGnmValidateCommandBuffers:\n"
    "jmp qword ptr [rip + __ptr_sceGnmValidateCommandBuffers]\n");

static __attribute__ ((used)) void* __ptr_sceGnmValidateDisableDiagnostics;
asm(".intel_syntax noprefix\n"
    ".global sceGnmValidateDisableDiagnostics\n"
    ".type sceGnmValidateDisableDiagnostics @function\n"
    "sceGnmValidateDisableDiagnostics:\n"
    "jmp qword ptr [rip + __ptr_sceGnmValidateDisableDiagnostics]\n");

static __attribute__ ((used)) void* __ptr_sceGnmValidateDisableDiagnostics2;
asm(".intel_syntax noprefix\n"
    ".global sceGnmValidateDisableDiagnostics2\n"
    ".type sceGnmValidateDisableDiagnostics2 @function\n"
    "sceGnmValidateDisableDiagnostics2:\n"
    "jmp qword ptr [rip + __ptr_sceGnmValidateDisableDiagnostics2]\n");

static __attribute__ ((used)) void* __ptr_sceGnmValidateDispatchCommandBuffers;
asm(".intel_syntax noprefix\n"
    ".global sceGnmValidateDispatchCommandBuffers\n"
    ".type sceGnmValidateDispatchCommandBuffers @function\n"
    "sceGnmValidateDispatchCommandBuffers:\n"
    "jmp qword ptr [rip + __ptr_sceGnmValidateDispatchCommandBuffers]\n");

static __attribute__ ((used)) void* __ptr_sceGnmValidateDrawCommandBuffers;
asm(".intel_syntax noprefix\n"
    ".global sceGnmValidateDrawCommandBuffers\n"
    ".type sceGnmValidateDrawCommandBuffers @function\n"
    "sceGnmValidateDrawCommandBuffers:\n"
    "jmp qword ptr [rip + __ptr_sceGnmValidateDrawCommandBuffers]\n");

static __attribute__ ((used)) void* __ptr_sceGnmValidateGetDiagnosticInfo;
asm(".intel_syntax noprefix\n"
    ".global sceGnmValidateGetDiagnosticInfo\n"
    ".type sceGnmValidateGetDiagnosticInfo @function\n"
    "sceGnmValidateGetDiagnosticInfo:\n"
    "jmp qword ptr [rip + __ptr_sceGnmValidateGetDiagnosticInfo]\n");

static __attribute__ ((used)) void* __ptr_sceGnmValidateGetDiagnostics;
asm(".intel_syntax noprefix\n"
    ".global sceGnmValidateGetDiagnostics\n"
    ".type sceGnmValidateGetDiagnostics @function\n"
    "sceGnmValidateGetDiagnostics:\n"
    "jmp qword ptr [rip + __ptr_sceGnmValidateGetDiagnostics]\n");

static __attribute__ ((used)) void* __ptr_sceGnmValidateGetVersion;
asm(".intel_syntax noprefix\n"
    ".global sceGnmValidateGetVersion\n"
    ".type sceGnmValidateGetVersion @function\n"
    "sceGnmValidateGetVersion:\n"
    "jmp qword ptr [rip + __ptr_sceGnmValidateGetVersion]\n");

static __attribute__ ((used)) void* __ptr_sceGnmValidateOnSubmitEnabled;
asm(".intel_syntax noprefix\n"
    ".global sceGnmValidateOnSubmitEnabled\n"
    ".type sceGnmValidateOnSubmitEnabled @function\n"
    "sceGnmValidateOnSubmitEnabled:\n"
    "jmp qword ptr [rip + __ptr_sceGnmValidateOnSubmitEnabled]\n");

static __attribute__ ((used)) void* __ptr_sceGnmValidateResetState;
asm(".intel_syntax noprefix\n"
    ".global sceGnmValidateResetState\n"
    ".type sceGnmValidateResetState @function\n"
    "sceGnmValidateResetState:\n"
    "jmp qword ptr [rip + __ptr_sceGnmValidateResetState]\n");

static __attribute__ ((used)) void* __ptr_sceGnmValidationRegisterMemoryCheckCallback;
asm(".intel_syntax noprefix\n"
    ".global sceGnmValidationRegisterMemoryCheckCallback\n"
    ".type sceGnmValidationRegisterMemoryCheckCallback @function\n"
    "sceGnmValidationRegisterMemoryCheckCallback:\n"
    "jmp qword ptr [rip + __ptr_sceGnmValidationRegisterMemoryCheckCallback]\n");

static __attribute__ ((used)) void* __ptr_sceRazorCaptureCommandBuffersOnlyImmediate;
asm(".intel_syntax noprefix\n"
    ".global sceRazorCaptureCommandBuffersOnlyImmediate\n"
    ".type sceRazorCaptureCommandBuffersOnlyImmediate @function\n"
    "sceRazorCaptureCommandBuffersOnlyImmediate:\n"
    "jmp qword ptr [rip + __ptr_sceRazorCaptureCommandBuffersOnlyImmediate]\n");

static __attribute__ ((used)) void* __ptr_sceRazorCaptureCommandBuffersOnlySinceLastFlip;
asm(".intel_syntax noprefix\n"
    ".global sceRazorCaptureCommandBuffersOnlySinceLastFlip\n"
    ".type sceRazorCaptureCommandBuffersOnlySinceLastFlip @function\n"
    "sceRazorCaptureCommandBuffersOnlySinceLastFlip:\n"
    "jmp qword ptr [rip + __ptr_sceRazorCaptureCommandBuffersOnlySinceLastFlip]\n");

static __attribute__ ((used)) void* __ptr_sceRazorCaptureImmediate;
asm(".intel_syntax noprefix\n"
    ".global sceRazorCaptureImmediate\n"
    ".type sceRazorCaptureImmediate @function\n"
    "sceRazorCaptureImmediate:\n"
    "jmp qword ptr [rip + __ptr_sceRazorCaptureImmediate]\n");

static __attribute__ ((used)) void* __ptr_sceRazorCaptureSinceLastFlip;
asm(".intel_syntax noprefix\n"
    ".global sceRazorCaptureSinceLastFlip\n"
    ".type sceRazorCaptureSinceLastFlip @function\n"
    "sceRazorCaptureSinceLastFlip:\n"
    "jmp qword ptr [rip + __ptr_sceRazorCaptureSinceLastFlip]\n");

static __attribute__ ((used)) void* __ptr_sceRazorIsLoaded;
asm(".intel_syntax noprefix\n"
    ".global sceRazorIsLoaded\n"
    ".type sceRazorIsLoaded @function\n"
    "sceRazorIsLoaded:\n"
    "jmp qword ptr [rip + __ptr_sceRazorIsLoaded]\n");

static unsigned short __handle = 0;
static void __attribute__((constructor(104)))
__constructor(void) {
  if(sprx_dlopen("libSceGnmDriverForNeoMode", &__handle)) return;
  if(sprx_dlsym(__handle, "b0xyllnVY-I", &__ptr_sceGnmAddEqEvent)) return;
  if(sprx_dlsym(__handle, "b08AgtPlHPg", &__ptr_sceGnmAreSubmitsAllowed)) return;
  if(sprx_dlsym(__handle, "ihxrbsoSKWc", &__ptr_sceGnmBeginWorkload)) return;
  if(sprx_dlsym(__handle, "ffrNQOshows", &__ptr_sceGnmComputeWaitOnAddress)) return;
  if(sprx_dlsym(__handle, "EJapNl2+pgU", &__ptr_sceGnmComputeWaitSemaphore)) return;
  if(sprx_dlsym(__handle, "5udAm+6boVg", &__ptr_sceGnmCreateWorkloadStream)) return;
  if(sprx_dlsym(__handle, "qpGITzPE+Zc", &__ptr_sceGnmDebugHardwareStatus)) return;
  if(sprx_dlsym(__handle, "dqPBvjFVpTA", &__ptr_sceGnmDebugModuleReset)) return;
  if(sprx_dlsym(__handle, "RNPAItiMLIg", &__ptr_sceGnmDebugReset)) return;
  if(sprx_dlsym(__handle, "PVT+fuoS9gU", &__ptr_sceGnmDeleteEqEvent)) return;
  if(sprx_dlsym(__handle, "UtObDRQiGbs", &__ptr_sceGnmDestroyWorkloadStream)) return;
  if(sprx_dlsym(__handle, "bX5IbRvECXk", &__ptr_sceGnmDingDong)) return;
  if(sprx_dlsym(__handle, "byXlqupd8cE", &__ptr_sceGnmDingDongForWorkload)) return;
  if(sprx_dlsym(__handle, "HHo1BAljZO8", &__ptr_sceGnmDisableMipStatsReport)) return;
  if(sprx_dlsym(__handle, "0BzLGljcwBo", &__ptr_sceGnmDispatchDirect)) return;
  if(sprx_dlsym(__handle, "Z43vKp5k7r0", &__ptr_sceGnmDispatchIndirect)) return;
  if(sprx_dlsym(__handle, "wED4ZXCFJT0", &__ptr_sceGnmDispatchIndirectOnMec)) return;
  if(sprx_dlsym(__handle, "nF6bFRUBRAU", &__ptr_sceGnmDispatchInitDefaultHardwareState)) return;
  if(sprx_dlsym(__handle, "HlTPoZ-oY7Y", &__ptr_sceGnmDrawIndex)) return;
  if(sprx_dlsym(__handle, "GGsn7jMTxw4", &__ptr_sceGnmDrawIndexAuto)) return;
  if(sprx_dlsym(__handle, "ED9-Fjr8Ta4", &__ptr_sceGnmDrawIndexIndirect)) return;
  if(sprx_dlsym(__handle, "thbPcG7E7qk", &__ptr_sceGnmDrawIndexIndirectCountMulti)) return;
  if(sprx_dlsym(__handle, "5q95ravnueg", &__ptr_sceGnmDrawIndexIndirectMulti)) return;
  if(sprx_dlsym(__handle, "jHdPvIzlpKc", &__ptr_sceGnmDrawIndexMultiInstanced)) return;
  if(sprx_dlsym(__handle, "oYM+YzfCm2Y", &__ptr_sceGnmDrawIndexOffset)) return;
  if(sprx_dlsym(__handle, "4v+otIIdjqg", &__ptr_sceGnmDrawIndirect)) return;
  if(sprx_dlsym(__handle, "cUCo8OvArrw", &__ptr_sceGnmDrawIndirectCountMulti)) return;
  if(sprx_dlsym(__handle, "f5QQLp9rzGk", &__ptr_sceGnmDrawIndirectMulti)) return;
  if(sprx_dlsym(__handle, "Idffwf3yh8s", &__ptr_sceGnmDrawInitDefaultHardwareState)) return;
  if(sprx_dlsym(__handle, "QhnyReteJ1M", &__ptr_sceGnmDrawInitDefaultHardwareState175)) return;
  if(sprx_dlsym(__handle, "0H2vBYbTLHI", &__ptr_sceGnmDrawInitDefaultHardwareState200)) return;
  if(sprx_dlsym(__handle, "yb2cRhagD1I", &__ptr_sceGnmDrawInitDefaultHardwareState350)) return;
  if(sprx_dlsym(__handle, "8lH54sfjfmU", &__ptr_sceGnmDrawInitToDefaultContextState)) return;
  if(sprx_dlsym(__handle, "im2ZuItabu4", &__ptr_sceGnmDrawInitToDefaultContextState400)) return;
  if(sprx_dlsym(__handle, "pF1HQjbmQJ0", &__ptr_sceGnmDrawInitToDefaultContextStateInternalCommand)) return;
  if(sprx_dlsym(__handle, "jajhf-Gi3AI", &__ptr_sceGnmDrawInitToDefaultContextStateInternalSize)) return;
  if(sprx_dlsym(__handle, "stDSYW2SBVM", &__ptr_sceGnmDrawOpaqueAuto)) return;
  if(sprx_dlsym(__handle, "TLV4mswiZ4A", &__ptr_sceGnmDriverCaptureInProgress)) return;
  if(sprx_dlsym(__handle, "ODEeJ1GfDtE", &__ptr_sceGnmDriverInternalRetrieveGnmInterface)) return;
  if(sprx_dlsym(__handle, "4LSXsEKPTsE", &__ptr_sceGnmDriverInternalRetrieveGnmInterfaceForGpuDebugger)) return;
  if(sprx_dlsym(__handle, "3EXdrVC7WFk", &__ptr_sceGnmDriverInternalRetrieveGnmInterfaceForReplay)) return;
  if(sprx_dlsym(__handle, "P9iKqxAGeck", &__ptr_sceGnmDriverInternalRetrieveGnmInterfaceForResourceRegistration)) return;
  if(sprx_dlsym(__handle, "t-vIc5cTEzg", &__ptr_sceGnmDriverInternalRetrieveGnmInterfaceForValidation)) return;
  if(sprx_dlsym(__handle, "BvvO8Up88Zc", &__ptr_sceGnmDriverInternalVirtualQuery)) return;
  if(sprx_dlsym(__handle, "R6z1xM3pW-w", &__ptr_sceGnmDriverTraceInProgress)) return;
  if(sprx_dlsym(__handle, "d88anrgNoKY", &__ptr_sceGnmDriverTriggerCapture)) return;
  if(sprx_dlsym(__handle, "Fa3x75OOLRA", &__ptr_sceGnmEndWorkload)) return;
  if(sprx_dlsym(__handle, "vbcR4Ken6AA", &__ptr_sceGnmFindResources)) return;
  if(sprx_dlsym(__handle, "4Mv9OXypBG8", &__ptr_sceGnmFindResourcesPublic)) return;
  if(sprx_dlsym(__handle, "iBt3Oe00Kvc", &__ptr_sceGnmFlushGarlic)) return;
  if(sprx_dlsym(__handle, "GviyYfFQIkc", &__ptr_sceGnmGetCoredumpAddress)) return;
  if(sprx_dlsym(__handle, "meiO-5ZCVIE", &__ptr_sceGnmGetCoredumpMode)) return;
  if(sprx_dlsym(__handle, "O-7nHKgcNSQ", &__ptr_sceGnmGetCoredumpProtectionFaultTimestamp)) return;
  if(sprx_dlsym(__handle, "bSJFzejYrJI", &__ptr_sceGnmGetDbgGcHandle)) return;
  if(sprx_dlsym(__handle, "UoYY0DWMC0U", &__ptr_sceGnmGetEqEventType)) return;
  if(sprx_dlsym(__handle, "H7-fgvEutM0", &__ptr_sceGnmGetEqTimeStamp)) return;
  if(sprx_dlsym(__handle, "oL4hGI1PMpw", &__ptr_sceGnmGetGpuBlockStatus)) return;
  if(sprx_dlsym(__handle, "Fwvh++m9IQI", &__ptr_sceGnmGetGpuCoreClockFrequency)) return;
  if(sprx_dlsym(__handle, "tZCSL5ulnB4", &__ptr_sceGnmGetGpuInfoStatus)) return;
  if(sprx_dlsym(__handle, "iFirFzgYsvw", &__ptr_sceGnmGetLastWaitedAddress)) return;
  if(sprx_dlsym(__handle, "KnldROUkWJY", &__ptr_sceGnmGetNumTcaUnits)) return;
  if(sprx_dlsym(__handle, "FFVZcCu3zWU", &__ptr_sceGnmGetOffChipTessellationBufferSize)) return;
  if(sprx_dlsym(__handle, "QJjPjlmPAL0", &__ptr_sceGnmGetOwnerName)) return;
  if(sprx_dlsym(__handle, "dewXw5roLs0", &__ptr_sceGnmGetPhysicalCounterFromVirtualized)) return;
  if(sprx_dlsym(__handle, "fzJdEihTFV4", &__ptr_sceGnmGetProtectionFaultTimeStamp)) return;
  if(sprx_dlsym(__handle, "4PKnYXOhcx4", &__ptr_sceGnmGetResourceBaseAddressAndSizeInBytes)) return;
  if(sprx_dlsym(__handle, "O0S96YnD04U", &__ptr_sceGnmGetResourceName)) return;
  if(sprx_dlsym(__handle, "eLQbNsKeTkU", &__ptr_sceGnmGetResourceRegistrationBuffers)) return;
  if(sprx_dlsym(__handle, "UBv7FkVfzcQ", &__ptr_sceGnmGetResourceShaderGuid)) return;
  if(sprx_dlsym(__handle, "bdqdvIkLPIU", &__ptr_sceGnmGetResourceType)) return;
  if(sprx_dlsym(__handle, "UoBuWAhKk7U", &__ptr_sceGnmGetResourceUserData)) return;
  if(sprx_dlsym(__handle, "nEyFbYUloIM", &__ptr_sceGnmGetShaderProgramBaseAddress)) return;
  if(sprx_dlsym(__handle, "k7iGTvDQPLQ", &__ptr_sceGnmGetShaderStatus)) return;
  if(sprx_dlsym(__handle, "ln33zjBrfjk", &__ptr_sceGnmGetTheTessellationFactorRingBufferBaseAddress)) return;
  if(sprx_dlsym(__handle, "QLdG7G-PBZo", &__ptr_sceGnmGpuPaDebugEnter)) return;
  if(sprx_dlsym(__handle, "tVEdZe3wlbY", &__ptr_sceGnmGpuPaDebugLeave)) return;
  if(sprx_dlsym(__handle, "NfvOrNzy6sk", &__ptr_sceGnmInsertDingDongMarker)) return;
  if(sprx_dlsym(__handle, "7qZVNgEu+SY", &__ptr_sceGnmInsertPopMarker)) return;
  if(sprx_dlsym(__handle, "aPIZJTXC+cU", &__ptr_sceGnmInsertPushColorMarker)) return;
  if(sprx_dlsym(__handle, "W1Etj-jlW7Y", &__ptr_sceGnmInsertPushMarker)) return;
  if(sprx_dlsym(__handle, "aj3L-iaFmyk", &__ptr_sceGnmInsertSetColorMarker)) return;
  if(sprx_dlsym(__handle, "jiItzS6+22g", &__ptr_sceGnmInsertSetMarker)) return;
  if(sprx_dlsym(__handle, "URDgJcXhQOs", &__ptr_sceGnmInsertThreadTraceMarker)) return;
  if(sprx_dlsym(__handle, "1qXLHIpROPE", &__ptr_sceGnmInsertWaitFlipDone)) return;
  if(sprx_dlsym(__handle, "HRyNHoAjb6E", &__ptr_sceGnmIsCoredumpValid)) return;
  if(sprx_dlsym(__handle, "jg33rEKLfVs", &__ptr_sceGnmIsUserPaEnabled)) return;
  if(sprx_dlsym(__handle, "26PM5Mzl8zc", &__ptr_sceGnmLogicalCuIndexToPhysicalCuIndex)) return;
  if(sprx_dlsym(__handle, "RU74kek-N0c", &__ptr_sceGnmLogicalCuMaskToPhysicalCuMask)) return;
  if(sprx_dlsym(__handle, "Kl0Z3LH07QI", &__ptr_sceGnmLogicalTcaUnitToPhysical)) return;
  if(sprx_dlsym(__handle, "29oKvKXzEZo", &__ptr_sceGnmMapComputeQueue)) return;
  if(sprx_dlsym(__handle, "A+uGq+3KFtQ", &__ptr_sceGnmMapComputeQueueWithPriority)) return;
  if(sprx_dlsym(__handle, "+N+wrSYBLIw", &__ptr_sceGnmPaDisableFlipCallbacks)) return;
  if(sprx_dlsym(__handle, "8WDA9RiXLaw", &__ptr_sceGnmPaEnableFlipCallbacks)) return;
  if(sprx_dlsym(__handle, "tNuT48mApTc", &__ptr_sceGnmPaHeartbeat)) return;
  if(sprx_dlsym(__handle, "6IMbpR7nTzA", &__ptr_sceGnmQueryResourceRegistrationUserMemoryRequirements)) return;
  if(sprx_dlsym(__handle, "+rJnw2e9O+0", &__ptr_sceGnmRaiseUserExceptionEvent)) return;
  if(sprx_dlsym(__handle, "9Mv61HaMhfA", &__ptr_sceGnmRegisterGdsResource)) return;
  if(sprx_dlsym(__handle, "t7-VbMosbR4", &__ptr_sceGnmRegisterGnmLiveCallbackConfig)) return;
  if(sprx_dlsym(__handle, "ZFqKFl23aMc", &__ptr_sceGnmRegisterOwner)) return;
  if(sprx_dlsym(__handle, "j6mSQs3UgaY", &__ptr_sceGnmRegisterOwnerForSystem)) return;
  if(sprx_dlsym(__handle, "nvEwfYAImTs", &__ptr_sceGnmRegisterResource)) return;
  if(sprx_dlsym(__handle, "gObODli-OH8", &__ptr_sceGnmRequestFlipAndSubmitDone)) return;
  if(sprx_dlsym(__handle, "6YRHhh5mHCs", &__ptr_sceGnmRequestFlipAndSubmitDoneForWorkload)) return;
  if(sprx_dlsym(__handle, "f85orjx7qts", &__ptr_sceGnmRequestMipStatsReportAndReset)) return;
  if(sprx_dlsym(__handle, "MYRtYhojKdA", &__ptr_sceGnmResetVgtControl)) return;
  if(sprx_dlsym(__handle, "hS0MKPRdNr0", &__ptr_sceGnmSdmaClose)) return;
  if(sprx_dlsym(__handle, "31G6PB2oRYQ", &__ptr_sceGnmSdmaConstFill)) return;
  if(sprx_dlsym(__handle, "Lg2isla2XeQ", &__ptr_sceGnmSdmaCopyLinear)) return;
  if(sprx_dlsym(__handle, "-Se2FY+UTsI", &__ptr_sceGnmSdmaCopyTiled)) return;
  if(sprx_dlsym(__handle, "OlFgKnBsALE", &__ptr_sceGnmSdmaCopyWindow)) return;
  if(sprx_dlsym(__handle, "LQQN0SwQv8c", &__ptr_sceGnmSdmaFlush)) return;
  if(sprx_dlsym(__handle, "suUlSjWr7CE", &__ptr_sceGnmSdmaGetMinCmdSize)) return;
  if(sprx_dlsym(__handle, "5AtqyMgO7fM", &__ptr_sceGnmSdmaOpen)) return;
  if(sprx_dlsym(__handle, "KXltnCwEJHQ", &__ptr_sceGnmSetCsShader)) return;
  if(sprx_dlsym(__handle, "Kx-h-nWQJ8A", &__ptr_sceGnmSetCsShaderWithModifier)) return;
  if(sprx_dlsym(__handle, "X9Omw9dwv5M", &__ptr_sceGnmSetEmbeddedPsShader)) return;
  if(sprx_dlsym(__handle, "+AFvOEXrKJk", &__ptr_sceGnmSetEmbeddedVsShader)) return;
  if(sprx_dlsym(__handle, "FUHG8sQ3R58", &__ptr_sceGnmSetEsShader)) return;
  if(sprx_dlsym(__handle, "jtkqXpAOY6w", &__ptr_sceGnmSetGsRingSizes)) return;
  if(sprx_dlsym(__handle, "UJwNuMBcUAk", &__ptr_sceGnmSetGsShader)) return;
  if(sprx_dlsym(__handle, "VJNjFtqiF5w", &__ptr_sceGnmSetHsShader)) return;
  if(sprx_dlsym(__handle, "vckdzbQ46SI", &__ptr_sceGnmSetLsShader)) return;
  if(sprx_dlsym(__handle, "bQVd5YzCal0", &__ptr_sceGnmSetPsShader)) return;
  if(sprx_dlsym(__handle, "5uFKckiJYRM", &__ptr_sceGnmSetPsShader350)) return;
  if(sprx_dlsym(__handle, "q-qhDxP67Hg", &__ptr_sceGnmSetResourceRegistrationUserMemory)) return;
  if(sprx_dlsym(__handle, "K3BKBBYKUSE", &__ptr_sceGnmSetResourceUserData)) return;
  if(sprx_dlsym(__handle, "0O3xxFaiObw", &__ptr_sceGnmSetSpiEnableSqCounters)) return;
  if(sprx_dlsym(__handle, "lN7Gk-p9u78", &__ptr_sceGnmSetSpiEnableSqCountersForUnitInstance)) return;
  if(sprx_dlsym(__handle, "cFCp0NX8wf0", &__ptr_sceGnmSetVgtControl)) return;
  if(sprx_dlsym(__handle, "gAhCn6UiU4Y", &__ptr_sceGnmSetVsShader)) return;
  if(sprx_dlsym(__handle, "y+iI2lkX+qI", &__ptr_sceGnmSetWaveLimitMultiplier)) return;
  if(sprx_dlsym(__handle, "XiyzNZ9J4nQ", &__ptr_sceGnmSetWaveLimitMultipliers)) return;
  if(sprx_dlsym(__handle, "+xuDhxlWRPg", &__ptr_sceGnmSetupMipStatsReport)) return;
  if(sprx_dlsym(__handle, "xbxNatawohc", &__ptr_sceGnmSubmitAndFlipCommandBuffers)) return;
  if(sprx_dlsym(__handle, "Ga6r7H6Y0RI", &__ptr_sceGnmSubmitAndFlipCommandBuffersForWorkload)) return;
  if(sprx_dlsym(__handle, "zwY0YV91TTI", &__ptr_sceGnmSubmitCommandBuffers)) return;
  if(sprx_dlsym(__handle, "jRcI8VcgTz4", &__ptr_sceGnmSubmitCommandBuffersForWorkload)) return;
  if(sprx_dlsym(__handle, "yvZ73uQUqrk", &__ptr_sceGnmSubmitDone)) return;
  if(sprx_dlsym(__handle, "ArSg-TGinhk", &__ptr_sceGnmUnmapComputeQueue)) return;
  if(sprx_dlsym(__handle, "yhFCnaz5daw", &__ptr_sceGnmUnregisterAllResourcesForOwner)) return;
  if(sprx_dlsym(__handle, "fhKwCVVj9nk", &__ptr_sceGnmUnregisterOwnerAndResources)) return;
  if(sprx_dlsym(__handle, "k8EXkhIP+lM", &__ptr_sceGnmUnregisterResource)) return;
  if(sprx_dlsym(__handle, "nLM2i2+65hA", &__ptr_sceGnmUpdateGsShader)) return;
  if(sprx_dlsym(__handle, "GNlx+y7xPdE", &__ptr_sceGnmUpdateHsShader)) return;
  if(sprx_dlsym(__handle, "4MgRw-bVNQU", &__ptr_sceGnmUpdatePsShader)) return;
  if(sprx_dlsym(__handle, "mLVL7N7BVBg", &__ptr_sceGnmUpdatePsShader350)) return;
  if(sprx_dlsym(__handle, "V31V01UiScY", &__ptr_sceGnmUpdateVsShader)) return;
  if(sprx_dlsym(__handle, "iCO804ZgzdA", &__ptr_sceGnmValidateCommandBuffers)) return;
  if(sprx_dlsym(__handle, "SXw4dZEkgpA", &__ptr_sceGnmValidateDisableDiagnostics)) return;
  if(sprx_dlsym(__handle, "BgM3t3LvcNk", &__ptr_sceGnmValidateDisableDiagnostics2)) return;
  if(sprx_dlsym(__handle, "qGP74T5OWJc", &__ptr_sceGnmValidateDispatchCommandBuffers)) return;
  if(sprx_dlsym(__handle, "hsZPf1lON7E", &__ptr_sceGnmValidateDrawCommandBuffers)) return;
  if(sprx_dlsym(__handle, "RX7XCNSaL6I", &__ptr_sceGnmValidateGetDiagnosticInfo)) return;
  if(sprx_dlsym(__handle, "5SHGNwLXBV4", &__ptr_sceGnmValidateGetDiagnostics)) return;
  if(sprx_dlsym(__handle, "HzMN7ANqYEc", &__ptr_sceGnmValidateGetVersion)) return;
  if(sprx_dlsym(__handle, "rTIV11nMQuM", &__ptr_sceGnmValidateOnSubmitEnabled)) return;
  if(sprx_dlsym(__handle, "MBMa6EFu4Ko", &__ptr_sceGnmValidateResetState)) return;
  if(sprx_dlsym(__handle, "Q7t4VEYLafI", &__ptr_sceGnmValidationRegisterMemoryCheckCallback)) return;
  if(sprx_dlsym(__handle, "xeTLfxVIQO4", &__ptr_sceRazorCaptureCommandBuffersOnlyImmediate)) return;
  if(sprx_dlsym(__handle, "9thMn+uB1is", &__ptr_sceRazorCaptureCommandBuffersOnlySinceLastFlip)) return;
  if(sprx_dlsym(__handle, "u9YKpRRHe-M", &__ptr_sceRazorCaptureImmediate)) return;
  if(sprx_dlsym(__handle, "4UFagYlfuAM", &__ptr_sceRazorCaptureSinceLastFlip)) return;
  if(sprx_dlsym(__handle, "f33OrruQYbM", &__ptr_sceRazorIsLoaded)) return;
}

static void __attribute__((destructor(104)))
__destructor(void) {
  sprx_dlclose(__handle);
}
